### ISSUE TITLE
More configurations for Gitlab decoration

### ISSUE THREAD

**Issue by bmaehr** [mc1arke/sonarqube-community-branch-plugin#101]
After getting the plugin to work (master with sonarqube 8.0) I started to extend the Gitlab decoration plugin. The implemented features are:

- Compact issue commenting (only one line)
- Switch to turn off failing of pipeline (if quality gate is not reached it is not possible to merge, which is to hard for us)
- Filtering by severity which issues are added to MR
- If possible modification of comment instead of deleting and recreating (keeps comments and resolved status)

The problem is, that I did a refactoring of the whole class GitlabServerPullRequestDecorator because the main method was so long. How should I proceed?

**Comment by bmaehr** [comment]
[sonarqube-community-branch-plugin-1.2.1-SNAPSHOT.jar.zip](https://github.com/mc1arke/sonarqube-community-branch-plugin/files/4247791/sonarqube-community-branch-plugin-1.2.1-SNAPSHOT.jar.zip)

**Comment by bmaehr** [comment]
"How should I proceed?": One MR, multiple MR, ....

**Comment by bmaehr** [comment]
![image](https://user-images.githubusercontent.com/16438498/75209804-8b6f1f00-577f-11ea-8a1a-1d3c68e6a5ce.png)
![image](https://user-images.githubusercontent.com/16438498/75209819-97f37780-577f-11ea-968b-bae7f5c8b75d.png)

**Comment by bmaehr** [comment]
![image](https://user-images.githubusercontent.com/16438498/75209870-b9ecfa00-577f-11ea-9d0f-df5fc7a5b278.png)
![image](https://user-images.githubusercontent.com/16438498/75209899-d0935100-577f-11ea-86d5-75fa50719102.png)
![image](https://user-images.githubusercontent.com/16438498/75209915-e3a62100-577f-11ea-9b7d-278e24d98fc7.png)

**Comment by mc1arke** [comment]
If you can break the work up until multiple commits (ideally one per change you've listed above) then that makes it easier to review. Ideally, also submitting an MR per feature means it's easier to discuss the intent of that feature individually, rather then have diverging conversations on a single MR.

**Comment by bmaehr** [comment]
https://github.com/bmaehr/sonarqube-community-branch-plugin/commits/master
