### ISSUE TITLE
Pull request decoration for Azure DevOps Services

### ISSUE THREAD

**Issue by RobinZergiebel** [mc1arke/sonarqube-community-branch-plugin#102]
Hey @mc1arke,

since you closed the other issue and the 1.3.0-release covers everything but Azure DevOps, I hope you don't mind me opening a new issue for it?
I would kindly request pull request decoration for Azure DevOps Services :).

Cheers,
Robin

**Comment by Iloer** [comment]
@RobCoPKC Please check the solution from this thread on your server.

**Comment by RobCoPKC** [comment]
I just installed it and don't see any option to pick Azure DevOps as provider?

![image](https://user-images.githubusercontent.com/56680419/76614518-90262800-6520-11ea-99a9-c817383dba3c.png)

**Comment by Iloer** [comment]
Build [branch](https://github.com/Iloer/sonarqube-community-branch-plugin/tree/issue/102-8_1support)
![image](https://user-images.githubusercontent.com/17268903/76615359-f4ea7e00-6532-11ea-85e3-465fb8cf233b.png)

on document: https://docs.sonarqube.org/8.1/analysis/pr-decoration/

**Comment by RobCoPKC** [comment]
So I have to update to SonarQube 8.1?

**Comment by Iloer** [comment]
Yes.

**Comment by pratikibm** [comment]
> Build [branch](https://github.com/Iloer/sonarqube-community-branch-plugin/tree/issue/102-8_1support)
> ![image](https://user-images.githubusercontent.com/17268903/76615359-f4ea7e00-6532-11ea-85e3-465fb8cf233b.png)
> 
> on document: https://docs.sonarqube.org/8.1/analysis/pr-decoration/

Hi Iloer,
I am not able to generate jar file could you please attached here.

**Comment by pratikibm** [comment]
> So I have to update to SonarQube 8.1?

will it work for 8.2 as well?

**Comment by Iloer** [comment]
Hi @pratikibm, i'm attaching .jar
[sonarqube-community-branch-plugin-1.2.1-SNAPSHOT.zip](https://github.com/mc1arke/sonarqube-community-branch-plugin/files/4456986/sonarqube-community-branch-plugin-1.2.1-SNAPSHOT.zip)

 I didn’t check on 8.2, but judging by the discussion history, it should work

**Comment by pratikibm** [comment]
> Hi @pratikibm, i'm attaching .jar
> [sonarqube-community-branch-plugin-1.2.1-SNAPSHOT.zip](https://github.com/mc1arke/sonarqube-community-branch-plugin/files/4456986/sonarqube-community-branch-plugin-1.2.1-SNAPSHOT.zip)
> 
> I didn’t check on 8.2, but judging by the discussion history, it should work

Thanks @Iloer , I tried it on 8.2, however I can see ALM with Azure DevOps server option but there is no option of Pull request decoration.

**Comment by Iloer** [comment]
brief instruction
1.
![image](https://user-images.githubusercontent.com/17268903/78999331-0edba880-7b53-11ea-9a4f-ab641dcba31a.png)

2.
![image](https://user-images.githubusercontent.com/17268903/78999462-5bbf7f00-7b53-11ea-9d0c-6adbada603a7.png)

**Comment by cescidistus** [comment]
hello, 

I success to build a version for 8.2. There is a little error on project binding manipulation.

On file GetBindingAction.java, when you call `dbClient.projectAlmSettingDao().selectByProject(dbSession,projectDto),` projectDto need to be a ProjectDto and not a ComponentDto on version 8.2

Same on file DeleteBindingAction.java

I don't know how to do, if I have to make a pull request on your branch, and I don't know how to make the two version work since I only have the 8.2 version.

To get the project, I add that row 
          `
  ComponentDto project = componentFinder.getByKey(dbSession, projectKey);
            ProjectDto projectDto = componentFinder.getProjectByKey(dbSession, projectKey);
`

I attache built version for 8.2
[sonarqube-community-branch-plugin-1.2.1-SNAPSHOT.zip](https://github.com/mc1arke/sonarqube-community-branch-plugin/files/4462105/sonarqube-community-branch-plugin-1.2.1-SNAPSHOT.zip)

**Comment by jcuzzi** [comment]
Take a look at #202 . It is working for me using SonarQube 8.2 with Azure DevOps.  There are a few required properties that need to be set in the SonarQube Prepare task in the Azure Build Pipeline which are mentioned in the PR.

**Comment by raschmitt** [comment]
Can anyone confirm if it does work on 7.9.1?

**Comment by bbarman4u** [comment]
Can any one please confirm if this Works for the Azure DevOps Services (The Cloud Hosted Version) and not only for the Server version (Self Hosted) since the original issue is stated as open yet I noticed comments on some solutions listed but seems to be only for the server edition ?

**Comment by jcuzzi** [comment]
> Can any one please confirm if this Works for the Azure DevOps Services (The Cloud Hosted Version) and not only for the Server version (Self Hosted) since the original issue is stated as open yet I noticed comments on some solutions listed but seems to be only for the server edition ?

It works for the cloud hosted version too.

**Comment by bbarman4u** [comment]
> > Can any one please confirm if this Works for the Azure DevOps Services (The Cloud Hosted Version) and not only for the Server version (Self Hosted) since the original issue is stated as open yet I noticed comments on some solutions listed but seems to be only for the server edition ?
> 
> It works for the cloud hosted version too.

@jcuzzi Thanks for the information, I will try this out.

**Comment by jcuzzi** [comment]
@mc1arke this issue can probably be closed since the feature was released.
