### ISSUE TITLE
Summary comment must be resolved by a hand before pull request could be merged.

### ISSUE THREAD

**Issue by exxbrain** [mc1arke/sonarqube-community-branch-plugin#106]
Summary comment must be resolved by a hand before pull request could be merged. So now pull request decoration at least in gitlab negatively affects a merge process when pull request couldn't be merged automatically after successful completion of a pipeline.

1. Navigate to your gitlab project’s settings page, select the **Only allow merge requests to be merged if all threads are resolved** check box and hit Save for the changes to take effect.
2. Make merge request without issues and click a button "Merge when pipeline succeeds"

**Expected behavior**
Pull request should be automatically merged.

**Screenshots**
<img width="957" alt="Screenshot 2020-02-26 at 14 06 47" src="https://user-images.githubusercontent.com/1011558/75339584-d84b1680-58a1-11ea-841b-e6e67a893918.png">

<img width="856" alt="Screenshot 2020-02-26 at 14 13 34" src="https://user-images.githubusercontent.com/1011558/75339780-3546cc80-58a2-11ea-8e6f-b34910fee8f4.png">

<img width="994" alt="Screenshot 2020-02-26 at 13 55 20" src="https://user-images.githubusercontent.com/1011558/75340631-e306ab00-58a3-11ea-96ff-8ab3a2c6a560.png">

**Software Versions**
 - Gitlab
 - SonarQube Version: 7.9.2 (build 30863)
 - Plugin Version: 1.2.1-RC3

**Suggestion**
I think that it will be good to resolve summary comment thread automatically if there are no issues found.

**Comment by mc1arke** [comment]
This sounds like a feature request rather than a bug: you've enabled decoration, but your current pipeline then prevents decorated MRs from being auto-merged. I presume you're asking for the summary comment to posted in another way?

**Comment by kortov** [comment]
I guess it's similar to #97

**Comment by exxbrain** [comment]
> I presume you're asking for the summary comment to posted in another way?

If it is possible then yes. But current solution is nice as well except the case when there are no issues.

**Comment by exxbrain** [comment]
> I guess it's similar to #97

@kortov I think you are right. But I posted a bug because current functionality is conflicting with gitlab settings.

**Comment by exxbrain** [comment]
Gitlab provides 2 endpoints: discussions and notes. Now we use discussions one. https://docs.gitlab.com/ee/api/discussions.html, https://docs.gitlab.com/ee/api/notes.html. I think we can try notes.

**Comment by kortov** [comment]
Let's sum up all of this. I guess it's all should work like checks on github - if check is failed - it prevents merge, and if passed then no matter what the check may write in comments (e.g codecov) it doesn't prevent merge. 
So I guess the plugin should work like this. If quality gate passed - write something not preventing merge (note, resolved thread, autoresolved by plugin thread etc)
I guess this is not implemented now but there are options in gitlab api to work it out and we only should pick the suitable one. Am I right?

**Comment by exxbrain** [comment]
Yes. We need to solve 2 requirements when no issues found:
1. No notification.
2. Note (discussion) should be resolved. (This will allow auto-merge).

By the way
> If quality gate passed

This doesn't mean that there are no issues. I think code human reviewer should decide in this case.

**Comment by mfolnovic** [comment]
From my point of view, it makes sense to use Discussion API for issues and Notes API for summary. Which is probably what you thought, right?

**Comment by exxbrain** [comment]
The fix for the problem is in the #124.

**Comment by bmaehr** [comment]
Implemented here: https://github.com/bmaehr/sonarqube-community-branch-plugin/blob/editComments/src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/gitlab/GitlabServerPullRequestDecorator.java

**Comment by MCMicS** [comment]
Change #226 will auto resolve the discussion if quality gates passes
