### ISSUE TITLE
Bitbucket server - plugin ignores sonar.host.url param

### ISSUE THREAD

**Issue by dzmitry-rudnouski** [mc1arke/sonarqube-community-branch-plugin#111]
**Describe the bug**
Bitbucket server - plugin ignores sonar.host.url param. As result icons are not displayed in PR decoration and "View in SonarQube" url points to default localhost.

**To Reproduce**
1. Run sonar scanner with sonar.host.url parameter
2. See pull request decoration

**Expected behavior**
Icons and "View in SonarQube" url point to provided url.

**Screenshots**
![sonar](https://user-images.githubusercontent.com/19704782/75433451-05123300-5961-11ea-891c-86b0da285210.png)

**Software Versions**
 - SonarQube Version: 8.0
 - Plugin Version: 1.3.0

**Additional context**
Workaround: go to SonarQube -> Administration -> Configuration -> General -> Server base URL and set url manually.

**Comment by mc1arke** [comment]
I don't think this is a valid use-case. The plugin doesn't have anything in it to allow `sonar.host.url` to be specified from the command line, and I'm not aware of Sonarqube core allowing it either. I think you can only set the property from the UI or in server-side configuration. Where are you seeing a suggestion that `sonar.host.url` can be set from the command line?

**Comment by dzmitry-rudnouski** [comment]
@mc1arke please see this doc:
https://docs.sonarqube.org/latest/analysis/analysis-parameters/

Analysis / Command line parameters, defined when launching an analysis (with -D on the command line), override project analysis parameters.

sonar.host.url is mandatory parameter.

**Comment by rusguliev** [comment]
> @ mc1arke, пожалуйста, смотрите этот документ:
> https://docs.sonarqube.org/latest/analysis/analysis-parameters/
> 
> Параметры анализа / командной строки, определенные при запуске анализа (с -D в командной строке), переопределяют параметры анализа проекта.
> 
> sonar.host.url является обязательным параметром.

These are the scanner settings (not the SQ server).

**Comment by mc1arke** [comment]
As @rusguliev has indicated, `sonar.host.url` tells the scanner how to connect to Sonarqube, it doesn't drive what's used in decoration for building the URL for loading images from. `sonar.core.serverBaseURL` is the property you'd need to set, but this can't be over-ridden from the command line.

**Comment by dzmitry-rudnouski** [comment]
@mc1arke Ok, got your point, thank you.
