### ISSUE TITLE
No value for coverage difference for branches

### ISSUE THREAD

**Issue by emil-nasso** [mc1arke/sonarqube-community-branch-plugin#12]
We are using this plugin for a project in sonarqube but are having issues with coverage on branches.

In this exemple, we have a master-branch with 75.3% coverage and a branch with 81.4%. 

In the column for coverage difference we just get a dash. Is this a bug?

![](http://take.ms/fnt2U)
![](http://take.ms/hS7dS)

**Comment by mc1arke** [comment]
Can you confirm which version of SonarQube you're running please?

**Comment by emil-nasso** [comment]
I am running `Community EditionVersion 7.7 (build 23042)` with version `1.0.2` of this plugin.

**Comment by heidricha** [comment]
For me, the coverage value totally lost for the master branch. It is only present in the branches, but not as a graph, just a value in the metrics tab.  Anyway, is there a way to select which is the master branch (or is it hardcoded to "master"), or more convenient: which is the parent branch of the current one? We have got several releases, all of them have fixes and features in a single repository.

**Comment by mc1arke** [comment]
The primary branch is the first one scanned in your project. The selection of target branches is then controlled by the `sonar.branch.target` parameter, defaulting to the primary branch if this isn't set. You'll also need to account for short-lived versus long-lived branches which is controlled by the regular expression in the project configuration.

**Comment by heidricha** [comment]
Thanks! Are there any other secret options? ;)
I have already set up the long-lived branches regex.

Any idea on why no coverage data for primary branch?

> The primary branch is the first one scanned in your project. The selection of target branches is then controlled by the `sonar.branch.target` parameter, defaulting to the primary branch if this isn't set. You'll also need to account for short-lived versus long-lived branches which is controlled by the regular expression in the project configuration.

**Comment by emil-nasso** [comment]
We don't have any problems with coverage on the master-branch, the issue is just that the "coverage change" between master and branches is not shown in the branch-view, as shown in my screenshot.

**Comment by flaviusemil** [comment]
The column that it’s not shown for you is actually the coverage for the new code? Do you have any new code or just unit tests?

**Comment by emil-nasso** [comment]
I think we found the problem.

In the branch in sonarqube we had the following error:

> Could not find ref 'master' in refs/heads or refs/remotes/origin. You may see unexpected issues and changes. Please make sure to fetch this ref before pull request analysis.

We build our applications and perform sonarqube scanning in jenkins. Jenkins just checks out the current branch, it doesn't fetch master.

By using the answer in this post we now fetch master before building: https://stackoverflow.com/questions/44433069/jenkins-pipeline-how-do-i-fetch-not-pull-a-different-branch

With that in place we not get full coverage information. 👍 

![http://take.ms/QZmbi](http://take.ms/QZmbi)

Hopefully, this might help someone else. :) Thanks for the responses.
