### ISSUE TITLE
Allow configuring/overriding Pull Request Providers at project level

### ISSUE THREAD

**Issue by nejch** [mc1arke/sonarqube-community-branch-plugin#121]
Thanks for the amazing plugin, we're on GitLab and I'm so thankful we have all this functionality with MR decorations for free and in LTS when it's not even in a paid-tier LTS yet :)

As a follow-up from my comment in https://github.com/mc1arke/sonarqube-community-branch-plugin/issues/118#issuecomment-595986940, I wanted to suggest the ability to configure PR providers and credentials (or override system settings) at the project level. This would solve the following use cases:
- Project admins can more easily configure integrations (see original post of the other issue)
- Multiple instances of GitLab or even different SCM providers can be used across the SQ instance
- More granular permission model for the user with the PR decoration token. Some people might not want to share a single API token for all SCM projects that are being analyzed on SonarQube.

If this isn't feasible, configuring multiple providers at instance level, as is available in higher paid tiers, would also help (if not cover all of the concerns above). See: https://docs.sonarqube.org/latest/analysis/pr-decoration/#header-2

I should say that using GitLab CI with recent SQ versions (8.0+), the commercial versions essentially provide almost zero-configuration setup (except the PR API token) because the sonar-scanner performs auto-discovery from GitLab's CI environment variables, so maybe this would help, and then only the PR API token would need to be configurable on the project level.

I think the above also covers source/target branches, MR id, etc. I haven't checked to see if this is fully replicated with this plugin, but I will give it a try later and open a separate issue if needed.

**Comment by nejch** [comment]
Ugh, looks like I'm an idiot and this is already possible? I was just looking at our production instance at work, which had an older version of the plugin. Sorry! Has anyone tried configuring some of this via `sonar-project.properties`?

I won't close this just yet as the documentation is lacking so I'll try to open a small doc PR for this :)

**Comment by mc1arke** [comment]
Closing since this no longer seems to be an issue. I'm happy for this to be re-opened if further details are available, or a Pull Request raised if further documentation is required.
