### ISSUE TITLE
Problem with long lived branch

### ISSUE THREAD

**Issue by lwiedenhoeft** [mc1arke/sonarqube-community-branch-plugin#13]
If Sonarqube identifies a branch as a "longLivedBranche"(based not the regex expression), the sonar analysis breaks with the following error:

![image](https://user-images.githubusercontent.com/17198911/58955140-6377ff80-879b-11e9-943d-acef2d2342e8.png)

No issues with short living branches.

Sonarqube Version: 7.7.0
Branch Plugin Version: 1.0.2

**Comment by mc1arke** [comment]
Could you provide full replication steps for this please? To replicate this, you'll need to confirm:
1. What configuration/properties needs set on a project (or if it's the default SonarQube project configuration)
2. Which branches need scanned and in what order
3. Where and when to look for any error messages

**Comment by mc1arke** [comment]
Closing as 'unable to replicate' until further information provided
