### ISSUE TITLE
[GitHub][PR Decoration] Private Sonarqube server static images unavailable

### ISSUE THREAD

**Issue by Brialius** [mc1arke/sonarqube-community-branch-plugin#130]
**Describe the bug**
Github uses `https://camo.githubusercontent.com/` to proxy any user images on their side and this [cannot be disabled](https://stackoverflow.com/questions/57857193/github-image-without-camo). It means every image should be available for GitHub proxy server, which is impossible with the way of serving static images #80 for private hosted Sonarqube server behind a strict firewall.

**To Reproduce**
1. Setup CE Branch plugin on a private Sonarqube server
2. Use GitHub as a provider
3. Run Sonarqube branch check

**Expected behavior**
Static images are available in GitHub PR checks for private and public accessible Sonarqube servers

**Screenshots**
![image](https://user-images.githubusercontent.com/6441812/76855773-e23db500-6862-11ea-9690-2abfffbe553b.png)

![image](https://user-images.githubusercontent.com/6441812/76855816-fd102980-6862-11ea-9784-132639e98f4d.png)

**Software Versions**
 - SonarQube Version: Version 7.9.2 (build 30863)
 - Plugin Version: 1.3.0

**Additional context**
Please return back function of `com.github.mc1arke.sonarqube.plugin.branch.image-url-base` and make it optional or provide other way to solve this issue.

**Comment by don-vip** [comment]
I guess a partial revert of #81 is needed to reintroduce the property I removed?

**Comment by choi-inkyun** [comment]
I have the same problem. The problem arises because the my sonarqube server is 'http' and github is 'https'.

**Comment by dzianisbeliatski-nbcuni** [comment]
> I guess a partial revert of #81 is needed to reintroduce the property I removed?

Yeah, looks like that..

**Comment by Brialius** [comment]
> I guess a partial revert of #81 is needed to reintroduce the property I removed?

Yeah, looks like that..
