### ISSUE TITLE
Is 1.3.0 plugin work for 7.9 with pull request in gitlab decoration?

### ISSUE THREAD

**Issue by hluguoj** [mc1arke/sonarqube-community-branch-plugin#133]
I install the plugin 1.3.0 in sonarqube 7.9, and use the gitlab server.
but I get the error "**No decorator found for this Pull Request**" when I report to sonar server

**Comment by mc1arke** [comment]
Yes, 1.3.0 should work with Sonarqube 7.9. You'll need to give more details about your configuration if you want support on this.

**Comment by mc1arke** [comment]
Closing due to the lack of details and response. Please re-open if you continue to have issues and can provide further details.
