### ISSUE TITLE
[Gitlab] Compact mode of file comments

### ISSUE THREAD

**Issue by bmaehr** [mc1arke/sonarqube-community-branch-plugin#139]
**Describe the Enhancement**
Compact mode of file comments

**Additional context**
The file comments are much to bulky, so it should be possible to use a more compact form.

**Comment by bmaehr** [comment]
I have reimplemented the change based on master if someone is interested ...

**Comment by bmaehr** [comment]
@phermsdorf "All changes required"? There are only 39 lines.

I submitted some patches  a year ago including restructoring the the addiung/updating comments. Unfortunatlly they have never been accepted, so I stopped working on them. In the meantime a big refactoring has happend so applying them is not so easy. Perhaps I will do the rework at some time because I'm going to upgrade my Sonar but at the moment I don't have a timeframe and motivation for it.

**Comment by mc1arke** [comment]
This should be resolved with the new comment structure in #995
