### ISSUE TITLE
[Gitlab] Implement updating comment instead of deleting and recreating

### ISSUE THREAD

**Issue by bmaehr** [mc1arke/sonarqube-community-branch-plugin#141]
**Describe the Enhancement**
Implement updating comment instead of deleting and recreating

**Additional context**
If deleting all comments and recreating them already approved comments get reset, discussions deleted and the MR poluted.

**Comment by bmaehr** [comment]
https://github.com/mc1arke/sonarqube-community-branch-plugin/pull/142

**Comment by bmaehr** [comment]
I have reimplemented the change based on master if someone is interested ...

**Comment by mc1arke** [comment]
Released in v1.9.0 of the plugin

**Comment by mc1arke** [comment]
Backported to 1.8.1 of the plugin for Sonarqube 8.9 support.

**Comment by felixoi** [comment]
@mc1arke Do I need to configure this somehow? Using v1.9.0 and it's creating a new summary every time + resolving the old one (not even deleting the old..)-

**Comment by teake** [comment]
> @mc1arke Is there any chance to still delete the old summary or only update the first summary post every time? I'm using version 1.9.0 and the comment spam with summaries is insane when pushing some commits to a merge request.

@felixoi That bugged me too, so I've opened #494.
