### ISSUE TITLE
Allow override Github App name from CLI

### ISSUE THREAD

**Issue by Brialius** [mc1arke/sonarqube-community-branch-plugin#144]
In case of several projects in one repository it might be useful to have ability to change App name for different Sonarqube checks. Github can handle this and will combine all of them under single Check tab:
![image](https://user-images.githubusercontent.com/6441812/77522323-21888900-6e95-11ea-9f56-4a41aa4ba4dd.png)

To enable this ability, `sonar.alm.github.app.name` needs to be configured from CLI (scanner)
PR with proposal: #143

**Comment by mc1arke** [comment]
Closing this given the use case seems to be very specialized and no other reactions have been added to this issue to indicate other people would like the feature.
