### ISSUE TITLE
Short-lived branch -> no issues

### ISSUE THREAD

**Issue by matizk144** [mc1arke/sonarqube-community-branch-plugin#15]
### Expected Behavior

New Issues appear (difference) in Issues tab in short-lived branch

### Actual Behavior

Once I purposely added new bug (possible null reference exception in c# code) in pull request branch, that bug was recognized and presented in Overview tab. But if i go to issues tab, I see nothing.

Example for PR-60 (Short lived branch) from develop (Base branch)

[Overview tab](http://kramarzowie.eu/sonar/overview.png)
[Issues tab](http://kramarzowie.eu/sonar/issues.png)

In addition I see interesting error on top, that lanalysis is failed. I observed that error appear on any failed analysis (develop branch - base) included. Could be this error related?

[Error](http://kramarzowie.eu/sonar/error.png)

### Plug-in version, SonarQube version, CI system, build type

Sonar: 7.7.0.23042
Community Branch Plugin: 1.0.2

**Comment by mc1arke** [comment]
I suspect your errors are related. Is there any more details in your SonarQube logs to indicate what the error is?

**Comment by matizk144** [comment]
Thanks for reply. Today I had issue, that disk was full and for recover SonarQube I had to wipe all elastic search indexes, becasue had read only mode. Afer Sonar reboot everyting start work fine :) Now everything worsks as expected.

Thanks for help
