### ISSUE TITLE
Not Able to integrate ALM on Azure Devops Server 

### ISSUE THREAD

**Issue by pratikibm** [mc1arke/sonarqube-community-branch-plugin#152]
**Describe the bug**
Not Able to integrate ALM on Azure Devops Server. using sonarqube 8.2 and 1.3.0 sonarqube-community-branch-plugin.
**To Reproduce**
1. Go to 'Global setting'
2. Click on 'Administartion'
3. click on 'ALM integration'

**Expected behavior**
Should able to do  Decorating Pull Requests on Azure DevOps server

**Screenshots**

**Software Versions**
 - SonarQube Version: 8.2
 - Plugin Version: 1.3.0
![ALM](https://user-images.githubusercontent.com/20286321/78677939-f4f95600-7905-11ea-8d4e-8c779fb5ccc9.png)

*Additional context**

**Comment by mc1arke** [comment]
This is expected.

You need to be using a build of #156 to allow configuring PR decoration with Sonarqube 8.2 (or #58 if using Sonarqube 8.1) as these implement these new WebServices that the Sonarqube front-end is trying to call. However, the plugin does not currently support Azure DevOps, so you'll also need to try merging #123  if building the plugin locally.
