### ISSUE TITLE
PR decoration on github

### ISSUE THREAD

**Issue by eddycharly** [mc1arke/sonarqube-community-branch-plugin#16]
Hi, thanks for the plugin work !

I am trying to decorate my pull requests on github, is this suposed to work ?
I didn't find any settings related to it in the plugin.

Any advice very apreciated ;)

**Comment by mc1arke** [comment]
Sorry, as per the README `the decoration of pull requests with any issues is not currently supported`. It is a feature I would like to introduce at some point, but haven't had the time to work on, as I'm likely to need to write something to call the Github `Checks` API (note: this API hasn't been marked as fully stable) and am likely to require to force the use of SonarQube 7.6 or above to be able to get the Commit Identifier from the scan data.

I'm happy to work with others on getting this implemented, but don't currently have an ETA for picking this up myself.

**Comment by eddycharly** [comment]
Thank you for your feedback.
