### ISSUE TITLE
Sonarqube PR decorator not working

### ISSUE THREAD

**Issue by abhijeetsingh89** [mc1arke/sonarqube-community-branch-plugin#163]
I am using the sonar-decorator plugin,everything seems fine ,but here i wanted the PR analysis to be showed in github checks with bugs,and vulnerabilities count,is there any way we can acheive it?

**Comment by mc1arke** [comment]
I'm not sure what your question/issue is. This plugin supports decorating Github PRs, but given you've not specified anything about Sonarqube or plugin versions, or any configuration you've applied, it's a bit difficult to provide any support

**Comment by abhijeetsingh89** [comment]
So we are using sonarqube 7.9 LTS ,also we are using jenkins to scan the projects,i want to publish the analysis report in github while raising a PR 
 stating PR with the vulnerabilities / bugs found during analysis.

Is there any way?

**Comment by marian-craciunescu** [comment]
I have a similar question.
I'm using SOnarqube 8.2, and I want to add pull request statistics to a github repository.
I've installed the latest plugin version,
