### ISSUE TITLE
is there anyway to change the default branch

### ISSUE THREAD

**Issue by abhijeet-netizen** [mc1arke/sonarqube-community-branch-plugin#165]
Is there any way to change  the default branch from master to develop instead of renaming the branch

As mostly i need to set the base branch as develop instead of master,please let how can i do that?
I am using Sonarqube version 7.9 LTS

**Comment by mc1arke** [comment]
No, this currently can't be changed. See #32 for details.

**Comment by janvanveldhuizen** [comment]
You can: see this link: [https://rajbos.github.io/blog/2021/02/12/SonarQube-change-branch-community-version](https://rajbos.github.io/blog/2021/02/12/SonarQube-change-branch-community-version)
