### ISSUE TITLE
[GitHub] PR decoration missing with trace error Current analysis is not for a Pull Request

### ISSUE THREAD

**Issue by balusarakesh** [mc1arke/sonarqube-community-branch-plugin#166]
Thank you for this product
**Describe the bug**
For some reason our branch is NOT considered as a pull request and it is skipping all the PR decorations, sonar scanning works fine though.
This took me quite a while to debug and I still feel like I'm not looking in the right place.

**Expected behavior**
PR decorations on the pull request

**Software Versions**
 - sonarqube version: 7.9.2-community
 - java version 8
 - Plugin Version: 1.3.0

**Additional context**

here are the sonar parameters
The PR number 111 exists for sure (this is a private repo)
```
-Djsse.enableSNIExtension=true -Dsonar.host.url=https://SONAR_URL/ -Dsonar.login=SECRET_HERE -Dsonar.exclusions=**/dto/* -Dsonar.pullrequest.branch=feature-update-sonarqube-config -Dsonar.pullrequest.key=111 -Dsonar.pullrequest.base=development -Dsonar.branch.name=feature-update-sonarqube-config -Dsonar.pullrequest.github.repository=${COMPANY_NAME}/${SERVICE} -Dsonar.pullrequest.provider=github
```
I printed the object `projectAnalysis.getBranch().toString()` after this line (https://github.com/mc1arke/sonarqube-community-branch-plugin/blob/master/src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/PullRequestPostAnalysisTask.java#L79) and this is what I see in the logs

```
ce.log-2020.05.07 06:26:05 DEBUG ce[AXHtz_zJZnbACDrAHIAm][c.g.m.s.p.c.p.PullRequestPostAnalysisTask] found 3 pull request decorators
ce.log:2020.05.07 06:26:05 TRACE ce[AXHtz_zJZnbACDrAHIAm][c.g.m.s.p.c.p.PullRequestPostAnalysisTask] Current analysis is not for a Pull Request. Task being skipped
ce.log-2020.05.07 06:26:05 TRACE ce[AXHtz_zJZnbACDrAHIAm][c.g.m.s.p.c.p.PullRequestPostAnalysisTask] Optional[Branch{isMain=false, name='feature-update-sonarqube-config', type=SHORT}]
```
All the values in the GitHub settings are filled appropriately, weirdly I'm not seeing any errors in `ce` or `web` logs. As you can see above I've enabled trace logs

**Comment by mc1arke** [comment]
Remove the entry `-Dsonar.branch.name=feature-update-sonarqube-config` from your scanner arguments. The plugin has to decide if it's a branch analysis or a pull request analysis and does so based on which properties you pass. Any `branch` properties cause the plugin to treat the scan as a branch analysis.

**Comment by balusarakesh** [comment]
@mc1arke thank you for a quick reply,
I'm seeing the decorations now but they are all empty, I'm facing this issue - https://github.com/mc1arke/sonarqube-community-branch-plugin/issues/104

I did set the `-Dsonar.scm.revision` to the latest commit id in the pull request

**Comment by balusarakesh** [comment]
also the links are pointing at `localhost:9000`
```
## 0 Issues
- ![Bug](http://localhost:9000/static/communityBranchPlugin/common/bug.svg?sanitize=true) 0 Bugs
- ![Vulnerability](http://localhost:9000/static/communityBranchPlugin/common/vulnerability.svg?sanitize=true) 0 Vulnerabilities
- ![Code Smell](http://localhost:9000/static/communityBranchPlugin/common/vulnerability.svg?sanitize=true) 0 Code Smells

```

**Comment by balusarakesh** [comment]
I figured it out, I had to set `sonar.core.serverBaseURL` on the server
