### ISSUE TITLE
Document or implement setting branch scoped "new code period"

### ISSUE THREAD

**Issue by jensborrmann** [mc1arke/sonarqube-community-branch-plugin#169]
Currently setting new code period for branches (https://docs.sonarqube.org/latest/branches/overview/) does not seem to possible. 

This should be either implemented or mentioned as an additional caveat in the documentation.

**Comment by mc1arke** [comment]
Can you confirm which version of Sonarqube and which version of the plugin you're using please?

**Comment by jensborrmann** [comment]
Sonarqube: 7.7.0.23042
Plugin: 1.0.2

I did not confirm by installing that the feature is still not available in more recent versions, but by reading source code. Hopefully, I did not miss anything.

**Comment by mc1arke** [comment]
The options of setting New Code Period on branches were only introduced in SonarQube 8, and are made visible based on the presence of the branch management features, so there's not been any requirement to explicitly do anything in the plugin to manage this.
