### ISSUE TITLE
Can not switch branch from Sonarqube UI

### ISSUE THREAD

**Issue by olivierboudet** [mc1arke/sonarqube-community-branch-plugin#17]
In sonarqube 7.4, I can see branches in the project summary but I can not switch from the master to others.

In the chrome console, I can see an error 404 on this request : 
```
/api/navigation/component?componentKey=myproject-main&branch=develop%C2%A0
```
This does not happen on all projects. I do not know if there is a link but only project in TypeScript seems to have this issue.

Same happen with sonar-scanner : 
```
ERROR: Caused by: Target branch 'develop' does not exist
```

**Comment by mc1arke** [comment]
`%C2%A0` is a non-breaking space. Do you have a branch that has bad characters in its name on the impacted project?

**Comment by olivierboudet** [comment]
You are right, I found a non-breaking space in the script executing sonar-scanner which create an invalid branch.

Thanks for your help and sorry for the inconvenience, I close this issue.
