### ISSUE TITLE
PR analysis find hardly any new code to analyze

### ISSUE THREAD

**Issue by Stanislaw000** [mc1arke/sonarqube-community-branch-plugin#170]
Hello,
First of all thanks for creating rally nice plugin - it is great work!

Plugin version: 1.3.0
SonarQube version: 7.9.3
Azure Devops cloud

I manage to configure plugin and it is somehow working (there is connection and PR analysis is performed), but there is hardly any new code detected.

For big PR'e with about 20 classes changes and 5 new classes added analysis find only 2 changed files and performs analysis on them, while other 23 are ignored.

It isn't a problem excluded/included configuration, since analysis of whole project on main branches see all this files, so it seems that somehow plugin is ignoring most of them.

It is big .NET framework 4.5.2 project with about 160 projects.

Expected behavior:
All files changed/added in PR will be analysed by plugin

Results:
Only small parts of changes are detected and analysed compared to pull request view from azure dev ops.

I am also not sure how to debug this and since it is commercial software I can't post logs etc, so could you give me some advice about where to look to find what is wrong?

**Comment by mc1arke** [comment]
This is going to be difficult to diagnose without steps to replicate. I suspect Sonarqube isn't picking up the version control annotations correctly but obviously don't have any evidence to support this. Can you provide some details about your setup: is your build system checking out the branch as-is (no merges or rebases), and how far have the source and target branches diverged?

**Comment by Stanislaw000** [comment]
Thank you for quick anwer. 

I am using standard Azure Devops setup and it is the standard case. I have created feature branch from master and then I am going to merge back to master that branch. Meanwhile there were some merges from other branches to master, but nothing major.

SQ setup is working this way: 
Long living branches (master, current releases) are build nightly if needed by CI and feature branches are build in pull request.

The way how Azure devops handles merging feature branches is that it is making build on merged (not commited branch), so in scenario like this:

new branch: master -> feature_branch.
pull request: feature_branch -> master
Pull request is making merge locally on CI agent and actual build is made on source branch merged into target branch (without commit), so in this case it is master +feature_branch changes. 
For running SonarQube I am using build-in steps in build configuration created by SonarSource.

Is this answering your question or should I elaborate on something more?

**Comment by mc1arke** [comment]
This does answer my question, but doesn't provide my any more insight as to why this might be failing. Sonarqube detects changed files by looking at the SCM blame information, but that should be present if the build has performed a merge of 2 committed branches. Unfortunately without a sample project/scan to help replicate this, there's probably not much more I can do to help resolve this just now

**Comment by mc1arke** [comment]
@Stanislaw000 are you able to provide a sample project that replicates this issue? I've been unable to replicate it and don't have enough detail to allow me to change anything in the project.

**Comment by mc1arke** [comment]
Closing since this can't be replicated. Please add replication steps if you would like this re-opened.
