### ISSUE TITLE
docker compose example not working for me

### ISSUE THREAD

**Issue by cvega** [mc1arke/sonarqube-community-branch-plugin#171]
Attempting to use the docker compose example in the README does not work for me. I was able to find an example that worked without issue here:

https://gist.github.com/Warchant/0d0f0104fe7adf3b310937d2db67b512

Update commit for README incoming.

**Comment by mc1arke** [comment]
Docker compose has since been removed from README and a working file is now included in the repo and used for publishing images containing this plugin to docker hub
