### ISSUE TITLE
Branches and Pull Requests are never deleted in SonarQube 8.x

### ISSUE THREAD

**Issue by egherrmann** [mc1arke/sonarqube-community-branch-plugin#174]
**Describe the bug**
Branches and Pull Requests are never deleted in SonarQube 8.x. This is causing our database to balloon to an enormous size if we don't manually delete branches within SonarQube. 

**To Reproduce**
1. Analyze a branch or Pull Request
2. Wait a month or two
3. Navigate to the _project/branches_ page of your project (e.g. https://example.com/sonar/project/branches?id=project-id)
4. Note that the old branch is still present

**Expected behavior**
Expect branches and Pull Requests to be deleted after 30 days, or another time period based the configured setting value.

**Screenshots**
![image](https://user-images.githubusercontent.com/26093534/82688016-26b04d00-9c26-11ea-830d-8b04928cd548.png)
![image](https://user-images.githubusercontent.com/26093534/82681648-15624300-9c1c-11ea-9ecd-0b63c467e77d.png)

**Software Versions**
 - SonarQube Version: Version 8.2 (build 32929)
 - Plugin Version: Custom build from _sq-8_2-support_ branch at commit _e7219c4af9_

**Comment by egherrmann** [comment]
I noticed after opening this issue that you do have code to support the new purge property in: https://github.com/mc1arke/sonarqube-community-branch-plugin/blob/e7219c4af999f6c0c89ee7b761cde5645cd76dcd/src/main/java/com/github/mc1arke/sonarqube/plugin/CommunityBranchPlugin.java#L87-L100

Whereas I originally suspected that this was simply not implemented for 8.x. So I guess it's a bug that's happening only for me, or in some specific scenario. I'll see if I can gather more logging or other information.

**Comment by mc1arke** [comment]
I'm closing this since I haven't been able to replicate it, but I'm happy to re-open it if you can provide any further details or evidence.

**Comment by gjabouley-invn** [comment]
Hello
we are also facing the same issue, old PRs are not deleted automatically:
![image](https://user-images.githubusercontent.com/47566129/88074992-7785e880-cb78-11ea-8a1a-ac4e2f6dd6c3.png)

Not sure what information you need, we use SQ8.2 and local plugin build 1.2.1-SNAPSHOT.

sonar.dbcleaner.daysBeforeDeletingInactiveBranchesAndPRs is let unconfigured, ie. default to 30

**Comment by egherrmann** [comment]
> Hello
> we are also facing the same issue, old PRs are not deleted automatically:
> 
> Not sure what information you need, we use SQ8.2 and local plugin build 1.2.1-SNAPSHOT.
> 
> _sonar.dbcleaner.daysBeforeDeletingInactiveBranchesAndPRs_ is left unconfigured, ie. default to 30

I originally reported this issue, however, after you comment I checked our SonarQube instance again and both Branches & Pull Requests are now being correctly deleted in all projects. We have _not_ upgrade SonarQube or the Community Branch Plugin in that time. We have performed several upgrades to Jenkins and the Maven code that initiates the Sonar Scanner calls, so _perhaps_ something in there triggered the deletions to start happening again, though I can't find any evidence of what that would be. In any case, it's resolved for me with no obvious explanation.
