### ISSUE TITLE
[Question] No metrics for any of the branches

### ISSUE THREAD

**Issue by simkin** [mc1arke/sonarqube-community-branch-plugin#18]
I am a fairly new user of SonarQube and stumbled upon your plugin, but I am starting to doubt if I am using it correctly, I hope that you can either confirm that or point me in the right direction. Sorry of the mistakes I make are obvious.

I have started running sonar-scanner for master branch and the results get displayed in SQ correctly, with many smells/issues detected.
Next, I checked out a branch "sprint_nn", edited the sonar.properties files and added the sonar.branch.name=xxx name. This branch becomes visible in SQ, but all of the metrics/issues/measures/code tabs shows nothing (all passed, while master fails while many smells/issues)

Am I using your plugin incorrectly?

**Comment by mc1arke** [comment]
Sonarqube only shows new issues on branches? If your branch only contains the same issue as its target branch then you'll pass the quality gate and get no issues shown. Try creating a new issue on your branch then re-running the scan and see if that appears in SonarQube.

**Comment by simkin** [comment]
So all the issues/smells that already got detected in master, but also resides in a branch, will not get shown in the branch level? (and this is expected behaviour?) Sorry for the likely obvious question

**Comment by mc1arke** [comment]
Yes, all issues on master aren't shown against the branch, and this is expected behaviour. See https://docs.sonarqube.org/latest/branches/short-lived-branches/ for details.
