### ISSUE TITLE
[Github] PR Decoration - Annotation on wrong line

### ISSUE THREAD

**Issue by cncgoko** [mc1arke/sonarqube-community-branch-plugin#189]
**Describe the bug**
On Github PR decoration, annotation for single line issues are reported on the wrong line, because end line of the annotated error is incremented by one.

**To Reproduce**
1. Explore any issue in PR Checks decorator

**Expected behavior**
Annotation should be made on the last line of the issue. If the issue is single lined, the annotation should be made on that single line.

**Screenshots**
No screenshot available

**Software Versions**
 - SonarQube Version: 7.9.3
 - Plugin Version: Release 1.3.1

**Additional context**
The issue seems to come from line https://github.com/mc1arke/sonarqube-community-branch-plugin/blob/230d84e325182b1e6ed760f8797aee31fbbecf80/src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/github/v4/GraphqlCheckRunProvider.java#L230
I'm not sure if it's by design, or any requirement from Github API, but there is a suspicious `+ 1` that can be the cause of this issue

**Comment by mc1arke** [comment]
If you think you have a potential fix and can prove it resolves the issue then feel free to submit a Pull Request.

**Comment by marvin-w** [comment]
This can be closed.

**Comment by mc1arke** [comment]
The fix has been released in 1.3.2 of the plugin (Sonarqube 7.8-8.0) and 1.4.0 (Sonarqube 8.1)
