### ISSUE TITLE
[Github] PR Decoration - Fixed issues are annotated as error

### ISSUE THREAD

**Issue by cncgoko** [mc1arke/sonarqube-community-branch-plugin#190]
**Describe the bug**
After committing on an existing PR to resolve previously idetified issues, the fixed issues appear as issue on line 0-1

**To Reproduce**
1. Create a PR with issues
2. Let Sonarqube analyse and decorate the PR
3. Fix one of the issue and push on the same PR
4. Analyse and decorate again.

**Expected behavior**
Fixed issues should be filtered out of annotated issue. Actually only resolved issues should be annotated.

**Screenshots**

**Software Versions**
- SonarQube Version: 7.9.3
- Plugin Version: Release 1.3.1

**Additional context**
A filter should be added here https://github.com/mc1arke/sonarqube-community-branch-plugin/blob/230d84e325182b1e6ed760f8797aee31fbbecf80/src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/github/v4/GraphqlCheckRunProvider.java#L227
something like 
```
.filter(i -> i.getIssue().getResolution() == null)
```
or 
```
.filter(i -> i.getIssue().getStatus() == org.sonar.api.issue.Issue.STATUS_OPEN)
```
See Sonarqube issue status for more info: https://github.com/SonarSource/sonarqube/blob/3f6f5496277c76c2498fd245a112931d19830497/sonar-plugin-api/src/main/java/org/sonar/api/issue/Issue.java

I can open a PR if the proposed solution is ok.

**Comment by mc1arke** [comment]
Fix release in 1.3.2 of the plugin (Sonarqube 7.8-8.0) and 1.4.0 (Sonarqube 8.1)
