### ISSUE TITLE
PR decoration not working on Github

### ISSUE THREAD

**Issue by arunava-st** [mc1arke/sonarqube-community-branch-plugin#203]
**Describe the bug**
Using Github, Sonarqube 8.0 and plugin version 1.3.1, on sonarqube the branch analysis is showing up fine but the PR in Gihub is not getting decorated. Enabled debug logging on the sonar analysis but still getting no logs as to why the decoration is not working. We are getting nothing on the PR. Need help on what is being missed.

**Expected behavior**
The PR should get decorated or an error in the logs if something is wrong with the configuration.

**Software Versions**
 - SonarQube Version: 8.0
 - Plugin Version: 1.3

**Comment by arunava-st** [comment]
@mc1arke Any inputs from you would be very valuable, can you please let me know what logs etc. do I need to enable to get what error is happening?

**Comment by Rory898** [comment]
Enable Trace Logging under Administration>System
Run your scan again
Set logging level back to Info
Download the Compute Engine Log and check it to see if there are any stack traces around where it says pull request decoration failed

**Comment by mc1arke** [comment]
@arunava-st as @Rory898 has said, you need to change the log levels and check the Compute Engine logs. You'll either get a message telling you that no decorators have been set, a message from a specific decorator telling you that it's missing properties, or a stacktrace telling you what the failure was if the decorator did try and execute. We'd need you to provide as much of that log as possible with as minimal removal/obfuscation of values if you can.

**Comment by arunava-st** [comment]
Sorry for being late, the issue was resolved. Thanks.

**Comment by PeterPorzuczek** [comment]
> Enable Trace Logging under Administration>System
> Run your scan again
> Set logging level back to Info
> Download the Compute Engine Log and check it to see if there are any stack traces around where it says pull request decoration failed

Please add it somewhere in readme
