### ISSUE TITLE
Branch name with forward slash "/" support

### ISSUE THREAD

**Issue by josephlim75** [mc1arke/sonarqube-community-branch-plugin#205]
Is not a bug but clarification.  We are currently running SonarQube CE 7.9.  We ran into branch name issue where it doesn't support forward "/" because we are following branching model like feature/*, bugfix/* and etc.

Would like to know if we install this plugin into our SonarQube server, will it resolve the branching character limitation ?

This is the error

> Task :sonarqube
batching:feature/FERM-666" is not a valid project or module key. Allowed characters are alphanumeric, '-', '_', '.' and ':', with at least one non-digit.

**Comment by mc1arke** [comment]
@josephlim75 I'm not sure what process you're following that results in that message, but can confirm that the plugin allows branches with slashes in the name
