### ISSUE TITLE
support sonarqube 8.3 ?

### ISSUE THREAD

**Issue by lanbiter** [mc1arke/sonarqube-community-branch-plugin#219]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Software Versions**
 - SonarQube Version: [e.g. Version 7.8 (build 26217)]
 - Plugin Version: [e.g. 1.1.0, or custom build from master at commit 004AD34FAA]

**Additional context**

**Comment by mc1arke** [comment]
Sonarqube 8.3 is supported from the (unreleased) master version

**Comment by lanbiter** [comment]
Hey man, could you please help to compile current master branch(8.3) into a JAR for me, cus i have some trouble compiling it locally using my own computer, this is my mailbox : wklworkmail@gmail.com. Thx very much and looking forward to hearing from you.
