### ISSUE TITLE
[Question][Github] Does plugin support Github Enterprise?

### ISSUE THREAD

**Issue by achmudas** [mc1arke/sonarqube-community-branch-plugin#220]
Hi,

I have setup application according https://docs.sonarqube.org/7.9/analysis/pull-request/ but from ce.log getting `No commit details were submitted with this analysis. Check the project is committed to Git` and pull request is not decorated.

Is Github enterprise supported? If yes maybe issue is that the repository is private?

Thank you.

**Comment by mc1arke** [comment]
Yes, Github enterprise is supported. You log snippet indicates that the scanner did not submit and SCM Blame information to the Compute Engine as part of the analysis which means the decorator would have no way of knowing which lines to annotate in a Pull Request. Can you confirm if your checkout or build process is doing any steps that would prevent Sonarqube having the Git information available to it?

**Comment by achmudas** [comment]
Ok, I don't what was the issue, but took newer plugin version 1.3.2, configured everything again ant it's working. Probably missed something in configuration. Thank you for the support.
