### ISSUE TITLE
[INFORMATION] Any plans to support Sonar 8.4?

### ISSUE THREAD

**Issue by rogeraraujo90** [mc1arke/sonarqube-community-branch-plugin#222]
I tried use this plugin in a Sonar Community 8.4 instance but I'm getting an Error from server. Seems like the support of tag 1.4.0 is just for Sonar 8.1

Can we wait for a version with support for Sonar 8.4 soon?

Thank you!

**Comment by PiekJ** [comment]
Hello, have you tried the current version of the master branch?

**Comment by rogeraraujo90** [comment]
No. I haven't. It's supposed to work!? :)

**Comment by nixel2007** [comment]
It works with 8.3 and may work with 8.4

**Comment by rogeraraujo90** [comment]
I made a build from master code and will test! Thank you!

**Comment by rogeraraujo90** [comment]
I not tested yet. But, there is some schedule to code in `master` code be tagged in a short time?
