### ISSUE TITLE
[Information] SonarQube 8.3 no branch support 

### ISSUE THREAD

**Issue by parapar** [mc1arke/sonarqube-community-branch-plugin#223]
I tried to update the plugin to the 1.4.0 version on my sonar 8.3.1 docker image (8.3.1.34397). At first, I observed that it kind of worked although MR decoration for gitlab did not work. Then I tried to go back to my previous plugin version but now it seems that the branch support is not working at all. I tried to use again the 1.4.0 and it says the very same error: 

> 2020.07.23 18:26:40 ERROR web[AXN868FVpmbZ92AQAAAw][o.s.s.w.WebServiceEngine] Fail to process request http://XXXXXX:9000/api/ce/submit?projectKey=org.irlab%3Aname&projectName=IRLab%20Library&characteristic=branch%3Dbranch-name&characteristic=branchType%3DBRANCH
> java.lang.IllegalStateException: Current edition does not support branch feature
>         at com.google.common.base.Preconditions.checkState(Preconditions.java:508)
>         at org.sonar.server.ce.queue.BranchSupport.createComponentKey(BranchSupport.java:63)
>         at org.sonar.server.ce.queue.ReportSubmitter.submit(ReportSubmitter.java:83)
>         at org.sonar.server.ce.ws.SubmitAction.handle(SubmitAction.java:113)
>         at org.sonar.server.ws.WebServiceEngine.execute(WebServiceEngine.java:110)
>         at org.sonar.server.platform.web.WebServiceFilter.doFilter(WebServiceFilter.java:88)
>         at org.sonar.server.platform.web.MasterServletFilter$GodFilterChain.doFilter(MasterServletFilter.java:139)
>         at org.sonar.server.platform.web.MasterServletFilter.doFilter(MasterServletFilter.java:108)
>         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
>         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
>         at org.sonar.server.platform.web.UserSessionFilter.doFilter(UserSessionFilter.java:88)
>         at org.sonar.server.platform.web.UserSessionFilter.doFilter(UserSessionFilter.java:72)

But I can see a successful integration of the same project with the 1.4.0 version being correctly analyzed (in the Background Tasks
) with branches by sonar. 

Any idea of this weird behavior?

thx in advance!

**Comment by nixel2007** [comment]
Check lib/common and extensions/plugins dir for exact plugin version.
Also 1.4.0 does not support 8.3

**Comment by parapar** [comment]
Hi Nixel, 
  Thank you, after removing all the jars and the docker volumes and recreate them, it is now again working for branches. As expected, PR decoration is not working. I just put here the error in the case it is util when implementing support for 8.3.1: 

> javax.servlet.ServletException: Filter execution threw an exception
>         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:200)
>         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
>         at org.sonar.server.platform.web.UserSessionFilter.doFilter(UserSessionFilter.java:88)
>         at org.sonar.server.platform.web.UserSessionFilter.doFilter(UserSessionFilter.java:72)
>         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
>         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
>         at org.sonar.server.platform.web.CacheControlFilter.doFilter(CacheControlFilter.java:76)
>         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
>         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
>         at org.sonar.server.platform.web.SecurityServletFilter.doHttpFilter(SecurityServletFilter.java:76)
>         at org.sonar.server.platform.web.SecurityServletFilter.doFilter(SecurityServletFilter.java:48)
>         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
>         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
>         at org.sonar.server.platform.web.RedirectFilter.doFilter(RedirectFilter.java:58)
>         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
>         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
>         at org.sonar.server.platform.web.RequestIdFilter.doFilter(RequestIdFilter.java:66)
>         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
>         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
>         at org.sonar.server.platform.web.RootFilter.doFilter(RootFilter.java:62)
>         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
>         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
>         at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:109)
>         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
>         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
>         at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
>         at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
>         at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
>         at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
>         at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
>         at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)
>         at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
>         at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
>         at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:615)
>         at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
>         at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)
>         at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1623)
>         at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
>         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
>         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
>         at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
>         at java.base/java.lang.Thread.run(Unknown Source)
> Caused by: java.lang.NoSuchMethodError: 'java.util.Optional org.sonar.db.alm.setting.ProjectAlmSettingDao.selectByProject(org.sonar.db.DbSession, org.sonar.db.component.ComponentDto)'
>         at com.github.mc1arke.sonarqube.plugin.server.pullrequest.ws.action.GetBindingAction.handleProjectRequest(GetBindingAction.java:63)
>         at com.github.mc1arke.sonarqube.plugin.server.pullrequest.ws.action.ProjectWsAction.handle(ProjectWsAction.java:49)
>         at org.sonar.server.ws.WebServiceEngine.execute(WebServiceEngine.java:110)
>         at org.sonar.server.platform.web.WebServiceFilter.doFilter(WebServiceFilter.java:88)
>         at org.sonar.server.platform.web.MasterServletFilter$GodFilterChain.doFilter(MasterServletFilter.java:139)
>         at org.sonar.server.platform.web.MasterServletFilter.doFilter(MasterServletFilter.java:108)
>         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
>         ... 41 common frames omitted

**Comment by mc1arke** [comment]
1,4,0 of the plugin does not support Sonarqube 8.3. You'll need to create a build from master if you want to run against anything beyond Sonarqube 8.2.
