### ISSUE TITLE
SonarQube Community Branch plugin 1.3.1 Support with LTS 7.9.3 

### ISSUE THREAD

**Issue by WankhadeS** [mc1arke/sonarqube-community-branch-plugin#229]
Hi ,

Am using SonarQube Community LTS 7.9.3
Operating System: Windows Server 2012 R2

Issue: I had updated the SonarQube Community Branch Plugin from v1.1.1 to v1.3.1 but am unable to perform the branch analysis, I had also tried with v1.3.0 and v1.3.2 output is same.

on the below link it says that it is compatible with 7.9 and above
https://github.com/mc1arke/sonarqube-community-branch-plugin/releases

Please provide Solution.

Regards,
Sheetal

**Comment by gbonnefille** [comment]
The same here (SQ  7.9.0.26994).

In the log:
```
2020.08.14 15:37:26 ERROR web[AXPsE+wOCI9R26zWAAZX][o.s.s.w.WebServiceEngine] Fail to process request http://192.168.251.240:9000/api/ce/submit?projec
tKey=prolb.lbsolver&projectName=LBsolver&characteristic=branch%3Ddevelop&characteristic=branchType%3DSHORT
java.lang.IllegalStateException: Current edition does not support branch feature
```

In the marketplace tab, the plugin is identified as installed. In the log: `Deploy plugin Community Branch Plugin / 1.3.2` and no errors.

**Comment by an-sush** [comment]
@WankhadeS  can you confirm if the plugin is copied to both the locations: `extensions/plugins/` and `lib/common/` as defined in the [installation guide](https://github.com/mc1arke/sonarqube-community-branch-plugin#installation)

**Comment by gbonnefille** [comment]
> @WankhadeS can you confirm if the plugin is copied to both the locations: `extensions/plugins/` and `lib/common/` as defined in the [installation guide](https://github.com/mc1arke/sonarqube-community-branch-plugin#installation)

No it wasn't copied in `lib/common`. This was not required by 1.1.1 so I forgot to do it for 1.3.2. I will try again with this tip, thanks.

**Comment by lsbwant** [comment]
It is worked after I copy it to lib/common, Thank you for maintaining the great plugin
