### ISSUE TITLE
[Bitbucket] create project from ALM not working

### ISSUE THREAD

**Issue by josefschabasser** [mc1arke/sonarqube-community-branch-plugin#231]
**Describe the bug**
If an Bitbucket Cloud ALM integration is set up, the feature **Import repositories from your ALM** lights up with a green checkmark. However, if one tries to do this, a red error message on top of the page appears: `Unknown url : /api/alm_integrations/check_pa...`

**To Reproduce**
1. Go to **Administration/General Settings/ALM Integrations** and select **Bitbucket**
2. Enter Server URL (https://api.bitbucket.org) and PAT (base64-encoded `USERNAME:APP_PASSWORD`)
3. Click **Save**
4. See the 2 info boxes right below the save button (they should be green now).
5. Click **+** (plus sign) in the upper right corner (between search box and avatar).
6. Click **Create new project**
7. Select **From Bitbucket Server**
8. An error message on top of the page pops up

**Expected behavior**
No error message, choose bitbucket repo and successfully create project.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/45227795/90150953-7bc3b100-dd86-11ea-9c9b-de6e380c6071.png)

**Software Versions**
 - SonarQube Version: 8.2.0.32929
 - Plugin Version: 1.4.1 (commit 0e8cbea9add2818e85d3c7a7d68ea2f8d75bdd39)

**Additional context**
The plugin is properly installed:
```
$ kubectl exec -n sonarqube sonarqube-sonarqube-8678f8869b-thfbs -it -- ls -lrt -d -1 /opt/sonarqube/lib/common/sonarqube-community-branch-plugin-1.4.1-SNAPSHOT.jar /opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin-1.4.1-SNAPSHOT.jar
-rw-r--r-- 1 sonarqube sonarqube 5105640 Aug 13 13:45 /opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin-1.4.1-SNAPSHOT.jar
-rw-r--r-- 1 sonarqube sonarqube 5105640 Aug 13 13:45 /opt/sonarqube/lib/common/sonarqube-community-branch-plugin-1.4.1-SNAPSHOT.jar
```

**Comment by josefschabasser** [comment]
Successfully upgraded to SQ 8.4.1.35646: same error

**Comment by mc1arke** [comment]
This is expected: the plugin only implements the features for branch management and pull request decoration, not for other ALM integrations (project import, supplementary branch information, authentication etc). Whilst this could theoretically be added in the future, there are no current plans for doing so.
