### ISSUE TITLE
java.lang.IllegalStateException: Current edition does not support branch feature   if sonar.branch.name is set

### ISSUE THREAD

**Issue by cpater** [mc1arke/sonarqube-community-branch-plugin#232]
**Describe the bug**
Plugin is installed in Community-Edition.

The report upload is failing with: Failed to upload report - An error has occurred. Please contact your administrator.
If the param sonar.branch.name is set

The Response from sonar server is HTTP-Status-Code 500.
And the Exception on sonar server side that leads to the 500 is:

java.lang.IllegalStateException: Current edition does not support branch feature

**To Reproduce**
1. Install Plugin
2. run analysis with mvn sonar:sonar without sonar.branch.name is set to create the project
3. run analysis with mv sonar:sonar on other branch (or same) with sonar.branch.name set.
4. See error on mvn The report upload is failing with: Failed to upload report - An error has occurred. Please contact your administrator. and sonar server error: java.lang.IllegalStateException: Current edition does not support branch feature

**Expected behavior**
sonar.branch.name is acceptet and a branch report is assigned to the existing project in sonar

**Software Versions**
 - SonarQube Version: Community EditionVersion 7.9.3 (build 33349)
 - Plugin Version: 1.3.2

**Comment by nixel2007** [comment]
https://github.com/mc1arke/sonarqube-community-branch-plugin#installation

**Comment by cpater** [comment]
thanks. i

**Comment by hectoralicea** [comment]
Is there some secret of setting this up with the helm chart version of sonar qube at https://oteemo.github.io/charts ?
I'm adding the plugin to my values.yaml for the helm install
```
plugins:
  install:
    - "https://github.com/mc1arke/sonarqube-community-branch-plugin/releases/download/1.4.0/sonarqube-community-branch-plugin-1.4.0.jar"
```
I can see that the plugin installed in the Administration/Marketplace/Installed but when I set the value on my mvn command
```
mvn sonar:sonar -Dsonar.branch.name=${BRANCH} -s ./jenkins/settings-kubernetes.xml
```
where BRANCH=ci-pipeline, I get the following error on the my jenkins pipeline:
```
[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar (default-cli) on project ria-jsonify-svc: Failed to upload report - An error has occurred. Please contact your administrator -> [Help 1]
```
and the following error in the sonarqube_web.log.
```
2020.09.22 18:00:39 ERROR web[AXS20BZqdFOowOBoAAGt][o.s.s.w.WebServiceEngine] Fail to process request http://sonar.cicd.svc.cluster.local:9000/api/ce/submit?projectKey=com.duh.tco.ria%3Aria-jsonify-svc&projectName=ria-jsonify-svc&characteristic=branch%3Dci-pipeline&characteristic=branchType%3DBRANCH
java.lang.IllegalStateException: Current edition does not support branch feature
```

**Comment by nixel2007** [comment]
@hectoralicea 
mc1arke/sonarqube-community-branch-plugin#installation
