### ISSUE TITLE
Bitbucket Cloud PR Decoration - Annotation summary is displaying a URL instead of the user message

### ISSUE THREAD

**Issue by ksl67** [mc1arke/sonarqube-community-branch-plugin#233]
The message displayed in the annotation on the pull request is a URL which points to the issue in SonarQube. 

This is because the `summary` field of the annotation body is serialising `link`. See screenshot.

```
public class CloudAnnotation extends CodeInsightsAnnotation {
    @JsonProperty("external_id")
    private final String externalId;
    @JsonProperty("summary")
    private final String link;
    @JsonProperty("annotation_type")
    private final String annotationType;
```

Is this intentional? Would it not be better to serialise the message instead? Then the analysis message is visible directly in the PR.  

Furthermore, I can't see anywhere in the Bitbucket API where `message` is specified in annotation body.

```
public class CodeInsightsAnnotation {
    @JsonProperty("line")
    private final int line;
    @JsonProperty("message")
    private final String message;
```

**Software Versions**
 - SonarQube Version: 8.1
 - Plugin Version: [1.4.0]

![Screenshot 2020-08-23 at 11 23 38](https://user-images.githubusercontent.com/8506869/90976323-ef5a8080-e533-11ea-8643-d551b88147f4.png)

**Comment by ksl67** [comment]
https://github.com/mc1arke/sonarqube-community-branch-plugin/pull/237.

**Comment by mc1arke** [comment]
Release in 1.5.0 of the plugin
