### ISSUE TITLE
Sonarqube 8.4.1: Missing ability to set or pass in project ALM and repository name (Not through the UI)

### ISSUE THREAD

**Issue by Tsuesun** [mc1arke/sonarqube-community-branch-plugin#234]
**Describe the bug**
- Upgrade path 7.9 LTS -> 8.4.1 build 35646

After upgrading two problems have occured:
1. Not able to pass in repository via sonar scanner 
` -Dsonar.pullrequest.github.repository='$org/${repoName}'`
__Note:__ `projectKey` works fine. However `sonar.pullrequest.github.repository` seems to do nothing now (looking at the patch notes I should have gotten a warning that it was being deprecated` but it should have worked)
2. Not able to set a default ALM

These two issues stop the plugin from working.

**To Reproduce**
1. Run sonar scaner on a PR as per normal or a new project passing the `-Dsonar.pullrequest.github.repository` value
2. As admin click on project in Sonar and check the project settings/PullRequestDecorator
3. The settings are empty
4. Check ce.log `No ALM has been set on the current project`

**Expected behavior**
The ALM and repository name are able to be set via the scanner

**Software Versions**
 - SonarQube Version: 8.4.1
 - Plugin Version: custom build from master at commit 0e8cbea9add2818e85d3c7a7d68ea2f8d75bdd39

**Additional context**
Manually setting the ALM and entering the `$org\$reponame` enables pull decoration to work however, manually entering this for the hundreds or projects we have is not viable nor for every new project that is created.
Current workaround has been to hardcode these values into: https://github.com/mc1arke/sonarqube-community-branch-plugin/blob/master/src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/PullRequestPostAnalysisTask.java#L95
```
        ProjectAlmSettingDto projectAlmSettingDto = new ProjectAlmSettingDto();
        Optional<AlmSettingDto> optionalAlmSettingDto;
        try (DbSession dbSession = dbClient.openSession(false)) {
            projectAlmSettingDto.setAlmRepo("$org/" + projectAnalysis.getProject().getKey());
            projectAlmSettingDto.setAlmSettingUuid("$ALM_DB_UUID");
            projectAlmSettingDto.setAlmSlug("");
            projectAlmSettingDto.setProjectUuid(projectAnalysis.getProject().getUuid());

            optionalAlmSettingDto = dbClient.almSettingDao().selectByUuid(dbSession, "$ALM_DB_UUID");
```
*ALM_DB_UUID is pulled from the DB table alm_settings

**Comment by mc1arke** [comment]
This is working as per design. Sonarqube 8.2 introduced APIs for managing the binding of projects to ALMs. These should be used to configure projects rather than trying to set them at runtime since this can lead to incorrect reports and/or results.
