### ISSUE TITLE
[SONARQUBE 8.2] GitLab MR Decoration - Project ALM Settings in Error

### ISSUE THREAD

**Issue by agaillar** [mc1arke/sonarqube-community-branch-plugin#235]
I installed SonarQube 8.2 (build 32929) and the release 1.4.0.
| screenshots |
| --- |
| ![image](https://user-images.githubusercontent.com/17762091/91270738-6af93f00-e779-11ea-9259-5916814f1852.png) |
| ![image](https://user-images.githubusercontent.com/17762091/91270708-5f0d7d00-e779-11ea-8881-e0392a3f32d0.png) |

I configured the README options:
* `admin / configuration / general / sonar.core.serverBaseURL`
* `admin / configuration / AM Integrations / GitLab` (url + reporter personal token with API)

I have the message: "Merge Request Decoration - This feature is enabled" 😃 
| screenshots |
| --- |
| ![image](https://user-images.githubusercontent.com/17762091/91270643-41401800-e779-11ea-91b1-df2febf68490.png) |

I launched a first analysis on the master branch of my project. 🆗 
I launched an analysis on a feature branch with the parameters: 🆗 
```yaml
-Dsonar.pullrequest.gitlab.instanceUrl = https: //gitlab.xxxxx \
       -Dsonar.pullrequest.gitlab.projectId = $ CI_MERGE_REQUEST_PROJECT_ID \
       -Dsonar.pullrequest.key = $ CI_MERGE_REQUEST_ID \
       -Dsonar.pullrequest.branch = $ CI_COMMIT_REF_NAME \
       -Dsonar.pullrequest.base = master \
       -Dsonar.qualitygate.wait = true
```

On the "Project Settings / General Settings / Pull Request Decoration" screen, I have the popup: 

| screenshots |
| --- |
| ![image](https://user-images.githubusercontent.com/17762091/91270929-b3b0f800-e779-11ea-9890-559019ab484f.png) |

The api `{{SONAR_URL}}/api/alm_settings/get_binding?project=xxx` return a 500 error.

In the web logs, i've the error :

```log
2020.08.25 12:30:06 ERROR web[][o.s.s.p.w.RootFilter] Processing of request /api/alm_settings/get_binding?project=xxx failed
javax.servlet.ServletException: Filter execution threw an exception
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:200)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.sonar.server.platform.web.UserSessionFilter.doFilter(UserSessionFilter.java:88)
	at org.sonar.server.platform.web.UserSessionFilter.doFilter(UserSessionFilter.java:72)
...
Caused by: java.lang.NoSuchMethodError: 'java.util.Optional org.sonar.db.alm.setting.ProjectAlmSettingDao.selectByProject(org.sonar.db.DbSession, org.sonar.db.component.ComponentDto)'
	at com.github.mc1arke.sonarqube.plugin.server.pullrequest.ws.action.GetBindingAction.handleProjectRequest(GetBindingAction.java:63)
	at com.github.mc1arke.sonarqube.plugin.server.pullrequest.ws.action.ProjectWsAction.handle(ProjectWsAction.java:49)
```

Do you also have this error ? 
Did I miss something ?

Thanks for your help.

**Comment by PiekJ** [comment]
1.4.0 release is not compatible with SonarQube 8.2. Instead try to compile the master branch yourself and try again.

**Comment by agaillar** [comment]
Oh, i'm sorry. I had not seen the point after `8.1`.
I believed the 1.4.0 release  was compatible with 8.1 and 8.2.

![image](https://user-images.githubusercontent.com/17762091/91845827-23335580-ec5a-11ea-8539-b6f0d484066c.png)
