### ISSUE TITLE
java.lang.IllegalStateException: Current edition does not support branch feature

### ISSUE THREAD

**Issue by Devender210590** [mc1arke/sonarqube-community-branch-plugin#238]
**2020.09.08 17:22:08 ERROR web[AXRuej3fwSHRZWGMAAoz][o.s.s.w.WebServiceEngine] Fail to process request http://sonarqube.XXXXX.com/api/ce/submit?projectKey=notanashtray-aem&projectName=notanashtray-aem&characteristic=branch%3Dmaster&characteristic=branchType%3DLONG
java.lang.IllegalStateException: Current edition does not support branch feature**
        at com.google.common.base.Preconditions.checkState(Preconditions.java:173)
        at org.sonar.server.ce.queue.BranchSupport.createComponentKey(BranchSupport.java:66)
        at org.sonar.server.ce.queue.ReportSubmitter.submit(ReportSubmitter.java:83)
        at org.sonar.server.ce.ws.SubmitAction.handle(SubmitAction.java:121)
        at org.sonar.server.ws.WebServiceEngine.execute(WebServiceEngine.java:110)
        at org.sonar.server.ws.WebServiceFilter.doFilter(WebServiceFilter.java:88)
        at org.sonar.server.platform.web.MasterServletFilter$GodFilterChain.doFilter(MasterServletFilter.java:126)
    

Jar File is copied at both location  as mentioned in Readme.md file (https://github.com/mc1arke/sonarqube-community-branch-plugin/blob/master/README.md)   

sonarqube@sonarqube-dev-sonarqube-76b5998689-76mzx:/opt/sonarqube/extensions/plugins$ 
**-rw-r--r--. 1 sonarqube sonarqube  5082581 Sep  5 04:02 sonarqube-community-branch-plugin-1.3.2.jar**
sonarqube@sonarqube-dev-sonarqube-76b5998689-76mzx:/opt/sonarqube/lib/common$
**-rw-r--r--. 1 sonarqube sonarqube  5082581 Sep  8 17:14 sonarqube-community-branch-plugin-1.3.2.jar**

Version Used : 7.9.4-community (we are using oteemo charts for Sonarqube installation)
Kindly help

**Comment by Devender210590** [comment]
Could you please provide update .. This is a kind of blocker for us to upgrade to next version.

**Comment by artbear** [comment]
I'm stopping on same error for plugin based on current master branch

SonarQube server 8.3

**Comment by y0an** [comment]
Same error on my new setup with SonarQube server 8.4.2.36762 + plugin 1.4.0

**Comment by Joibel** [comment]
@y0an and @artbear  Plugin 1.4 doesn't work with anything other than 8.1. There is a fork https://github.com/anthonybriand/sonarqube-community-branch-plugin that does.

The install process requires that you install this plugin to two locations. I suspect that is the problem for everyone else.

For oteemo charts, I just added the line "cp /opt/sonarqube/extensions/plugins/sonarqube-community-branch* /opt/sonarqube/lib/common" just before the last line /.../run.sh into the sonarqube-copy-plugins config map and deleted the sonarqube pod to make it reinitialise.

**Comment by tpokki** [comment]
No need to modify the ConfigMap manually, you just have to list the branch plugin in `lib` section of your custom `values.yaml` as well:
```
plugins:
  install:
    - "https://github.com/mc1arke/sonarqube-community-branch-plugin/releases/download/1.3.2/sonarqube-community-branch-plugin-1.3.2.jar"
  lib:
    - "sonarqube-community-branch-plugin-1.3.2.jar"
```

Works with version `6.8.0` of `oteemocharts/sonarqube`. 

n.b. if you modify existing installation, the SonarQube pod is not recreated and you'll have to do that (delete) manually.
