### ISSUE TITLE
Branch Analysis is analyzing complete code instead of new code with SonarQube Version 8.1

### ISSUE THREAD

**Issue by umeshchhabra** [mc1arke/sonarqube-community-branch-plugin#240]
Upgraded SonarQube 8.0 to SonarQube 8.1 

SonarQube Version: 8.1
Plugin Version: 1.4

Each Branch analysis is analyzing million of lines of code instead of changed code. This was working with SonarQube Version 8.0 and v1.3 Plugin.

- Master branch is working fine and showing complete code.

- We are not specifying target branch parameter in both 8.0 and 8.1.

- New Code definition is default i.e. Previous Version

Here is the SonarScanner context:
SonarQube plugins:
  - SonarPython 2.3.0.5351 (python)
  - SonarCSS 1.1.1.1010 (cssfamily)
  - JaCoCo 1.0.2.475 (jacoco)
  - SonarGo 1.6.0.719 (go)
  - SonarKotlin 1.5.0.315 (kotlin)
  - Svn 1.9.0.1295 (scmsvn)
  - SonarJS 6.1.0.11503 (javascript)
  - SonarRuby 1.5.0.315 (ruby)
  - SonarScala 1.5.0.315 (sonarscala)
  - SonarC# 8.1.0.13383 (csharp)
  - SonarJava 5.14.0.18788 (java)
  - SonarHTML 3.2.0.2082 (web)
  - Git 1.9.1.1834 (scmgit)
  - SonarFlex 2.5.1.1831 (flex)
  - SonarXML 2.0.1.2020 (xml)
  - SonarPHP 3.3.0.5166 (php)
  - SonarTS 2.1.0.4359 (typescript)
  - SonarVB 8.1.0.13383 (vbnet)
  - Community Branch Plugin 1.4.0 (communityBranchPlugin)
Global server settings:
  - sonar.core.id=AD59B106-AW2d6rOae_NZm8k85jKh
  - sonar.core.startTime=2020-09-11T01:39:31+0000
  - sonar.dbcleaner.daysBeforeDeletingInactiveBranchesAndPRs=5
  - sonar.forceAuthentication=true
  - sonar.jacoco.reportPaths=target/jacoco.exec
  - sonar.python.coverage.reportPaths=coverage-reports/*coverage-*.xml,*results*.xml,*coverage*.xml
  - sonar.python.pylint.reportPath=*pylint*.txt
Project server settings:
Project scanner properties:
  - sonar.branch.name=mybranch
  - sonar.coverage.exclusions=src/**/*.stories.tsx,src/**/*.mock.ts,src/**/*.mock-api.ts
  - sonar.host.url=***
  - sonar.login=******
  - sonar.projectBaseDir=/opt/atlassian/pipelines/agent/build
  - sonar.projectKey=myproject
  - sonar.scanner.app=ScannerNpm
  - sonar.scanner.appVersion=2.7.0
  - sonar.sourceEncoding=US-ASCII
  - sonar.sources=src

**Comment by mc1arke** [comment]
This is how Sonarqube works. Newer versions of Sonarqube  provide an additional view of differences to the target branch, but 8.1 is limited in handling differences unless analyzing a Pull Request.
