### ISSUE TITLE
PR/MR analysis intermittently reporting zero coverage for C++ code

### ISSUE THREAD

**Issue by john-forrest** [mc1arke/sonarqube-community-branch-plugin#245]
**Describe the bug**
We are analysing C++ code using the sonar-cxx plugin running on sonarqube LTS (LTS centos docker image). We are trying to use the branch plugin to get proper reflection of our working style - we use gitlab MRs, so many small, often parallel branches. The analysis is generally working *except* that about 50% of the time the coverage is reported as 0%.

The coverage is being reported via sonar.cxx.coverage.reportPath and the generation of the reports is unchanged in our run (which is happening a Jenkins pipeline build). I sonar-cxx plugin does mention in the log that it sees the coverage report and I have no reason to disbelieve it. I have long assumed that some of the actions occur during the background processing phase and I am wondering if there is a race condition for this plugin perhaps not waiting for the sonar-cxx plugin to finish.

I have only seen this on analysis of a Merge Reqest, although that is our usual place to do sonar runs. branch analysis has sofar been fine. 

**To Reproduce**
Analyse C++ git project. clang debug run is used to generate code coverage data. sonar-cxx plugin setup to take that, also cpp-check and clang-tidy input. Setup to to use branch plugin "pullrequest" settings. See screenshot below.

**Expected behavior**
The coverage should be as expected.

**Screenshots**
Problem case:
![sonarnocoverage](https://user-images.githubusercontent.com/6684282/93750823-056f6580-fbf4-11ea-874e-c7f02086f092.png)

**Software Versions**
 - SonarQube Version: 7.9.4
 - Plugin Version: 1.3.2
 - sonar-cxx version: 1.3.2

**Additional context**
We use "develop" as our default branch on git, rather than master. I have generated a develop version on sonarqube and am comparing to that - although seems that I should read master on sonarqube as "default branch". I plan to make the change. Don't know if this will affect the reported issue - assume not but perhaps that is the only tested scenario. Don't know if others are using sonar-cxx plugin.

**Comment by john-forrest** [comment]
Seems to be that just comparing against the "master"/default branch, rather than a "develop" sonar dataset, works.

**Comment by john-forrest** [comment]
I might have spoken too soon then. Still seems intermittent, just that I am perhaps yesterday I was seeing less of the issue. Might have been fluke.

**Comment by mc1arke** [comment]
I've been unable to replicate this with any build tool I've tried, and don't have enough details to provide steps to try. I'm therefore closing the issue, but feel free to open a new one if you can create a suitable project and minimum set of replication steps this can be seen with.
