### ISSUE TITLE
Github changes in giithub app webhooks.

### ISSUE THREAD

**Issue by Meet116** [mc1arke/sonarqube-community-branch-plugin#248]
Github do the changes in GitHub app webhook actions. https://developer.github.com/changes/2020-04-15-replacing-the-installation-and-installation-repositories-events/  did this thing affects the Github pr decoration app and if yes then where to find this in GitHub.

**Comment by mc1arke** [comment]
The plugin doesn't use webhooks, so this doesn't impact us.
