### ISSUE TITLE
Unable to use this plugin with Azure Devops

### ISSUE THREAD

**Issue by dassay75** [mc1arke/sonarqube-community-branch-plugin#251]
Hi 
I deploy a Sonarqube in a docker containner , tje version is the 7.9.4 ( community edition) , so I download the version 1.3.2 of the plugin in the directory  extensions/plugins and I restart the sonarqube. I can see  now the plugin in the MarketPlace
I update the pipeline and add this parameter: sonar.branch.name with the name of my feature branch.
But When I launch the analyze it fail all the time with this error ( error in pipeline)
##[error]The SonarQube Scanner did not complete successfully

I have also an error in the logs of sonarqube:
java.lang.IllegalStateException: Current edition does not support branch feature

Please can you provide me some help to solve that.
Thanks

**Comment by mc1arke** [comment]
This error indicates the plugin is not properly installed. Please ensure you've deployed the plugin to both locations specified in the README file.
