### ISSUE TITLE
Support for SonarQube 8.4

### ISSUE THREAD

**Issue by adityamenongithub** [mc1arke/sonarqube-community-branch-plugin#256]
**Describe the bug**
This is not a bug per say, But I would like to know when do you think we will able to support SonarQube 8.4. 
If you can point me in the right direction I can try to add a pull request for that change as well. But I don't know where to start :( 

**Software Versions**
 - SonarQube Version: [e.g. Version 8.4 (build 26217)]
 - Plugin Version: [e.g. 1.1.0, or custom build from master at commit 004AD34FAA]

**Additional context**

**Comment by nixel2007** [comment]
https://github.com/mc1arke/sonarqube-community-branch-plugin/issues/222
