### ISSUE TITLE
PR Decoration works but no comments

### ISSUE THREAD

**Issue by robbertvanstaveren** [mc1arke/sonarqube-community-branch-plugin#261]
Hi,

I'm using SQ 7.9.4 and plugin version 1.3.2. This problem exists on Bitbucket Server  v6.10.1. Everything works as expected but I am having some issues with the comments (summary comment). The decoration of a PR works, I can see the line comments but I never see a summary comment. I am expecting to see this comment in the Activity list of a PR where all other comments are

<img width="959" alt="Screenshot 2020-10-22 at 10 47 32" src="https://user-images.githubusercontent.com/15276129/96848165-5d4bf700-1454-11eb-83db-937bed132b8f.png">

<img width="662" alt="Screenshot 2020-10-22 at 10 39 31" src="https://user-images.githubusercontent.com/15276129/96848183-663cc880-1454-11eb-9101-cb06d9eee85f.png">

The settings mention _"This enables the summary comment (if implemented)"_ and I am wondering if I need to do anything else to make this "implemented". Maybe I am expecting to see this comment in the wrong location.

**Comment by bohdantverdyi** [comment]
Hi, have you resolved this ?

**Comment by mc1arke** [comment]
Hi! I suspect I've written a comment and then managed to click 'close' without submitting the comment. I don't currently have access to a Bitbucket Server instance to gather information, but the decorator does have summary comments implemented.

Given 8.9 is the latest Sonarqube LTS, please confirm if you're still seeing problems there and open a new issue if you are.

**Comment by bohdantverdyi** [comment]
Can confirm that sonarqube did't write comment. Only comments in code changes as notes. 

Probably it is normal case, but should sonarqube write general comment for pull Requests ?
