### ISSUE TITLE
enforce project quality failures on pull request decoration

### ISSUE THREAD

**Issue by mojtabye2** [mc1arke/sonarqube-community-branch-plugin#266]
Hi, I am using the PR decoration feature with GitHub and it's working well, but it only fails with issues in the new codes.

it there any way to enforce project quality status to PR, so it fails the check and forces the team to fix all project issues before doing any other contribution to the project?

**Comment by mc1arke** [comment]
The simple answer to this is no.

Sonarqube is specifically designed to report new issues in code so the project quality doesn't degrade over time, and should improve as existing lines are modified, so Pull Request analysis only supports reporting new issues. There is the ability to perform a branch scan to see all issues, but there's no way to decorate an external system with these issues.
