### ISSUE TITLE
Very big icons on PR decoration on Bitbucket server

### ISSUE THREAD

**Issue by racodond** [mc1arke/sonarqube-community-branch-plugin#267]
**Describe the bug**
Very big icons on PR decoration on Bitbucket server
Same issue as https://github.com/mc1arke/sonarqube-community-branch-plugin/issues/204
I'm on version 1.3.2 of the plugin. Is it supposed to be fixed in 1.3.2?

**Software Versions**
 - SonarQube Version: 7.9.2
 - Plugin Version: 1.3.2
 - Bitbucket server: 7.6.0

**Comment by mc1arke** [comment]
Can you provide screenshots please?

**Comment by racodond** [comment]
Hi @mc1arke,

Here it is:

![image](https://user-images.githubusercontent.com/1215713/98212102-6a341480-1f43-11eb-885c-6e30ee0951f2.png)

David

**Comment by baudren** [comment]
I found a div in the html hierarchy, below the link to the svg, which probably overrides any size that could have been read from the svg.
![image](https://user-images.githubusercontent.com/3526120/98214392-ba60a600-1f46-11eb-9bec-09ede2996853.png)
But I could not understand from your com.github.mc1arke.sonarqube.plugin.ce.pullrequest.markup package why is this part added - or indeed if it's you that add this or somehow bitbucket does that automatically.

**Comment by mc1arke** [comment]
The plugin will generate a line of text as `**Type:** CODE_SMELL ![code_smell](image_url)`, so the actual rendered divs are something that's generated by Bitbucket. Unfortunately I don't think we have any real control over the styling and sizing of components when using markdown, but I'll see if there's any guidance in the Bitbucket documentation

**Comment by baudren** [comment]
I found [this ticket](https://jira.atlassian.com/browse/BSERV-7426) that looks promising - apparently the syntax 

```
![alt text for the image](image-file.png){height=50 width=60}
![alt text for the image](image-file.png){height=100}
![alt text for the image](image-file.png){width=200px}
![alt text for the image](image-file.png){width=30%}
```
should work on bitbucket 7.5.0 or newer (so ok for us). But to see if previous versions accept the syntax without botching the display, or if you could send it conditionnaly on the version?

Cheers

**Comment by racodond** [comment]
Our bad... We forgot to also upgrade the plugin in lib/common. Our apologies for that.
It works fine on 1.3.2.
