### ISSUE TITLE
AzureDevops PR Decoration - comments in PR are not closed

### ISSUE THREAD

**Issue by bambuca** [mc1arke/sonarqube-community-branch-plugin#270]
**Describe the bug**
Some comments remain active in AzureDevops PR, although they are marked as closed in the sonar.
These issues are in sonar twice.

**To Reproduce**
I'm not entirely sure, but I'd say the problem occurs when the pipeline starts in AzureDevops, but before it finish, the programmer make a push with some SQ issues fixes. This cancels the running pipeline and starts a new one. After that the fixed issues are not closed in PR.
1. Create PR with issues
2. Sonnar will create comments in PR
3. Push commit to Azure
4. Azure trigger PR validation pipeline
5. Push commit to Azure with fix of some issues (maybe you have to wait until "Prepare Analysis Configuration" finish, but before "Run Code Analysis" task start.
6. Azure cancels pipeline from step 4 and trigger new one
7. Issue is closed in sonar but not in Azure

**Expected behavior**
I expect that corresponding thread in PR will be closed.

**Screenshots**

**Software Versions**
 - SonarQube Version: 8.4.2.36762 in docker
 - Plugin Version: 1.5.0

**Additional context**

**Comment by bambuca** [comment]
I tried to simulate the error again, but without success. So the problem still exists, but I don't know how to simulate it.
I'll leave the TRACE log enabled and when the problem reappears, I'll check the log and upload it here.

**Comment by bambuca** [comment]
The comments remains active in PR when the source file is removed.
AzureDevops
![image](https://user-images.githubusercontent.com/4871907/99297092-0dd8cb00-2848-11eb-8beb-8b52d26e6e7e.png)

SonarQube:
![image](https://user-images.githubusercontent.com/4871907/99297291-585a4780-2848-11eb-91a0-aeb81cf3f138.png)

**Comment by mc1arke** [comment]
I believe this is fixed by the second commit in #391 . Are you able to test out a snapshot of that build and provide feedback?

**Comment by mc1arke** [comment]
Released in v1.9.0 of the plugin

**Comment by mc1arke** [comment]
Backported to 1.8.1 of the plugin for Sonaqube 8.9.
