### ISSUE TITLE
pr decoration on sonarqube 8.2 is only working if added from project settings page

### ISSUE THREAD

**Issue by dgokcin** [mc1arke/sonarqube-community-branch-plugin#271]
Hello

I managed to get the plugin working on SonarQube 8.2 by adding my configuration name per project

![image](https://user-images.githubusercontent.com/33603535/98966812-c89d5c00-251c-11eb-9695-92fe7f454e5d.png)
 
Is there a way to make it work globally so that I don't have to do the same thing for each project?

Thanks

**Comment by mc1arke** [comment]
No, you can't set this globally. There is an API for doing this though,

**Comment by dgokcin** [comment]
@mc1arke 

How can I do it via the API? Is it like adding something to the sonar.properties file? I would appreciate any help.
