### ISSUE TITLE
Project level new code setting won't save

### ISSUE THREAD

**Issue by thefang12** [mc1arke/sonarqube-community-branch-plugin#272]
**Describe the bug**
Setting new_code_period at the project level doesn't work at all.
**To Reproduce**
1. create a project 
2. go to Project Settings > New Code 
2. set the _Define a specific setting for this project_ setting to any other than global default
3. click save
2. UI will show saved but reloading the page shows the project new_code_period doesn't change

**Expected behavior**
Project new_code_period is persisted once changed from the global default.

**Screenshots**
Setting new_code_period:
<img width="1203" alt="Screen Shot 2020-11-12 at 14 07 35" src="https://user-images.githubusercontent.com/6216023/98990702-6d557480-24f0-11eb-9c14-4a59f744693f.png">
After reload:
<img width="1514" alt="Screen Shot 2020-11-12 at 14 08 12" src="https://user-images.githubusercontent.com/6216023/98990828-9d9d1300-24f0-11eb-9431-13a22f54f57a.png">

**Software Versions**
 - SonarQube Versions: 8.4.1, 8.4.0,8.4.2
 - Plugin Version: 1.5.0

**Additional Comments**
The feature works correctly at global and branch levels.
Tried setting it  using the UI and the web API and both return a 200 without persisitiing the new_code_period change. The only workaround I've found is to insert the new_code_period record in the new_code_periods table manually 😞 .

**Comment by anand-ispg** [comment]
@thefang12 I also had this issue but If you notice while making changes, it says this setting will apply after your next scan. So after making the change and running another analysis it worked.

**Comment by powerdefy** [comment]
I also have the issue.

**Comment by thefang12** [comment]
@anand-ispg when you change the setting in the UI it retroactively changes any branch that has already been scanned to the new_code_period that why it works on next scan, the issue is for any **new branches** it still uses the global new_code_period not the one set at a project level. 
@powerdefy it's not a nice workaround, but the only thing that got this working was to manually access the DB and insert a new_code_period record with the project uuid and  branch name column null in the new_code_periods table. Hope it helps.

**Comment by powerdefy** [comment]
@thefang12 Thank you, I insert a new row manually and it works.

**Comment by Dr-Dream** [comment]
Same for me.
When setting reference branch for project it fills new_code_period.branch_uuid with project_uuid. if update branch_uuid null it works.

**Comment by mc1arke** [comment]
@Dr-Dream can you confirm the exact steps your taking here? I presume this is updates to values in the database you're making, so it would be useful to know which tables and columns you're altering, and example of their pre and post change values are

**Comment by Dr-Dream** [comment]
@mc1arke ,

As it works for me.

As i understood, according to what i saw during changes in new_code_periods through UI - project_uuid and branch_uuid have same value. 

So when you change project settings from default new record in new_code_periods record filled project_uuid and branch_uuid with same uuid value.

So if branch_uuid is set, setting reffers to master branch only.

Actually, currently, there is no way to change this settings at project level.
Branch-level settings only.

If barnch_uuid is null it counted as project settings.
i discovered it updating record for master branch, by 'update new_code_periods set  branch_uuid=null where .....' directly in postgres.

After that i've changed through UI settings exactly for master branch, because it should differs from project one (should not reffer itself).

After that all new analisys for new branches done against master.

I hope it will helps.

One more note. There is no unique constraints on table, so accidentally you could make two or more settings at project level. That will be followed by errors and you'll be not able to get project level settings of new code at all.
Experienced myself.

**Comment by Dr-Dream** [comment]
Exact steps to fix for 1 project, not a simpliest one. :)
For multiple projects at once i don't have solution..

1) Newly created project

![image](https://user-images.githubusercontent.com/16628588/100471988-72b7df00-30ec-11eb-9c40-868bf98f8e92.png)
Selecting new_code periods by project_uuid.
```
sonarDB=> 
select * from new_code_periods where project_uuid='AXYKmHx31W5kG7yc_CXo';
uuid | project_uuid | branch_uuid | type | value | updated_at | created_at
------+--------------+-------------+------+-------+------------+------------
(0 rows)
```

2) Changing default settings.
![image](https://user-images.githubusercontent.com/16628588/100473031-7ea4a080-30ee-11eb-82f0-0c1e0fb39794.png)

```
sonarDB=> select * from new_code_periods where project_uuid='AXYKmHx31W5kG7yc_CXo';
         uuid         |     project_uuid     |     branch_uuid      |       type       | value  |  updated_at   |  created_at
----------------------+----------------------+----------------------+------------------+--------+---------------+---------------
 AXYKtQCv1W5kG7yc_CX1 | AXYKmHx31W5kG7yc_CXo | AXYKmHx31W5kG7yc_CXo | REFERENCE_BRANCH | master | 1606497403052 | 1606497403052
(1 row)
```
3) Refresh
![image](https://user-images.githubusercontent.com/16628588/100473101-a431aa00-30ee-11eb-9ed7-3f909171beb4.png)
```
sonarDB=> select * from new_code_periods where project_uuid='AXYKmHx31W5kG7yc_CXo';
         uuid         |     project_uuid     |     branch_uuid      |       type       | value  |  updated_at   |  created_at
----------------------+----------------------+----------------------+------------------+--------+---------------+---------------
 AXYKtQCv1W5kG7yc_CX1 | AXYKmHx31W5kG7yc_CXo | AXYKmHx31W5kG7yc_CXo | REFERENCE_BRANCH | master | 1606497403052 | 1606497403052
(1 row)
```
4) Update & Refresh
```
sonarDB=> update new_code_periods set branch_uuid=null where uuid='AXYKtQCv1W5kG7yc_CX1';
UPDATE 1
```
![image](https://user-images.githubusercontent.com/16628588/100473658-eb6c6a80-30ef-11eb-9d42-0002b15cd307.png)

```
sonarDB=> select * from new_code_periods where project_uuid='AXYKmHx31W5kG7yc_CXo';
         uuid         |     project_uuid     |     branch_uuid      |       type       | value  |  updated_at   |  created_at
----------------------+----------------------+----------------------+------------------+--------+---------------+---------------
 AXYKtQCv1W5kG7yc_CX1 | AXYKmHx31W5kG7yc_CXo |                      | REFERENCE_BRANCH | master | 1606497403052 | 1606497403052
(1 row)
```

5) Saved master branch settings at branch level & refresh
![image](https://user-images.githubusercontent.com/16628588/100473533-a6483880-30ef-11eb-85d5-78f5510adc2f.png)
```
sonarDB=> select * from new_code_periods where project_uuid='AXYKmHx31W5kG7yc_CXo';
         uuid         |     project_uuid     |     branch_uuid      |       type       | value  |  updated_at   |  created_at
----------------------+----------------------+----------------------+------------------+--------+---------------+---------------
 AXYKtQCv1W5kG7yc_CX1 | AXYKmHx31W5kG7yc_CXo |                      | REFERENCE_BRANCH | master | 1606497403052 | 1606497403052
 AXYKwcip1W5kG7yc_CX2 | AXYKmHx31W5kG7yc_CXo | AXYKmHx31W5kG7yc_CXo | PREVIOUS_VERSION |        | 1606498240679 | 1606498240679
(2 rows)
```

**Comment by olivierboudet** [comment]
Hello, I have the same issue, can someone post an example of insert statement to make the workaround works ?
Thanks

**Comment by Sleepy-GH** [comment]
I'm running into this as well with the new SonarQube 8.9 LTS version and 1.8.0 version of the plugin.

**Comment by BlankSergey** [comment]
when it will be released?

**Comment by pro-krastinator** [comment]
Looking forward to release as well :)

**Comment by Golovanoff** [comment]
It's a miracle we need - the miracle
😀

**Comment by mc1arke** [comment]
Release in v1.9.0 of the plugin.

**Comment by Sleepy-GH** [comment]
@mc1arke Any chance that this can get backported to version 1.8.0 of the plugin?

**Comment by mc1arke** [comment]
> @mc1arke Any chance that this can get backported to version 1.8.0 of the plugin?

Yes! I was giving it a couple of days between the 1.9.0 release and performing any back-porting to make sure no-one reported any major issues. I'll be looking to back-port all the 1.9.0 functional changes other than the commit for supporting Sonarqube 9.0. I'll hopefully get a 1.8.1 release of the plugin out toward the end of this week.

**Comment by Sleepy-GH** [comment]
> Yes! I was giving it a couple of days between the 1.9.0 release and performing any back-porting to make sure no-one reported any major issues. I'll be looking to back-port all the 1.9.0 functional changes other than the commit for supporting Sonarqube 9.0. I'll hopefully get a 1.8.1 release of the plugin out toward the end of this week.

This is awesome. Thanks for your effort, it's much appreciated!

**Comment by pro-krastinator** [comment]
Unfortunately, it does not work for 8.9 LTS, are we forsed to update Sonarqube to 9 version anyway? (I'd prefer stick to latest LTS...)
Error:
```
2021.08.19 07:56:36 ERROR web[][o.s.s.p.PlatformImpl] Web server startup failed: Plugin Community Branch Plugin [communityBranchPlugin] requires at least SonarQube 9.0.0.45539
```

**Comment by mc1arke** [comment]
Backported to 1.8.1 of the plugin for Sonarqube 8.9 support.
