### ISSUE TITLE
8.2-community and plugin 1.5.0 - Missing Detection Section in admin Panel 

### ISSUE THREAD

**Issue by lgoral** [mc1arke/sonarqube-community-branch-plugin#273]
**Describe the bug**
Starting from scratch with documentation https://github.com/mc1arke/sonarqube-community-branch-plugin#installation-docker instead of lts, choose 8.2-community and plugin version 1.5.0
After booting, go to the /admin/settings and there is a missing Detection section, and can not configure short-lived branches name convention

**Expected behavior**
Should see Detection section in admin panel to set up short-lived branches naming convention

**Software Versions**
 - SonarQube Version: 8.2-community
 - Plugin Version: 1.5.0

**Additional context**
login as admin

**Comment by mc1arke** [comment]
This is expected - there's no longer a concept of short or long lived branches since Sonarqube 8.1.

**Comment by rwalravens** [comment]
> This is expected - there's no longer a concept of short or long lived branches since Sonarqube 8.1.

However, the [documentation](https://docs.sonarqube.org/latest/branches/overview/#header-3) clearly states that you still can configure which branches are excluded from housekeeping ("Using patterns to keep inactive branches").
The [migration script](https://github.com/SonarSource/sonarqube/blob/master/server/sonar-db-migration/src/main/java/org/sonar/server/platform/db/migration/version/v81/MigrateDefaultBranchesToKeepSetting.java) renames the former `sonar.branch.longLivedBranches.regex` to `sonar.dbcleaner.branchesToKeepWhenInactive`.

I found a screenshot from SQ8.4 [here](https://community.sonarsource.com/t/no-housekeeping-for-pull-requests-of-main-branch/33019/6).

So I think it's still useful to reintroduce this in the UI.

**Comment by olivierboudet** [comment]
I agree @rwalravens . I have values in my database for property `sonar.dbcleaner.branchesToKeepWhenInactive` that I don't edit anymore 

![image](https://user-images.githubusercontent.com/857205/106861627-4c9f5400-66c6-11eb-8deb-ae9fea48a043.png)
