### ISSUE TITLE
Not able to add Project tag for long live branch

### ISSUE THREAD

**Issue by abhimankhutia** [mc1arke/sonarqube-community-branch-plugin#279]
SonarQube version 7.9
Community Branch Plugin Version 1.2.0 

Not able to add Project tag from UI for long live branches other than master branch.

When you are in any projects long live branch dashboard (other than master branch), if we try to set a tag, it gets applied to master branch only.

Even web/rest api "api/project_tags/set" has no parameter for accepting branch name. It can only set the tag against master branch.

Does the community plugin support adding tags to long live branches other than master branch ?

**Comment by mc1arke** [comment]
No, tags can only be added to master. Branches inherit tags from the project's main branch.
