### ISSUE TITLE
Sonar is still complaining about the 'branch' parameter after installation of the plugin

### ISSUE THREAD

**Issue by nsirbu** [mc1arke/sonarqube-community-branch-plugin#28]
Hello.
Perhaps I didn't understand something, but how to use this plugin?
I installed it, restarted SonarQube and tried to run the analysis one more time with the 'branch' parameter defined, however it is still complaining that branch analysis is available in Developer Edition and above.

The command that I'm trying to run:
`sonar:sonar -Dsonar.branch="4.5-SNAPSHOT" -Dsonar.projectName="4.5-SNAPSHOT"`

**Comment by nixel2007** [comment]
sonar.branch is deprecated. You have to use sonar.branch.name property

**Comment by nsirbu** [comment]
Ok, the parameter worked, however the final result seems to be incorrect:
For instance, I ran the analysis on two branches, both of them are shown as PASSED, however this is not true.
![screenshot 2019-08-15 004](https://user-images.githubusercontent.com/7062048/63096293-43707380-bf76-11e9-9679-06c02cbc65e9.png)
![screenshot 2019-08-15 005](https://user-images.githubusercontent.com/7062048/63096380-76b30280-bf76-11e9-9258-21dc0bea638f.png)

And how does it detect which one is the master branch?

**Comment by mc1arke** [comment]
I'd suggest you read the documentation for SonarQube. 

Branch analysis is performed by comparing the results of a branch of its upstream long-lived branch. If your branch contains no new issues when compared to the target branch then it passes the quality gate.

Master is treated as the first branch you can on the project without having passed any parameters.

**Comment by nsirbu** [comment]
Thank you.

Small suggestion, perhaps it would be useful to mention in the README how should the 'branch' parameter be used, I mean it should be 'sonar.branch.**name**=...'.
