### ISSUE TITLE
[Question] Programmatically set ALM key and slug

### ISSUE THREAD

**Issue by sverhagen** [mc1arke/sonarqube-community-branch-plugin#282]
Would you happen to know and be able to help, if it is possible to set the key and the slug for a Bitbucket Cloud repository through the command line/SonarScanner?

<img src="https://user-images.githubusercontent.com/2049860/101238173-40315780-3693-11eb-8358-4c85c88903d0.png" width="415px" height="294px"/>

Projects get created when they are built for the first time, and they thus show up in Sonarqube without the ALM Integration/Pull Request Decoration set on the project.

Using Sonarqube 8.5/plugin 1.6.0.

Thank you.

**Comment by mc1arke** [comment]
You can't pass these from the scanner, but you can use Sonarqube's API to configure these per-project.

**Comment by sverhagen** [comment]
That worked, thanks. I'll leave the Groovy code here that we have in our Maven configuration now for every build, in case it is of use to anyone else, it works really well. The build already has access to a working token anyway, as it needs it for the SonarScanner.

    // see https://support.atlassian.com/bitbucket-cloud/docs/variables-and-secrets/
    // for reference of some of the environment variables used here

    def repositorySlug = System.getenv("BITBUCKET_REPO_SLUG")
    if (repositorySlug) {
        println("setting up alm integration for project to repository slug " +
                "${repositorySlug}")

        def separator = "&amp;" // since this code is embedded in Maven XML, ymmv
        def message = "almSetting=bitbucket${separator}" +
                "project=${project.groupId}%3A${project.artifactId}${separator}" +
                "repository=WORKSPACE_REDACTED${separator}" +
                "slug=${repositorySlug}"

        def path = "api/alm_settings/set_bitbucket_binding"
        def url = new URL("${sonar.instance.url}/${path}")
        def connection = url.openConnection()

        // set credentials as "user:password", sans password
        def credentials = "${env.SONAR_INSTANCE_TOKEN}:"
        def encoded = Base64.getEncoder().encodeToString(credentials.getBytes())
        def authorization = "Basic ${encoded}"
        connection.setRequestProperty("Authorization", authorization)

        connection.setRequestMethod("POST")
        connection.setDoOutput(true)
        connection.setRequestProperty("Content-Type",
                "application/x-www-form-urlencoded")
        connection.getOutputStream().write(message.getBytes("UTF-8"));

        def response = connection.getResponseCode();
        if (response != 204) {
            throw new RuntimeException("could not set up alm integration for " +
                    "project to repository slug ${repositorySlug}, at ${url}")
        }
    }

**Comment by ivayloc** [comment]
@sverhagen I am also trying to make SonarQube 8.5 to work with BitBucket MR, so for AML settings I have used:
 - BitBucket Server
   - **Bitbucket Server URL:** https://api.bitbucket.org/
   - **Personal Access token:** I have generated it `echo -n user:pass | base64`

In my `Project settings -> General Settings -> Pull Request Decoration`:
- **Project Key:** AN (the same from Project settings->Key)
- **Repository SLUG:** angularapp (from the URL)

I can see the PR in SonnarQube but there are no comments in my BitBucket cloud MR, could you point me to what I am missing?

**Comment by sverhagen** [comment]
This is probably way late, but you are aware that you need a separate build, right? In your Bitbucket Pipelines, we have the following `pipelines`:

```
  default:
    - step: ...stuff...
  branches:
    master:
      - step: ...stuff...
  pull-requests:  # this!
    '**':
      - step: ...stuff...
```

During the `pull-requests` builds you need to set different properties, I think they are `sonar.pullrequest.base`, `sonar.pullrequest.branch`, `sonar.pullrequest.key`, whereas for normal builds we set `sonar.branch.name`.
