### ISSUE TITLE
SonarQube PublishQuality Gate results throws an exception "Could not find target branch 'null' in project"  while creating Merge Pullrequest with new Branch

### ISSUE THREAD

**Issue by milyas123** [mc1arke/sonarqube-community-branch-plugin#283]
Hi,

I am using SonarQube Community Version: 8.4.1.35646 and
Community Branch Plugin: sonarqube-community-branch-plugin-1.5.0.jar.

Reprod steps:
Created new Branch ABC_123 from Parent Branch ABC
Created PR to Merge XYZ_OldBranch to ABC_123
It fails at Publish Quality Gate Tasks with Message : "**Could not find target branch 'null' in project"**"
![CouldnotfindTargetBranch](https://user-images.githubusercontent.com/37100227/101348478-1fd8e700-38a5-11eb-9d59-c8067e6747b2.PNG)
However, when I separately Build ABC_123 branch and re-run the failed build it works.

But, I cannot do it every time, it's becoming a hectic issue, please help me out to resolve it ASAP.

 @mc1arke : Would appreciate your support.

**Comment by brsbalazs** [comment]
Same here. I have tried with both parameters sonar.pullrequest.base and sonar.pullrequest.target, but none of them solved the problem.

**Comment by brsbalazs** [comment]
I had the same issue, but the` sonar.pullrequest.gitlab.repository` parameter solved the problem.

**Comment by mc1arke** [comment]
@milyas123 can you confirm what your build/workflow setup looks like - more specifically I need to know what commands are being passed to the Sonarqube scanner to launch the scan?

**Comment by milyas123** [comment]
@brsbalazs :  I used sonar.pullrequest.vsts.repository={Azure project repository} in "Prepare analysis on SonarQube" task. but no luck.

**Comment by milyas123** [comment]
@mc1arke please find my yml. I am using CI in azure DevOps with the standard SonarQube tasks. Please do the need full.

pool:
  name: Default
  demands:
  - vstest
  - msbuild
  - visualstudio
  - java
 
steps:
- task: NuGetCommand@2
  displayName: 'Tag Service NuGet restore'
  inputs:
    restoreSolution: '$(Parameters.solution)'
    feedsToUse: config
    nugetConfigPath: '{My Nuget.config PAth}'
    restoreDirectory: '..\..\packages\'

- task: sonarsource.sonarqube.15B84CA1-B62F-4A2A-A403-89B77A063157.SonarQubePrepare@4
  displayName: 'Prepare analysis on SonarQube'
  inputs:
    SonarQube: SonarQubeConnection
    projectKey: TAGSERVICE
    projectName: SonarQubeTagServiceProject
    extraProperties: |
     # Additional properties that will be passed to the scanner, 
     # Put one key=value per line, example:
     #sonar.exclusions=**/*.bin
     sonar.pullrequest.vsts.repository=DTS

- task: VSTest@2
  displayName: 'VsTest - testAssemblies'
  inputs:
    codeCoverageEnabled: true
  enabled: false

- task: VSBuild@1
  displayName: 'Build Tag Service'
  inputs:
    solution: '$(Parameters.solution)'
    vsVersion: 15.0
    msbuildArgs: '/p:OutDir="p"'
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    clean: true

- task: VisualStudioTestPlatformInstaller@1
  displayName: 'Visual Studio Test Platform Installer'
  inputs:
    packageFeedSelector: customFeed
    customFeed: {My custom URL}
    password: {My Password}
  enabled: false

- task: VSTest@2
  displayName: 'Automated Unit Test'
  inputs:
    vsTestVersion: toolsInstaller
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    diagnosticsEnabled: true
  enabled: false

- task: sonarsource.sonarqube.6D01813A-9589-4B15-8491-8164AEB38055.SonarQubeAnalyze@4
  displayName: 'Run Code Analysis'

- task: sonarsource.sonarqube.291ed61f-1ee4-45d3-b1b0-bf822d9095ef.SonarQubePublish@4
  displayName: 'Publish Quality Gate Result'

- task: SimondeLang.sonar-buildbreaker.sonar-buildbreaker.sonar-buildbreaker@8
  displayName: 'Break build on quality gate failure'
  inputs:
    SonarQube: SonarQubeConnection
  enabled: false

- task: PublishSymbols@2
  displayName: 'Publish symbols path'
  inputs:
    SearchPattern: '**\bin\**\*.pdb'
    PublishSymbols: false
  continueOnError: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: '$(Parameters.ArtifactName)'
  condition: succeededOrFailed()

**Comment by milyas123** [comment]
@mc1arke : Let me know if you get a chance to look into the issue.

**Comment by jcuzzi** [comment]
@milyas123 you need to use all three of the following scanner options so that SonarQube knows where the PR lives in Azure DevOps:

sonar.pullrequest.vsts.instanceUrl
sonar.pullrequest.vsts.project
sonar.pullrequest.vsts.repository

**Comment by omkar-kanekar-tfs** [comment]
Tried adding above options
still no luck

@milyas123 , did it worked for you? I am also facing same issue.

**Comment by honzajscz** [comment]
We have the same problem. The cause was that the SonarQube project had the main branch set on the **Master** whereas the repository was working with the **Main** branch. 

The solution was to change the SonarQube main branch to the **Main** by calling this PowerShell script
  
```
 # https://next.sonarqube.com/sonarqube/web_api/api/project_branches/rename
 $token = [System.Text.Encoding]::UTF8.GetBytes("SQ_TOKEN" + ":")
 $base64 = [System.Convert]::ToBase64String($token)
  
 $result = Invoke-RestMethod `
    -Uri https://SQ_HOST/api/project_branches/rename `
    -Method POST `
    -Headers @{ Authorization = "Basic $base64" } `    
    -ContentType "application/x-www-form-urlencoded" `
    -Body "project=SQ_Project_Name&name=main"

 $result
```

**Comment by omkar-kanekar-tfs** [comment]
Thank you so much @honzajscz , the above powershell script did solved the problems and the builds are running fine. But with these automated build, the quality gates are not getting applied. Gates are applied if I trigger build manually for same branch.

Do you face this issue?

**Comment by honzajscz** [comment]
@omkar-kanekar-tfs My Gates work properly.
