### ISSUE TITLE
Project level New Code settings doesn't save

### ISSUE THREAD

**Issue by BlankSergey** [mc1arke/sonarqube-community-branch-plugin#289]
**Describe the bug**
After change project new code setting to Reference branch and push Save button it is doesn't save (also after the next analysis)

**To Reproduce**
1. Go to 'New Code' project settings
2. Click on 'Reference branch'
3. Choose a branch from dropdown
4. Click on 'Save' button
![image](https://user-images.githubusercontent.com/23173933/102210839-c3e51280-3ee3-11eb-9b65-03253eb02742.png)

**Expected behavior**
After the next analysis new branch new code will be compare with Reference branch

**Actual**
After the next analysis new branch new code use general setting

**Screenshots**
![image](https://user-images.githubusercontent.com/23173933/102210919-dd865a00-3ee3-11eb-863f-65c0eb844b4f.png)

**Software Versions**
 - SonarQube Version: 8.5.1, 8.4.1 
 - Plugin Version: 1.6.0, 1.5.0

**Comment by Dr-Dream** [comment]
i think dublicates #272
