### ISSUE TITLE
Enhancement: report the actual number of solved issues

### ISSUE THREAD

**Issue by alexandrul** [mc1arke/sonarqube-community-branch-plugin#29]
Is it possible to report the actual number of issues solved in a given branch instead of showing `0`?

**Comment by mc1arke** [comment]
Could you share some details about what you're referring to here, and possibly some screenshots of expected versus actual values?

**Comment by alexandrul** [comment]
I have a dedicated branch for fixing old issues in my project, but in Sonar UI it appears with 0 bugs / code smells, even if after merge I will see a decrease in the issue count.

This computation is done on Sonar side, not in the branch analysis plugin?

Related issue: https://jira.sonarsource.com/browse/MMF-1474

**Comment by mc1arke** [comment]
Ok, that makes sense. The branch plugin doesn't provide/calculate those values, it's all done internally in SonarQube's compute engine. We therefore can't influence it directly with the APIs we implement for the branch plugin so can't change this functionality.

I'm therefore going to close this issue, although will have a dig through the relevant SonarQube source code to see what changes would be required to make this possible to do directly in core, or with an additional plugin.
