### ISSUE TITLE
PR decoration not working against on-prem TFS 2018 update 3 - due to incorrect api-version value

### ISSUE THREAD

**Issue by arcdev** [mc1arke/sonarqube-community-branch-plugin#290]
**Describe the bug**
PR decoration fails against TFS 2018 update 3 because the default value for the REST service `api-version` is `6.0-preview.1`.
It appears to be expecting the **Prepare Analysis** Sonar Scanner task to set the `sonar.pullrequest.vsts.apiVersion` property accordingly.  However, this value is not set.

**To Reproduce**
1. Create a build in TFS & configure as a Gated Build
2. Add **Prepare Analysis Configuration** task; configure normally.
3. create a PR (with something for SonarQube to comment on)
4. (Gated Build runs with analysis)
5. SonarQube logs indicate decorations, but fails to publish them to the PR.

**Expected behavior**
SonarQube decorations appear in the PR.

**Software Versions**
 - SonarQube Version: Community Edition - Version 8.5.1 (build 38104)
 - Plugin Version: 1.6.0
 - SonarQube extension for TFS (sonar-scanner-vsts) 4.15.0 [marketplace link](https://marketplace.visualstudio.com/items?itemName=SonarSource.sonarqube)

**Workaround**
Manually set the property in the **Prepare Analysis** tasks, e.g.
`sonar.pullrequest.vsts.apiVersion=4.1-preview.1`

**Additional notes**
log snippet attached with some values updated for public consumption

[sonarQube-issue-log-01.txt](https://github.com/mc1arke/sonarqube-community-branch-plugin/files/5731036/sonarQube-issue-log-01.txt)

**Comment by mc1arke** [comment]
@arcdev this sounds like it's working as expected: you're supposed to pass the additional parameter if you're running a versions of VSTS that requires a different API version
