### ISSUE TITLE
Pass bitbucket information in build maven

### ISSUE THREAD

**Issue by mblanloeil** [mc1arke/sonarqube-community-branch-plugin#292]
When I import a new project in sonar, it's possible to pass projetkey and repository in maven's parameter such as -D sonar.bitbucket.key=myket -Dsonar.bitbucket.repository=myrepository . 
Currently I need to add information via sonar in projet settings.

Thank's

**Comment by nixel2007** [comment]
There is no way to configure ALM settings through cli

https://github.com/mc1arke/sonarqube-community-branch-plugin/issues/282

**Comment by mblanloeil** [comment]
Thank's for answer!
