### ISSUE TITLE
Github PR decoration reports all issues found on project, not just those in changed files

### ISSUE THREAD

**Issue by jsedlace** [mc1arke/sonarqube-community-branch-plugin#293]
**Describe the bug**
When one of our bigger projects is analysed with sonar and issues are reported to pull request, plugin sends all issues found on the project, not just those found in files changed in pull requests. Our goals is to report to particular developer just his/her issues, all issues are available in sonar where all developers can access then and plan to reduce tech debt.

As a side effect of this, Github UI shows error if there is too many other issues (Github API returns http 414 'Your request URL is too long.' when it tries to load unchanged files)

**To Reproduce**
1. Have properly configured sonar with community branch plugin installed and configured to decorate Github PRs
2. Have various issues sonar can found in the code
3. Analyse branch with some issues in changed files, some in unchanged files
4. In PR you should be able to see annotations over unchanged files.

**Expected behavior**
I would expect not to report issues in unchanged files (or at least have this configurable).

**Software Versions**
 - SonarQube Version: 8.5.1
 - Plugin Version: 1.6.0

**Comment by lucasoares** [comment]
@jsedlace, may you please provide the commands you are using to generate analysis? Both commands using for the master branch pipeline and the PR pipeline. Maybe it will help :D

**Comment by mc1arke** [comment]
Closing since there are not enough details to replicate the issue, and the author has not responded to the request for information.

**Comment by jsedlace** [comment]
hello @lucasoares , I'm sorry for not replying sooner, too many messages from github 😞 

Command to run analysis for the master branch:
`mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar -U -e -Dsonar.projectName=service-name -Dsonar.login=*** -Dsonar.password=*** -Dsonar.host.url=****`
    
Command to run for branch/PR analysis:
`  mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar -U -e -Dsonar.login=***  -Dsonar.projectName=service-name  -Dsonar.report.export.path=sonar-report.json  -Dsonar.password=*** -Dsonar.host.url=*** -Dsonar.pullrequest.branch=feature-branch -Dsonar.pullrequest.base=master -Dsonar.pullrequest.key=122 -Dsonar.pullrequest.github.repository=organization/service-name -Dsonar.scm.revision=[sha1 of commit]`
