### ISSUE TITLE
Gitlab options?

### ISSUE THREAD

**Issue by adpeyre** [mc1arke/sonarqube-community-branch-plugin#302]
Hi,

Is there options for gitlab decoration ? I don't find theme.
For example, is it possible to keep only the summary commentary ?

Thanks for your help

**Comment by mc1arke** [comment]
No, there are no particular options for how comments are shown on Gitlab. You can enable/disable the deletion of comments on the re-scan of a Merge Request, but can't disable or filter individual issue comments.
