### ISSUE TITLE
PR decoration is not happening

### ISSUE THREAD

**Issue by su1985** [mc1arke/sonarqube-community-branch-plugin#313]
**Description**
PR analysis on SonarQube works but the PR decoration on github is not happening

Steps Tried:
I see the PR analysis published onto SonarQube server, however the PR decoration is not happening.
I have followed all the steps described under https://docs.sonarqube.org/7.9/analysis/pull-request/ for PR decoration

Properties used for PR analysis:
sonar.pullrequest.branch=test_sonar
sonar.pullrequest.key=2
sonar.pullrequest.provider=github
sonar.pullrequest.base=master

The checks tab in github always stays at "Waiting for checks information..."

I also enabled Trace logging on SonarQube server. I don't see any Traceback / Exceptions. However, I see the following at various stages in the compute_engine logs:

```
2021.03.09 04:47:55 INFO  ce[AXgVUBOcul0-1QE8N8N0][o.s.c.t.s.ComputationStepExecutor] Send issue notifications | status=SUCCESS | time=0ms
2021.03.09 04:47:55 INFO  ce[AXgVUBOcul0-1QE8N8N0][o.s.c.t.s.ComputationStepExecutor] Publish task results | status=SUCCESS | time=0ms
2021.03.09 04:47:55 INFO  ce[AXgVUBOcul0-1QE8N8N0][o.s.c.t.s.ComputationStepExecutor] Trigger refresh of Portfolios and Applications | status=SUCCESS | time=0ms
2021.03.09 04:47:55 WARN  ce[AXgVUBOcul0-1QE8N8N0][c.g.m.s.p.c.p.PullRequestPostAnalysisTask] No decorator could be found matching GitHub
2021.03.09 04:47:55 INFO  ce[AXgVUBOcul0-1QE8N8N0][c.g.m.s.p.c.p.PullRequestPostAnalysisTask] No decorator found for this Pull Request
2021.03.09 04:47:55 INFO  ce[AXgVUBOcul0-1QE8N8N0][o.s.c.t.CeWorkerImpl] Executed task | project=sshivaswamy:test_appliance-management-operator-master | type=REPORT | pullRequest=2 | id=AXgVUBOcul0-1QE8N8N0 | submitter=admin | status=SUCCESS | time=1572ms
2021.03.09 04:47:59 INFO  ce[][o.s.c.t.CeWorkerImpl] Execute task | project=sshivaswamy:test_appliance-management-operator-master | type=REPORT | branch=test_sonar | branchType=SHORT | id=AXgVUCtCul0-1QE8N8N2 | submitter=admin
2021.03.09 04:48:00 INFO  ce[AXgVUCtCul0-1QE8N8N2][o.s.c.t.s.ComputationStepExecutor] Extract report | status=SUCCESS | time=11ms
2021.03.09 04:48:00 INFO  ce[AXgVUCtCul0-1QE8N8N2][o.s.c.t.s.ComputationStepExecutor] Persist scanner context | status=SUCCESS | time=18ms
2021.03.09 04:48:00 INFO  ce[AXgVUCtCul0-1QE8N8N2][o.s.c.t.s.ComputationStepExecutor] Propagate analysis warnings from scanner report | status=SUCCESS | time=0ms
```

```
2021.03.09 07:50:23 DEBUG ce[AXgV9xgJul0-1QE8N8OO][c.g.m.s.p.c.p.PullRequestPostAnalysisTask] found 3 pull request decorators
2021.03.09 07:50:23 WARN  ce[AXgV9xgJul0-1QE8N8OO][c.g.m.s.p.c.p.PullRequestPostAnalysisTask] No decorator could be found matching GitHub
2021.03.09 07:50:23 INFO  ce[AXgV9xgJul0-1QE8N8OO][c.g.m.s.p.c.p.PullRequestPostAnalysisTask] No decorator found for this Pull Request
```

```
2021.03.09 07:50:38 DEBUG ce[AXgV91Wbul0-1QE8N8OQ][c.g.m.s.p.c.p.PullRequestPostAnalysisTask] found 3 pull request decorators
2021.03.09 07:50:38 TRACE ce[AXgV91Wbul0-1QE8N8OQ][c.g.m.s.p.c.p.PullRequestPostAnalysisTask] Current analysis is not for a Pull Request. Task being skipped
```

**Expected behavior**
PR decoration should work

**Software Versions**
 - SonarQube Version: Version 7.9.1 (build 27448)
 - Plugin Version: 1.3.2 (sonarqube-community-branch-plugin-1.3.2.jar)
 - GitHub Enterprise Version: 2.21.14

Please let me know if you need more information. Any pointers here would be really helpful. 
Appreciate your help.

**Comment by mc1arke** [comment]
```
No decorator could be found matching GitHub
```

The decorator name is `Github` (lower-case `h`)

**Comment by su1985** [comment]
@mc1arke - thank you very much for the response. 
I have not specified GitHub anywhere in the configuration.

**Comment by mc1arke** [comment]
@su1985 without more information (e.g. the full command you're using to launch your scans, and how you're passing properties in the scanner engine) then I can't really provide much more help.

**Comment by su1985** [comment]
@mc1arke here are some of the details:

**Environment:**
CI Tool - Travis
Sonar - Standalone Server for SonarQube

Sonar scanner is invoked with the below command:
sonar-scanner -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN -Dsonar.github.oauth=$SONAR_GIT_OAUTH -X

Contents of **sonar-project.properties**:
sonar.projectKey=sshivaswamy:test_appliance-management-operator-master
sonar.projectName=test_appliance-management-operator-master
sonar.projectVersion=1.0
sonar.host.url=http://<sonar-url>:9000

sonar.pullrequest.branch=test_sonar
sonar.pullrequest.key=3
sonar.pullrequest.provider=github
sonar.pullrequest.base=master
sonar.github.endpoint=https://github.<company_name>.com/api/v3

sonar.pullrequest.github.repository=sshivaswamy/test_appliance-management-operator-master
sonar.sources=.
sonar.exclusions=README.md, bin/**, hack/**, Makefile, Dockerfile

sonar.issuesReport.html.enable=true
sonar.sourceEncoding=UTF-8

**Comment by su1985** [comment]
@mc1arke - do you need any more information ? 
Appreciate your help

**Comment by mc1arke** [comment]
I'm unable to replicate this. I need you to provide steps to replicate this from a fresh Sonarqube install.

**Comment by mc1arke** [comment]
Closing since I'm unable to replicate the issue with the information currently available.
