### ISSUE TITLE
Setting up plugin on SonarQube v8.2 throws errors when performing analysis

### ISSUE THREAD

**Issue by forceedge01** [mc1arke/sonarqube-community-branch-plugin#316]
**Describe the bug**
Upon analysis, adding environment variables to specify the branch and other parameters result in errors stating that developer edition or above is required to specify the options.

**To Reproduce**
1. Running version of SonarQube 8.2 with extension as per readme
2. Running analysis with the sonar.branch.name variable
3. See error

**Expected behavior**
The analysis should run successfully without complaint and display the branch name in the UI for which the analysis was carried out.

**Screenshots**
<img width="1404" alt="Screenshot 2021-03-18 at 15 59 04" src="https://user-images.githubusercontent.com/1619816/111656925-de8c9780-8802-11eb-95d2-96a2c77a206f.png">

**Software Versions**
 - SonarQube Version: [Version 3.2 (build 32929)]
 - Plugin Version: [1.6.0]

**Comment by mc1arke** [comment]
Do you see reference to Community Branch Plugin in the Marketplace (see below), and in the startup logs? The fact it's failing in the scanner indicates that the plugin isn't correctly deployed to one of the paths

![image](https://user-images.githubusercontent.com/1250331/113059129-fcfd7600-91a6-11eb-8074-47dd3e72eaac.png)

**Comment by mc1arke** [comment]
Closing since this is an outdated version of the plugin, there's been no further updates from the reporter, and I'm unable to replicate the issue.
