### ISSUE TITLE
Unknown url : /api/alm_integrations/get_github_client_id

### ISSUE THREAD

**Issue by maximelebastard** [mc1arke/sonarqube-community-branch-plugin#318]
**Describe the bug**
Cannot create a GitHub Project

**To Reproduce**
1. As an administator
2. Go to **Administration > ALM Integrations > GitHub**
3. Follow the [instructions for GitHub (create a GitHub App)](https://docs.sonarqube.org/latest/analysis/github-integration/)
4. Save the integration
5. Go to Projects -> Create a new project -> From GitHub
6. A blocking message `Could not connect to GitHub` is shown
7. I have the following XHR query failing with the error api/alm_integrations/get_github_client_id?almSetting=github 
```
{
    "errors": [
        {
            "msg": "Unknown url : /api/alm_integrations/get_github_client_id"
        }
    ]
}
```

If I remove the plugin and restart SonarQube, I get the project creation page working properly.

**Screenshots**
<img width="673" alt="image" src="https://user-images.githubusercontent.com/6564357/112228173-28291800-8c31-11eb-8402-94e7922bc11e.png">

**Software Versions**
 - SonarQube Version: 8.4.2.36762
 - Plugin Version: 1.5.0

**Additional context**
I'm just looking for a workaround :) I already tried that downgrade to 8.4, with no luck

**Comment by mc1arke** [comment]
Fixed in 1.7.0 of the plugin
