### ISSUE TITLE
Error while restarting SonarQube v 8.6.1

### ISSUE THREAD

**Issue by punitmukherjee** [mc1arke/sonarqube-community-branch-plugin#319]
**Describe the bug**

Getting the error while starting sonarqube after placing the JAR in the mentioned directories:

ERROR web[][o.s.s.p.PlatformImpl] Web server startup failed: Found a plugin 'Community Branch Plugin' in the directory 'extensions/plugins' with the same key [communityBranchPlugin] as a built-in feature 'Community Branch Plugin'. Please remove 'extensions/plugins/sonarqube-community-branch-plugin-1.6.0.jar'.

**Comment by punitmukherjee** [comment]
Hi, 
Could someone help us with this issue?

**Comment by mc1arke** [comment]
I'm able to deploy 1.6.0 of the plugin into Sonarqube 8.6.1 without an issue, so you're somehow managing to place 2 copies of the plugin into the extensions/plugins/ directory. Do you have an older copy of the plugin in that directory, or another copy with a different name?
