### ISSUE TITLE
Doesn't work with Sonarqube version 8.7.1.42226

### ISSUE THREAD

**Issue by chly1103** [mc1arke/sonarqube-community-branch-plugin#322]
Version：Sonarqube 8.7.1+sonarqube-community-branch-plugin-1.7.0.jar

`mvn sonar:sonar -Dsonar.projectKey=*** -Dsonar.projectName=*** -Dsonar.projectVersion=master -Dsonar.ws.timeout=30 -Dsonar.login=[MASKED] -Dsonar.sourceEncoding=UTF-8 -Dsonar.java.binaries=target/classes -Dsonar.java.test.binaries=target/test-classes -Dsonar.java.surefire.report=target/surefire-reports -Dsonar.test.inclusions=/test/ -Dsonar.exclusions=/test/ --settings=./settings.xml -Dsonar.branch.name=master`

```
[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.8.0.2131:sonar (default-cli) on project ils-parent: Failed to upload report - An error has occurred. Please contact your administrator -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

Successful execution without parameter -Dsonar.branch.name=master
@mc1arke

![image](https://user-images.githubusercontent.com/5884703/113406266-c493ad00-93dd-11eb-9dca-a688d23a1eea.png)

![image](https://user-images.githubusercontent.com/5884703/113406299-d6755000-93dd-11eb-8c99-2e3031f3fc8d.png)

![image](https://user-images.githubusercontent.com/5884703/113406360-ef7e0100-93dd-11eb-8b32-3192c2ddac76.png)

![image](https://user-images.githubusercontent.com/5884703/113406393-fad12c80-93dd-11eb-8968-97eb25369e7f.png)

**Comment by Sryther** [comment]
Hi there, I have the same issue on SonarQube 8.8. :) https://github.com/mc1arke/sonarqube-community-branch-plugin/issues/321

**Comment by mc1arke** [comment]
I can't replicate this given the details you've provided. Can you confirm the `UID` and `GID` in the above screenshots is that of the user that Sonarqube is being run under? Can you also confirm if you're able to see Sonarqube community branch plugin listed in the 'Marketplace' screen when Sonarqube is running?

**Comment by chly1103** [comment]
![image](https://user-images.githubusercontent.com/5884703/113463084-90100780-9456-11eb-9f4c-a66e92fafb76.png)
