### ISSUE TITLE
New Code Project Specific Settings are not saved

### ISSUE THREAD

**Issue by hannidoch** [mc1arke/sonarqube-community-branch-plugin#326]
**Describe the bug**
When changing New Code Project Specific Settings Via web UI or via Web-API, the settings are not saved for the project. 

**To Reproduce**
Using Web Ui:

1. Go to projects
2. Click on Project Settings
3. Click on New Code
4. Select Define Specific Setting for the project
5. Select Reference Branch
6. Click Save
7. Reload
8. See new settings are not saved. Also only the default branch settings change to new and other branches follow old settings

Using Web-APi

1. Post to api/new_code_periods/set?type=REFERENCE_BRANCH&project=<project Key>&value=master. 
2. Post is successful with status 200 ok
3. Check web UI and no changes happen for project. Only default branch changed

**Expected behavior**

New Project Settings should Persist after saving and reloading or after calling web-api

**Screenshots**

**Software Versions**
 - SonarQube Version:  Version 8.7.1 (build 42226)
 - Plugin Version: 1.7

**Comment by mc1arke** [comment]
Duplicates #272
