### ISSUE TITLE
Question: Short-lived branches and test results

### ISSUE THREAD

**Issue by zbubric** [mc1arke/sonarqube-community-branch-plugin#33]
Hi,

sorry for noob question and also for posting this as an issue but I didn't found any other way to ask a question.
We have simple quality that we would like to use as a check before merging PR into mastzer branch. One of the rules is that there is no failing unit tests but, it seems that Sonar (or this plugin take into account only rules that apply to 'new code') and test results are completely ignored.

For example, in one of PR branches (short-lived) I introduce some failing tests (without change in src code, just adding asserts within tests folder). When I scan branch it says that is ok but, if I merge this code back to master QG will fail due to failing tests.
Also, if this is a feature of short-lived branch, is thare any way to 'trick it' with configuring patter as long-lived branch? As far as I understood, in that case all gates should be verified but I'm worried how 'new code' would be calculated (e.g. is there any way to configure that all code on branch is a 'new code')? Also, is there any additional drawbacks that I could face?

Thx in advanced
Zoran

**Comment by mc1arke** [comment]
I'm not sure why your test failure wasn't picked-up, but this isn't under control of this plugin: it's provided by SonarQube core. The branch plugin doesn't directly analyse results or manage the quality gates.

If you want to change your branches to be long-lived then you can change the `sonar.branch.longLivedBranches.regex` property for the project, normally done by going to the project's "brances" page and changing the value in the top-right corner.
