### ISSUE TITLE
GitHub PR decoration not working

### ISSUE THREAD

**Issue by NehaOberoi92** [mc1arke/sonarqube-community-branch-plugin#330]
**Describe the bug**
Github PR Decoration not reflecting in github

1.) Sonarube community edition running on HTTP v8.7.1
2.) Github Organization https
3.) Able to see multiple branch and run PR branch analysis on sonarqube. Also , able to view report of PR branch on sonarqube.
4.) Not able to see anything on github for sonar
5.) Logs of sonar ce state -
Pull Request Decoration | status=SUCCESS | time=0ms 

Argument used - /d:sonar.pullrequest.key="number" /d:sonar.pullrequest.branch="branch" /d:sonar.pullrequest.base="dev" 

I also added - /d:sonar.pullrequest.provider="GitHub"
But still not getting anything, do I need to add new parameter ?
Added - image base URL also https://raw.githubusercontent.com/mc1arke/sonarqube-community-branch-plugin/master/src/main/resources/static

**Comment by NehaOberoi92** [comment]
Update - 

Now I am getting in Project Setting - Pull Request Decoration - > This feature must first be enabled in the global settings. Learn More
Although, If I go to Admin General setting don't find such option. Is there any step I need to do to configure this. I am not able to create all integration using github app as sonarqube is running on http

**Comment by djakielskiadesso** [comment]
Same problem with Sonarqube 8.9 and plugin 1.8.

**Comment by mc1arke** [comment]
Please follow the steps on https://docs.sonarqube.org/latest/analysis/pull-request/ to configure Pull Request decoration.

**Comment by pkazi** [comment]
Same problem with Sonarqube 8.9.1 (build 44547) and plugin 1.8.0.
ALM config shows 🟢 -
![image](https://user-images.githubusercontent.com/37570849/122731886-556d7c80-d299-11eb-991a-4564fbbe65d4.png)
