### ISSUE TITLE
Do not display tokens in plain text in GUI Settings

### ISSUE THREAD

**Issue by nejch** [mc1arke/sonarqube-community-branch-plugin#336]
**Describe the bug**
Not sure if this is a limitation of the plugin architecture but would be great if the token was hidden in the GUI after saving. Just saw someone give a demo on SQ and all participants could see the token in plain text.

**To Reproduce**
1. Go to Project -> Administration -> Pull request ->
2. Scroll down to the token (e.g. Gitlab settings)

**Expected behavior**
Tokens shouldn't appear in the UI in plain text

**Screenshots**
![image](https://user-images.githubusercontent.com/16777978/114870319-50eb9a00-9df8-11eb-8882-71950a0e2695.png)

**Software Versions**
 - SonarQube Version: Version 7.9.3 (build 33349)
 - Plugin Version: 1.3.2

**Comment by mc1arke** [comment]
This is a limitation of Sonarqube. Newer versions of Sonarqube provide a nicer UI for managing ALM integration which hides sensitive values, so if you're on the LTS version of Sonarqube, you'll  need to wait for the latest LTS to allow the secrets to be restricted.
