### ISSUE TITLE
sonar scanner complain that, properties key for pull request decoration is supported with commercial edition only

### ISSUE THREAD

**Issue by rkjaiswal1** [mc1arke/sonarqube-community-branch-plugin#344]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Software Versions**
 - SonarQube Version: [e.g. Version 7.8 (build 26217)]
 - Plugin Version: [e.g. 1.1.0, or custom build from master at commit 004AD34FAA]

**Additional context**
![pullrequestdecoration](https://user-images.githubusercontent.com/16558524/115834042-62552780-a432-11eb-9643-0951714df154.JPG)

**Comment by mc1arke** [comment]
I don't provide support for custom builds. Your error indicates you've not got the plugin installed properly, so please check you've followed the installation guidance in the README.

Filling in the bug template properly is an important part of the process as it requires the submitter to re-try all their steps they're following to get to that point and either highlights where a step has been missed, or allows replication. Please ensure you're following the template when you submit a report.
