### ISSUE TITLE
Execution Error in Github Actions

### ISSUE THREAD

**Issue by tekmindz** [mc1arke/sonarqube-community-branch-plugin#345]
**Describe the bug**
Execution error while doing branch analysis with sonarqube-community-branch-plugin

**Expected behavior**
Code review for all branches in soanrqube. Currently only master branch review is available 

**Screenshots**
complete logs https://pastebin.com/grKN3hWC

**Software Versions**
 - SonarQube Version: 8.8
--
 - Plugin Version: 1.7.0

**Comment by mc1arke** [comment]
Closing as there are no replication steps or details of what's been attempted. If re-raising the bug, please attached relevant details to the issue rather than hosting them on external sites.
