### ISSUE TITLE
Plugin doesn't work with sonarqube 8.9 - No more lib/common folder

### ISSUE THREAD

**Issue by tahitiangabriel** [mc1arke/sonarqube-community-branch-plugin#350]
**Describe the bug**
I've upgraded my sonarqube server to version 8.9 released yesterday and the plugin does not work anymore.
There are no more lib/common folder in this latest version of sonarqube.
The branches are not available in the interface.

I had to rollback to version 8.8.

**To Reproduce**
1. upgrade your sonarqube server to 8.9
2. put the branch plugin in extensions/plugins and libs/common (folder which doesn't exist)
3. start sonar.

At the first start of sonarqube you will also get a warning about non official plugins being used.

**Expected behavior**
Be able to switch to branches in the interface

**Software Versions**
 - SonarQube Version: 8.9
 - Plugin Version: 1.7

**Comment by nixel2007** [comment]
See latest discussion

**Comment by tahitiangabriel** [comment]
Thank you for letting me know. I was not aware about the dicussion section.
Here's the direct link for those interrested : [SonarQube 8.9 LTS Support](https://github.com/mc1arke/sonarqube-community-branch-plugin/discussions/348)

**Comment by mc1arke** [comment]
Released in 1.8.0 of the plugin
