### ISSUE TITLE
Issues don't seem to propagate right from branches to PRs

### ISSUE THREAD

**Issue by css-inverso** [mc1arke/sonarqube-community-branch-plugin#351]
**Describe the bug**
We analyse branches in our project and once a feature is finished a PR is created for the branch.
If a branch is analysed with a major issue it is correctly marked as failed but if you create a pullrequest from that failed branch the issue doesn't show up in the PR analysis and so the PR can be merged (quality gate does not fail). Once merged the issue doesn't show up in the master branch either.

**To Reproduce**
1. Create a branch with a issue that fails the quality gate and analyse it
2. Create a PR for the branch (we're using Bitbucket Server) and analyse it
3. Merge the PR and analyse master

**Expected behavior**
PR shows issue from branch and master has the issue after PR was merged.

**Screenshots**

**Software Versions**
 - SonarQube Version: [Version 8.8 (build 42792)]
 - Plugin Version: [1.7.0]

**Comment by rwalravens** [comment]
What are the conditions of your quality gate?

For PR analysis, not all conditions are verified
> https://docs.sonarqube.org/latest/analysis/pull-request/#header-3
> "The Pull Request quality gate only uses your project's quality gate conditions that apply to "on New Code" metrics."

But this does not explain why the master analysis does not fail after merging.

**Comment by css-inverso** [comment]
It's the default Quality Gate (maintainability rating less than A on new Code) so a major issue (code smell) fails that quality gate and should fail it on a PR too.

**Comment by SMUnlimited** [comment]
Just to note the maintainability rating quality gate doesn't mean 0 new code smells, it means no new code smells that take a certain amount of time to fix above a threshold based on how much code there is. That would explain the behaviour you are seeing. There are new code smells but the grade is still A so doesn't fail.

**Comment by rwalravens** [comment]
It is not impossible to produce the wanted behaviour, so as @SMUnlimited suggests, it probably depends on the actual code and metrics that are configured.

Simulation using sonarqube mvn plugin:
1. analyze master **PASSED**
2. create and checkout branch `feature/f1`, analyze branch (`sonar.branch.name=feature/f1`) **PASSED**
3. commit a blocker violation on branch, analyze branch (`sonar.branch.name=feature/f1`) **FAILED**
4. analyze branch as PR (`sonar.pullrequest.key=1 sonar.pullrequest.base=master sonar.pullrequest.branch=feature/f1`) **FAILED**
5. merge branch to master, analyse master **FAILED**

**Comment by mc1arke** [comment]
Closing since this does not sound like an issue with the plugin, and there are not enough details to replicate the problem.
