### ISSUE TITLE
Failed to find Premain-Class manifest attribute -> ./extensions/plugins/sonarqube-community-branch-plugin-1.5.0.jar

### ISSUE THREAD

**Issue by rakzmin** [mc1arke/sonarqube-community-branch-plugin#354]
**Describe the bug**
Wanted to add the plugin based on the description.
Getting the error in subject while sonar starts.
Downloaded the prebuilt jar, added the needed configs to sonar.
Checked the jar manifest, there is really no premain-class attribute.
Running the 8.2-community image tried to add 1.5.0 plugin

**To Reproduce**
As stated in the readme.

**Software Versions**
 - SonarQube Version: 8.2.0.32929
 - Plugin Version: 1.5.0

**Additional context**
Tried also to update to sonarqube 8.9 LTS community but there I have a problem with the AccessDeniedException as I learned is from alpine having the same user id as existing previous installations of sonarqube.
Background is that I first also did a successful migration 7.3 -> 7.9 -> 8.2.

**Comment by mc1arke** [comment]
If you're using version 1.5.0 of the plugin (why haven't you migrated to the latest LTS if going through upgrades?) then you should be following https://github.com/mc1arke/sonarqube-community-branch-plugin/tree/1.5.0#installation. The agent steps are only valid for the latest LTS.

**Comment by rakzmin** [comment]
Ahh yep my bad sorry.

BTW I tried to go all the to 8.9-LTS as described but there (without dealing with plugin simply starting sonarqube) I faced that it cannot access the the es6 embedded db folder due to some instresecting user rights introduced with the latest alpine base image. So I just stuck with 8.2 which states 1.5.0.

Now I get it a mixed it up using the instructions for the latest 1.7.0 release.
Sorry for the confustion and opening a bug for this.

**Comment by Hello-Linux** [comment]
my sonarqube is 8.4.2 and plugin is 1.5.0,the error is
```
2021.09.24 03:27:31 INFO  app[][o.s.a.ProcessLauncherImpl] Launch process[[key='web', ipcIndex=2, logFilenamePrefix=web]] from [/opt/sonarqube]: /opt/java/openjdk/bin/java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/opt/sonarqube/temp -XX:-OmitStackTraceInFastThrow --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED -Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError -javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.5.0.jar=web -Dhttp.nonProxyHosts=localhost|127.*|[::1] -cp ./lib/common/*:/opt/sonarqube/lib/jdbc/postgresql/postgresql-42.2.14.jar org.sonar.server.app.WebServer /opt/sonarqube/temp/sq-process1302277054607316413properties
Failed to find Premain-Class manifest attribute in ./extensions/plugins/sonarqube-community-branch-plugin-1.5.0.jar
Error occurred during initialization of VM
agent library failed to init: instrument
2021.09.24 03:27:31 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [web]: 1
2021.09.24 03:27:31 INFO  app[][o.s.a.SchedulerImpl] Process[web] is stopped
2021.09.24 03:27:32 INFO  app[][o.s.a.SchedulerImpl] Process[es] is stopped
2021.09.24 03:27:32 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [es]: 143
2021.09.24 03:27:32 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped

```

**Comment by rakzmin** [comment]
> @mc1arke
> my sonarqube is 8.4.2 and plugin is 1.5.0,the error is
> 
> ```
> 2021.09.24 03:27:31 INFO  app[][o.s.a.ProcessLauncherImpl] Launch process[[key='web', ipcIndex=2, logFilenamePrefix=web]] from [/opt/sonarqube]: /opt/java/openjdk/bin/java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/opt/sonarqube/temp -XX:-OmitStackTraceInFastThrow --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED -Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError -javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.5.0.jar=web -Dhttp.nonProxyHosts=localhost|127.*|[::1] -cp ./lib/common/*:/opt/sonarqube/lib/jdbc/postgresql/postgresql-42.2.14.jar org.sonar.server.app.WebServer /opt/sonarqube/temp/sq-process1302277054607316413properties
> Failed to find Premain-Class manifest attribute in ./extensions/plugins/sonarqube-community-branch-plugin-1.5.0.jar
> Error occurred during initialization of VM
> agent library failed to init: instrument
> 2021.09.24 03:27:31 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [web]: 1
> 2021.09.24 03:27:31 INFO  app[][o.s.a.SchedulerImpl] Process[web] is stopped
> 2021.09.24 03:27:32 INFO  app[][o.s.a.SchedulerImpl] Process[es] is stopped
> 2021.09.24 03:27:32 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [es]: 143
> 2021.09.24 03:27:32 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
> ```
> 
> ![2021-09-24 11-33-35 的屏幕截图](https://user-images.githubusercontent.com/17851645/134614308-a13c39b6-d1da-4a88-9fbd-2a11c257e310.png)

Hi Buddy same stuff as @mc1arke pointed out to me, you are probably reading instructions on the master head for 1.5.0
https://github.com/mc1arke/sonarqube-community-branch-plugin/tree/1.5.0#installation
this should be followed.
