### ISSUE TITLE
Broken icons in MR comment in Gitlab

### ISSUE THREAD

**Issue by BenjaDiaz** [mc1arke/sonarqube-community-branch-plugin#358]
**Describe the bug**
Icons are broken in the MR comment that contains the scan summary when using Gitlab.

**To Reproduce**
1. Install and configure the plugin
2. Create a MR in Gitlab
3. See the MR comment with broken icons

**Expected behavior**
Icons should be correctly visible.
**Screenshots**
![Captura de pantalla 2021-05-18 a las 10 49 42](https://user-images.githubusercontent.com/19522964/118674945-92dd7680-b7d0-11eb-88b6-6beeea3de88e.png)

**Software Versions**
 - SonarQube Version: 8.8
 - Plugin Version: 1.7.0

**Additional context**
Going directly to the image link gives a "Denylist host failure".

**Comment by mc1arke** [comment]
This sounds like your infrastructure is blocking requests somewhere. Are you using Gitlab.com or a self-hosted Gitlab instance, and is your Sonarqube instance using a public or internal domain name?

**Comment by BenjaDiaz** [comment]
We are using Gitlab.com. Sonarqube is using an internal domain name, but the icon links are from https://user-content.gitlab-static.net

For example, this is one link:
https://user-content.gitlab-static.net/c25c59b81e2fc59161bc0b0fce4a38f7a6dd8197/68747470733a2f2f736f6e61722e746f6f6c732e616e6b2e696d2f7374617469632f636f6d6d756e6974794272616e6368506c7567696e2f636f6d6d6f6e2f6275672e7376673f73616e6974697a653d74727565

**Comment by popov-tensor** [comment]
That may happen, when SonarQube is HTTP, while GitLab is HTTPS. Links in comments become HTTPS-to-HTTP, which is forbidden by browser security. Also other security limits may be the reason.
Hint: Get an URL of "broken" image from page source, and open it in a separate tab. If it opens ok, then you hit browser restrictions. Open JS console for a SonarQube page and reload it — you should see errors about icons links, telling why they are blocked. If the URL of image still gives an error, at least, you will see it clearly.
In case of HTTP, adding HTTPS proxy in front of your SonarQube should solve the problem. Security is a good idea anyway.
