### ISSUE TITLE
common internal model for issues in PR

### ISSUE THREAD

**Issue by mildis** [mc1arke/sonarqube-community-branch-plugin#36]
Hi,  

We are working on integrating Gerrit on the pr-decoration branch.  
What we observed is that whatever backend is used for PR, there is a need for the same basic datas.  
Of course, depending on the tool, some additional informations may be useful.  

What about creating a common internal model for issues decorated in PR ?  
- a PR message : the comment set in the tool timeline, a general message about the decoration
- file-wide issue : not specifically related to a line or range, along its severity
- 0 or more line-issue : issues that are bound to a line in a file (or a range of lines), along there severities too

**Comment by mc1arke** [comment]
This should now be included in #30 through the `AnalysisDetails` class. Let me know if you need more added.
