### ISSUE TITLE
Azure Devops: mono repo support

### ISSUE THREAD

**Issue by axylophon** [mc1arke/sonarqube-community-branch-plugin#361]
Hi,

are mono repos supported with this plugin?
We have .NET and Angular projects mixed in a single repository.  If we create a PR are the comments and the quality gate then merged when consecutive sonar analysis are executed in separate pipelines?

I see a merged PR with the issue #213. But this is only for GitHub,

Thank you!

**Comment by mc1arke** [comment]
No, the analysis name would currently clash between different runs in Azure so overwrite the existing pipeline. The existing change should be easy to extend to cover all decorators though.

**Comment by axylophon** [comment]
Thank you for your response!

If the project name is added like in the Github solution, this would potentially break existing DevOps builds, as the name of the StatusCheck in DevOps is modified.
Would this be acceptable?

**Comment by mc1arke** [comment]
Yes, if the project is configured to depend on a status check with a particular name then renaming the Status Check will cause problems, however without having checks named differently then there's no way to support monorepos. I've implemented my proposed approach in #391, could you take a look and provide any feedback please?

**Comment by axylophon** [comment]
Hi thank you for your work it is highly appreciated!
The refactoring looks good to me.

**Comment by mc1arke** [comment]
Released in 1.9.0 and 1.8.1
