### ISSUE TITLE
No commit details were submitted with this analysis. Check the project is committed to Git

### ISSUE THREAD

**Issue by chakrapani123** [mc1arke/sonarqube-community-branch-plugin#372]
Hello,

PR decoration doesnt get populated in github and wondering if there is anything missing in configurations that is needed for setup

INFO: SonarScanner 4.6.2.2472
sonar version : 8.9 CE
plugin version : 1.8 

noticing this in ce log 
```
2021.06.23 21:12:11 DEBUG ce[AXo6t1AfQEv1JnSLLKyy][c.g.m.s.p.c.p.PullRequestPostAnalysisTask] found 4 pull request decorators
2021.06.23 21:12:11 WARN  ce[AXo6t1AfQEv1JnSLLKyy][c.g.m.s.p.c.p.PullRequestPostAnalysisTask] No commit details were submitted with this analysis. Check the project is committed to Git
2021.06.23 21:12:11 INFO  ce[AXo6t1AfQEv1JnSLLKyy][o.s.c.t.p.a.p.PostProjectAnalysisTasksExecutor] Pull Request Decoration | status=SUCCESS | time=9ms
```

`sonar-scanner -X -Dsonar.host.url=${SONAR_URL} -Dsonar.login=${SONAR_TOKEN} -Dsonar.projectKey=project-name -Dsonar.pullrequest.key=62 -Dsonar.pullrequest.branch=$(git branch --show-current)`

thanks
chakri

**Comment by mc1arke** [comment]
Is the Git plugin enabled in your Sonarqube installation?

**Comment by chakrapani123** [comment]
yes it is enabled

**Comment by mc1arke** [comment]
This error is shown when your project doesn't have a `revision` submitted as part of the analysis, with means the project decorators that normally detect this haven't run or aren't enabled, or that your project doesn't contain the Git metadata in the format these decorators expect.
