### ISSUE TITLE
Guide how to change "localhost:9000" link 

### ISSUE THREAD

**Issue by luisxiaomai** [mc1arke/sonarqube-community-branch-plugin#373]
When I click "View in soanrqube" link in gitlab pr decoration, it redirects to "localhost:9000"? Can anyone guide how to config the real self-host sonarqube server?
<img width="996" alt="Screen Shot 2021-06-24 at 8 20 29 PM" src="https://user-images.githubusercontent.com/6835229/123261924-ece8fe80-d529-11eb-8749-1f07cdaa40fb.png">

**Comment by nixel2007** [comment]
Check sonar.core.serverBaseURL in your server's administration settings

**Comment by luisxiaomai** [comment]
@nixel2007 thanks, resolved.
