### ISSUE TITLE
Often Analysis FAILED

### ISSUE THREAD

**Issue by maoyangcao** [mc1arke/sonarqube-community-branch-plugin#374]
**Describe the bug**
Often Analysis FAILED 
Error Details
Analyses suspended. Please set a valid license for the Edition you installed.
Sometimes SUCCESS
The code and branch are the same

**Software Versions**
docker images
mc1arke/sonarqube-with-community-branch-plugin:8.9-community
SonarScanner 4.6.2.2472

**Additional context**
command：
/var/jenkins_home/tools/hudson.plugins.sonar.SonarRunnerInstallation/zk-sonar-scanner/bin/sonar-scanner -X -Dsonar.projectKey=open-api -Dsonar.projectName=open-api -Dsonar.sourceEncoding=UTF-8 -Dsonar.language=java -Dsonar.projectVersion=1.0 -Dsonar.java.binaries=. -Dsonar.sources=. '-Dsonar.exclusions=**/test/**,**/target/**,**/changenacosconfig/**,**/changesql/**' -Dsonar.branch.name=dev

**Comment by mc1arke** [comment]
This isn't enough to replicate or diagnose. What appears in the logs when this message starts appearing? Can you also confirm if you're going anything else in the Docker image on startup?

**Comment by maoyangcao** [comment]
> This isn't enough to replicate or diagnose. What appears in the logs when this message starts appearing? Can you also confirm if you're going anything else in the Docker image on startup?

Except for the Generate admin Token , no other configuration is done.

docker start command：
docker run -d  --restart=always  --name sonarqube8.9 -p 19000:9000  -e SONARQUBE_JDBC_URL=xxx -e SONARQUBE_JDBC_USERNAME=xxx -e SONARQUBE_JDBC_PASSWORD=xxx mc1arke/sonarqube-with-community-branch-plugin:8.9-community


docker logs is Nothing when FAILED 


access.log :

172.18.241.243 - - [27/Jun/2021:00:25:41 +0000] "GET /batch/index HTTP/1.1" 200 - "-" "ScannerCLI/4.6.2.2472" "AXpGQaj4H6H9hXklAAM+"
172.18.241.243 - - [27/Jun/2021:00:25:42 +0000] "GET /api/settings/values.protobuf HTTP/1.1" 200 5024 "-" "ScannerCLI/4.6.2.2472" "AXpGQaj4H6H9hXklAAM/"
172.18.241.243 - - [27/Jun/2021:00:25:42 +0000] "GET /api/plugins/installed HTTP/1.1" 200 - "-" "ScannerCLI/4.6.2.2472" "AXpGQaj4H6H9hXklAANA"
172.18.241.243 - - [27/Jun/2021:00:25:43 +0000] "GET /api/settings/values.protobuf?component=open-api HTTP/1.1" 200 5031 "-" "ScannerCLI/4.6.2.2472" "AXpGQaj4H6H9hXklAANB"
172.18.241.243 - - [27/Jun/2021:00:25:43 +0000] "GET /api/project_branches/list?project=open-api HTTP/1.1" 200 314 "-" "ScannerCLI/4.6.2.2472" "AXpGQaj4H6H9hXklAANC"
172.18.241.243 - - [27/Jun/2021:00:25:43 +0000] "GET /api/project_pull_requests/list?project=open-api HTTP/1.1" 200 19 "-" "ScannerCLI/4.6.2.2472" "AXpGQaj4H6H9hXklAAND"
172.18.241.243 - - [27/Jun/2021:00:25:43 +0000] "GET /api/qualityprofiles/search.protobuf?project=open-api HTTP/1.1" 200 1640 "-" "ScannerCLI/4.6.2.2472" "AXpGQaj4H6H9hXklAANE"
172.18.241.243 - - [27/Jun/2021:00:25:43 +0000] "GET /api/rules/search.protobuf?f=repo,name,severity,lang,internalKey,templateKey,params,actives,createdAt,updatedAt,deprecatedKeys&activation=true&qprofile=AXpGQYNvmYLf551YA9w9&ps=500&p=1 HTTP/1.1" 200 6579 "-" "ScannerCLI/4.6.2.2472" "AXpGQaj4H6H9hXklAANF"
172.18.241.243 - - [27/Jun/2021:00:25:43 +0000] "GET /api/rules/search.protobuf?f=repo,name,severity,lang,internalKey,templateKey,params,actives,createdAt,updatedAt,deprecatedKeys&activation=true&qprofile=AXpGQYQFmYLf551YA9ya&ps=500&p=1 HTTP/1.1" 200 7859 "-" "ScannerCLI/4.6.2.2472" "AXpGQaj4H6H9hXklAANG"
172.18.241.243 - - [27/Jun/2021:00:25:43 +0000] "GET /api/rules/search.protobuf?f=repo,name,severity,lang,internalKey,templateKey,params,actives,createdAt,updatedAt,deprecatedKeys&activation=true&qprofile=AXpGQYRzmYLf551YA9y6&ps=500&p=1 HTTP/1.1" 200 11 "-" "ScannerCLI/4.6.2.2472" "AXpGQaj4H6H9hXklAANH"
172.18.241.243 - - [27/Jun/2021:00:25:43 +0000] "GET /api/rules/search.protobuf?f=repo,name,severity,lang,internalKey,templateKey,params,actives,createdAt,updatedAt,deprecatedKeys&activation=true&qprofile=AXpGQYSbmYLf551YA9z1&ps=500&p=1 HTTP/1.1" 200 6195 "-" "ScannerCLI/4.6.2.2472" "AXpGQaj4H6H9hXklAANI"
172.18.241.243 - - [27/Jun/2021:00:25:43 +0000] "GET /api/rules/search.protobuf?f=repo,name,severity,lang,internalKey,templateKey,params,actives,createdAt,updatedAt,deprecatedKeys&activation=true&qprofile=AXpGQYUimYLf551YA91W&ps=500&p=1 HTTP/1.1" 200 8114 "-" "ScannerCLI/4.6.2.2472" "AXpGQaj4H6H9hXklAANJ"
172.18.241.243 - - [27/Jun/2021:00:25:43 +0000] "GET /api/rules/search.protobuf?f=repo,name,severity,lang,internalKey,templateKey,params,actives,createdAt,updatedAt,deprecatedKeys&activation=true&qprofile=AXpGQYYimYLf551YA97C&ps=500&p=1 HTTP/1.1" 200 - "-" "ScannerCLI/4.6.2.2472" "AXpGQaj4H6H9hXklAANK"
172.18.241.243 - - [27/Jun/2021:00:25:43 +0000] "GET /api/rules/search.protobuf?f=repo,name,severity,lang,internalKey,templateKey,params,actives,createdAt,updatedAt,deprecatedKeys&activation=true&qprofile=AXpGQYesmYLf551YA-B_&ps=500&p=1 HTTP/1.1" 200 - "-" "ScannerCLI/4.6.2.2472" "AXpGQaj4H6H9hXklAANL"
172.18.241.243 - - [27/Jun/2021:00:25:43 +0000] "GET /api/rules/search.protobuf?f=repo,name,severity,lang,internalKey,templateKey,params,actives,createdAt,updatedAt,deprecatedKeys&activation=true&qprofile=AXpGQYismYLf551YA-FL&ps=500&p=1 HTTP/1.1" 200 7766 "-" "ScannerCLI/4.6.2.2472" "AXpGQaj4H6H9hXklAANM"
172.18.241.243 - - [27/Jun/2021:00:25:43 +0000] "GET /api/rules/search.protobuf?f=repo,name,severity,lang,internalKey,templateKey,params,actives,createdAt,updatedAt,deprecatedKeys&activation=true&qprofile=AXpGQYoomYLf551YA-Nw&ps=500&p=1 HTTP/1.1" 200 - "-" "ScannerCLI/4.6.2.2472" "AXpGQaj4H6H9hXklAANN"
172.18.241.243 - - [27/Jun/2021:00:25:43 +0000] "GET /api/rules/search.protobuf?f=repo,name,severity,lang,internalKey,templateKey,params,actives,createdAt,updatedAt,deprecatedKeys&activation=true&qprofile=AXpGQY0VmYLf551YA-gO&ps=500&p=1 HTTP/1.1" 200 - "-" "ScannerCLI/4.6.2.2472" "AXpGQaj4H6H9hXklAANO"
172.18.241.243 - - [27/Jun/2021:00:25:44 +0000] "GET /api/rules/search.protobuf?f=repo,name,severity,lang,internalKey,templateKey,params,actives,createdAt,updatedAt,deprecatedKeys&activation=true&qprofile=AXpGQY-emYLf551YA-oO&ps=500&p=1 HTTP/1.1" 200 6983 "-" "ScannerCLI/4.6.2.2472" "AXpGQaj4H6H9hXklAANP"
172.18.241.243 - - [27/Jun/2021:00:25:44 +0000] "GET /api/rules/search.protobuf?f=repo,name,severity,lang,internalKey,templateKey,params,actives,createdAt,updatedAt,deprecatedKeys&activation=true&qprofile=AXpGQZFEmYLf551YA-q2&ps=500&p=1 HTTP/1.1" 200 - "-" "ScannerCLI/4.6.2.2472" "AXpGQaj4H6H9hXklAANQ"
172.18.241.243 - - [27/Jun/2021:00:25:44 +0000] "GET /api/rules/search.protobuf?f=repo,name,severity,lang,internalKey,templateKey,params,actives,createdAt,updatedAt,deprecatedKeys&activation=true&qprofile=AXpGQZB8mYLf551YA-pE&ps=500&p=1 HTTP/1.1" 200 2720 "-" "ScannerCLI/4.6.2.2472" "AXpGQaj4H6H9hXklAANR"
172.18.241.243 - - [27/Jun/2021:00:25:44 +0000] "GET /api/rules/search.protobuf?f=repo,name,severity,lang,internalKey,templateKey,params,actives,createdAt,updatedAt,deprecatedKeys&activation=true&qprofile=AXpGQZI6mYLf551YA-v8&ps=500&p=1 HTTP/1.1" 200 - "-" "ScannerCLI/4.6.2.2472" "AXpGQaj4H6H9hXklAANS"
172.18.241.243 - - [27/Jun/2021:00:25:44 +0000] "GET /api/rules/search.protobuf?f=repo,name,severity,lang,internalKey,templateKey,params,actives,createdAt,updatedAt,deprecatedKeys&activation=true&qprofile=AXpGQZR0mYLf551YA-4c&ps=500&p=1 HTTP/1.1" 200 - "-" "ScannerCLI/4.6.2.2472" "AXpGQaj4H6H9hXklAANT"
172.18.241.243 - - [27/Jun/2021:00:25:44 +0000] "GET /api/rules/search.protobuf?f=repo,name,severity,lang,internalKey,templateKey,params,actives,createdAt,updatedAt,deprecatedKeys&activation=true&qprofile=AXpGQZW5mYLf551YA-_F&ps=500&p=1 HTTP/1.1" 200 - "-" "ScannerCLI/4.6.2.2472" "AXpGQaj4H6H9hXklAANU"
172.18.241.243 - - [27/Jun/2021:00:25:45 +0000] "GET /api/metrics/search?f=name,description,direction,qualitative,custom&ps=500&p=1 HTTP/1.1" 200 - "-" "ScannerCLI/4.6.2.2472" "AXpGQaj4H6H9hXklAANV"
172.18.241.243 - - [27/Jun/2021:00:25:46 +0000] "GET /batch/project.protobuf?key=open-api&branch=dev HTTP/1.1" 200 - "-" "ScannerCLI/4.6.2.2472" "AXpGQaj4H6H9hXklAANW"
172.18.241.243 - - [27/Jun/2021:00:26:07 +0000] "GET /api/new_code_periods/show.protobuf?project=open-api&branch=dev HTTP/1.1" 200 19 "-" "ScannerCLI/4.6.2.2472" "AXpGQaj4H6H9hXklAANX"
172.18.241.243 - - [27/Jun/2021:00:26:08 +0000] "POST /api/ce/submit?projectKey=open-api&projectName=open-api&characteristic=branch%3Ddev&characteristic=branchType%3DBRANCH HTTP/1.1" 200 44 "-" "ScannerCLI/4.6.2.2472" "AXpGQaj4H6H9hXklAANY"
172.18.241.243 - - [27/Jun/2021:00:26:28 +0000] "GET /api/ce/task?id=AXpK2_n7mYLf551YA_CY HTTP/1.1" 200 568 "-" "Scanner for Jenkins" "AXpGQaj4H6H9hXklAANZ"
172.18.241.243 - - [27/Jun/2021:00:26:29 +0000] "GET /api/ce/task?id=AXpK2_n7mYLf551YA_CY HTTP/1.1" 200 568 "-" "Scanner for Jenkins" "AXpGQaj4H6H9hXklAANa"


![image](https://user-images.githubusercontent.com/13943027/123529368-0f456c80-d722-11eb-9aee-b7f4a741d85b.png)
![image](https://user-images.githubusercontent.com/13943027/123529375-1cfaf200-d722-11eb-80c9-0d4133a7d2d9.png)

**Comment by maoyangcao** [comment]
Previously run developer-eidition，But container is remove and database is clear

**Comment by mc1arke** [comment]
When you say `database is clear`, what do you mean? I suspect you're either running with a license still saved in the database that isn't valid for the edition of Sonarqube that you're running, or that you're still running Developer edition but without a license file that matches your server ID.

Since the error has resulted in a suspended analysis then the logs that would be most likely to show this are either the CE or Web logs.

**Comment by maoyangcao** [comment]
I mean deleted all tables

**Comment by mc1arke** [comment]
I'd still need you to provide your CE and Web logs to allow this to be investigated.

**Comment by mc1arke** [comment]
Closing since this issues cannot be replicated, and no further detail provided
