### ISSUE TITLE
analysis project  branch measure all is zero,but same code master branch have measure

### ISSUE THREAD

**Issue by dnlixiaoxin** [mc1arke/sonarqube-community-branch-plugin#375]
sonarqube vesion is 7.8
branch plugin bersion is 1.3.2
no error log in sonarqube 
this is master picture
![image](https://user-images.githubusercontent.com/32609939/123537982-f90cd000-d764-11eb-8da0-58e50c27b5e6.png)
this is test branch picture 
![image](https://user-images.githubusercontent.com/32609939/123538004-0924af80-d765-11eb-95d4-180bc95521ec.png)

**Comment by dnlixiaoxin** [comment]
i select sonar issue table ，there is no data in table , so what do i need to do can use the branch plugin , expect  ur reply.  thanks

**Comment by dnlixiaoxin** [comment]
Long standing branch data is exist, but short standing branch data is not exit

**Comment by mc1arke** [comment]
What did you change on your branch? If you've not changed any executable code then the coverage will show as empty since no changed lines have any coverage.

**Comment by dnlixiaoxin** [comment]
i add 1k line code ， short branch show no data and source is empty

**Comment by mc1arke** [comment]
Can you provide a sample project and list of instructions to replicate this with please? I need to know some basic things like which build tools you're using, the commands you use to launch the scanner, what compilers/languages you're using etc, as my standard tests when releasing the plugin perform branch and pull request analysis that detect change metrics without any issues.

**Comment by dnlixiaoxin** [comment]
Thanks for ur reply, you can use the following information:
example repo:https://github.com/dnlixiaoxin/gulimall-1.git
execute commend line: mvn compile sonar:sonar -Dsonar.host.url = xxx -Dsonar.login=xxx
base info : jdk 1.8 ； maven version:Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f) 
OS：name: "mac os x", version: "10.15.7", arch: "x86_64", family: "mac"
