### ISSUE TITLE
Error: This feature must first be enabled in the global settings.

### ISSUE THREAD

**Issue by gvemula** [mc1arke/sonarqube-community-branch-plugin#389]
**Unable do Pull Request Decoration from Adminstration **

I am using SonarQube community edition 8.9.1 and sonarqube-community-branch-plugin: 1.8.0
In Project Settings > General Settings > Pull Request Decoration , I get message This feature must first be enabled in the global settings. Check the screen below
I did all configurations as mentioned in readme.

<img width="991" alt="Screenshot 2021-07-12 at 9 39 32 PM" src="https://user-images.githubusercontent.com/45610940/125321301-2dce7900-e35a-11eb-8ccd-f36fd06f001a.png">

When i check in Administration > Configuration , i do not see any pull request configuration. Check the screen below

<img width="1358" alt="Screenshot 2021-07-12 at 9 39 08 PM" src="https://user-images.githubusercontent.com/45610940/125321240-1b543f80-e35a-11eb-81a0-c538dd5e1555.png">

**Software Versions**
 - SonarQube Version: 8.9.1
 - Plugin Version: 1.8.9

**Comment by mc1arke** [comment]
You need to configure the relevant ALM in the `ALM Integrations` section of the global configuration screens

**Comment by gvemula** [comment]
> You need to configure the relevant ALM in the `ALM Integrations` section of the global configuration screens

Hi @mc1arke  i already configured my Github in 'ALM Integrations', but still sonar results summary does not appear in GIthub conversions. is there any other configuration required?

**Comment by mc1arke** [comment]
You need to provide more detail about what steps you've taken, as your screenshots don't show a Sonarqube instance capable of decoration, and what you need to execute to get comments on a PR will depend on what build system you're using

**Comment by gvemula** [comment]
I use maven with spring boot. Using git hub acttions I invoke sonar scan. Scan is successful, However I would like to see the results in PR conversation or checks tab.
