### ISSUE TITLE
Can not analyze feature branch for sonarqube 8.9

### ISSUE THREAD

**Issue by dassay75** [mc1arke/sonarqube-community-branch-plugin#390]
Hello
I have installed sonarqube 8.9 , to analyze feature branches I use the plugin  1.8.0 version.
I installed this plugin in:
extensions/plugins
I restart the sonarqube , I can see the plugin in the market place , but the features in not present
Thanks

**Comment by mc1arke** [comment]
Closing since the issue does not provide the details required in the template.
