### ISSUE TITLE
SQ[8.0] Scanner execution/reporting fails

### ISSUE THREAD

**Issue by simkin** [mc1arke/sonarqube-community-branch-plugin#40]
**Describe the bug**
ERROR: Error during SonarQube Scanner execution
ERROR: Unable to load component class org.sonar.scanner.scan.ProjectLock
ERROR: Caused by: Unable to load component class org.sonar.api.batch.fs.internal.DefaultInputProject
ERROR: Caused by: com.github.mc1arke.sonarqube.plugin.scanner.CommunityBranchParamsValidator.validate(Ljava/util/List;)V

SQ 8.0
Plugin 1.1.1

**Comment by nixel2007** [comment]
Duplicate of #38

**Comment by simkin** [comment]
Apologies
