### ISSUE TITLE
Cyclomatic complexity on short living branches

### ISSUE THREAD

**Issue by HassanWahba** [mc1arke/sonarqube-community-branch-plugin#406]
I see that the short-living branches don't analyze there own complexity, but I actually need it for my work. any tips on how to do that? in the photos below an illustration

for long living branches like master there is a complexity field in the measures tap

![image](https://user-images.githubusercontent.com/47371151/128265315-e9d98bfb-ab71-4864-a651-12ca50dcba79.png)

for short living branches there is not

![image](https://user-images.githubusercontent.com/47371151/128265370-c68cf85f-4331-46ae-8fb9-22d9f112c599.png)

**Comment by mc1arke** [comment]
Any metrics are managed by Sonarqube core, so are out-with the control of this plugin.
