### ISSUE TITLE
Sonar 7.9.3 community integration branch scan failed

### ISSUE THREAD

**Issue by danqiusheng** [mc1arke/sonarqube-community-branch-plugin#410]
**Describe the bug**
1.Configure branch scan as described in this document. An error is reported when starting the Sonar service
2. I have tried 1.3.0,1.3.1 and 1.3.2 as well
**To Reproduce**

1.Download version 1.3.0 and copy to /extensions/plugins
2.Modify the configuration
sonar.web.javaAdditionalOpts=-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.3.0.jar=web
sonar.ce.javaAdditionalOpts=-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.3.0.jar=ce

**Expected behavior**
The service starts normally.

**Screenshots**
![20210809215358](https://user-images.githubusercontent.com/32736331/128717660-4581c2bd-5cfc-4b56-ba95-b3c67541f61a.jpg)

2021.08.09 13:27:52 INFO  app[][o.s.a.SchedulerImpl] Process[web] is up
2021.08.09 13:27:52 INFO  app[][o.s.a.ProcessLauncherImpl] Launch process[[key='ce', ipcIndex=3, logFilenamePrefix=ce]] from [/opt/sonarqube]: /usr/local/openjdk-11/bin/java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/opt/sonarqube/temp --add-opens=java.base/java.util=ALL-UNNAMED -Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError -javaagent:/opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin-1.3.0.jar=ce -Dhttp.nonProxyHosts=localhost|127.*|[::1] -cp ./lib/common/*:/opt/sonarqube/lib/jdbc/postgresql/postgresql-42.2.5.jar org.sonar.ce.app.CeServer /opt/sonarqube/temp/sq-process2702095198793668890properties
Failed to find Premain-Class manifest attribute in /opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin-1.3.0.jar
Error occurred during initialization of VM
agent library failed to init: instrument
2021.08.09 13:27:52 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [ce]: 1
2021.08.09 13:27:52 INFO  app[][o.s.a.SchedulerImpl] Process[ce] is stopped
2021.08.09 13:27:52 INFO  web[][o.s.p.ProcessEntryPoint] Hard stopping process

**Software Versions**
 - SonarQube Version: Version 7.9.3 (build 33349)
 - Plugin Version: 1.3.0
 
**other**
Sonar service uses container build

**Comment by qqshfox** [comment]
You probably want to follow the instructions in [README in 1.3.2](https://github.com/mc1arke/sonarqube-community-branch-plugin/blob/1.3.2/README.md#installation).

> Copy the plugin JAR file to the extensions/plugins/ and the lib/common/ directories of your SonarQube instance and restart SonarQube.
