### ISSUE TITLE
SonarQube 7.9.6 doesn't start with open-jdk-11 and branch analysis plugin 1.3.2

### ISSUE THREAD

**Issue by maggosourabh** [mc1arke/sonarqube-community-branch-plugin#411]
**Bug Description**
While using SonarQube 7.9.6 (LTS) with sonar community branch analysis plugin 1.3.2 as per compatibility matrix defined, SonarQube crashes with following error:

**Failed to find Premain-Class manifest attribute in ./extensions/plugins/sonarqube-community-branch-plugin-1.3.2.jar**

**To Reproduce**
1. Install https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-7.9.6.zip on RHEL 7/8 or SuSE 12 SP3/Sp4 with openjdk-11.
2. Install 1.3.2 version in sonarqube.
3. Set values for javaagent opts both for web and ce as guided in README.
4. Start SonarQube and look for sonar.log file.

**Expected behavior**
As per compatibility matrix and requirements defined, sonarqube should be able to enable the plugin.

**Software Versions**
 - SonarQube Version: Community EditionVersion 7.9.6 (build 41879)
 - Plugin Version: 1.3.2

**Comment by mc1arke** [comment]
Version 1.3.2 doesn't use the Java Agent installation steps. You need to follow the installation instructions for that version: https://github.com/mc1arke/sonarqube-community-branch-plugin/tree/1.3.2#installation

However, 7.9 isn't the latest LTS version, is there any reason you're not using 8.9?

**Comment by maggosourabh** [comment]
@mc1arke  - We were preparing ourselves for migration from 6 to latest stable version of 7 first as we serve a big platform and want to migrate in a canary approach for the latest available versions with only minor hassles to our end-users.

Also we were able to fix the issue with **sonar.branch.name** option not working with our branches by changing our long live branches to master only (default is release in SonarQube installation). With default long live SonarQube was causing issue with our release branches not been able to analyze stating out "This parameter is only applicable to development and enterprise edition."

What i suggest is we need to update the README with the input as one using any version of this plugin or SonarQube will have to make sure that  they are referring "master" as long live branch and always make sure that first execution with sonar.branch.name parameter is done for master branch only.

![image](https://user-images.githubusercontent.com/25922853/128874586-d77dc175-b1af-48cb-a0fa-785d4ac8d383.png)
