### ISSUE TITLE
Can't use branch Analysis on sonarqube version 9.0.2 with plugin version 1.9.0

### ISSUE THREAD

**Issue by newsupapat** [mc1arke/sonarqube-community-branch-plugin#414]
Hi I try to work with Sonarqube version 9.0+ as a community version inside k8s cluster so I use Helm Chart from https://github.com/oteemo/charts and specifies the plugin at vaules.yaml 
![image](https://user-images.githubusercontent.com/38752747/129666449-41d413cd-b6a0-45ab-8e1d-baadd4e4ce60.png) but the bracnh analysis did't work

Btw The branch analysis work when used with the 8.8 version and plugin version 1.7.0

What am I missing here or need more additional steps to step please help

**Comment by mc1arke** [comment]
Are you setting variables in your helm chart anywhere that set the Java Agent parameters mentioned in the installation instructions in the README?
