### ISSUE TITLE
[GitHub] Make pull request status check name configurable

### ISSUE THREAD

**Issue by alexbde** [mc1arke/sonarqube-community-branch-plugin#415]
Hi!

Following idea for an enhancement: it would be great if the name of the status check on a pull request would be configurable. At the moment it is hard-coded to `<project-name> Sonarqube Results`, see [the source code](https://github.com/mc1arke/sonarqube-community-branch-plugin/blob/1.9.0/src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/github/v4/GraphqlGithubClient.java#L127).

Which leads to a status check like this (where `sonarqube-test` is the project name):

![image](https://user-images.githubusercontent.com/17784818/129718043-df013bdf-f323-4779-a144-3c8a3d3cae43.png)

This makes it hard to apply global policies for required status checks in GitHub, because the name differs per project. As an example: there is a global policy we apply to all GitHub repositories that a status check called "Jenkins" is required to pass before a PR could be merged. That is no problem, because the status check is called "Jenkins" for every repository.

If I would like to do the same for SonarQube, I would need to adjust the name of the status check in every repository, e.g.:

![image](https://user-images.githubusercontent.com/17784818/129718908-f5781998-1e60-4065-b9d2-21a8aae721a4.png)

If I could support by testing a new plugin version or similar, I would be happy to do so.

**Comment by Tsuesun** [comment]
@alexbde We faced the same problem, if you can't wait you can do what we did and forked the plugin and changed the status check name. If you don't want to do that you can use the github api to set the custom sonarqube status check for every repo.

**Comment by balusarakesh** [comment]
we are also facing the same issue and this problem started happening after upgrading sonarqube from `7.X` to `8.X`, before that we had a universal name for all checks...after the upgrade the check name changed with project name as prefix

**Comment by gjabouley-invn** [comment]
Hi, for information in the "Developer" edition (paid), GitHub status check has a fixed name `SonarQube Code Analysis`
Maybe could be relevant to align to this behavior...

![image](https://user-images.githubusercontent.com/47566129/234941478-c2a8da07-f394-444f-8366-a04f97da946f.png)
