### ISSUE TITLE
External issues ignored

### ISSUE THREAD

**Issue by tfedyanin** [mc1arke/sonarqube-community-branch-plugin#42]
**Describe the bug**
External issues are ignored in branches.

**To Reproduce**
Create a project with checkstyle report without errors and an empty quality profile.
Create the first build (create main sonar report for master).
Change branch and create checkstyle report with errors.
Run sonarqube in this branch. 
There is no new condesmells. But if you run sonarqube on master with this report, new issues will appear.

**Expected behavior**
There is new condesmell in branch report.

**Software Versions**
 - SonarQube Version: 7.9.0.26994
 - Plugin Version: 1.1.1

**Additional context**
Report path configured in webUI.

**Comment by tfedyanin** [comment]
I found that sonar ignore new issues as new, but present it in web-report:
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/1610914/67640533-37a51400-f90c-11e9-9bc9-901d1479dfb6.png">

**Comment by mc1arke** [comment]
This plugin only provides the implementation of branch functionality, not scanning or reporting of issues. I'm going to close this as a `Won't fix` as I believe this is a SonarQube core issue, but I'm happy to take a closer look at it if you can provide evidence this works properly with the official branch plugin, or a suitable test case that proves this plugin is operating incorrectly.

**Comment by tfedyanin** [comment]
Thanks, I'm trying to investigate this problem. If I find something helpful, I will write.
