### ISSUE TITLE
Docker Image for 1.9.0?

### ISSUE THREAD

**Issue by chrismaille** [mc1arke/sonarqube-community-branch-plugin#422]
I'm looking at the [Docker Hub images for this project](https://hub.docker.com/r/mc1arke/sonarqube-with-community-branch-plugin), am I'm wondering if we will get a docker image for version 1.9.0.

Thank you for the hard work.

**Comment by mc1arke** [comment]
These haven't been published yet. I'll be doing it in the next day!

**Comment by mc1arke** [comment]
These have  now been deployed.
