### ISSUE TITLE
Problem with sonar 8.9 can't create extra branches

### ISSUE THREAD

**Issue by hitokiri** [mc1arke/sonarqube-community-branch-plugin#423]
**Describe the bug**
The plugin appears installed in the marketplace, but I can't manage the branches, if when I run the sonar-scanner I put another different branch in the option 

e.g: sonar.branch.name = staging 

the scanner return this message to the end 

**Screenshots**
![bad_branch](https://user-images.githubusercontent.com/247528/130151478-aeb9d679-2d7d-47bc-9bb2-0838f2280e20.png)

**Expected behavior**

**Software Versions**
 - SonarQube Version: 8.9
 - Plugin Version: 1.8.0

**Additional context**
this option should appear in the menu
![image](https://user-images.githubusercontent.com/247528/130151925-83a53751-fa5c-46a3-a690-ce0ad2bb6878.png)

but in my case this does not happen
![image](https://user-images.githubusercontent.com/247528/130152006-24272dde-d467-493e-b9ad-d733c655015e.png)

**Comment by mc1arke** [comment]
The plugin isn't installed properly if you're unable to submit scans. It's likely you've not configured the Compute Engine installation properly.

**Comment by jgtvares** [comment]
Hey guys, I'm experiencing this running locally.
Our SonarQube version is currently in 7.9.3 and I'm trying to update to 8.9.
We also use this branch plugin and the same thing @hitokiri said is happening to me during analysis, and also, the settings doesn't show up anymore.
I'm running in Docker, so all I did was download the version 1.8.1 of this plugin, change the image tag and rebuild the container.
What am I missing?
