### ISSUE TITLE
Report upload from Azure CIDI do not work on Community edition for any branch except Master

### ISSUE THREAD

**Issue by PratikVavadia** [mc1arke/sonarqube-community-branch-plugin#43]
**Describe the bug**
Report upload from Azure CIDI do not work on Community edition for any branch except Master

**To Reproduce**
1. Go to 'Create build pipeline in azure devops and at the Run Code Analysis step it will fail'

_

> INFO: Sensor Zero Coverage Sensor
> INFO: Sensor Zero Coverage Sensor (done) | time=47ms
> INFO: SCM Publisher SCM provider for this project is: git
> INFO: SCM Publisher 14 source files to be analyzed
> INFO: SCM Publisher 14/14 source files have been analyzed (done) | time=573ms
> INFO: CPD Executor 29 files had no CPD blocks
> INFO: CPD Executor Calculating CPD for 136 files
> INFO: CPD Executor CPD calculation finished (done) | time=109ms
> INFO: SCM writing changed lines
> INFO: SCM writing changed lines (done) | time=187ms
> INFO: Analysis report generated in 312ms, dir size=377 KB
> INFO: Analysis report compressed in 203ms, zip size=208 KB
> INFO: ------------------------------------------------------------------------
> INFO: EXECUTION FAILURE
> INFO: ------------------------------------------------------------------------
> INFO: Total time: 56.494s
> INFO: Final Memory: 16M/160M
> INFO: ------------------------------------------------------------------------
> ##[error]ERROR: Error during SonarQube Scanner execution
> ERROR: Failed to upload report - An error has occurred. Please contact your administrator
> ERROR: 
> ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.
> ERROR: Error during SonarQube Scanner execution
> ERROR: Failed to upload report - An error has occurred. Please contact your administrator
> ERROR: 
> ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.
> ##[error]The process 'D:\a\_tasks\SonarQubeAnalyze_6d01813a-9589-4b15-8491-8164aeb38055\4.8.0\sonar-scanner\bin\sonar-scanner.bat' failed with exit code 1
> ##[section]Finishing: Run Code Analysis

_

Also if we check the web.log under logs folder we can see below

> 2019.10.30 07:49:10 ERROR web[AW4bh8qen6DU8a66AAIS][o.s.s.w.WebServiceEngine] Fail to process request http://<domain>/api/ce/submit?projectKey=<ProjectKey>&projectName=<projectName>&characteristic=branch%3<branchname>&characteristic=branchType%3DSHORT
> java.lang.IllegalStateException: Current edition does not support branch feature
>         at com.google.common.base.Preconditions.checkState(Preconditions.java:173)
>         at org.sonar.server.ce.queue.BranchSupport.createComponentKey(BranchSupport.java:63)
>         at org.sonar.server.ce.queue.ReportSubmitter.submit(ReportSubmitter.java:83)
>         at org.sonar.server.ce.ws.SubmitAction.handle(SubmitAction.java:113)
>         at org.sonar.server.ws.WebServiceEngine.execute(WebServiceEngine.java:110)
>         at org.sonar.server.platform.web.WebServiceFilter.doFilter(WebServiceFilter.java:92)
>         at org.sonar.server.platform.web.MasterServletFilter$GodFilterChain.doFilter(MasterServletFilter.java:138)
>         at org.sonar.server.platform.web.MasterServletFilter.doFilter(MasterServletFilter.java:107)
>         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
>         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
>         at org.sonar.server.platform.web.UserSessionFilter.doFilter(UserSessionFilter.java:88)
>         at org.sonar.server.platform.web.UserSessionFilter.doFilter(UserSessionFilter.java:72)
>         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
>         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
>         at org.sonar.server.platform.web.CacheControlFilter.doFilter(CacheControlFilter.java:76)
>         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
>         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
>         at org.sonar.server.platform.web.SecurityServletFilter.doHttpFilter(SecurityServletFilter.java:76)
>         at org.sonar.server.platform.web.SecurityServletFilter.doFilter(SecurityServletFilter.java:48)
>         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
>         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
>         at org.sonar.server.platform.web.RedirectFilter.doFilter(RedirectFilter.java:58)
>         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
>         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
>         at org.sonar.server.platform.web.RequestIdFilter.doFilter(RequestIdFilter.java:66)
>         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
>         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
>         at org.sonar.server.platform.web.RootFilter.doFilter(RootFilter.java:62)
>         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
>         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
>         at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:109)
>         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
>         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
>         at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
>         at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
>         at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
>         at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
>         at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
>         at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)
>         at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
>         at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
>         at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
>         at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
>         at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)
>         at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
>         at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
>         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
>         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
>         at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
>         at java.base/java.lang.Thread.run(Thread.java:834)
> 

**Expected behavior**
The Report should be updated to Sonarqube server

**Screenshots**
![image](https://user-images.githubusercontent.com/57172126/67840573-31858200-fb1c-11e9-877b-c02a3857daaf.png)

**Software Versions**
 - SonarQube Version:  8.0.0.29455
 - Plugin Version: sq-8_0-support Latest commit f2a3f56

**Additional context**
If we select the Master branch in CI for same it all works just fine and i can see the report under our install as seen in below screenshot
![image](https://user-images.githubusercontent.com/57172126/67840848-cbe5c580-fb1c-11e9-9daf-d2107b4fb1f7.png)

**Comment by mc1arke** [comment]
Are you sure you've installed the plugin correct, as per the README file from the branch you're building from? The line `java.lang.IllegalStateException: Current edition does not support branch feature` in your web.log indicates that SonarQube doesn't have all the settings to support branch analysis, and given this is coming from a class in the `ce` package, is likely to be due to the plugin not having been installed to both locations mentioned in the README.

**Comment by PratikVavadia** [comment]
Thanks a lot :D i just missed that one thing and now issues is resolved

**Comment by IbrahimUmar** [comment]
How did you resolved this issue?
I am using the Community Edition and getting this error?
**Fail to process request java.lang.IllegalStateException: Current edition does not support branch feature**

**Comment by PratikVavadia** [comment]
I just checked the README file in there there are two location where the files needs to be placed and i had missed at one of the location. So just check the README file and you should be fine
