### ISSUE TITLE
New Code for new branches on first run

### ISSUE THREAD

**Issue by adrielldagasuan** [mc1arke/sonarqube-community-branch-plugin#430]
Does this plugin support the project level setting for new code?
What I initially wanted to do was to have new branches always have the master branch as the reference branch for identifying new code. But for the community version, it looks like it can't be set (they say it's only starting with the Developer edition). I understand that I can do it via the individual branch setting. But that takes at least 2 runs of my branch: 1st one to actually 'register' the branch in SonarQube. Once it's there, tweak the setting so that the new code setting is to a reference branch. After all of this, succeeding runs would be compared to master. What I ideally was looking for was not having to go about setting this for individual branches, or at the very minimum have the setting already there on the first run.

**Comment by mc1arke** [comment]
Sonarqube defaults to using the master branch as the reference branch if one has not been manually set. The plugin provides the functionality (as of 1.8.1 or 1.9.0) to set the reference branch.
