### ISSUE TITLE
Project level setting not saved into the database

### ISSUE THREAD

**Issue by adrielldagasuan** [mc1arke/sonarqube-community-branch-plugin#434]
The project level setting for New Code isn't saved into the database after upgrading from 6.7 -> 7.9.6 -> 8.9. The community branch plugin was installed only for the 8.9 upgrade.

1. Select a project and go to Project Settings
2. Change the New Code definition of the New Code to be a reference branch to master
3. Save the changes

**Expected behavior**
If I go back to the Project Settings and check the New Code definition, it has defaulted back to old setting which was the Global setting. Checking the database, it also doesn't look like it's saved there.

**Software Versions**
 - SonarQube Version: Version 8.9.2 build 46101
 - Plugin Version: 1.8.0

**Additional context**

**Comment by earthpyy** [comment]
I guess it's already resolved in version 1.8.1. Related issue: #272
