### ISSUE TITLE
Preview flag required in Azure Devops Server (on-premise) for certain API calls

### ISSUE THREAD

**Issue by jbaehr-phoenis** [mc1arke/sonarqube-community-branch-plugin#442]
**Describe the bug**
On Azure-Devops-Server (the on-premise version of Azure Devops) certain API calls need the "-preview" flag added to the api version.
Namely the "Pull Request Statuses API".

**To Reproduce**
Use features that call the "Pull Request Statuses API" in the Azure Devops Api handler.

**Expected behavior**
The call should succeed.

**Screenshots**
Not really a screenshot but a log file (from the discussion in the pr mentioned below):
[sonarqube_ce.log](https://github.com/mc1arke/sonarqube-community-branch-plugin/files/7126065/sonarqube_ce.log)

**Software Versions**
 - SonarQube Version: irrelevant
 - Plugin Version: latest
 
**Additional context**
This issue was raised as a result of discussing the proposed fix/changes in PR #438

**Comment by mc1arke** [comment]
Released in 1.10.0 of the plugin
