### ISSUE TITLE
Expected URL scheme 'http' or 'https' but no colon was found

### ISSUE THREAD

**Issue by fabiano041197** [mc1arke/sonarqube-community-branch-plugin#443]
**Describe the bug**
I'm trying to use Sonarqube in my CI/CD proccess with GitLab Plugin and Sonarqube-Community-Branch-Plugin, but when i change the branch, this message appers.

**To Reproduce**
1. Configure sonarqube 8.9 w
2. Install sonarqube-community-branch-plugin with[ sonar-gitlab-plugin](https://github.com/gabrie-allaigre/sonar-gitlab-plugin/releases/tag/4.1.0-SNAPSHOT)
3. Try to scan with the command bellow
`- mvn --batch-mode verify sonar:sonar -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_LOGIN -Dsonar.gitlab.project_id=$CI_PROJECT_PATH -Dsonar.gitlab.commit_sha=$CI_COMMIT_REF -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME`

The message appers

`[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.0.2155:sonar (default-cli) on project iss: Unable to execute SonarScanner analysis: Fail to get bootstrap index from server: Expected URL scheme 'http' or 'https' but no colon was found -> [Help 1]`

**Screenshots**
![image](https://user-images.githubusercontent.com/18452250/133259304-70cb7fcc-197f-488d-9569-1098319bb864.png)

**Software Versions**
 - SonarQube Version: 8.9 (build 43852)]
 - Plugin Version: [e.g. 1.8.1

**Comment by mc1arke** [comment]
This doesn't look related to this plugin. The sonarqube task is attempting to parse the URL from your command line, but presumably `$SONAR_URL` doesn't exist, or doesn't start with `https://` or `http://`
