### ISSUE TITLE
Strange duplications in PR decorations on Azure DevOps

### ISSUE THREAD

**Issue by software-programmer** [mc1arke/sonarqube-community-branch-plugin#448]
**Describe the bug**
I am observing some strange duplications when using the PR decoration feature through Azure Devops that I've not seen before. It seems to be intermittent and I can't narrow it down to a particular cause or easily reproduce it in a consistent manner

**Expected behavior**
I would expect the PR annotation to include the original source code as it was committed, but as you can see from the screenshots something has caused the original code to be mutated slightly

**Screenshots**
![image](https://user-images.githubusercontent.com/5966776/134296178-361845a9-ded5-488a-a895-b5db60989157.png)

![image](https://user-images.githubusercontent.com/5966776/134296204-c0123a52-ec4f-4888-9325-bb11ce6200ae.png)

**Software Versions**
`mc1arke/sonarqube-with-community-branch-plugin:8.9-community`

**Comment by mc1arke** [comment]
This isn't the plugin that's causing this. When the plugin submits an decoration, it states the line numbers the decoration is for, and the text to show in the decoration body. It does not specify the code that's on those line numbers. What you see in the Pull Request view is Azure DevOps having taken the line number submitted in the reports and extracted and rendered code, so this is something wrong in the extraction process for Azure DevOps
