### ISSUE TITLE
Failed to find Premain-Class manifest attribute in ./extensions/plugins/sonarqube-community-branch-plugin-1.5.0.jar Error occurred during initialization of VM

### ISSUE THREAD

**Issue by Hello-Linux** [mc1arke/sonarqube-community-branch-plugin#453]
Due to development restrictions, we can only use version 8.4 and cannot upgrade to the latest lts version. How can we solve this problem?　And I see that other people have also encountered this problem, but they have not given a specific solution. Can you give me a detailed solution

**Describe the bug**
the start log is

Failed to find Premain-Class manifest attribute in ./extensions/plugins/sonarqube-community-branch-plugin-1.5.0.jar
Error occurred during initialization of VM

**Screenshots**
![2021-09-24 11-33-35 的屏幕截图](https://user-images.githubusercontent.com/17851645/134619472-bad7c320-a71f-48c2-b3be-a2f6a0a8a15c.png)

**Software Versions**
 - SonarQube Version: 8.4.2
 - Plugin Version: 1.5.0

**Comment by larruda** [comment]
I have the same issue. Why was this closed without a resolution?

**Comment by mc1arke** [comment]
@larruda if you're using 1.5.0 of the plugin then the issue is that you're not installing it properly. You need to follow the guide for that version: https://github.com/mc1arke/sonarqube-community-branch-plugin/tree/1.5.0#installation

**Comment by larruda** [comment]
I'm using 1.4.0 as it's the target version for Sonarqube 8.1 (as per the docs)

**Comment by larruda** [comment]
But I'll look further the instructions. Thanks!
