### ISSUE TITLE
Switching from Developer Edition to this plugin?

### ISSUE THREAD

**Issue by albanf** [mc1arke/sonarqube-community-branch-plugin#46]
We are currently using the Developer Edition.

Is this plugin using the same data model? Can we switch to community + this plugin?

**Comment by mc1arke** [comment]
The plugin implements the same APIs and aims to provide compatibility, and should be generating the same component identifiers, but I've never tested migration between this plugin and developer edition so can't be sure this works cleanly. I'd suggest you take a backup of your data and try running community edition with this plugin installed to see if your data is returned ok, then rescan of one of your existing branches to see if this plugin continues to provide the same data.

**Comment by mc1arke** [comment]
Feel free to provide any information you gather whilst attempting any migration to assist anyone who may attempt this in the future. In the meantime I'm going to close this issue since there's no further action to be performed on it.
