### ISSUE TITLE
[Azure DevOps] Pull request summary comment missing content with on-premise instances

### ISSUE THREAD

**Issue by KrylixZA** [mc1arke/sonarqube-community-branch-plugin#469]
**Describe the bug**
When running on on-premise SonarQube instance that isn't accessible via the world wide web, the pull request summary comment that has been added as part of SonarQube 9.1 + Plugin 1.10.0 (using snapshot as of time of submission) doesn't render in an easily readable manner. 
The reason for this is simply because Azure DevOps has no way of reaching the SonarQube instance to fetch the images such as `passed.svg`, `bug.svg`, etc.

While this is technically not a bug per say, it would be nice to have a way to customize the URL through which Azure DevOps fetches the images. Or potentially use a universally accessible URL such as something hosted through GitHub or potentially even SonarCloud itself. While it is not unusable, it does take an extra second to look at and interpret the results.

This particular issue can also extend to allow teams running on-premise SonarQube instances to get badges for their repository `README.md` files as well 👍 

**To Reproduce**
1. Host on on-premise instance of SonarQube Community Edition which is not accessible outside of an internal network (such as a company network)
2. Configure and enable pull request decoration using the 1.10.0 snapshot release of SonarQube Community Branch Plugin
3. Submit a pull request through Azure DevOps, ensuring build validation is configured for the branch policies for that particular repository.
4. Wait for the `SonarQubePublish` task to complete in your pipeline and browse to your pull request.
5. Observe the malformed pull request summary comment on the pull request as per the screenshot below.

**Expected behavior**
Below is a screenshot of the expected behaviour if the image URLs used are universally accessible through the WWW:
![image](https://user-images.githubusercontent.com/16819506/136507358-9c9fcde8-2282-417d-a082-4cb7f46e1d64.png)

**Screenshots**
Below is a screenshot of the current behaviour of the pull request summary comment with the SonarQube Server URL configured to be an internal link within my company's private VPN:
![image](https://user-images.githubusercontent.com/16819506/136505984-9b257378-ccbb-46f5-b74f-deade84acb31.png)

**Software Versions**
 - SonarQube Version: 9.1
 - Plugin Version: 1.10.0 snapshot

**Additional context**
In my particular case. the SonarQube server is only accessible within my company's internal VPN and is the root cause of the images not being accessible.

**Comment by mc1arke** [comment]
Does https://github.com/mc1arke/sonarqube-community-branch-plugin#serving-images-for-pr-decoration not provide what you need?

**Comment by KrylixZA** [comment]
Hey @mc1arke - yeah that is exactly what I needed. Thanks! 💯
