### ISSUE TITLE
Question: API to get result summary

### ISSUE THREAD

**Issue by link89** [mc1arke/sonarqube-community-branch-plugin#476]
Is there any API endpoint that I can get all result of a specific analysis. When I finish a sonar scan for a pull request, I would like to have the ability to get the result, like cov, bugs, security issue, code smell, etc and display in the report so that it would be convenient for developers to get result without open the link.

It would be great if the plugin provide a single endpoint that I can get all of those result. I am not sure if such an API already exists. Thank you.

**Comment by nixel2007** [comment]
Check the /web_api page at your server.
