### ISSUE TITLE
I am using sonarqube 8.9.3 (build 48735) community, but facing error ' Failed to upload report - An error has occurred. Please contact your administrator'

### ISSUE THREAD

**Issue by BalajiGuruanywhere** [mc1arke/sonarqube-community-branch-plugin#481]
I configured everything as said in readme.downloaded  plugin 1.8.0 jar. also added properties in conf/sonar.properties, ran the command sh sonar.sh from mac installation part but in web.log it's showing java.lang.IllegalStateException: Current edition does not support branch feature
Please help me out in this

**Comment by mosesontheweb** [comment]
I have the same issue right now with this. How has it been solved?

Regards, Thomas
