### ISSUE TITLE
Sonarqube 8.1 sonarqube-community-branch-plugin-1.4.0 not working

### ISSUE THREAD

**Issue by Haydar-Rap** [mc1arke/sonarqube-community-branch-plugin#482]
* Hello, I'm having trouble activating the sonarqube-community-branch-plugin-1.4.0 plugin. I throw the relevant file into the extension and add the necessary lines to the sonar.properties file. I'm getting an error can you help?

ERROR 
Error occurred during initialization of VM
agent library failed to init: instrument
Failed to find Premain-Class manifest attribute in ./extensions/plugins/sonarqube-community-branch-plugin-1.4.0.jar

sonar.properties
sonar.web.javaAdditionalOpts=-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.4.0.jar=web

sonar.ce.javaAdditionalOpts=-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.4.0.jar=ce

note: windows 2012 R2 installed sonarqube

**Comment by nixel2007** [comment]
You don't need to edit java opts for 1.4.0.
Check corresponding README at 1.4.0 git tag: https://github.com/mc1arke/sonarqube-community-branch-plugin/tree/1.4.0#installation

**Comment by Haydar-Rap** [comment]
I fixed the problem when I copied the .jar file under sonarqube/lib/com.
