### ISSUE TITLE
Justification Issues [“False Positive” or “Won’t fix”] aren’t synchronized between branches

### ISSUE THREAD

**Issue by Wankhadess** [mc1arke/sonarqube-community-branch-plugin#485]
**Describe the bug**
I want the issues justification set to “False Positive” or “Won’t fix” on a development branch merged back into the master branch. But these issues keep showing after merging the branch into master.

**To Reproduce**
I created a new branch for my project at Gitlab.
I executed sonar-scanner and got the branch analysis on SonarQube.
I reviewed some of the reported issues, fixed some at code, changed some others to “False Positive” / “Won’t Fix”
I executed sonar-scanner again, fixed issues are closed, and other issues are kept (good!)
I submit a Merge Request at Gitlab, and my branch gets merged into the master branch.
I checkout my project’s master branch and pull the changes. I confirm my changes have been merged.
I execute sonar-scanner again (on the master branch) ,but all “False positive” / “Won’t fix” issues are reopened again on SonarQube UI.

**Expected behavior**
I expected the master branch at SonarQube to have the “False positive” / “Won’t fix” issues to be resolved, but there they are, reported as open issues again.

**Software Versions**
 - SonarQube Version:  8.9.2 LTS
 - Plugin Version: 1.8.1

**Comment by mc1arke** [comment]
This plugin is not responsible for the reporting or merging of issues, only for the identification and management of branches. If you'd like this feature then you'll need to raise a request with Sonarsource to have it created in Sonarqube's core.

**Comment by Wankhadess** [comment]
Hi @mc1arke ,

As suggested by you I have raised the ticket on [SonarSource Community ](https://community.sonarsource.com/t/justification-issues-false-positive-or-won-t-fix-aren-t-synchronized-between-branches/53136) from there response it's clear that this development needs to be take care by Community Branch Plugin.

Can you please justify why from your point of view this feature development is invalid. 

Regards

**Comment by mc1arke** [comment]
If you mention this plugin then this response they've given if the standard response. The issue with the feature you're requesting is that there would need to be a mechanism in Sonarqube for requesting synchronization of issues from a Pull Request or Branch back to the target branch when a merge is performed, but this mechanism - or even an abstraction for performing this which the plugin could implement - does not exist. The feature therefore requires changes in Sonarqube core before the plugin can do anything.

**Comment by marceloavilaoliveira** [comment]
@mc1arke this is true. If someone just mentions the community-branch-plugin (the context doesn't matter) they immediately close the ticket with the standard response. It's really a shame.
