### ISSUE TITLE
Version 1.8.1 not working in 8.9.3LTS

### ISSUE THREAD

**Issue by mosesontheweb** [mc1arke/sonarqube-community-branch-plugin#486]
**Describe the bug**
We upgraded our system from the previous LTS version 7.9 to 8.9.3.48735 and also updated those previous plugins to their corresponding new version at the same time. So, the Community branch plugin has been updated from 1.3.2 to 1.8.1 as described in the matrix.
We now tried to make some tests. The plugin is loaded as expected, I see the bullet point "Branches & pull requests" under "Project Settings" and going there, I see all previous branches from that project. We build a new branch, built it with Maven and then let it analyze with SonarQube, which does not work. Error message: "Current edition does not support branch feature"
I increased the error level to debug for all components in sonar.properties, but I do not see that error message anywhere else, only in the error details of that branch.
Parameter used in pom.xml is `-Dsonar.branch.name=....`

**To Reproduce**
1. Install the plugin as described in README
2. Start analysis from Maven 

**Expected behavior**

**Screenshots**
None available.

**Software Versions**
 - SonarQube Version: 8.9.3.48735
 - Plugin Version: 1.8.1

**Additional context**
I already had once a problem with that plugin, which I solved by stepping back to some previous version and upgraded it step by step (1.1.1 -> 1.2.0 -> 1.3.2, for example). Would be great if someone could point me to a direction where to fix that problem. It's somehow weird because I see everything I expect but only the analyze part seems to have stopped working.

**Comment by nixel2007** [comment]
How exactly did you install the plugin?

**Comment by mosesontheweb** [comment]
Hi,

as described in the README tagged for version 1.8.1:

1. Copied the plugin JAR file to the extensions/plugins/ directory 
 2. Added -javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.8.1.jar=web to the sonar.web.javaAdditionalOpts to config/sonar.properties
 3. Added -javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.8.1.jar=ce to the sonar.web.javaAdditionalOpts to config/sonar.properties
 4. Started Sonarqube, ran the upgrade section, logged in and accepted the warning for 3rd party plugins

Regards, Thomas

**Comment by flozzone** [comment]
@mosesontheweb you should write to the `sonar.ce.javaAdditionalOpts` -> `.ce.` property in the second step.

but it still doesn't work with the correct property for me

**Comment by mosesontheweb** [comment]
Sorry, my bad. I added `-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.8.1.jar=ce` to `sonar.web.javaAdditionalOpts` instead of `sonar.ce.javaAdditionalOpts`. It works fine now for me.

Thanks to @flozzone for pointing that out to me. Sorry for the inconveniences I caused!

Regards, Thomas
