### ISSUE TITLE
Empty PR analysis report with 0 new code lines

### ISSUE THREAD

**Issue by Bloof** [mc1arke/sonarqube-community-branch-plugin#489]
Hi,

I have a problem with SonarQube showing always 0 new code on the finished PR analysis. Below is more information about the problem and things that i have already tried.

SonarQube Community EditionVersion 9.1 
SonarScanner 4.6.2
mc1arke/sonarqube-community-branch-plugin 1.9.0

GitLab Community Edition 13.12.11
GitLab Branch Source plugin 1.0.6

Jenkins 2.289.1
Jenkins Git Plugin 4.10.0

We are configuring pull request analysis with Gitlab webhook to Jenkins. This provides “GitLab branch source plugin” the required git branches (target/source) and is supposed to build ${gitlabSourceBranch} and analyse the new code versus ${gitlabTargetBranch}.
This project is a large corporate software with multiple modules, and is build with Gradle.

What we have tried so far:

- Works on a smaller Spring Boot project. Has configuration copied from this Jenkins job, but this Spring project uses maven to build the project
- Changed New Code analysis from "Previous Version" to "Reference Branch"
- Changed sonar-scanner JDK to Java 11 and also compiled the whole project in Java 11 
- Using refspec with only fetching source and target branch
- Git plugin step "Clean before checkout" 
	Adds these commands on log output:
		git rev-parse --verify HEAD
		git reset --hard
		git clean -fdx
		
- Git plugin configuration "Preserve second fetch for checkout"
	Removes "Avoid second fetch" from log output
	
- Changed git plugin to use SSH rather than HTTP
	Removed "skipping resolution of commit **********, since it originates from another repository" from log output
	
We have also updated the plugins and SonarQube + Gitlab to newer version	
GitLab "Git shallow clone" is left blank so it should fetch all branches

Sonar properties set:

sonar.language=java
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=build/classes
sonar.java.test.binaries=build/classes
sonar.java.libraries=../../client/lib/*.jar
sonar.java.test.libraries=/tmp/jars/*junit*.jar
sonar.junit.reportPaths=build/test-results
sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
sonar.modules=module1,module2,module3,module4
sonar.projectBaseDir=**/custom-extensions/custom-projects
sonar.java.source=11
sonar.java.jdkHome=/usr/java/jdk-11.0.10
sonar.login=username
sonar.password=password
sonar.java.libraries=/**/jobs/SonarScanner_merge_request/workspace/**/client/lib/*.jar
sonar.ci.autoconfig.disabled=true
sonar.pullrequest.key=${gitlabMergeRequestIid}
sonar.pullrequest.branch=${gitlabSourceBranch}
sonar.pullrequest.base=${gitlabTargetBranch}
sonar.log.level=DEBUG
sonar.analysis.mode=publish

Here is to my understanding the relevant snippet from Jenkins job log:

Triggered by <a href="http://git.company/root/custom-extensions/merge_requests/1056" target="_blank">GitLab Merge Request #1056</a>: root/sonarqube_mergereq_test1 => sandbox
Running as SYSTEM
Building in workspace /var/lib/jenkins/jobs/SonarScanner_merge_request/workspace
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Deferred wipeout is used...
[WS-CLEANUP] Done
The recommended git tool is: NONE
using credential JenkinsSshGitlabAccess
Cloning the remote Git repository
Honoring refspec on initial clone
Cloning repository git@git.company:root/custom-extensions.git
 > /usr/local/bin/git init /var/lib/jenkins/jobs/SonarScanner_merge_request/workspace # timeout=10
Fetching upstream changes from git@git.company:root/custom-extensions.git
 > /usr/local/bin/git --version # timeout=10
 > git --version # 'git version 2.9.5'
using GIT_SSH to set credentials Used for ssh access to gitlab
 > /usr/local/bin/git fetch --tags --progress -- git@git.company:root/custom-extensions.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > /usr/local/bin/git config remote.origin.url git@git.company:root/custom-extensions.git # timeout=10
 > /usr/local/bin/git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > /usr/local/bin/git config remote.origin.url git@git.company:root/custom-extensions.git # timeout=10
Fetching upstream changes from git@git.company:root/custom-extensions.git
using GIT_SSH to set credentials Used for ssh access to gitlab
 > /usr/local/bin/git fetch --tags --progress -- git@git.company:root/custom-extensions.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > /usr/local/bin/git rev-parse 6a25a03d74df2318938dfb033344b2a143d9d4ee^{commit} # timeout=10
 > /usr/local/bin/git branch -a -v --no-abbrev --contains 6a25a03d74df2318938dfb033344b2a143d9d4ee # timeout=10
Checking out Revision 6a25a03d74df2318938dfb033344b2a143d9d4ee (origin/sonarqube_mergereq_test1)
 > /usr/local/bin/git config core.sparsecheckout # timeout=10
 > /usr/local/bin/git checkout -f 6a25a03d74df2318938dfb033344b2a143d9d4ee # timeout=10
Commit message: "commit message"
 > /usr/local/bin/git rev-list --no-walk 6a25a03d74df2318938dfb033344b2a143d9d4ee # timeout=10
Cleaning workspace
 > /usr/local/bin/git rev-parse --verify HEAD # timeout=10
Resetting working tree
 > /usr/local/bin/git reset --hard # timeout=10
 > /usr/local/bin/git clean -fdx # timeout=10
.
.
.
15:45:59.277 INFO: SCM collecting changed files in the branch (done) | time=264ms
15:45:59.278 DEBUG: SCM reported 11 files changed in the branch
.
.
.
16:08:57.537 DEBUG: SCM revision ID '6a25a03d74df2318938dfb033344b2a143d9d4ee'
16:08:57.759 INFO: SCM writing changed lines
16:08:57.783 DEBUG: Merge base sha1: ced0107b7e0dd5afa3c0643f2efc1251968440a9
16:08:57.784 DEBUG: SCM reported changed lines for 0 files in the branch

The main question is why the log first states "SCM reported 11 files changed in the branch" and later "SCM reported changed lines for 0 files in the branch"?

Any help or ideas on what to try is greatly appreciated

**Comment by Abrahamberg** [comment]
have you seen this https://github.com/mc1arke/sonarqube-community-branch-plugin/issues/454

**Comment by Bloof** [comment]
> have you seen this #454

Yes, and we actually updatet to newer version hoping that it would work. Same issue persists through different versions..

**Comment by Bloof** [comment]
It came down to the target branch missing all of its blame information. We had come shell copy scripts going on in the corporate project that was not copying .git folder and thus the blame information was missing. Fixing this issue whole PR analysis now works. Hopefully someone else gets some insight to their problem with what we had tried before.

PS. I can confirm that the plugin works with Sonarqube 9.1

**Comment by tuan1nguyen** [comment]
I am facing the same problem. My target branch has all blame information

SonarQube Community EditionVersion 9.1
SonarScanner 4.6.2
mc1arke/sonarqube-community-branch-plugin 1.9.1

GitLab Community Edition 14.5.0

**Comment by patricknoffke** [comment]
I have the same issue with pull requests in Azure DevOps.  The PR analysis shows zero coverage, no code, empty metrics (but coverage percentage after merge is non-zero).

23:54:59.196 DEBUG: SCM revision ID '5549cfa3fd7f298e7fd4ba3bf62b8f167f40d849'
23:54:59.276 INFO: SCM writing changed lines
23:54:59.295 DEBUG: Merge base sha1: 7afac00c44eb9ca8421312d2e1dce049b7e7cf95
23:54:59.302 DEBUG: SCM reported changed lines for 0 files in the branch
23:54:55.115 DEBUG: SCM reported 251 files changed in the branch

...

23:54:59.196 DEBUG: SCM revision ID '5549cfa3fd7f298e7fd4ba3bf62b8f167f40d849'
23:54:59.276 INFO: SCM writing changed lines
23:54:59.295 DEBUG: Merge base sha1: 7afac00c44eb9ca8421312d2e1dce049b7e7cf95
23:54:59.302 DEBUG: SCM reported changed lines for 0 files in the branch
23:54:59.302 INFO: SCM writing changed lines (done) | time=26ms

If I just analyze the branch directly, I get full coverage information and metrics.  Something about the PR integration seems to be causing this.

I don't have any messages about missing blame information.  Any suggestions on how to debug this further?

I am using SonarQube 8.9.9 Developer edition.
