### ISSUE TITLE
To use the property "sonar.branch.name" and analyze branches, Developer Edition or above is required

### ISSUE THREAD

**Issue by chuchothecat** [mc1arke/sonarqube-community-branch-plugin#49]
SonarQube 7.9.1 complains when I pass the sonar.branch.name parameter that it requires the developer edition. This is being passed through Gitlab CICD with the following line:

`mvn package sonar:sonar -Dsonar.host.url=$Sonar_URL -Dsonar.login=$Sonar_USER -Dsonar.password=$Sonar_PASS -Dsonar.branch.name=$CI_COMMIT_REF_NAME`

```
INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  24.979 s
[INFO] Finished at: 2019-11-20T21:22:50Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar (default-cli) on project hello_world: Validation of project reactor failed:
[ERROR]   o To use the property "sonar.branch.name" and analyze branches, Developer Edition or above is required. See https://redirect.sonarsource.com/doc/branches.html for more information.

```
The plugin does appear to be working as I have branch options within the SonarQube UI now that I didn't previously since I added the plugin. 

If I remove the sonar.branch.name parameter it goes through fine.  I can also rename a master to a branch name inside the SQ UI, but cannot seem to push them through automatically from the CLI.

**Comment by chuchothecat** [comment]
The issue occurs if sonar.branch.target is passed.  There are no issues if neither parameter is passed and it goes through as normal and defaults in the UI to 'master' (which can be changed in the UI). 

`To use the property "sonar.branch.target" and analyze branches, Developer Edition or above is required. See https://redirect.sonarsource.com/doc/branches.html for more information.`

This is from invoking the following command:
-Dsonar.host.url=$Sonar_URL -Dsonar.login=$Sonar_USER -Dsonar.password=$Sonar_PASS -Dsonar.branch.name=$CI_COMMIT_REF_NAME -Dsonar.branch.target=helloworld2

**Comment by mc1arke** [comment]
What version of the plugin are you using, and have you ensure you've followed the full installation instructions in the README file?

**Comment by chuchothecat** [comment]
Using 1.2 sonarqube-community-branch-plugin-1.2.0.jar
with the .jar added to sonarqube/lib/common/ & sonarqube/extensions/plugins/ inside a bitnami docker image. Which, now that I realize it, could be the issue, although I'm not sure how it would make a difference.

**Comment by chuchothecat** [comment]
Full Sonarqube server version is: 7.9.1.27448
[https://github.com/bitnami/bitnami-docker-sonarqube](url)
Added the jar to the locations listed in the readme via a simple Dockerfile. 

`FROM bitnami/sonarqube:7

COPY sonarqube-community-branch-plugin-1.2.0.jar /opt/bitnami/sonarqube/lib/common/
COPY sonarqube-community-branch-plugin-1.2.0.jar /opt/bitnami/sonarqube/extensions/plugins/
`

**Comment by chuchothecat** [comment]
Think I found the problem.  I exec'd a bash shell into the container and do not see the .jar in the plugins dir, only the common one -- which is probably the problem. Now to figure out why it didn't get added.

**Comment by chuchothecat** [comment]
That was the source of the issue. Not sure why the COPY didn't work for both locations, neither did ADD. To fix I opened a shell into the container, copied the existing .jar from lib/common to extensions/plugins, chmod'd to the correct user:group of sonarqube and bounced the container. Now I can push with the sonar.branch.name parameter!  Closing!

**Comment by chuchothecat** [comment]
I should add for clarity sake for anyone else that runs into this, the root cause is the .jar is not deployed in both locations.  This error will occur if it is only in /lib/commons and not also available in /extensions/plugins.

**Comment by klagan** [comment]
isnt this message due to the fact that you are attempting to scan a branch other than `master` on the community edition.  This was the issue for me through AZDO

**Comment by mc1arke** [comment]
@klagan The whole point of this plugin is to allow branch scanning in community edition, so getting that error indicates the plugin isn't installed properly or isn't working properly.

**Comment by klagan** [comment]
> @klagan The whole point of this plugin is to allow branch scanning in community edition, so getting that error indicates the plugin isn't installed properly or isn't working properly.

@mc1arke sorry - i was actually searching for a what this error meant and Google brought me here.  I didnt look to see what this repository was but am glad I found it.  Thanks for pointing out the mistake.
