### ISSUE TITLE
Does not work on latest 7.7

### ISSUE THREAD

**Issue by PhillOliver-Dev** [mc1arke/sonarqube-community-branch-plugin#5]
Web server startup failed when plugin placed in the latest 7.7 version of sonarqube. This is using the dockerised version of sonarqube community edition. Built the plugin using gradle in the repo and copied to mounted directory. No additional logging could be found on my attempt to run

**Comment by nixel2007** [comment]
I'm using 1.0.0 version of plugin with dockerized (and k8sed) SQ 7.7 without any problems.

**Comment by PhillOliver-Dev** [comment]
Did you build this into your own image? If so can you share the docker file?

**Comment by nixel2007** [comment]
I use official SQ image from dockerhub.

**Comment by PhillOliver-Dev** [comment]
In that case, could you describe the process you're using to install? Unless I'm missing something the generated file should be adequate for use

**Comment by nixel2007** [comment]
`/opt/sonarqube/extensions/downloads` and `/opt/sonarqube/extensions/plugins` are mounted to host. On new plugin release I simply copy jar to downloads folder and restart SQ server.

Could you provide error logs from your installation?

**Comment by PhillOliver-Dev** [comment]
Was using 1.1.0-snapshot. changed to 1.0.0 and works a charm

**Comment by nixel2007** [comment]
You should switch to 1.0.1, cause there was a fix for #1

**Comment by mc1arke** [comment]
Could you confirm what was being shown in the logs for startup, and if the 1.1.0-SNAPSHOT was built off master or another branch?
