### ISSUE TITLE
java.lang.IllegalStateException: Current edition does not support branch feature

### ISSUE THREAD

**Issue by Bhushan19** [mc1arke/sonarqube-community-branch-plugin#507]
Hello Team
        I am trying to use branch plugin(sonarqube image-9.0-community and plugin-1.9.0). I have installed plugin as per instructions provided, copied jar file at both locations. But I am getting below error, can you please suggest anything

ERROR web[][o.s.s.w.WebServiceEngine] Fail to process request http://localhost:9000/api/ce/submit?projectKey=projectKey1%3AprojectKey2&projectName=myProject&characteristic=branch%3Dfeature%2FmyFeatureBranch&characteristic=branchType%3DBRANCH
sonarqube_1  | java.lang.IllegalStateException: Current edition does not support branch feature

**Comment by mad-pojo** [comment]
Hello.
You need to copy the file to one location and modify the _config/sonar.properties_ file. Did you do so?

**Comment by Bhushan19** [comment]
hi, thanks for your reply. That solved my problem :) 
So 
1) I placed jar only in extensions folder
2) Added recommended arguments to docker launch configuration

**Comment by yiscasar** [comment]
Hi,
@mad-pojo which change should be done in the properties file?

**Comment by HieuMinh67** [comment]
> hi, thanks for your reply. That solved my problem :) So
> 
> 1. I placed jar only in extensions folder
> 2. Added recommended arguments to docker launch configuration

Could you please tell me which arguments did add to the docker configuration?

**Comment by JaydeepGorasiya** [comment]
Hello, 

I'm getting same error for Sonarqube version 9.9.5. Can anyone help here ?
