### ISSUE TITLE
When the Azure's project_name is Chinese, import_azure_project is error

### ISSUE THREAD

**Issue by tonglei100** [mc1arke/sonarqube-community-branch-plugin#509]
**Describe the bug**
I want to add project from import_azure_project. My Azure's project_name is Chinese
but, it's error
Malformed key for Project: '人工智能_ai'. Allowed characters are alphanumeric, '-', '_', '.' and ':', with at least one non-digit.

**To Reproduce**
Add project -> Azure DevOps -> import_azure_project

**Expected behavior**

**Screenshots**
![20211209131235](https://user-images.githubusercontent.com/530089/145338399-dc6cde29-9cbd-497a-b25f-5ae0464b8c35.png)

![20211209151925](https://user-images.githubusercontent.com/530089/145351557-4948134d-3cba-478d-baf2-a50f25bd72f4.png)

**Software Versions**
 - SonarQube Version: 8.9.3 (build 48735)
 - Plugin Version: 1.8.0

**Additional context**

**Comment by mc1arke** [comment]
I don't believe this is anything to do with this plugin, as the project key is generated by Sonarqube core. Have you tried this import without the plugin installed?

**Comment by tonglei100** [comment]
> I don't believe this is anything to do with this plugin, as the project key is generated by Sonarqube core. Have you tried this import without the plugin installed?

OK，thank you! Maybe it's SonarQube's bug. I can only solve it by modifying the database.
