### ISSUE TITLE
Short living branch shows only coverage estimated after merge

### ISSUE THREAD

**Issue by MaxCCC** [mc1arke/sonarqube-community-branch-plugin#51]
Versions:
```
Sonar Docker sonarqube:7.9.1-community
Plugin: sonarqube-community-branch-plugin-1.1.1.jar
```

When I perform an analysis of a short living branch (branched from master) I do only see the coverage estimated after merge and not of the branch itself.

Command:
`mvn sonar:sonar -Dsonar.host.url=http://localhost:9000 -Dsonar.login=admin -Dsonar.password=admin -Dsonar.branch.name=feature/test -Dsonar.branch.target=master`

![coverage](https://user-images.githubusercontent.com/24589936/69705713-60c8e800-10f6-11ea-8ba0-efe5b4c25779.PNG)

What is wrong here?

**Comment by MaxCCC** [comment]
I saw https://github.com/mc1arke/sonarqube-community-branch-plugin/issues/12 but I'm fetching and pulling my master before.

**Comment by mc1arke** [comment]
What has been changed in the branch you're scanning? Was it a change to file that would be included in coverage stats, or is it a change to a configuration file (POM, properties, or resources)?

Do you have a project you can share publicly  to allow me to replicate this?

**Comment by MaxCCC** [comment]
@mc1arke I used this project https://github.com/LableOrg/java-maven-junit-helloworld and ran the master analysis. After that I created a branch from the master branch and putted some tests in comment and ran a new analysis (short-living branch). I did not really change code except putting tests in comment. The estimated after merge is lower as expected but I hoped to see the coverage of the branch too.

**Comment by mc1arke** [comment]
If you only changed tests or added comments then SonarQube wont see any non-test code as changed, so wont have any changed lines to check coverage of. The screen you've highlighted shows measures for lines that have changed in that analysis, so coverage is only on the 'production' code (src/main/java for Maven) that has been changed.

This plugin also has no influence on what the contents of those measures are, it purely provides the facility for SonarQube to be able to detect branches. Those measures are calculated and managed as part of SonarQube's core.
