### ISSUE TITLE
Bitbucket Server is not updated after allowing the comments in SonarQube

### ISSUE THREAD

**Issue by preddymm** [mc1arke/sonarqube-community-branch-plugin#510]
@mc1arke 
Thanks for the plugin.
I have a issue while integrating the plugin with Bitbucket server. I allowed few minor bugs in SonarQube and commented them to pass the merge.  I don't see it is getting updated in Bitbucket and passing the merge. Do I need any webhook between SonarQube and Bitbucket server? If yes, could you please walk me through on how to resolve this issue.

Thanks

**Comment by mad-pojo** [comment]
Hello, I think you need to analyze your project again. In this case your resolved minor bugs will be treated as closed and will not be used to calculate passing the quality gate.

**Comment by mc1arke** [comment]
@preddymm Please provide the details the issue template asks for: you've not given any information about the plugin version, how you've configured sonarqube for decoration, or anything from the logs to show what Sonarqube is doing.
