### ISSUE TITLE
How to display a code detection result

### ISSUE THREAD

**Issue by wgh728** [mc1arke/sonarqube-community-branch-plugin#514]
Hello, everyone. If the pull request is submitted multiple times, there will be multiple detection results. Can you do this by displaying only the latest code detection results

![image](https://user-images.githubusercontent.com/7524530/146485543-3d19ac9d-44b3-4f22-8be1-c20d865065b7.png)

**Comment by mc1arke** [comment]
Sonarqube is resolving the previous summary comment and creating the second one. When you open the merge request it will normally have any resolved comments collapsed so the comment contents are not visible.

There is currently no way to stop Sonarqube generating these comments on every build.
