### ISSUE TITLE
Release 1.10.0 not working with SonarQube 9.2 ?

### ISSUE THREAD

**Issue by joelguittet** [mc1arke/sonarqube-community-branch-plugin#518]
Hello @mc1arke 

Following your message at https://github.com/mc1arke/sonarqube-community-branch-plugin/issues/454 and the release of 1.10.0 plugin, I have updated my installation with this release.

However, I still have no branches support with SonarQube 9.2. Error message on SonarQube server: `Current edition does not support branch feature` and analysis finishes with error 500 with message `An error has occurred. Please contact your administrator`.

My SonarQube release is Version 9.2.3 (build 50713). I'm running in docker container. What is the SQ release you have tested for plugin 1.10.0 ?

**Expected behavior**
Release note indicate compatibility with 9.1+ but maybe something to do in order to have it working ? A reset of some data or ... ? Or maybe an update is required for the 9.2.1 / 9.2.2 etc ?

**Software Versions**
 - SonarQube Version: 9.2.3 (build 50713)
 - Plugin Version: 1.10.0 jar from the release page

Thanks,
Joel

**Comment by mc1arke** [comment]
Hi @joelguittet,

When you say you're running in a docker container, is this using the docker image provided by this project, or your own one? If it's your own one, can you provide the steps you perform to add and configure the plugin?

Thanks

**Comment by joelguittet** [comment]
Hello @mc1arke 

Thanks for the quick reply.

This is the official sonarqube container (9-community tag) with the plugin added to the "extensions/plugins" directory.

Looking forward I just realized I have forgotten to update "SONAR_WEB_JAVAADDITIONALOPTS" and "SONAR_CE_JAVAADDITIONALOPTS" in my env variables ! Now working like a charm.

Sorry for the annoyance and again thanks for all this great job!

Joel
