### ISSUE TITLE
plugin seems to not get loaded in sonarqube 8.0

### ISSUE THREAD

**Issue by thorus90** [mc1arke/sonarqube-community-branch-plugin#52]
**Describe the bug**
We upgraded to sonarqube 8.0 and sonarqube-community-branch-plugin 1.2.0, but we cannot choose branches anymore, with sonarqube 7.9 and branch-plugin 1.1.1 it worked fine.
The Marketplace shows it is installed, there are no errors regarding the plugin in the logs, only this:
```
2019.11.28 11:32:54 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin Community Branch Plugin / 1.2.0
```

**Expected behavior**
Being able to switch branches

**Screenshots**
![Bildschirmfoto von 2019-11-28 11-26-16](https://user-images.githubusercontent.com/4346977/69799310-53356000-11d3-11ea-9b85-3356ae701e86.png)

**Software Versions**
 - SonarQube Version: 8.0 (build 29455)
 - Plugin Version: 1.2.0

Anyone else experiencing this? Any way to debug why it is not loaded?

Thanks!

**Comment by asosnoviy** [comment]
Check this https://github.com/mc1arke/sonarqube-community-branch-plugin#installation please.

**Comment by thorus90** [comment]
Thanks! didn't noticed that the installation way changed.
