### ISSUE TITLE
Plugin 1.10.0 on SQ 9.1 CE Upload Error: Current edition does not support branch feature

### ISSUE THREAD

**Issue by AyozeVera** [mc1arke/sonarqube-community-branch-plugin#524]
**Describe the bug**
Seems like the SQ plugin is not working, I am getting the Current edition does not support branch feature error.

**My pipeline config**
```
pull-requests:
    '**': #this runs as default for any branch not elsewhere defined
      - step:
          name: PR SonarQube analysis
          image: sonarsource/sonar-scanner-cli
          script:
            - echo ${SONAR_HOST_URL}
            - echo ${SONAR_TOKEN}
            - export BITBUCKET_PR_KEY=$BITBUCKET_PR_ID
            - echo ${BITBUCKET_PR_KEY}
            - export BITBUCKET_BRANCH=$BITBUCKET_BRANCH
            - echo ${BITBUCKET_BRANCH}
            - export BITBUCKET_BASE_BRANCH=$BITBUCKET_PR_DESTINATION_BRANCH
            - echo ${BITBUCKET_BASE_BRANCH}
            - sonar-scanner -X
              -Dsonar.projectBaseDir=$(pwd)
              -Dproject.settings=sonar-project.properties
              -Dsonar.host.url=${SONAR_HOST_URL}
              -Dsonar.login=${SONAR_TOKEN}
              -Dsonar.pullrequest.key=${BITBUCKET_PR_KEY}
              -Dsonar.pullrequest.branch=${BITBUCKET_BRANCH}
              -Dsonar.pullrequest.base=${BITBUCKET_BASE_BRANCH}
```
The plugin seems to be ok because I am able to see it as installed plugins on the SQ Marketplace section

The only difference I found is that on the documentation says that the plugin should be referenced on the config folder, and on my project, there is no config folder, the folder name is conf.

Thanks for your time!

**Comment by mc1arke** [comment]
The plugin is not installed properly. Please check your sonar startup log to ensure it contains references to the Java agent arguments.

**Comment by AyozeVera** [comment]
This is my configuration: 
![image](https://user-images.githubusercontent.com/5493234/147554174-6ab85f00-4bf7-4e0c-aa14-7f019eaca6c2.png)
Config file: 
![image](https://user-images.githubusercontent.com/5493234/147554250-87a40ab2-6980-4592-88a2-aee9263fc397.png)
![image](https://user-images.githubusercontent.com/5493234/147554365-5c473b00-4676-45d7-a301-77fbba56f024.png)
Jar File:
![image](https://user-images.githubusercontent.com/5493234/147554431-aa32d644-a0e1-41aa-8a25-3cd838304c4d.png)

I also gave full permission to jar file just in case and I am still getting the error.

I didn't get what you mean with your previous comment, which log file did you refer to?

**Comment by YTN01** [comment]
@AyozeVertone he is referring to the logs sonarqube prints during startup.

**Comment by AyozeVera** [comment]
Thanks @YTN01 , we finally fixed the issue.
For us seems like, using the plugin on the extensions/plugins folder was not working ,the plugin was being shown on SQ MarketPlace but it was not working.
The correct configuration that worked for us: 
**sonar.web.javaAdditionalOpts=-javaagent:/opt/sonarqube/lib/extensions/sonarqube-community-branch-plugin-1.10.0.jar=web
sonar.ce.javaAdditionalOpts=-javaagent:/opt/sonarqube/lib/extensions/sonarqube-community-branch-plugin-1.10.0.jar=ce**

Also, on 9.1 and 9.2 **config** folder doesn't exist, the folder name is **conf**
