### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by winnertako** [mc1arke/sonarqube-community-branch-plugin#54]
Hi,

After the installation of the Community Branch Plugin it seems the parameters sonar.branch.target and sonar.branch.name doesn't work. On my logs I've the `Current edition does not support branch feature` error.

What I'm missing?

Thank you.

**Comment by nixel2007** [comment]
See https://github.com/mc1arke/sonarqube-community-branch-plugin/issues/53

**Comment by winnertako** [comment]
Thank you @nixel2007 .

I didn't place the plugin in  **lib/common**. I put in  **extensions/plugins** folder. 

I have to remove from **extensions/plugins** and place in **lib/common**?

Thank you

**Comment by mc1arke** [comment]
Given this seems to duplicate #53, #52, #50, #49, #38, and #40, I've updated the releases page to explicitly call-out the requirement to review the README when upgrading to this version of the plugin.

**Comment by winnertako** [comment]
@mc1arke it's working now.
