### ISSUE TITLE
Cant see the option to integrate pull requests for github

### ISSUE THREAD

**Issue by shashankpai** [mc1arke/sonarqube-community-branch-plugin#543]
### Discussed in https://github.com/mc1arke/sonarqube-community-branch-plugin/discussions/542

<div type='discussions-op-text'>

<sup>Originally posted by **shashankpai** February  1, 2022</sup>
Hi , I am running the community-branch-plugin docker-compose file , My requirement is  to integrate pull request decoration for my github repo. When trying to integrate i dont see any option  for github, only bitbucket is shown up , attaching screenshot. Is there anything that i am missing ?
![image](https://user-images.githubusercontent.com/24639491/151980251-cf39fc32-e513-4936-8360-a3b86d43b50c.png)
</div>

**Comment by mc1arke** [comment]
Please don't cross-post between issues and discussions.
