### ISSUE TITLE
Mono repo support for Bitbucket (Server) PR decoration

### ISSUE THREAD

**Issue by MrMightyNighty** [mc1arke/sonarqube-community-branch-plugin#544]
Hello there :)

Bitbucket has issues with multiple reports in one PR. It seems like that the report key has to be unique otherwise the "older" report is overwritten. Is there a way that this could be added?

**Comment by MuhKuh7** [comment]
The official plugin adds the project key to the report key, making it unique. This would be a nice feature.

**Comment by MrMightyNighty** [comment]
#552 I added a PR for this. We tested this on our 8.9 LTS on-prem instance and it worked!

**Comment by MuhKuh7** [comment]
@MrMightyNighty, that sounds great! Cannot wait for it to be merged and released :)

**Comment by mc1arke** [comment]
Merged under #578

**Comment by mc1arke** [comment]
Released in 1.11.0
