### ISSUE TITLE
Azure DevOps Error

### ISSUE THREAD

**Issue by vidal777** [mc1arke/sonarqube-community-branch-plugin#546]
**Describe the bug**

Even using the plugin, Azure Devops does not allow you to use branch control with sonarqube. Do I have to pass on any special property?

**To Reproduce**

**Expected behavior**
I am using the image "sonarqube-with-community-branch-plugin:8.5-community" to be able to use the PR of sonarqube without needing to use the Developer edition.

**Screenshots**
![image](https://user-images.githubusercontent.com/43821333/152833096-a3a9c41c-f33f-48aa-b623-9b558b202dce.png)

**Software Versions**
 - SonarQube Version: [sonarqube-with-community-branch-plugin:8.5-community]

**Additional context**

**Comment by mc1arke** [comment]
You'll need to provide the `web.log` contents to allow this to be diagnosed. I'd also suggest you upgrade to a newer version of Sonarqube, at least the current LTS (8.9), but if you don't need to stick to LTS then using the latest docker tag means you'll get features shortly after Sonarsource release them.
