### ISSUE TITLE
Inactive branches are not purged 

### ISSUE THREAD

**Issue by usinelogicielle** [mc1arke/sonarqube-community-branch-plugin#549]
### **Describe the bug**
We noticed in the SonarQube interface that branch purging was not done after 30 days of inactivity.
Here is an example :
![image](https://user-images.githubusercontent.com/73827301/154301467-12f34475-0fc4-4a24-8b68-944c09448b8e.png)
The value in "General Settings" is set to 30 days.
![image](https://user-images.githubusercontent.com/73827301/154301758-37213d70-bae9-4598-bd58-2905b28d7e1e.png)

In the post here : [https://github.com/mc1arke/sonarqube-community-branch-plugin/issues/273](https://github.com/mc1arke/sonarqube-community-branch-plugin/issues/273) It says to check if the parameter **sonar.dbcleaner.branchesToKeepWhenInactive** exists. We have checked on our side in the "properties" table and this parameter is present.

Did we miss something? 

### **Software Versions**
 - SonarQube Version : 8.9.6
 - Plugin Version : 1.8.1

Thanks in advance for your help :)

**Comment by rwalravens** [comment]
We encountered the same issue.

Could you try to manually override the value to 30, so it isn't marked as `(default)` anymore?
Next trigger an analysis of master and check if the feature branch is purged.

Note this isn't a bug in the plugin, but in the sonarqube core.

**Comment by usinelogicielle** [comment]
Hello @rwalravens thanks for your advice! We tested it on our side and it worked. 
Thank you again for your help :)
