### ISSUE TITLE
Plugin 1.10.0 doesn't work for React application on Azure DevOPS pipeline

### ISSUE THREAD

**Issue by Pooja-graafika** [mc1arke/sonarqube-community-branch-plugin#550]
Hi,

This plugin works absolutely fine for .Net application on Azure DevOPS.I tried using this plugin for Node.js application and have placed the following info in sonar-project.properties file in the source code.

sonar.projectKey=*********
sonar.projectName=*******
sonar.branchName=test-branch
sonar.projectVersion="1.0"
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/assets/**
sonar.test.inclusions=**/*.spec.ts

sonar.ts.tslint.configPath=tslint.json
sonar.host.url=https://*********.com/

Build passes but by default Master branch is getting analyzed. Please help what property should be used to specify the Branch name in the sonar-project.properties file.

**Comment by nixel2007** [comment]
sonar.branch.name

**Comment by Pooja-graafika** [comment]
I tried with sonar.branch.name

Its failing with the following error 
 ##[error]java.lang.IllegalStateException: Failed to upload report: Error 500 on https://***************.com/api/ce/submit?projectKey=*************&projectName=*****&characteristic=branch%3D%22test-branch%22&characteristic=branchType%3DBRANCH : {"errors":[{"msg":"An error has occurred. Please contact your administrator"}]}

**Comment by mc1arke** [comment]
This sounds like you've not installed the plugin properly. As you've not completed the issue template as required, this issue is being closed without any further investigation.
