### ISSUE TITLE
Decoration issue fails due invalid project id when branch is in fork

### ISSUE THREAD

**Issue by kna0085** [mc1arke/sonarqube-community-branch-plugin#554]
**Describe the bug**
For gitlab PR decoration issue fixed on version 1.7.0 and reported in #181  is back in version 1.10.0.

**To Reproduce**
1. Create a fork from a project in your personal repository
2. Create a branch, push it to your personal repository and launch sonar analysis.
3. PR decoration will not be available at the end. 
4. Check CE logs to see the exception

**Expected behavior**
PR decoration being updated in gitlab merge request

**Software Versions**
 - SonarQube Version: 9.2.4
 - Plugin Version: 1.10.0

**Comment by shellwalker** [comment]
Got the same issue. Is there any update?

**Comment by mc1arke** [comment]
Released in 1.11.0
