### ISSUE TITLE
Analysis of feature branch treats entire codebase as new code

### ISSUE THREAD

**Issue by RobCoPKC** [mc1arke/sonarqube-community-branch-plugin#56]
**Describe the bug**
The problem is that the feature branch analysis doesn't show only new code and new bugs, code smells etc. It treats the entire codebase and every single quality issue as new.

**To Reproduce**
1. Analyze master branch.
2. Create feature branch based on master branch.
3. Add 1 vulnerability.
4. Analyze feature branch with sonar.branch.name=${name of feature branch}
5. Analysis treats the entire codebase and every bug, code smell etc. as new.

**Expected behavior**
Analysis result should be 1 modified file and 1 new vulnerabilty.

**Screenshots**
Master branch analysis: 
![image](https://user-images.githubusercontent.com/56680419/70616977-eaf17000-1c0f-11ea-8ced-2ab70a2d1032.png)

Feature Branch Analysis:
![image](https://user-images.githubusercontent.com/56680419/70617046-09576b80-1c10-11ea-8f46-2dd934aba90a.png)

**Software Versions**
 - SonarQube Version: 8.0 (build 29455)
- SonarScanner for MSBuild: 4.7.1
 - Plugin Version: 1.2.0

**Additional context**
Maybe I should add that this is a project using TFVC (sigh). With Git everything works just fine.

**Comment by mc1arke** [comment]
Unfortunately, this isn't an issue with this plugin, but with Sonarqube's ability to detect changes when scanning a project. With Git and SVN, the annotations/blame on a file are used to detect what lines have been changed, any only issues reported for those lines are shown as new issues, with the rest being excluded/hidden for the current branch. Presumably Sonarqube doesn't have the ability to perform annotation/blame with TFVC, so can't do this filtering after the Compute Engine has generated the issue list. As this plugin provides the functionality for Sonarqube to record branches, but doesn't directly interact with the underlying SCM, there's nothing we can do here.

There may be options to implement an SCM detector for TFVC as a SonarQube plugin, although I've not looked at whether this is fully possible, or the effort required to do so.

**Comment by mc1arke** [comment]
@RobCoPKC This may do what you need: https://github.com/lg2de/sonar-scm-tfvc
