### ISSUE TITLE
0 issues when analyzing prs.

### ISSUE THREAD

**Issue by jonyto123** [mc1arke/sonarqube-community-branch-plugin#561]
Hi pr analisys geting 0 mesures. I think something not write. Here what i do and what happens, I am using mc1arke/sonarqube-with-community-branch-plugin   9.2-community   5c936a4f1060

So i run sonarscaner on develop all ok detects the codesmells  bugs etc.
Then run sonarscaner on PR, the pr is submitted to sonarqube, report gets to bitbucket, but with sonar detects no issues, but i purposely put them. 
I am runing sonarscanner using jenkins. these are the commands that i am using in the ci file:
```
    script{
                    scannerHome = tool 'SonarScanner';
                }
                withSonarQubeEnv("SonarQube Server") {
                    sh "${scannerHome}/bin/sonar-scanner \
                        -Dsonar.projectKey=airc_fun \
                        -Dsonar.pullrequest.key=150 \
                        -Dsonar.pullrequest.branch=KOI-840-fun \
                        -Dsonar.pullrequest.base=develop \
                        -Dsonar.java.binaries=."
                }
```
and for the develop branch that is the target i am using -Dsonar-branch-name=develop
in the repository forlder i have:
    -java-app
    -angular-app
    -ci-files
  If you need more details please ask and i will do my best to provide it.
  
what i mean with o measures is:
![image](https://user-images.githubusercontent.com/38688932/157911514-54670c04-878c-4e94-91d6-3ec895072fe4.png)

**Comment by jonyto123** [comment]
So used lts image had partial success that is my old sonar detected a blocker that this version dint detect. 
![image](https://user-images.githubusercontent.com/38688932/157919625-b9299b23-ff34-4855-8e06-04458ac0c316.png)
![image](https://user-images.githubusercontent.com/38688932/157919741-30939872-aea9-4d3e-825b-9d87c92544f5.png)

**Comment by gamerson** [comment]
Two things to keep in mind.  When you are doing the PR analysis, there must be a 'baseline' scan of the 'develop' branch already available on sonarqube server. Secondly, for me at least, on jenkins, I had to fetch the 'develop' branch into the checked out repo on jenkins so sonar-scanner would have the PR branch and the reference baselines branch of 'develop' available.

**Comment by jonyto123** [comment]
@gamerson I did got the develop baseline. Not shure where my problem is. Didnt change the process i did with the lts version instead of 9.2 and had a better result. Now seams to that the reports inst consistent with old version i used.

**Comment by mc1arke** [comment]
@jonyto123 You'll need to provide a full set of steps to replicate this, i.e. what branches you have, what you've scanned, what PRs you've raised, and what scans you've then run against them. This functionality does work, so it's likely to be something about the baselines you're generating for PR decoration.
