### ISSUE TITLE
PR decoration reporting issues on unchanged lines

### ISSUE THREAD

**Issue by nishwalshetty** [mc1arke/sonarqube-community-branch-plugin#563]
**Describe the bug**
sonarqube is reporting issues on unchanged lines.

**To Reproduce**

below is the command used
/opt/sonar-scanner-4.6.1.2450-linux/bin/sonar-scanner -Dsonar.host.url="$NEWSONARURL" -Dsonar.sourceEncoding=UTF-8 -Dsonar.sources="$sonar" -Dsonar.projectVersion=1.0 -Dsonar.projectKey="x" -Dsonar.projectName="y" -Dsonar.login="$SONAR_TOKEN" -Dsonar.verbose=true -Dsonar.pullrequest.key="${ghprbPullId}" -Dsonar.pullrequest.branch="$ghprbSourceBranch" -Dsonar.pullrequest.base="$ghprbTargetBranch" -Dsonar.scm.revision="$ghprbActualCommit" -Dsonar.java.binaries="$lib" -Dsonar.java.libraries="caches/modules-2/files-2.1/**/*.jar"
**Expected behavior**
sonarqube to report issues only on the changed lines and not the existing issue in the pull request

**Screenshots**

![image](https://user-images.githubusercontent.com/48088420/158383425-2ba26076-6d5c-4b0a-91b5-599322a28fe1.png)

line no 173 was not changed

**Software Versions**
 - SonarQube Version:  Version 8.9.1 (build 44547)
 - Plugin Version:  1.8.1
 - CI tool - Jenkins
   SCM tool - Github 

**Additional context**
pr branch is upto date with the base branch and quality gate is set only on new code.

**Comment by mc1arke** [comment]
Your report doesn't contain enough details to allow this to be replicated: I'd need to see a pull request that replicates this - or details of how to create one. This issue isn't caused directly by this plugin: the analysis and comparison of issues is performed by Sonarqube's Compute Engine, not the plugin, so this is a bug in Sonarqube core if it is actually an issue.
