### ISSUE TITLE
There are no decorating comments on the Files change tab.

### ISSUE THREAD

**Issue by taetaetae** [mc1arke/sonarqube-community-branch-plugin#564]
hi.
First of all, I would like to express my deep gratitude for providing this function.

I would like to run sonar-scanner to perform static analysis when pullrequest occurs using github action.
First, the screenshot below is the contents of the yml file to execute the github action.
> For your information, I'm using Github Enterprise version, so I'm using the runner directly.

<img width="538" alt="image" src="https://user-images.githubusercontent.com/10969354/158838150-32a87266-31aa-404a-b442-c120d3d7b7f1.png">

The install scan step is to download the sonarqube-scanner to the runner.
I have set up the Github App using the above settings and the following guides.
> https://docs.sonarqube.org/8.9/analysis/github-integration/#header-2

The results of the github action are as follows.

<img width="448" alt="image" src="https://user-images.githubusercontent.com/10969354/158839008-bff4a3bf-a8ec-48aa-aa87-545afea1563c.png">

At the bottom of the above screen, I expected the analysis results from the ANNOTATIONS area to be shown in the Files change tab, but nothing was expressed.

<img width="960" alt="image" src="https://user-images.githubusercontent.com/10969354/158840114-1c180d24-15a2-4a48-9644-504d02a07eba.png">

Could you please help me which settings I missed or if I can use github action to support this function?

I look forward to your warm advice. Thank you.

**Comment by nishwalshetty** [comment]
Hi @taetaetae ,

you mean to say that plugin is reporting issues on unchanged lines of pull request ?

if yes then i have the same [issue](https://github.com/mc1arke/sonarqube-community-branch-plugin/issues/563)

**Comment by taetaetae** [comment]
@nishwalshetty 

Hello.
No, my problem is that the checks tab shows static analysis results, but the fileChages tab does not show static analysis results.

**Comment by taetaetae** [comment]
@mc1arke 

Hello. Is there any option that I missed? I've been looking into it for days, and I'd really appreciate it if you could help me!

**Comment by mc1arke** [comment]
There isn't a reason for this that I'm aware of. It works for me!
