### ISSUE TITLE
old PR comment is not updated/removed when new analysis is run

### ISSUE THREAD

**Issue by nishwalshetty** [mc1arke/sonarqube-community-branch-plugin#567]
**Describe the bug**
Analysis details is posted as comment in pull request, when the pull request is updated or analysis is run again expectation is that same pr comment is updated again or existing old comment is removed and new analysis details are posted but this is not the case as each analysis post one comment in PR(with previous plugin this was not the case)

**To Reproduce**
1. run the analysis more than once (with github as scm)

**Expected behavior**
single analysis details in pull request as comment

**Screenshots**
![image](https://user-images.githubusercontent.com/48088420/159646852-27a2e608-31a5-4aaf-b5c6-cf4b08d49888.png)

**Software Versions**
 - SonarQube Version:  Version 8.9.1 (build 44547)
 - Plugin Version: 1.8.1
- CI tool - Gituhb Action
- SCM tool - Github

**Comment by mc1arke** [comment]
This is working as designed. We don't delete old comments when new ones are added.

**Comment by mably** [comment]
Would be an interesting feature to have though, like it's done on sonarcloud.io

After multiple PR/MR updates, comments get quickly unreadable.

**Comment by mably** [comment]
I pushed a PR which aims to implement this feature (Gitlab only at the moment): #648
