### ISSUE TITLE
Add sonar.branch.revision parameter

### ISSUE THREAD

**Issue by HassanWahba** [mc1arke/sonarqube-community-branch-plugin#576]
Hello,
It's now not possible to know which git commit (revision) has triggered the analysis in the branches
while it is easy to do that to long-lived branches through passing the parameter sonar.scm.revision.
can you add this feature? 
thanks

**Comment by mc1arke** [comment]
@HassanWahba I don't understand what it is you're asking for, as `sonar.scm.revision` can be used against any branch. Could you submit further details, preferably in the format of `The steps you take to get to a point`, `What you want to happen next`, `What happens next (if anything)`, `Any alternative approaches or similar concepts that you're aware of`

**Comment by HassanWahba** [comment]
Hello there! thanks for answering quickly.
Our analysis looks something like this
![image](https://user-images.githubusercontent.com/47371151/162945668-7dbe24f2-cb6a-4d43-b8be-05ce8e0e2081.png)
so we actually do pass the parameters to all branches.
The problem is that it seems like SonarQube does NOT offer an API endpoint to reach this information
for example the endpoints:
/api/project_branches/list does not give the revision info per branch
/api/projects/search shows the revisions of the master branch of each project only but not sub-branches.
/api/project_analyses/search gives the revision of each release of a given project but not the branches

the question is, how can we export the revision hash for all branches so that a prometheus client can scrape them.

**Comment by mc1arke** [comment]
This is not something the plugin controls. We only implement the API definitions s provided by Sonarqube, rather than define the structure of the API endpoints. If this is something one of the endpoints doesn't already provide for you then you'll need to open a request with Sonarsource to add the feature.
