### ISSUE TITLE
PR Decoration is very verbose on GitHub

### ISSUE THREAD

**Issue by onigoetz** [mc1arke/sonarqube-community-branch-plugin#581]
**Describe the bug**
We have enabled PR Decoration on GitHub, each time we push a new commit, a new analysis is done and a new commit is added.

I see in the source that previous comments should be minimized : https://github.com/mc1arke/sonarqube-community-branch-plugin/blob/master/src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/github/v4/GraphqlGithubClient.java#L203-L209

I don't know what "minimize" is supposed to do, but every comment still takes a lot of visual space (see screenshot below)

I see two reasons for this : 
* minimize doesn't do anything ?
* for some reason the filter to find comments to minimize doesn't find the right comments

**To Reproduce**
We have that on all our decorated projects, so I don't know if that's isolated to our installs (we have multiple sonarqube instances, scripted to have the same config) So for us, the repro is :
1. create PR on GitHub
2. SonarQube adds a comment with the analysis results
3. Push new commit to the PR
4. SonarQube adds a comment with the analysis results
5. Repeat steps 3-4 ad vitam aeternam

**Expected behavior**
That new analysis hides or removes the previous comments altogether

**Screenshots**
![image](https://user-images.githubusercontent.com/309594/163333457-b9673b90-4db4-4344-9ce9-fdbb7201696d.png)

**Software Versions**
 - SonarQube Version: Version 8.9.7 (build 52159)
 - Plugin Version: 1.8.1
 - GitHub Enterprise 3.3.1

**Additional context**

**Comment by mc1arke** [comment]
The minimization of comments has not been backports to the 1.8 branch yet. The feature is currently only available in the releases targeting Sonarqube 9.1 and above.

**Comment by onigoetz** [comment]
Would you accept a PR that targets the 1.8 branch ?

**Comment by mc1arke** [comment]
1.8.2 of the plugin released with fix for #435
