### ISSUE TITLE
Sonarqube Issue status changes are not merged to main branch

### ISSUE THREAD

**Issue by milyas-salik** [mc1arke/sonarqube-community-branch-plugin#582]
Hi All/ @mc1arke ,

I am using **SonarQube Community EditionVersion 8.4.1**. 
I marked few Vulnerabilities & Bugs to "Resolve as False Positive" & "Wont fix" and also marked few Security Hotspots to "Fixed" & "Safe" in my feature branch , then I tried to merge my feature branch into main branch.

After I merge when I run the Build on main branch my status changes for the Issues of type Vulnerabilities & BUGs are lost. However, only "Security Hotspot" status changes "Fixed"& "Safe" are synchronized in main branch analysis.

Is there anyway to synchronize the status changes of type Vulnerability/Bugs/Code Smells into the target branch after merge. 

Pls reply.

**Comment by mc1arke** [comment]
This is functionality managed by Sonarqube code, so not one the plugin manages.
