### ISSUE TITLE
Is there any good way to turn off  inline PR comment when sonarqube find code smell problems?

### ISSUE THREAD

**Issue by mengyan9521** [mc1arke/sonarqube-community-branch-plugin#584]
Thank you for your wonderful job! Maybe this is a feature request, or maybe anyone can help me with the issue.

I have used this plugin for a while, but I found that it is noisy when I create a pull request in gitlab, there is too many PR inline comment when sonarqube trigger the PR decoration. That SonarQube find  code  smell problems, there are so many inline PR comments in the pull request discussion part. 

![スクリーンショット 2022-04-18 15 55 21](https://user-images.githubusercontent.com/26315455/163768552-869679e1-ea59-429b-be24-a2872038048f.png)

You can see there are 87 comments in my Discussion part, 85 of comments are code smell problems, it is really hard to find out bug comment, and it is annoying with so many code smell comments.

I know I have to resolve these problems, but I want to deal with bugs firstly, And I can deal with the code smell problems by checking ui of sonarqube.

So, here is my imagination about the feature: 
1. Using gitlab ci or something to turn off code smell inline PR comment when PR is created, but user can check bugs or security problem in inline PR comment
![スクリーンショット 2022-04-18 16 01 03](https://user-images.githubusercontent.com/26315455/163769383-789db52f-a598-439d-87f2-007ac85017ad.png)

2. I can set the amount of code smell inline comment in my PR decoration. For example: if there are more than 3 code smell problems, sonarqube PR decoration can show the amount of code smell problems in summary comment. But if the code smell problems are less than 3, sonarqube can comment code problem inline of code.

Either **1** or **2** is ok for me. Is there any good idea about my issue?

**Comment by mably** [comment]
I pushed a PR which aims to implement this feature: #648
