### ISSUE TITLE
How to setting  dev branch compare master branch?

### ISSUE THREAD

**Issue by bestv5** [mc1arke/sonarqube-community-branch-plugin#589]
when I scan dev branch,  dev branch  New code  setting to master branch  new bugs  in dev branch  not show

**Comment by mc1arke** [comment]
Please use the template when submitting bug reports. You've not given any indication of which version of the plugin or Sonarqube you're using, what parameters you're using to trigger a scan, what already exists in Sonarqube prior to you triggering a scan etc. This makes it impossible for anyone to accurately replicate your issue and provide any meaningful guidance.
