### ISSUE TITLE
SonarQube 9.4 unable to start

### ISSUE THREAD

**Issue by Blasterdick** [mc1arke/sonarqube-community-branch-plugin#597]
Facing an error in sonarqube startup log:
```
Error opening zip file or JAR manifest missing : /opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin.jar`
```
Dockefile:
```
FROM sonarqube:9.4.0-community

ARG V1=1.11.0
ARG URL1=https://github.com/mc1arke/sonarqube-community-branch-plugin/releases/download/$V1/sonarqube-community-branch-plugin-$V1.jar
ARG V2=5.1.3
ARG URL2=https://github.com/javamachr/sonar-gitlab-plugin/releases/download/$V2/sonar-gitlab-plugin-$V2.jar

ADD  $URL1 /opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin.jar
ADD  $URL2 /opt/sonarqube/extensions/plugins/sonar-gitlab-plugin.jar

COPY sonar.properties /opt/sonarqube/conf/
```
sonar.properties:
```
sonar.web.javaAdditionalOpts=-javaagent:/opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin.jar=web
sonar.ce.javaAdditionalOpts=-javaagent:/opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin.jar=ce
```

Great thanks in advance for any kind of help.

**Comment by inugravi** [comment]
@Blasterdick 
Can u try adding the below lines of code (I have appended the version 1.11.0 in the below) to the `sonar.properties` file and verify it
```
sonar.web.javaAdditionalOpts=-javaagent:/opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin.1.11.0.jar=web
sonar.ce.javaAdditionalOpts=-javaagent:/opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin.1.11.0.jar=ce
```

**Comment by Blasterdick** [comment]
Thank you for a suggestion, @inugravi 

Is setting the version number to the file path really matter? I do already have those lines in my `sonar.properties`.

**Comment by inugravi** [comment]
It does not matter. But let's give it a try also remove those `ADD` lines and don't rename the plugin. Not sure, but still give it a try. I know this is like a beating around the bush :)

**Comment by Blasterdick** [comment]
But how do I suppose to download the plugin jar file without those `ADD` lines?

**Comment by ezintz** [comment]
From my perspective the version should not matter. However, I think that you may use a volume configuration for spinning up the container? So in the end the directory is empty, is that possible?

**Comment by Blasterdick** [comment]
> Hi. The same issue 9.3 version

@KirillKomarov550503 I'm using 8.9 now, so I can't say if there're issues with 9.x versions. Trying to switch to 9.4 because Java 17 support was implemented there.

**Comment by mc1arke** [comment]
> and /opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin.jar exists.

> sonar.ce.javaAdditionalOpts=-javaagent:/opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin-1.10.0.jar=ce

Your file names don't match

**Comment by Blasterdick** [comment]
> > and /opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin.jar exists.
> 
> > sonar.ce.javaAdditionalOpts=-javaagent:/opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin-1.10.0.jar=ce
> 
> Your file names don't match

Yup, because those lines are from different comments from different people. Can't see the reason to close the issue.

**Comment by Blasterdick** [comment]
@mc1arke please re-open that issue. There's no error in the file names and paths in the issue description, please, read it carefully.

**Comment by Blasterdick** [comment]
Anyway seems like the user, which starts the process of sonarqube is changed since 8.9 docker image, so it's permissions issue.

Fixed for me like this:

```
ADD --chown=sonarqube:sonarqube $URL1 /opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin.jar
ADD --chown=sonarqube:sonarqube $URL2 /opt/sonarqube/extensions/plugins/sonar-gitlab-plugin.jar
```

**Comment by mc1arke** [comment]
@Blasterdick This issue cannot be replicated with the Dockerfiles bundled with the plugin, hence the issue being closed (sorry, the comment I'd written to state that didn't publish).
