### ISSUE TITLE
Invalid Azure URL or Personal Access Token

### ISSUE THREAD

**Issue by stefansta1** [mc1arke/sonarqube-community-branch-plugin#599]
**Description**
We use an on-prem Sonarqube server https://server:port and use a connection to a AzureDevOps https://dev.azure.com/company. Using the Sonarqube Version 8.5 everything was working fine. After an update to the version 8.9. the connection to Azure DevOps is not working anymore.
The url and the PAT are correct.

**Screenshots**
![image](https://user-images.githubusercontent.com/47751951/165318994-67826b37-ab9d-4529-9e25-9ca25631b621.png)

**Software Versions**
 - SonarQube Version: Version 8.9.5 (build 50698)
 - Plugin Version: 1.8.1

**Additional context**

**Comment by mc1arke** [comment]
Can you provide the server logs from your Sonarqube instance around the time this request was made please?

**Comment by stefansta1** [comment]
I can only see the following in the logs:

2022.04.26 16:38:51 DEBUG web[AYBmQkAjSGfJEKFHAABO][o.s.a.c.a.AzureDevOpsHttpClient] check pat : [https://dev.azure.com/company/_apis/projects?api-version=3.0]

127.0.0.1 - - [26/Apr/2022:16:25:06 +0200] "GET /api/alm_settings/validate?key=AzureDevOps HTTP/1.1" 400 65 "https://srv01tb2:504/admin/settings?category=almintegration" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36 Edg/100.0.1185.50" "AYBmQkAjSGfJEKFHAAAk"
127.0.0.1 - - [26/Apr/2022:16:27:07 +0200] "GET /api/alm_settings/validate?key=AzureDevOps HTTP/1.1" 400 65 "https://srv01tb2:504/admin/settings?category=almintegration" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36 Edg/100.0.1185.50" "AYBmQkAjSGfJEKFHAAAl"

127.0.0.1 - - [26/Apr/2022:16:25:06 +0200] "GET /api/alm_settings/validate?key=AzureDevOps HTTP/1.1" 400 65 "https://srv01tb2:504/admin/settings?category=almintegration" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36 Edg/100.0.1185.50" "AYBmQkAjSGfJEKFHAAAk"
127.0.0.1 - - [26/Apr/2022:16:27:07 +0200] "GET /api/alm_settings/validate?key=AzureDevOps HTTP/1.1" 400 65 "https://srv01tb2:504/admin/settings?category=almintegration" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36 Edg/100.0.1185.50" "AYBmQkAjSGfJEKFHAAAl"

**Comment by mc1arke** [comment]
They look like access logs rather than server logs. Could you provide the logs for the server component of your Sonarqube installation please?

**Comment by stefansta1** [comment]
Is it possible to send the log directly to you?

**Comment by stefansta1** [comment]
here is the Sonarqube log itself
[serverlog.zip](https://github.com/mc1arke/sonarqube-community-branch-plugin/files/8581314/serverlog.zip)

**Comment by mc1arke** [comment]
This doesn't look like the log file I'd expect to see. Sonarqube is split into various parts: elastic search, compute engine (CE), and server. Each of these parts has its own log file. The server log will show the java logs for the requests you've shown as failing in your above access logs, but your logs only shows a set of TLS loading message rather than any logs of sonarqube execution.

**Comment by stefansta1** [comment]
Which log of the 4 logs (sonarxx.log, web.log, access.log, es.log) do you mean? I posted a part of the sonarxx.log.
