### ISSUE TITLE
Sonar 8.1 java.lang.NoSuchFieldError: LONG

### ISSUE THREAD

**Issue by CondormanFr** [mc1arke/sonarqube-community-branch-plugin#60]
Issue during running sonar analysis since sonar 8.1.

**To Reproduce**
1. Running maven analysis with param -Dsonar.branch.name=xxxx
2. The error :   
```
Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar
Unable to load component class org.sonar.scanner.scan.filesystem.InputComponentStore
Unable to load component interface org.sonar.scanner.scan.branch.BranchConfiguration
Caused by: java.lang.NoSuchFieldError: LONG
    at com.github.mc1arke.sonarqube.plugin.scanner.CommunityBranchConfigurationLoader.createBranchConfiguration ([CommunityBranchConfigurationLoader.java:133])
    at com.github.mc1arke.sonarqube.plugin.scanner.CommunityBranchConfigurationLoader.load (CommunityBranchConfigurationLoader.java:97)
    at org.sonar.scanner.scan.branch.BranchConfigurationProvider.provide (BranchConfigurationProvider.java:43)

```
[Error here in the code](https://github.com/mc1arke/sonarqube-community-branch-plugin/blob/cf74e30f29c53cf0f1ee8d87a8741caab513ac80/src/main/java/com/github/mc1arke/sonarqube/plugin/scanner/CommunityBranchConfigurationLoader.java#L133)
**Expected behavior**
No error 

**Software Versions**
 - SonarQube Version: 8.1
 - Plugin Version:  Community Branch Plugin 1.2.0 (communityBranchPlugin)

**Additional context**
It seems that the place where to define long branch name by project has changed in sonar ui.

**Comment by mc1arke** [comment]
See #58

**Comment by dcherniv** [comment]
@mc1arke What is currently the plan for 8.1 branch? is it going to be maintained as an LTS branch? or is there a chance it can get integrated into master at some point?
From reading #58 there are some incompatibilities that prevent merging back in to master.

**Comment by mc1arke** [comment]
I'm going to bring this up-to-date against master then merge and release it. I'll keep a branch from 1.3.0 as an LTS branch to support Sonarqube's current LTS where possible.

**Comment by reddare** [comment]
8.2 same error.

**Comment by upr-kmd** [comment]
Same error in 8.3

**Comment by mc1arke** [comment]
1.4.0 of the plugin has been release to support Sonarqube 8.1. Note that a separate release is required for 8.2 and above due to further changes in those releases.

**Comment by jrogers** [comment]
Weird, I'm seeing this with 8.4 and plugin jar 1.5.0 🤔

**Comment by mc1arke** [comment]
@jrogers can you provide your stacktrace, and confirm you have the up-to-date JARs in both the installation paths please?

**Comment by jrogers** [comment]
@mc1arke Hey sorry i figured it out and I got it working. Our install ended up having 1.5.0 in lib/common and 1.3.0 in extensions/plugins, which was causing all sorts of strange behaviour, but now resolved.
