### ISSUE TITLE
sonarqube-community-branch-plugin-1.7.0 cannot support sonarqube-8.8.0.42792 version,  sonarQube server cannot up

### ISSUE THREAD

**Issue by crystalyxiaoxianer** [mc1arke/sonarqube-community-branch-plugin#600]
**Describe the bug**
sonarqube-community-branch-plugin-1.7.0 cannot support sonarqube-8.8.0.42792 version

**To Reproduce**
1. download sonarqube-community-branch-plugin-1.7.0.jar and put in the directory ./extensions/plugins
2.  chmod a+x sonarqube-community-branch-plugin-1.7.0.jar 
3.   vi ./conf/sonar.properties and configure as follows:
sonar.web.javaAdditionalOpts=-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.7.0.jar=web
sonar.ce.javaAdditionalOpts=-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.7.0.jar=ce
4.  sh sonar.sh start
5.  sonarQube server cannot up and see error logs：
2022.04.29 17:52:16 DEBUG app[][o.s.a.p.ManagedProcessLifecycle] EventWatcher[es] tryToMoveTo web from STARTING to STARTED => true
Failed to find Premain-Class manifest attribute in ./extensions/plugins/sonarqube-community-branch-plugin-1.7.0.jar
Error occurred during initialization of VM
agent library failed to init: instrument
2022.04.29 17:52:16 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [web]: 1

**Expected behavior**
server is up

**Screenshots**

**Software Versions**
 - SonarQube Version: 8.8.0.42792
 - Plugin Version:  1.7.0

**Comment by mc1arke** [comment]
You're following the wrong installation steps for 1.7.0 of the plugin, you need to follow the steps related to the version you're using: https://github.com/mc1arke/sonarqube-community-branch-plugin/tree/1.7.0#installation.

I'd also recommend using the latest version, or an LTS version rather than an old version of Sonarqube.

**Comment by crystalyxiaoxianer** [comment]
it works, thanks very much.
