### ISSUE TITLE
The "See the PR" link does not work for Azure DevOps

### ISSUE THREAD

**Issue by honzajscz** [mc1arke/sonarqube-community-branch-plugin#601]
**Bug description**
On the pull request analysis page in SonarQube, there is a link pointing to the PR in Azure DevOps. This link, however, does not work properly since there is the organization name as a prefix to the host part of the URL. 

https://organization@dev.azure.com/organization/project/_git/repo/pullRequest/2875

**To Reproduce**
1. Run SonarQube integrated pipeline in Azure DevOps on a pull request
2. Open the PR analysis page in SonarQube
3. Click the See the PR in the upper right corner
4. A new tab opens but with no content.
5. One has to edit the URL in browser address bar in order to open the PR in Azure DevOps

**Screenshots**
![image](https://user-images.githubusercontent.com/3704381/166299538-c3b6cdb5-a9a4-49bb-814b-4161972efcec.png)
![image](https://user-images.githubusercontent.com/3704381/166299995-3447cd8b-78c5-4590-b460-b8d9873243ae.png)

**Software Versions**
 - SonarQube Version: Community EditionVersion 9.4 (build 54424)
 - Plugin Version: 1.11.0

**Comment by mc1arke** [comment]
Released in 1.8.2 and 1.12.0 of the plugin
