### ISSUE TITLE
Mono-repo support for SonarQube 8.9.6 / BitBucket Server / plugin version 1.8(.1)

### ISSUE THREAD

**Issue by DevInsanity** [mc1arke/sonarqube-community-branch-plugin#604]
I noticed there were a few issues for adding mono-repo support that were applied for GitLab and Azure Devops that got back-ported into version 1.8.1 of the plugin. I'd like to request something similar for Bitbucket Server.

From some inspection of the code, it looks like in 1.8.1 of the plugin, the report key passed when uploading the report is hard-coded to com.github.mc1arke.sonarqube, which causes multiple reports to overwrite each other on the same pull request. It looks like in current master this uses the project key instead, which I believe would allow reports for separate projects in the same repository to co-exist on a PR. Not sure if this is all that would need to be adjusted or if there's some additional complexity that I'm missing.

**Comment by mc1arke** [comment]
1.8.2 released with #578
