### ISSUE TITLE
branch plugin throwing error

### ISSUE THREAD

**Issue by PriyankaPanda389** [mc1arke/sonarqube-community-branch-plugin#613]
I tried to follow all the steps mentioned in  the installation document and tried to start sonarqube with this plugin installed, but i am getting errors now and sonar is not starting
These are my configuration changes.

1. add the plugin jar to extensions/plugins and lib/common/ folder
2. add java args to sonar.properties file 
3. add the sonar base url in general settings for sonarqube 
This is the error that I get while restarting sonar
**Failed to find Premain-Class manifest attribute in /scratch/sonar/sonarqube-7.9/extensions/plugins/sonarqube-community-branch-plugin-1.3.2.jar
Error occurred during initialization of VM
agent library failed to init: instrument**

Can someone tell me what am I doing wrong?
sonar and plugin version are there in the error message.

As an extra step, I tried to build the source code and this is the error that I got.
FAILURE: Build failed with an exception.

***** Where:
Build file '/home/sonar-plugin/sonarqube-community-branch-plugin-1.3.2/build.gradle' line: 79**

*** What went wrong:
A problem occurred configuring root project 'sonarqube-community-branch-plugin'.
> Could not resolve all dependencies for configuration ':zip'.
   > Could not resolve sonarqube:sonarqube:7.8.
     Required by:
         project :
      > Could not resolve sonarqube:sonarqube:7.8.
         > Could not get resource 'https://dl.bintray.com/americanexpress/maven/sonarqube/sonarqube/7.8/sonarqube-7.8.pom'.**
            **> Could not GET 'https://dl.bintray.com/americanexpress/maven/sonarqube/sonarqube/7.8/sonarqube-7.8.pom'. Received status code 502 from server: Bad Gateway

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 23s****

How can I resolve this error?

**Comment by mc1arke** [comment]
Why are you using such an old version of Sonarqube? The latest LTS is 8.9, and the latest release at time you'd raised the ticket was 9.4. The rebuild of old releases is likely to require some tweaking of the files since Bintray has been shutdown, however rebuilding isn't going to solve your problem as your issue is that you're not following the installation instructions for that version of the plugin: you need to read the instructions in the README for the appropriate release tag.
