### ISSUE TITLE
plugin error

### ISSUE THREAD

**Issue by danilooliveira88** [mc1arke/sonarqube-community-branch-plugin#622]
I made all the settings for using the plugin, but it seems that the settings are not being replicated.

```
ERROR web[AYFKNmRbTvm7eW1VAAJb][o.s.s.w.WebServiceEngine] Fail to process request https://sonarqubezyzl/api/ce/submit?projectKey=sonarqube-testes&projectName=sonarqube-testes&characteristic=branch%3DMAZG-2295&characteristic=branchType%3DBRANCH


java.lang.IllegalStateException: Current edition does not support branch feature

```

```
  "errors": [
    {
      "msg": "HTTP method POST is required"
    }
  ]
}


```
Sonar - Community EditionVersion | 9.2.4
-- | --

Community Branch PluginEnables branch and pull request analysis in SonarQube Community Edition, without having to upgrade to Developer Edition | 1.11.0installed
-- | --

**Comment by saurabhsinha-7** [comment]
@danilooliveira88  How did you solve this issue?
