### ISSUE TITLE
Are there any plans to fix the PR decorate bug about MergeRequest in the low-version plugin?

### ISSUE THREAD

**Issue by lngg057** [mc1arke/sonarqube-community-branch-plugin#625]
**Describe the bug**
 
- Sonarqube Version：8.9.2
 - Gitlab Version：14.0.0
 - Plugin Version：1.8.1

First of all, thank you very much for this plugin and all the developers, it is you who make the daily work of our project progress normally.

Next is the problem description.

When I merged the personal repo to the central repo with some bugs. Trigger the sonar's pr scan. Although the merge can be intercepted normally, the pr page does not display the sonar result page rendering normally, and the subsequent series of operations are not triggered. 

I found by tracking the sonarqube log that gitlab's link request reported 404. 
> URL like below:
2022.06.16 16:33:37 WARN  ce[AYFtXOoipgpYZdbEaQyf][c.g.m.s.p.c.p.g.GitlabRestClient]###############URL:http://xxxx.com/api/v4/projects/10/merge_requests/10/discussions

After further tracking, I found that sonar requested the discussions of the pr corresponding to the "**merge_requests**" of my personal repo. This obviously doesn't exist.

At one point I thought it was my configuration error, but after I looked at your source code, I found that the **MergeRequest** object only has a "**sourceProjectId**" field, but no "**targetProjectId**" field. In fact, the program is looking for the sourceProject, but the real discussions are located in the targetProject.

This makes me sad, because I firmly believe that your lower version(etc. 1.8.1)  is absolutely correct and had fix this bug, but unfortunately you just modified the logic in the Master branch . But because I used a low version of Sonarqube, I had to pull your tag 1.8.1 and to make local modifications.

Modifying the code is nothing, mainly because it takes too much time to locate the problem, and I think this should not be necessary.

So are there any plans to fix the PR decorate bug about MergeRequest in the lower-version plugin?thx.

**Comment by mc1arke** [comment]
1.8.2  release with Gitlab source/target changes (#554, #555)

**Comment by lngg057** [comment]
> 

Thank you for your positive response and have a nice day❤️
