### ISSUE TITLE
Housekeeping seems not working : inactive branches not purged

### ISSUE THREAD

**Issue by emericv** [mc1arke/sonarqube-community-branch-plugin#630]
Hello,

I have an instance of SonarQube with a couple of projects and analysis over two years. The problem is that I have many old branches without any activity since several months still here.
The housekeeping configuration is the default one and the inactive branches should be deleted after 30 days

I don't know if the sonarqube-community-branch-plugin is compatible with the housekeeping.

Regards,
Emeric

Technical information:
Instance of SonarQube (version 8.9 community) with the plugins :
* sonar-cxx-plugin 2.0.7.3119
* sonar-gitlab-plugin 5.1.2
* sonarqube-community-branch-plugin 1.8.2

**Comment by mc1arke** [comment]
https://github.com/mc1arke/sonarqube-community-branch-plugin/issues/221
