### ISSUE TITLE
Comments in Merge Request are not loading as expected

### ISSUE THREAD

**Issue by Wankhadess** [mc1arke/sonarqube-community-branch-plugin#631]
**Describe the bug**
we are currently having a strange issue with some of our Merge Requests in Gitlab. The comments of the MR and PR decoration cannot be loaded. We have other open Merge Requests which can be accessed without any issues. The Merge Request does not really differ from the other MRs, is not very big (another, working MR actually has way more comments and changed files). 

I have also check in the SonarQube logs if something is wrong with the bot but it's working fine. no clue what could be the Issue.

In previous version this plugin  provide an option in the project setting to disable different comments. But now it follows the official sonarsource implementation, which does not provide that option. will there be any chance to implement it again?
https://github.com/mc1arke/sonarqube-community-branch-plugin/pull/487 

Also, in the latest release https://github.com/mc1arke/sonarqube-community-branch-plugin/releases/tag/1.8.2
new feature added for  Github,  Hide outdated summary comments in Github Pull Request decoration (https://github.com/mc1arke/sonarqube-community-branch-plugin/pull/435)  will this feature be available for Gitlab users in future? 
 
 
**To Reproduce**
Create a Merge Request from one branch to other with multiple comments.

**Expected behavior**
 MR overview tab should  load properly with all comments and decoration.

**Screenshots**
<img width="497" alt="image-2022-06-09-10-36-59-851" src="https://user-images.githubusercontent.com/64198883/175047910-f6a4012a-1cb9-40e7-9840-1c4b85d60656.png">

**Software Versions**
 - SonarQube Version: LTS 8.9.2 (build 46101)
 - Plugin Version: [1.8.1](https://github.com/mc1arke/sonarqube-community-branch-plugin/releases/tag/1.8.1)
 - Gitlab Version: 

**Additional context**
Do let me know if you required any further inputs from my end.

**Comment by mc1arke** [comment]
On the main issue you've reported (threads not loading), does your browser console show any pending network requests or Javascript errors?

For your other comments:
* The plugin has never supported filtering by comment types, and I don't have any plans to introduce this
* Hiding outdated summary comments is effectively introduced in 1.9.0 of the plugin (Sonarqube 9.0) through resolving threads when the associate issue is resolved

**Comment by mably** [comment]
@Wankhadess: I just pushed a PR (#648) trying to mimick then current sonarcloud.io behavior where the previous analysis summary is deleted when the new one is published.
