### ISSUE TITLE
Quality gate new branch for first analysis with new issues

### ISSUE THREAD

**Issue by michoudu13820** [mc1arke/sonarqube-community-branch-plugin#635]
Hello,

**Describe the bug**
SonarQube quality gate is configured on new code (due to legacy project with many bugs). For first analysis on a new  branch, even if new bugs/errors are introduiced the quality gate is PASSED

Done few research and on SonarQube Entreprise edition I found that we can configure from which branch new code should be compared to for the build (in our case it should be great to compare new code/ bugs / issues from master and not new code from previous branch analysis).
Because there is no previous analysis, so if new bugs are introduiced before the first analysis on the new branch the quality gate will be PASSED.
 

**To Reproduce**
0. Configure Sonar quality gate for new code, and new bugs/issues less than 0.
1. Analyse a project on master
2. Create a branch from master
3. Add a new bug (i.e NPE for example)
4. Analyse new branch ==> Quality gate is PASSED

**Expected behavior**
Quality Gate should be FAILED

**Software Versions**
 - SonarQube Version: 8.9.7 LTS community
 - Plugin Version: 1.8.1

**Additional context**
Is it possible to configure the plugin to specify from where new code should be compared to ?

**Comment by mc1arke** [comment]
For step 4, is this the first analysis of the branch? By default analysis is performed against the baseline for the branch, with the first analysis of a branch being the creation of the baseline. From 1.9.0 of the plugin #272 was fixed which allowed baseline targets to be specifically set per project.

**Comment by michoudu13820** [comment]
For step 4, yes it is the first analysis of the branch.
Ok thank you so if I understand well we should upgrade to 1.9.0 or higher and specify master branch for exemple to be the reference branch ?

Thank you for your answer :)
