### ISSUE TITLE
Broken build - missing branch plugin

### ISSUE THREAD

**Issue by oscrx** [mc1arke/sonarqube-community-branch-plugin#638]
**Describe the bug**
We are running with the docker image mc1arke/sonarqube-with-community-branch-plugin:8.9-community
And it seems to have changed. It doesn't succeed Kubernetes health checks anymore.

**To Reproduce**
Try to start mc1arke/sonarqube-with-community-branch-plugin:8.9-community

**Expected behavior**
Starting and becoming healthy.

**Screenshots**
<img width="537" alt="afbeelding" src="https://user-images.githubusercontent.com/6731096/177119961-e5e8125a-a309-4511-b022-670b5c43f356.png">

**Software Versions**
 - SonarQube Version: [e.g. Version 7.8 (build 26217)]
 - Plugin Version: [e.g. 1.1.0, or custom build from master at commit 004AD34FAA]

**Additional context**
It seems the branch plugin is no longer included with the build. Our local docker cache (screenshot) indicated the image is changed. I'll update our instance to fix the issue. But I made this issue to notify and hopefully fix it for others.

```
Error opening zip file or JAR manifest missing : /opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin-1.8.1.jar
Error occurred during initialization of VM
agent library failed to init: instrument
2022.07.04 07:56:53 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [web]: 1
2022.07.04 07:56:53 INFO  app[][o.s.a.SchedulerImpl] Process[web] is stopped
2022.07.04 07:56:53 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [es]: 143
2022.07.04 07:56:53 INFO  app[][o.s.a.SchedulerImpl] Process[es] is stopped
2022.07.04 07:56:53 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
```

**Comment by mc1arke** [comment]
I'm not sure I understand this issue: the latest 8.9 version does contain a plugin: https://hub.docker.com/layers/sonarqube-with-community-branch-plugin/mc1arke/sonarqube-with-community-branch-plugin/8.9-community/images/sha256-3256e8ca443ce930ff67c7288b8d3674f6b17da26e8be95366f6f89402997eef?context=explore. Are you running extra commands ontop of the container that expect 1.8.1 (rather than 1.8.2) to be present?

**Comment by mc1arke** [comment]
Closing since no further replication steps have been provided
