### ISSUE TITLE
[SQ8] Gateway summary but no individual code smell decoration on gitlab

### ISSUE THREAD

**Issue by bcouetil** [mc1arke/sonarqube-community-branch-plugin#641]
Thank you for the wonderful work, that helped me for years 🥰

**Describe the bug**
With Gitlab, the MR is decorated with quality gate status, but no individual code smell decoration.
It used to work with SonarQube 8.4 and associated plugin version.

**To Reproduce**
Classic usage with Gitlab

**Expected behavior**
A way to know what's wrong, if this is a user misconfiguration 

**Screenshots**

Sonarqube CE logs :

```
2022.07.19 09:35:05 INFO  ce[AYIVz5HYJEFr3rsCCqQN][c.g.m.s.p.c.p.PullRequestPostAnalysisTask] using pull request decorator com.github.mc1arke.sonarqube.plugin.ce.pullrequest.gitlab.GitlabMergeRequestDecorator
2022.07.19 09:35:08 INFO  ce[AYIVz5HYJEFr3rsCCqQN][o.s.c.t.p.a.p.PostProjectAnalysisTasksExecutor] Pull Request Decoration | status=SUCCESS | time=3316ms
2022.07.19 09:35:08 INFO  ce[AYIVz5HYJEFr3rsCCqQN][o.s.c.t.CeWorkerImpl] Executed task | project=minz | type=REPORT | pullRequest=1936 | id=AYIVz5HYJEFr3rsCCqQN | submitter=me | status=SUCCESS | time=5653ms
```

I did not find anything meaningful using DEBUG logs, so I won't paste them for now

**Software Versions**
 - SonarQube Version: 8.9.9
 - Plugin Version: 1.8.2
- Gitlab : gitlab.com (GitLab Enterprise Edition 15.2.0-pre [23631a9ae51])

**Comment by bcouetil** [comment]
I forgot to mention that this is a mono-repository, so one project on Gitlab side and multiple projects on SonarQube side. I tested by adding deliberate code smalls to 2 modules.

**Comment by bcouetil** [comment]
Although, I may use some outdated scanner fields :

```
sonar.pullrequest.key=$CI_MERGE_REQUEST_IID 
sonar.pullrequest.branch=$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME 
sonar.pullrequest.base=$CI_MERGE_REQUEST_TARGET_BRANCH_NAME 
sonar.pullrequest.gitlab.instanceUrl=$CI_API_V4_URL -Dsonar.pullrequest.gitlab.projectId=$CI_PROJECT_PATH 
sonar.pullrequest.gitlab.projectUrl=$CI_MERGE_REQUEST_PROJECT_URL 
com.github.mc1arke.sonarqube.plugin.branch.pullrequest.gitlab.pipelineId=$CI_PIPELINE_ID 
sonar.scm.revision=$CI_COMMIT_SHA
```

**Comment by mc1arke** [comment]
The fact you're getting the Quality Gate status indicates the ability to post a summary comment is ok. I'd expect a failure to post a 'diff' comment would cause an error in your logs, so would need to see either your debug-level logs, or an example Merge Request that I can try and replicate the issue is with myself

**Comment by bcouetil** [comment]
Thank you for your time.

An example MR to show would be too complicated as of now, so here are debug logs :
[sonarqube_ce(13).log](https://github.com/mc1arke/sonarqube-community-branch-plugin/files/9157782/sonarqube_ce.13.log)

**Comment by bcouetil** [comment]
Does it help ?

**Comment by xC0dex** [comment]
Hey @bcouetil,
we recently updated from GitLab 14.4.x to 15.3.x and SonarQube from 9.5 to 9.6.x and facing the same issue you described. Do you still have the issue or any solution?

**Comment by bcouetil** [comment]
Unfortunately no solution as of now...

I guess @mc1arke has not found time to dig into this for now...

**Comment by bcouetil** [comment]
Anyone coming to this issue knows a working version ?

**Comment by yaverhussain** [comment]
The latest this bundle has is sonar 9.5.0 unless you have your own docket image pulling 9.6.1 sonar with latest pull request community plugin

**Comment by yaverhussain** [comment]
Ok update is I got it working Sonar 9.6.1, Community plug-in 1.12.0. Couple of gotchas but ended up well. Have raised a PR as well to make it easier for next guy

**Comment by mareksabo** [comment]
We had similar issue in our project, only summary without individual comments. The problem was in the setup, _Administration -> ALM Integrations -> GitLab URL (`sonar.auth.gitlab.url`)_ needs to be https://gitlab.com/, not https://gitlab.com/api/v4/.

**Comment by mc1arke** [comment]
I did have a look at your logs previously and can see that the plugin doesn't appear to be attempting to submit comments for the individual findings, which would normally indicate that your build process is performing an operation like a git merge/rebase that results in a different commit hash being used in the build than is set in the Merge Request, so results in none of the issues being matched to the current merge request. Are you able to confirm how your build process works?

**Comment by bcouetil** [comment]
Thank you for your response @mc1arke . Your plugin being very useful for a lot of people (thanks), I thought I could contribute a bit more of my time for the community.

I had to add some logs in a forked version : https://github.com/bcouetil/sonarqube-community-branch-plugin/pull/1/files

And the reason of our trouble is simple (beyond the absolute lack of logs) : If there is a shallow clone, blame information may not be sent to SonarQube. The plugin compares the issues list and the blame information containing modified code, I guess to prevent comment on unmodified code. In my case, there where issue, but not matching the blame information (scmInfoRepository).

I say "may be", because it may depend on the SonarQube analyzer. I use the .NET Framework SonarQube analyzer, and it does not give blame information when it detects a shallow clone. In practice this lazy foe could give the info on the commits effectively presents 😅  (by defaut 20 to 50 depending on GitLab version, overwritten with GIT_DEPTH variable).

While it is a fine idea in theory to be sure that the issues are matching the MR, doing a full clone (GIT_DEPTH 0) on each job is too much for feature branches on non-trivial projects

I removed the `.filter(issue -> isIssueFromCommitInCurrentRequest(issue.getLeft(), commitIds, scmInfoRepository))`, compiled my jar and used it, and know issue commenting works.

The best solution would be to detect that we are on GitLab in MR mode, and not filter out in this case.

Could you help me with the java condition I could use ?
