### ISSUE TITLE
Could not decorate pull request on SonarQube 8.9

### ISSUE THREAD

**Issue by Nabilberd** [mc1arke/sonarqube-community-branch-plugin#642]
**Describe the bug**
I'm facing the problem below when upgrading sonarqube from 6.7 to 8.9 and the plugin sonarqube-branch :

In Github Pull requests i see the message : **Expected — Waiting for status to be reported**

In Sonarqube i see the message : 

2022.07.19 14:16:33 DEBUG ce[AYIWmdpRpjYHrAxW79G_][c.g.m.s.p.c.p.PullRequestPostAnalysisTask] found 4 pull request decorators
2022.07.19 14:16:33 INFO  ce[AYIWmdpRpjYHrAxW79G_][o.s.c.t.p.a.p.PostProjectAnalysisTasksExecutor] Pull Request Decoration | status=SUCCESS | time=0ms

Software Versions

SonarQube Version: 8.9.7
Plugin Version: 1.8.1
openjdk 11.0.13 2021-10-19
Github 2.22.2

**Comment by mc1arke** [comment]
This looks like you've not configured the project to use a specific pull request decorator. Please ensure you're providing minimum replication steps the demonstrate the configuration you currently have in place

**Comment by Nabilberd** [comment]
This is my configuration in Jenkinsfile:

sh "mvn package sonar:sonar  -f ${WORKSPACE} " +
                  "-Dsonar.pullrequest.key=${PULL_REQUEST_ID} " +
                  "-Dsonar.pullrequest.branch="+ env.BRANCH_NAME +" " +
                  "-Dsonar.pullrequest.base="+ env.CHANGE_BRANCH +" " +
                  "-Dsonar.github.pullRequest=${PULL_REQUEST_ID} " +
                  "-Dsonar.github.repository=${GITHUB_REPO}  " +
                  "-Dsonar.github.oauth=${GITHUB_LOGIN} " +
                  "-Dsonar.host.url=${SONAR_URL}  " +
                  "-Dsonar.login=${SONAR_LOGIN}  " +
                  "-Dsonar.verbose=true " +
                  "-Dsonar.issuesReport.console.enable=true " +
                  "-DskipTests"

I alson configured the ALM integration in Sonarqube.

Could you please explain what configuration i must add ?

**Comment by mc1arke** [comment]
It's the configuration of the project within Sonarqube that you need to manage. Have you setup the ALM bindings against the project in the Sonarqube UI?

**Comment by Nabilberd** [comment]
UPDATE:

Now i'm getting this error : 

2022.07.20 09:38:50 DEBUG ce[AYIawmEec8s6zK8ImoNk][c.g.m.s.p.c.p.PullRequestPostAnalysisTask] No ALM has been set on the current project

But in the general setting of sonarqube im configuration ALM github 

![image](https://user-images.githubusercontent.com/48296406/179944501-03464d3a-bb55-4041-81f2-f1c4011194fb.png)

**Comment by mc1arke** [comment]
You'll need to follow https://docs.sonarqube.org/8.9/analysis/github-integration/#:~:text=Adding%20pull%20request%20decoration%20to%20a%20manually%20created%20or%20existing%20project to setup decoration on your project
