### ISSUE TITLE
Gitlab CI project ID auto detection not working

### ISSUE THREAD

**Issue by lucasoares** [mc1arke/sonarqube-community-branch-plugin#653]
Hello.

I was using sonarqube 8.2 with `sonarqube-community-branch-plugin-1.5.0` and inside my project configuration I just needed to select the gitlab configuration:

![image](https://user-images.githubusercontent.com/10624972/184221377-412927a0-6fa0-4cce-81f7-c0ad812ff7a5.png)

The project id from gitlab CI were automatically detected for my jobs.

Now I just updated the sonarqube to 9.5 with `sonarqube-community-branch-plugin-1.12.0` and my MR decoration stops working.

Why the project id auto detection is not working anymore? I manually set the project ID in the new devops configuration and everything worked again.

Would be nice to have at least an sonar-scanner attribute to set the project ID directly from the CI. I have thousand of projects and would be nice to fix this inside my CI instead of manually fixing every single project inside sonarqube configuration.

Thanks.

**Comment by mc1arke** [comment]
The scanner doesn't support this in Developer edition, and generally wouldn't be a good thing to aim for given inconsistent scan parameters would cause the project to analyse differently. You can setup bindings using Sonarqubes API
