### ISSUE TITLE
[QUESTION] SQ 9.6 incremental Java PR support

### ISSUE THREAD

**Issue by mildis** [mc1arke/sonarqube-community-branch-plugin#657]
Does 1.12.0 support the incremental Java PR analysis reintroduced in Sonar 9.6 ?

**Comment by chinhodado** [comment]
I'm interested in knowing this as well, would love it if someone can confirm whether v1.12 works with SonarQube 9.6, and whether the incremental Java PR analysis works.

**Comment by mildis** [comment]
Looks like 1.12.0 works under 9.6 (at least, we get results from the analysis)  

We are still running analysis to find out if there are optimisation going on.  

However, Sonar themselves place some restrictions about how the skip unchanged files or not
https://docs.sonarqube.org/latest/analysis/languages/java/#header-7

**Comment by cartmanez** [comment]
@mildis can you please share results of your analysis?

Sonar have expanded and improved incremental analysis in the recent releases, but I don't understand whether increment analysis will work in community edition with community branch plugin

Thanks!
