### ISSUE TITLE
PR decoration links to icon SVG

### ISSUE THREAD

**Issue by marcelstoer** [mc1arke/sonarqube-community-branch-plugin#662]
**Describe the bug**
The (GitLab) PR decoration comment has each analysis icon wrapped with a hyperlink _that points to the icon SVG_.

I see how the list items are created at https://github.com/mc1arke/sonarqube-community-branch-plugin/blob/release/1_8/src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/AnalysisDetails.java#L224-L236. However, I don't understand yet how the image ends up being wrapped by a link. `MarkdownFormatterFactory` and friends don't smuggle in elements, do they?

**Expected behavior**
Not sure...either no link at all or a link to respective metric e.g. https://my.sonar/component_measures?id=some-id&metric=new_coverage&pullRequest=42&view=list

**Screenshots**
<img width="463" alt="Screen Shot 2022-08-24 at 16 59 55" src="https://user-images.githubusercontent.com/624195/186453550-fa7e2b0d-f210-434d-be8c-76f28a65d215.png">

**Software Versions**
 - SonarQube Version: 8.9.6
 - Plugin Version: 1.8 something

**Comment by mc1arke** [comment]
This isn't the plugin, it's a 'feature' of Gitlab to allow you to see the image directly. We don't set a link, and don't have control over Gitlab adding one.

**Comment by marcelstoer** [comment]
Thanks for the clarification. I'm relieved I didn't miss anything obvious in my analysis.

Am I right in assuming that if I were to only wrap each image list item in `AnalysisDetails` (as proposed in "Expected behavior") the serialized Markdown would represent what I expected?

**Comment by mc1arke** [comment]
I'm not sure how Gitlab would handle you wrapping the list item contents with a link. I suspect it you still wrap the image in a link and leave the rest of the content wrapped in your link

**Comment by marcelstoer** [comment]
Arggg, sorry 🙇 . Instead of the bogus "image list item" I had meant to say "list item image". Of course, it makes more sense to wrap the icon rather than the entire list item.

**Comment by marcelstoer** [comment]
I am just revisiting this as the behavior keeps annoying me enough to want to provide a PR. Can you please reopen it.

I just did some experimenting with your latest version and our local GitLab installation. Should actually be very easy to fix.

- In https://github.com/mc1arke/sonarqube-community-branch-plugin/blob/master/src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/report/AnalysisSummary.java#L188 ff. wrap each list item image with `new Link(url, image)`.
- Allow `Link` to have children of type `Image` at `https://github.com/mc1arke/sonarqube-community-branch-plugin/blob/master/src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/markup/Link.java#L36`.

-> gives you a proper Markdown link around the icon in the form of `- [![Bug](bugImageUrl)](SQ-MR-bug-URL) 911 Bugs`
-> GitLab won't render its own HTML link around the icon but use the one from the Markdown
