### ISSUE TITLE
pullrequest decoration comments should include a link to sonarqube's task detail page and vice versa

### ISSUE THREAD

**Issue by jizhilong** [mc1arke/sonarqube-community-branch-plugin#67]
For now, the pullrequest decoration message only contains a brief summary  of the  analysis, but no direct link to guide the developer to the sonarqube's task page, where he/she can view the details of each metric category. As a workaround, one can find the sonar task link at gitlabci's CI/CD pipeline page,  which could be more convenient if it was already included in the pullrequest decoration message. And on sonar's task page, a link to the corresponding PR/MR page would also make life easier.

**Comment by tisoft** [comment]
Added PR #70 for adding the link to SonarQube into the PR comments.

**Comment by kortov** [comment]
Hi I'd like to ask a question. The link the issue about is the dashboard url? Because I'd like to notice that sonar dumps https://github.com/SonarSource/sonarqube/blob/f61e29bce771e56f8d45ad07a235c0399a1a9772/sonar-scanner-engine/src/main/java/org/sonar/scanner/report/ReportPublisher.java#L230 dashboardUrl to report-task.txt file. There is a similar plugin which works with this file and I opened a PR about this dashboardUrl https://github.com/gabrie-allaigre/sonar-gitlab-plugin/pull/268
maybe it would be interesting for you. But I don't see that this plugin used report-task.txt before

**Comment by tisoft** [comment]
The summary comment links to the dashboard, the issue comments link to the issue in the file.

**Comment by mc1arke** [comment]
For the link from Sonarqube to the PR, this functionality is currently provided by Sonarqube core if we set the `url` property on the BranchDto, which we don't currently do. This should be do-able in `PullRequestPostAnalysisTask` by having the constructor take a `DbClient` instance, getting the `PullRequestBuildStatusDecorator` to generate the PR URL (I've not yet decided if it's best to do this as a return value on the `decorateQualityGateStatus` call, or as another method), and then using something similar to
```
        try (DbSession dbSession = dbClient.openSession(false)) {
            BranchDao branchDao = dbClient.branchDao();
            Optional<BranchDto> optionalBranchDto = branchDao.selectByPullRequestKey(dbSession, projectAnalysis.getProject().getUuid(), projectAnalysis.getScannerContext().getProperties().get("sonar.pullrequest.key"));
            if (optionalBranchDto.isPresent()) {
                BranchDto branchDto = optionalBranchDto.get();
                DbProjectBranches.PullRequestData.Builder pullRequestDataBuilder = DbProjectBranches.PullRequestData.newBuilder(branchDto.getPullRequestData());
                pullRequestDataBuilder.setUrl(url);
                branchDto.setPullRequestData(pullRequestDataBuilder.build());
                branchDao.upsert(dbSession, branchDto);
            }
        }
```

I'll try this out when I get time and get a PR raised.

**Comment by mc1arke** [comment]
Release in version 1.3.1
