### ISSUE TITLE
Unclear warning when adding another ALM configuration

### ISSUE THREAD

**Issue by p3k** [mc1arke/sonarqube-community-branch-plugin#673]
**Describe the bug**
In the dialog for adding another ALM configuration a warning appears:

> Binding more than one instance of an ALM will deactivate the import of repositories from that ALM

Although the words are clear we cannot make head nor tail about the implications of this warning. It is not clear whether it might be a mistake to create a second instance of the ALM, it rather creates FUD.

**To Reproduce**
1. Go to `Administration` → `Configuration` → `General Settings` → `ALM Integrations`
2. Activate the `GitLab` tab
3. Click on the `Create configuration` button

**Expected behavior**
It should be clear what the actual consequences of adding another ALM configuration are: what does the deactivated import of a repository imply? Is analyzing a repository still possible? How about creating a new project?

**Screenshots**
![image](https://user-images.githubusercontent.com/16631/195043814-7713a38c-f783-40a9-9acc-59127337c8c2.png)

**Software Versions**
 - SonarQube Version: 8.9.9.56886
 - Plugin Version: 1.8.2

**Comment by mc1arke** [comment]
This isn't a message generated by the plugin: it's coming from Sonarqube core. We just allow the message to be present since we allow the Multiple ALM feature to be available.
