### ISSUE TITLE
PR Decoration Images and Links Broken

### ISSUE THREAD

**Issue by amberhart1** [mc1arke/sonarqube-community-branch-plugin#675]
**Describe the bug**
PR decoration broken images and links, all links are broken except "View in SonarQube" link.

**To Reproduce**
1.Complete an analysis on the pull request
2.Scroll down to sonarqube bot comment section
3.View and click links. The link navigate to an "Invalid upstream response (403)" page.  

**Expected behavior**
Expect to see images and to be redirected to SonarQube when clicking the links under "Analysis Details"

**Screenshots**
<img width="960" alt="Screen Shot 2022-10-18 at 4 12 00 PM" src="https://user-images.githubusercontent.com/98336703/196536846-52d528a1-c7f4-44e4-836f-bc66ca48b347.png">

<img width="855" alt="Screen Shot 2022-10-18 at 4 27 09 PM" src="https://user-images.githubusercontent.com/98336703/196537813-3533fdad-07f3-4f69-8e4f-b1b2a1f68a90.png">

**Software Versions**
 - SonarQube Version: 9.5.0.56709
 - Plugin Version: 1.12.0

**Additional context**

**Comment by jpspringall** [comment]
Have you set your server url:
```
Make sure sonar.core.serverBaseURL in SonarQube [/admin/settings](http://localhost:9000/admin/settings) is properly set in order to for the links in the comment to work.
```

I had the same issue a couple of days ago, and that was my fix

**Comment by amberhart1** [comment]
That worked! Thank you.
