### ISSUE TITLE
SonarQube suppressed Old Issues Raised as New Issues

### ISSUE THREAD

**Issue by Wankhadess** [mc1arke/sonarqube-community-branch-plugin#690]
Hi,

We have recently upgraded our SonarQube community version: from 8.9 LTS to 8.9.10 LTS on 28-Oct-2022</p><p>One of our project in SonarQube is facing issue that there old suppressed Issues are raised as New Issues.<br>→ The suppressions + arguments (comments) have already been entered into SonarQube over the last 2 years.<br>This happened after they have shifted to new Red Hat on 27 Oct 2022</p><p>There are multiple changes happened on Project side:</p><div class="md-table" style="overflow-y: auto; margin: 1em 0px;">

Old Jenkins | New Jenkins
-- | --
CentOS Linux 8.1 | Red Hat Enterprise Linux 8.5
cmake version 3.11.4 | cmake version 3.20.2
gcc version 8.3.1 | gcc version 8.5.0
Qt version 5.12.5 | Qt version 5.15.8

</div><p>project is using RTC-SCM</p><p>This will lead to change in the analysis setting sonar.cxx.includeDirectories</p><ul style="margin: 1em 0px 1em 1.25em; padding: 0px 0px 0px 1.25em; clear: both;"><li><strong style="font-weight: bolder;">sonar.cxx.includeDirectories</strong>=/usr/include,/usr/include/c++/8,/usr/include/c++/8/x86_64-redhat-linux,/usr/lib/gcc/x86_64-redhat-linux/8/include,/opt/qt/Qt5.15.8/5.15.8/gcc_64/include,/opt/qt/Qt5.15.8/5.15.8/gcc_64/include/QtNetwork,cg-etcs-pi-aramis/src/main/native,cg-etcs-pi-aramis/src/main/native/Connection,cg-etcs-pi-aramis/src/main/native/Command,cg-etcs-pi-aramis/src/main/native/Handlers,cg-etcs-pi-logger/src,cg-etcs-pi-pii/src/main/native/include</li></ul><p>I have went through these blogs<span> </span><a href="https://community.sonarsource.com/t/old-issues-raised-as-new-issues/23461" class="inline-onebox" style="background-color: transparent; color: var(--tertiary); text-decoration: none; cursor: pointer; overflow-wrap: break-word;">Old Issues Raised as New Issues<span> </span><span class="badge badge-notification clicks" title="1 click" style="display: inline-block; font-weight: normal; white-space: nowrap; border-radius: 10px; padding: 0.21em 0.42em; min-width: 0.5em; color: var(--primary-medium); font-size: var(--font-down-2); line-height: var(--line-height-small); text-align: center; background-color: var(--primary-low); top: -1px; position: relative; border: none;">1</span></a><br><a href="https://community.sonarsource.com/t/old-issue-became-new/2465" class="inline-onebox" style="background-color: transparent; color: var(--tertiary); text-decoration: none; cursor: pointer; overflow-wrap: break-word;">Old issue became new?<span> </span><span class="badge badge-notification clicks" title="1 click" style="display: inline-block; font-weight: normal; white-space: nowrap; border-radius: 10px; padding: 0.21em 0.42em; min-width: 0.5em; color: var(--primary-medium); font-size: var(--font-down-2); line-height: var(--line-height-small); text-align: center; background-color: var(--primary-low); top: -1px; position: relative; border: none;">1</span></a></p><p>According to the above blog if we change anything from the previous analysis setting that will lead suppressed Old Issues to raised as New Issues.</p><p>I need to verification if this is the main cause or something else???

We have raised this ticket on SonarQube community https://community.sonarsource.com/t/sonarqube-suppressed-old-issues-raised-as-new-issues/76068 as well but got a response that , if only thing we have updated  is being passed through Plugin Parameter there might be any chance this could cause this behavior can you check and verify from your end. Also, let me know if any input is required from our side.

Regards,
Sheetal

**Comment by Wankhadess** [comment]
Hi, Any update on this???

**Comment by mc1arke** [comment]
There's nothing in this plugin that controls the creation or filtering of issues so I'm not sure there's much to check. I'm going to close this issue, but can investigate further if you can provide replication steps in the future.
