### ISSUE TITLE
Housekeeping seems not working : inactive branches not purged

### ISSUE THREAD

**Issue by hasmikg** [mc1arke/sonarqube-community-branch-plugin#701]
Noticed that similar old issue (#630 ) was fixed for old versions

Versions which are not working:
SQ Community Edition Version 8.9.10 (build 61524)
Plugin version 1.8.1

**Comment by mc1arke** [comment]
This is not a bug in the plugin. Please see the comments on the issue that was linked to from the issue you've mentioned in your report.
