### ISSUE TITLE
sonarqube-community-branch-plugin not compatible with the versions 9.7.0.61563 and 9.7.1.62043

### ISSUE THREAD

**Issue by yfrindel** [mc1arke/sonarqube-community-branch-plugin#705]
The version 1.12.0 of the sonarqube-community-branch-plugin and the version 9.6.0.59041 are installed on our SonarQube server.
I tried to install the versions 9.7.0.61563 and 9.7.1.62043, but we have now these errors 

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/22955005/209164227-86975248-e9d9-457b-a166-896e3854922c.png)
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/22955005/209164300-800fc7dc-bc9e-4bbe-bd10-4e9463f18145.png)

**Comment by yfrindel** [comment]
thanks for your reply, but don't think it's secure to using a "snapshot" version in prod.
I prefer to stay in the 9.6 version, and wait for a 1.13 release version

**Comment by mc1arke** [comment]
I'm not sure I understand why you don't want to use a snapshot given it's a signed commit and the code and scripts for producing a release and a snapshot are both contained in that commit.

Closing since this is a duplicate.
