### ISSUE TITLE
Zero code coverage for branch with latest java-plugin version

### ISSUE THREAD

**Issue by mfominov** [mc1arke/sonarqube-community-branch-plugin#71]
**Describe the bug**
I've recently update all plugins on my SonarQube server and my developers noticed an issue with coverage on branches. With latest version of java-plugin 6.0 (build 20538) there is no coverage. I've downgrade plugin to 5.14 version and coverage come back.
In my opinion this is not an issue of a branch plugin, by u should look at this in future releases

**To Reproduce**
1. Go to MarketPLace update java-plugin to latest version
2. Execute maven build with coverage for branch
3. Go to branch analysis and see zero coverage.  

**Expected behavior**
Coverage for branch) 

**Screenshots**

**Software Versions**
 - SonarQube Version: 7.9.1 (build 27448)]
 - Plugin Version: 1.1.1

**Additional context**

**Comment by mc1arke** [comment]
I think you're hitting https://github.com/SonarSource/sonar-java/commit/16175a3752060c3470625254adafb6c80312fa55 where the Jacoco binary file is being generated but is no longer being parsed by Sonarqube. For building this plugin, the following needs added to the build.gradle - as well as moving to the latest Sonarqube Gradle plugin - if moving to a newer version of Sonarqube:
```
jacocoTestReport {
    reports {
        xml.enabled = true
    }
}
plugins.withType(JacocoPlugin) {
    tasks['test'].finalizedBy 'jacocoTestReport'
}

```
I've not checked what the equivalent configuration is for Maven, although that's beyond the scope of this plugin.
