### ISSUE TITLE
SONAR_CE_JAVAOPTS not implemented

### ISSUE THREAD

**Issue by AceCoderYoda** [mc1arke/sonarqube-community-branch-plugin#722]
**Describe the bug**
When definining SONAR_CE_JAVAOPTS with -Xmx2G  -Xms2G the parameters are seemingly ignored.

2023.01.12 06:36:51 INFO  es[][o.e.n.Node] JVM arguments [-XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -Djava.io.tmpdir=/opt/sonarqube/temp, -XX:ErrorFile=../logs/es_hs_err_pid%p.log, -Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dio.netty.allocator.numDirectArenas=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.locale.providers=COMPAT, -Des.enforce.bootstrap.checks=true, **-Xmx512m, -Xms512m**, -XX:MaxDirectMemorySize=256m, -XX:+HeapDumpOnOutOfMemoryError, -Des.path.home=/opt/sonarqube/elasticsearch, -Des.path.conf=/opt/sonarqube/temp/conf/es, -Des.distribution.flavor=default, -Des.distribution.type=tar, -Des.bundled_jdk=false]

**To Reproduce**
add SONAR_CE_JAVAOPTS -Xmx2G  -Xms2G  to image params

**Expected behavior**
Elastisearch to start with correct memory allocation

**Screenshots**
2023.01.12 06:36:33 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /opt/sonarqube/temp,
2023.01.12 06:36:33 INFO  app[][o.s.a.es.EsSettings] Elasticsearch listening on [HTTP: 127.0.0.1:9001, TCP: 127.0.0.1:34687],
2023.01.12 06:36:33 INFO  app[][o.s.a.ProcessLauncherImpl] Launch process[[key='es', ipcIndex=1, logFilenamePrefix=es]] from [/opt/sonarqube/elasticsearch]: /opt/sonarqube/elasticsearch/bin/elasticsearch,
2023.01.12 06:36:33 INFO  app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running,
warning: no-jdk distributions that do not bundle a JDK are deprecated and will be removed in a future release,
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.,
2023.01.12 06:36:51 INFO  es[][o.e.n.Node] version[7.12.1], pid[31], build[default/tar/3186837139b9c6b6d23c3200870651f10d3343b7/2021-04-20T20:56:39.040728659Z], OS[Linux/4.14.35-linuxkit/amd64], JVM[AdoptOpenJDK/OpenJDK 64-Bit Server VM/11.0.11/11.0.11+9],
2023.01.12 06:36:51 INFO  es[][o.e.n.Node] JVM home [/opt/java/openjdk],
2023.01.12 06:36:51 INFO  es[][o.e.n.Node] JVM arguments [-XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -Djava.io.tmpdir=/opt/sonarqube/temp, -XX:ErrorFile=../logs/es_hs_err_pid%p.log, -Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dio.netty.allocator.numDirectArenas=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.locale.providers=COMPAT, -Des.enforce.bootstrap.checks=true, -Xmx512m, -Xms512m, -XX:MaxDirectMemorySize=256m, -XX:+HeapDumpOnOutOfMemoryError, -Des.path.home=/opt/sonarqube/elasticsearch, -Des.path.conf=/opt/sonarqube/temp/conf/es, -Des.distribution.flavor=default, -Des.distribution.type=tar, -Des.bundled_jdk=false],
2023.01.12 06:36:53 INFO  es[][o.e.p.PluginsService] loaded module [analysis-common],
2023.01.12 06:36:53 INFO  es[][o.e.p.PluginsService] loaded module [lang-painless],
2023.01.12 06:36:53 INFO  es[][o.e.p.PluginsService] loaded module [parent-join],
2023.01.12 06:36:53 INFO  es[][o.e.p.PluginsService] loaded module [percolator],
2023.01.12 06:36:53 INFO  es[][o.e.p.PluginsService] loaded module [transport-netty4],
2023.01.12 06:36:53 INFO  es[][o.e.p.PluginsService] no plugins loaded,
2023.01.12 06:36:53 INFO  es[][o.e.e.NodeEnvironment] using [1] data paths, mounts [[/ (overlay)]], net usable_space [18.6gb], net total_space [19.6gb], types [overlay],
2023.01.12 06:36:53 INFO  es[][o.e.e.NodeEnvironment] heap size [495.3mb], compressed ordinary object pointers [true],
2023.01.12 06:36:53 INFO  es[][o.e.n.Node] node name [sonarqube], node ID [NR7T1sooQNi5DZ0yygDTKQ], cluster name [sonarqube], roles [master, remote_cluster_client, data, ingest],
2023.01.12 06:37:03 INFO  es[][o.e.t.NettyAllocator] creating NettyAllocator with the following configs: [name=unpooled, suggested_max_allocation_size=1mb, factors={es.unsafe.use_unpooled_allocator=null, g1gc_enabled=false, g1gc_region_size=0b, heap_size=495.3mb}],
2023.01.12 06:37:04 INFO  es[][o.e.d.DiscoveryModule] using discovery type [zen] and seed hosts providers [settings],
2023.01.12 06:37:05 INFO  es[][o.e.g.DanglingIndicesState] gateway.auto_import_dangling_indices is disabled, dangling indices will not be automatically detected or imported and must be managed manually,
2023.01.12 06:37:06 INFO  es[][o.e.n.Node] initialized,
2023.01.12 06:37:06 INFO  es[][o.e.n.Node] starting ...,
2023.01.12 06:37:07 INFO  es[][o.e.t.TransportService] publish_address {127.0.0.1:34687}, bound_addresses {127.0.0.1:34687},
2023.01.12 06:37:07 INFO  es[][o.e.b.BootstrapChecks] explicitly enforcing bootstrap checks,
ERROR: [3] bootstrap checks failed. You must address the points described in the following [3] lines before starting Elasticsearch.,
bootstrap check failure [1] of [3]: max file descriptors [4096] for elasticsearch process is too low, increase to at least [65535],
bootstrap check failure [2] of [3]: max number of threads [3766] for user [sonarqube] is too low, increase to at least [4096],
bootstrap check failure [3] of [3]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144],
ERROR: Elasticsearch did not exit normally - check the logs at /opt/sonarqube/logs/sonarqube.log,
2023.01.12 06:37:08 INFO  es[][o.e.n.Node] stopping ...,
2023.01.12 06:37:08 INFO  es[][o.e.n.Node] stopped,
2023.01.12 06:37:08 INFO  es[][o.e.n.Node] closing ...,
2023.01.12 06:37:08 INFO  es[][o.e.n.Node] closed,
2023.01.12 06:37:08 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [es]: 78,
2023.01.12 06:37:08 INFO  app[][o.s.a.SchedulerImpl] Process[es] is stopped,
2023.01.12 06:37:08 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped,

**Software Versions**
 - SonarQube Version: 8.9 and 9.0
 - Plugin Version:1.8.2, 1.8.3 and 1.9.0

**Additional context**

**Comment by mc1arke** [comment]
CE is the compute engine, not Elastic Search. You need to be setting SONAR_SEARCH_JAVAOPTS https://docs.sonarqube.org/8.9/setup-and-upgrade/configure-and-operate-a-server/environment-variables/#elasticsearch

**Comment by AceCoderYoda** [comment]
Thanks, but why did it work before?
