### ISSUE TITLE
"Pull Request Decorator" option not showing in project general settings.

### ISSUE THREAD

**Issue by Cimihan123** [mc1arke/sonarqube-community-branch-plugin#723]
Hy. I have installed the plugin. But the "Pull Request Decorator"  is not showing in settings.

![image](https://user-images.githubusercontent.com/47425314/212027661-345047cd-295d-42f7-9881-8fee9e2906d3.png)

I am using.
Sonarqube Community EditionVersion 9.8 (build 63668)
and
sonarqube-community-branch-plugin-1.14.0.jar

Env variables that I set on Dokerfile.
![image](https://user-images.githubusercontent.com/47425314/212027984-44598b08-a841-4e7c-a697-2a467659c92b.png)

**Comment by mc1arke** [comment]
Your `SONAR_CE_JAVAADDITIONALOPTS` should end with `=ce` not `=web` otherwise the CE component (branch management and decoration) wont work. However, the issue you're reporting isn't actually a problem: the decorator settings have been moved to the `DevOps Platform Integration` tab/

**Comment by Cimihan123** [comment]
Ah, thank you. I was correct. Hope this helps others.
