### ISSUE TITLE
docker run is failing, Error opening zip file or JAR manifest missing

### ISSUE THREAD

**Issue by jcnk9** [mc1arke/sonarqube-community-branch-plugin#727]
Hi,

i would like to replace my standard sonarqube instance with this, but i can't run the provided image: "mc1arke/sonarqube-with-community-branch-plugin". I allways get the following error: 

> Error opening zip file or JAR manifest missing : ./extensions/plugins/sonarqube-community-branch-plugin-1.14.0.jar
> Error occurred during initialization of VM
> agent library failed to init: instrument

**To Reproduce**
`docker run -d --restart always     -p 9000:9000     -v /var/sonar/sonarqube_data:/opt/sonarqube/data     -v /var/sonar/sonarqube_extensions:/opt/sonarqube/extensions     -v /var/sonar/sonarqube_logs:/opt/sonarqube/logs     --net=network     --name sonar_server      mc1arke/sonarqube-with-community-branch-plugin:latest`

**Expected behavior**
Sonar starting without errors.

Version: mc1arke/sonarqube-with-community-branch-plugin:**_latest_** (SonarQube 9.8)

**Comment by kuhmuh** [comment]
Hi,
I run into the same issue and wondering why you closed this issue so fast.
What am I missing?

BR
Stefan

**Comment by jcnk9** [comment]
Hi Stefan, 

you can't mount the extension folder, then it overrides the .jar file in the container. So only start the COntainer without mounting the extension. Then it works like a charm.

Regards
Jan

**Comment by kuhmuh** [comment]
Thanks a lot. That was a push in the right direction. I used docker compose for orchestration and I missed that a colleague added – for what reason ever – a named volume for extensions.
Many thanks
Stefan
