### ISSUE TITLE
Compatibility with Sonarqube 8.1

### ISSUE THREAD

**Issue by ramaprakashganesan** [mc1arke/sonarqube-community-branch-plugin#73]
This plugin does not seem to work with Sonarqube 8.1 currently. Error is attached. 
Not sure where else to request for this, so creating this issue.
[scan error.txt](https://github.com/mc1arke/sonarqube-community-branch-plugin/files/4058741/scan.error.txt)

**Comment by mc1arke** [comment]
Duplicates #60 with a proposed fix in #58
