### ISSUE TITLE
sonarqube_1  | Error opening zip file or JAR manifest missing : ./extensions/plugins/sonarqube-community-branch-plugin-1.8.2.jar

### ISSUE THREAD

**Issue by agunduboina** [mc1arke/sonarqube-community-branch-plugin#733]
Hi ,

I'm using sonar Community EditionVersion 8.9.7 . I'm trying to configure sonarqube-community-branch-plugin-1.8.2 to run analysis for multiple branches . As followed the document I added below two lines in sonar.properties file and trying to restart but its not working and hitting below error .

vi sonar.properties 
sonar.web.javaAdditionalOpts=-javaagent:./sonar_docker_sonarqube_extensions/_data/plugins/sonarqube-community-branch-plugin-1.8.2.jar=web
sonar.ce.javaAdditionalOpts=-javaagent:./sonar_docker_sonarqube_extensions/_data/plugins/sonarqube-community-branch-plugin-1.8.2.jar=ce

Error : 
sonarqube_1  | Error opening zip file or JAR manifest missing : /sonar_docker_sonarqube_extensions/_data/plugins/sonarqube-community-branch-plugin-1.8.2.jar
sonarqube_1  | Error occurred during initialization of VM
sonarqube_1  | agent library failed to init: instrument

Can you please me to fix the issue ?

Regards,
Ashok G

**Comment by nixel2007** [comment]
Did you place jar in a folder?

**Comment by agunduboina** [comment]
Yes I placed a Jar and tried a restart

**Comment by brother** [comment]
the file name in config is not the same as in your file system. they need to match.

1.8.3 != 1.8.2

**Comment by agunduboina** [comment]
It's same version in the both the places. Its my typo mistake in above content.

I have tried 1.8.3 and also 1.8.2 both are having same issues

**Comment by mc1arke** [comment]
I suspect something is getting corrupted in your download then, as this works ok for me in local dev/testing of each release.

**Comment by agunduboina** [comment]
I downloaded fresh one and compared the size etc all are same .

sonarqube_1  | 2023.02.08 11:44:57 INFO  app[][o.s.a.ProcessLauncherImpl] Launch process[[key='web', ipcIndex=2, logFilenamePrefix=web]] from [/opt/sonarqube]: /opt/java/openjdk/bin/java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/opt/sonarqube/temp -XX:-OmitStackTraceInFastThrow --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED -Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError -javaagent:/var/lib/docker/volumes/sonar_docker_sonarqube_extensions/_data/plugins/sonarqube-community-branch-plugin-1.8.2.jar=web -Dhttp.nonProxyHosts=localhost|127.*|[::1] -cp ./lib/sonar-application-8.9.7.52159.jar:/opt/sonarqube/lib/jdbc/postgresql/postgresql-42.2.19.jar org.sonar.server.app.WebServer /opt/sonarqube/temp/sq-process8967848510953344886properties
sonarqube_1  | Error opening zip file or JAR manifest missing : /var/lib/docker/volumes/sonar_docker_sonarqube_extensions/_data/plugins/sonarqube-community-branch-plugin-1.8.2.jar
sonarqube_1  | Error occurred during initialization of VM
sonarqube_1  | agent library failed to init: instrument
sonarqube_1  | 2023.02.08 11:44:57 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [web]: 1
sonarqube_1  | 2023.02.08 11:44:57 INFO  app[][o.s.a.SchedulerImpl] Process[web] is stopped
sonarqube_1  | 2023.02.08 11:44:57 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [es]: 143
sonarqube_1  | 2023.02.08 11:44:57 INFO  app[][o.s.a.SchedulerImpl] Process[es] is stopped
sonarqube_1  | 2023.02.08 11:44:57 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
sonar_docker_sonarqube_1 exited with code 0

**Comment by agunduboina** [comment]
Can you please help to fix the issue .

**Comment by Xeyos88** [comment]
I have the same error.
` Error opening zip file or JAR manifest missing : ./extensions/_data/plugins/sonarqube-community-branch-plugin-1.8.2.jar`

**Comment by mc1arke** [comment]
There are 3 things that are likely to be potential causes for this:
1. The JAR file doesn't exist at the location you've specified in the agent arguments
2. The JAR file is invalid/corrupted
3. The user running the Sonarqube process file doesn't have permission to read the JAR

Unfortunately these are all things we can't really guide you on as they're all internal to the way you're running your sonarqube, and not an issue with the plugin.

**Comment by agunduboina** [comment]
Hi All,
My issue is resolved . I changed below in sonar.properties file .
From : 
	/var/lib/docker/volumes/sonar_docker_sonarqube_extensions/_data/plugins/sonarqube-community-branch-plugin-1.8.2.jar=web
        /var/lib/docker/volumes/sonar_docker_sonarqube_extensions/_data/plugins/sonarqube-community-branch-plugin-1.8.2.jar=ce 

To :
 	./extensions/plugins/sonarqube-community-branch-plugin-1.8.2.jar=web  
	./extensions/plugins/sonarqube-community-branch-plugin-1.8.2.jar=ce 

Thanks

**Comment by agunduboina** [comment]
Thanks for your support and help .
