### ISSUE TITLE
SonarQube 9.9 LTS: Current edition does not support branch feature

### ISSUE THREAD

**Issue by nils2504** [mc1arke/sonarqube-community-branch-plugin#736]
**Describe the bug**
Since upgrading to SonarQube 9.9 LTS I am facing following issue when using branch-scan:

> 2023.02.16 19:14:54 ERROR web[AYZba5qhf8FNoUUAAAC7][o.s.s.w.WebServiceEngine] Fail to process request http://localhost:9000/api/ce/submit?projectKey=transaction-service&characteristic=branch%3Dxxxx&characteristic=branchType%3DBRANCH
> java.lang.IllegalStateException: Current edition does not support branch feature

**Software Versions**
 - SonarQube Version: 9.9 LTS
 - Plugin Version: 1.14.0

**Comment by riyaz-ahmed-dev** [comment]
How did you resolve this issue

**Comment by dt233569** [comment]
Hi I am having same issue,
Since upgrading to SonarQube 9.9 LTS I am facing following issue when using branch-scan:

**Comment by dt233569** [comment]
@nils2504 how was the issue resolved for you

**Comment by mhagnumdw** [comment]
@nils2504 , how did you solve it?
