### ISSUE TITLE
Empty PR report with zero lines of code

### ISSUE THREAD

**Issue by patricknoffke** [mc1arke/sonarqube-community-branch-plugin#741]
I don't know how to reopen an issue, but this is the same as issue #489.  Here is my comment in that issue:

I have the same issue with pull requests in Azure DevOps.  The PR analysis shows zero coverage, no code, empty metrics (but coverage percentage after merge is non-zero).

23:54:59.196 DEBUG: SCM revision ID '5549cfa3fd7f298e7fd4ba3bf62b8f167f40d849'
23:54:59.276 INFO: SCM writing changed lines
23:54:59.295 DEBUG: Merge base sha1: 7afac00c44eb9ca8421312d2e1dce049b7e7cf95
23:54:59.302 DEBUG: SCM reported changed lines for 0 files in the branch
23:54:55.115 DEBUG: SCM reported 251 files changed in the branch

...

23:54:59.196 DEBUG: SCM revision ID '5549cfa3fd7f298e7fd4ba3bf62b8f167f40d849'
23:54:59.276 INFO: SCM writing changed lines
23:54:59.295 DEBUG: Merge base sha1: 7afac00c44eb9ca8421312d2e1dce049b7e7cf95
23:54:59.302 DEBUG: SCM reported changed lines for 0 files in the branch
23:54:59.302 INFO: SCM writing changed lines (done) | time=26ms

If I just analyze the branch directly, I get full coverage information and metrics.  Something about the PR integration seems to be causing this.

I don't have any messages about missing blame information.  Any suggestions on how to debug this further?

I am using SonarQube 8.9.9 Developer edition.

_Originally posted by @patricknoffke in https://github.com/mc1arke/sonarqube-community-branch-plugin/issues/489#issuecomment-1451075815_

**Comment by patricknoffke** [comment]
Sorry, this is probably the wrong place to report this, but I don't know how/where to report issues for Developer edition, and I'm hoping it's the same underlying issue.

**Comment by nixel2007** [comment]
Customer support or community.sonarsource.com
