### ISSUE TITLE
Execution ERROR "Expected: 200, Got: 403" on pullrequest.PullRequestPostAnalysisTask

### ISSUE THREAD

**Issue by h0rsth** [mc1arke/sonarqube-community-branch-plugin#751]
We are using Sonarqube 9.9LTS with Plugin Version 1.14.0.

Analysis and merge request decoration to GitLab works. But in the Log file we see an Error directly followed up by an successful request.

2023.03.27 **06:52:18** **ERROR** ce[AYch1r37afLgriM6uM42][o.s.c.t.p.a.p.PostProjectAnalysisTasksExecutor] Execution of task class com.github.mc1arke.sonarqube.plugin.ce.pullrequest.PullRequestPostAnalysisTask failed
java.lang.IllegalStateException: An unexpected response code was returned from the Gitlab API - **Expected: 200, Got: 403**
	at com.github.mc1arke.sonarqube.plugin.almclient.gitlab.GitlabRestClient.validateResponse(GitlabRestClient.java:233)
...
2023.03.27 **06:52:18** **INFO**  ce[xx][o.s.c.t.p.a.p.PostProjectAnalysisTasksExecutor] Pull Request Decoration | status=FAILED | time=846ms
2023.03.27 06:52:18 INFO  ce[xx][o.s.c.t.CeWorkerImpl] Executed task | project=xy | type=REPORT | pullRequest=3 | id=xx | submitter=xy | status=**SUCCESS** | time=2381ms

Is this just only a first attempt without authentication followed by a call with correct authentication.
So can we just ignore the error?

**Software Versions**
 - SonarQube Version: 9.9 (build 65466)
 - Plugin Version: 1.14.0

**Comment by mc1arke** [comment]
You've truncated the stack trace at a point that means I cant tell what the failure actually impacted, but I'd expect a `403` response to be consistent across requests and therefore a permanent failure.

**Comment by h0rsth** [comment]
Thanks for the answer. Here the complete stack trace. As mentioned the functionality "merge request decoration to GitLab" seems to work at the end. 

`2023.03.24 10:59:27 ERROR ce[AYcTRd3BafLgriM6uM4x][o.s.c.t.p.a.p.PostProjectAnalysisTasksExecutor] Execution of task class com.github.mc1arke.sonarqube.plugin.ce.pullrequest. │
│ java.lang.IllegalStateException: An unexpected response code was returned from the Gitlab API - Expected: 201, Got: 403                                                        │
│     at com.github.mc1arke.sonarqube.plugin.almclient.gitlab.GitlabRestClient.validateResponse(GitlabRestClient.java:233)                                                       │
│     at com.github.mc1arke.sonarqube.plugin.almclient.gitlab.GitlabRestClient.lambda$setMergeRequestPipelineStatus$4(GitlabRestClient.java:157)                                 │
│     at com.github.mc1arke.sonarqube.plugin.almclient.gitlab.GitlabRestClient.entity(GitlabRestClient.java:177)                                                                 │
│     at com.github.mc1arke.sonarqube.plugin.almclient.gitlab.GitlabRestClient.setMergeRequestPipelineStatus(GitlabRestClient.java:152)                                          │
│     at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.gitlab.GitlabMergeRequestDecorator.submitPipelineStatus(GitlabMergeRequestDecorator.java:133)                        │
│     at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.gitlab.GitlabMergeRequestDecorator.submitPipelineStatus(GitlabMergeRequestDecorator.java:50)                         │
│     at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.DiscussionAwarePullRequestDecorator.decorateQualityGateStatus(DiscussionAwarePullRequestDecorator.java:106)          │
│     at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.PullRequestPostAnalysisTask.finished(PullRequestPostAnalysisTask.java:138)                                           │
│     at org.sonar.ce.task.projectanalysis.api.posttask.PostProjectAnalysisTasksExecutor.executeTask(PostProjectAnalysisTasksExecutor.java:102)                                  │
│     at org.sonar.ce.task.projectanalysis.api.posttask.PostProjectAnalysisTasksExecutor.finished(PostProjectAnalysisTasksExecutor.java:93)                                      │
│     at org.sonar.ce.task.step.ComputationStepExecutor.executeListener(ComputationStepExecutor.java:89)                                                                         │
│     at org.sonar.ce.task.step.ComputationStepExecutor.execute(ComputationStepExecutor.java:61)                                                                                 │
│     at org.sonar.ce.task.projectanalysis.taskprocessor.ReportTaskProcessor.process(ReportTaskProcessor.java:75)                                                                │
│     at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.executeTask(CeWorkerImpl.java:212)                                                                                  │
│     at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.run(CeWorkerImpl.java:194)                                                                                          │
│     at org.sonar.ce.taskprocessor.CeWorkerImpl.findAndProcessTask(CeWorkerImpl.java:160)                                                                                       │
│     at org.sonar.ce.taskprocessor.CeWorkerImpl$TrackRunningState.get(CeWorkerImpl.java:135)                                                                                    │
│     at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:87)                                                                                                      │
│     at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:53)
`

**Comment by mc1arke** [comment]
That stacktrace is Sonarqube failing to report the pipeline to Gitlab. Are there other errors reported in the logs, or do you get successful summary and findings comments added to your Merge Requests by Sonarqube?

**Comment by h0rsth** [comment]
There is only this one error with each analysis, directly followed (same timestamp) by the successful call "PostProjectAnalysisTasksExecutor] Pull Request Decoration".
Based on the second successful call the results are also displayed correctly at the merge request. Further tests did not show any errors regarding the results.
So except for the respective exception in the log it works.
I just wanted to note that. Maybe there is a way to suppress this. Otherwise we could close the issue.

**Comment by johan-boule** [comment]
I have observed this error too recently.
In Gitlab, I notice that the comment containing the global analyses message is created, but not the messages for individual warnings.
I remember it used to work some months ago, and what has changed since is the Gitlab version. We are on Gitlab 16.1
