### ISSUE TITLE
Plugin not working with SonarQube 9.8 Community Version

### ISSUE THREAD

**Issue by shubhs248** [mc1arke/sonarqube-community-branch-plugin#763]
**Describe the bug**
For Branch/ PR analysis we installed plugin in sonarqube 9.8 but it is not working as expected, Giving 500 error when the plugin is installed in SonarQube and without the plugin when scan is ran it is working fine.

**To Reproduce**
Steps to reproduce the behavior: We installed Sonarqube 9.8 with just 1 Plugin which is Community Branch Plugin.

**Expected behavior**
As per Plugin description we expect plugin to work with Branch/ PR analysis.

**Software Versions**
 - SonarQube Version: 9.8
 - Plugin Version: 1.14

**Additional context**
Adding logs for reference which have errors.

Logs from Build >>>
Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.1.2184:sonar (default-cli) on project shoppingcart-shoppingcart-reactor: Failed to upload report: Error 500 on http://illin7811:30722/api/ce/submit?projectKey=com.amdocs.digital.ms.shoppingcart.shoppingcart%3Ashoppingcart-shoppingcart-reactor&projectName=com.amdocs.digital.ms.shoppingcart.shoppingcart%3Ashoppingcart-shoppingcart-reactor&characteristic=branch%3D2.387.1-jenkins&characteristic=branchType%3DBRANCH : {"errors":[{"msg":"An error has occurred. Please contact your administrator"}]} -> [Help 1]

Logs from SonarQube>>>
2023.04.12 10:26:30 ERROR web[AYd08sH/48fGQuTqAAC1][o.s.s.w.WebServiceEngine] Fail to process request http://illin7811:30722/api/ce/submit?projectKey=com.amdocs.digital.ms.shoppingcart.shoppingcart%3Ashoppingcart-shoppingcart-reactor&projectName=com.amdocs.digital.ms.shoppingcart.shoppingcart%3Ashoppingcart-shoppingcart-reactor&characteristic=branch%3D2.387.1-jenkins&characteristic=branchType%3DBRANCH
java.lang.IllegalStateException: Current edition does not support branch feature

**Comment by mc1arke** [comment]
You've not installed the plugin properly if you're getting that error. The guides explain how to install it, and a working example can be seen from the Docket file. This is *not* a plugin bug.

**Comment by shubhs248** [comment]
Hi @mc1arke,

We are trying to install with Helm Charts (I followed instruction wrt helm chart version < 6.1.0)

and in the YAML, following configuration was added wrt plugin:

plugins:
  install: []
  lib:
    - sonarqube-community-branch-plugin-1.12.0.jar
  jvmOpts: "-javaagent:/opt/sonarqube/lib/common/sonarqube-community-branch-plugin-1.12.0.jar=web"
  jvmCeOpts: "-javaagent:/opt/sonarqube/lib/common/sonarqube-community-branch-plugin-1.12.0.jar=ce"

permissions for the plugin on following path is also aligned, what could be the issue?

**Comment by martinack** [comment]
Hi @shubhs248 ,

it looks like you are trying to use plugin version 1.12.0 with sonarqube 9.8
Following the [Compatibility Matrix](https://github.com/mc1arke/sonarqube-community-branch-plugin#compatibility) you are supposed to use plugin version 1.14.0
