### ISSUE TITLE
Is `purging inactive branches` supposed to work?

### ISSUE THREAD

**Issue by scholz-afis** [mc1arke/sonarqube-community-branch-plugin#764]
My apologies, if I'm asking something completely unrelated to the *Community-Branch-Plugin* but *SonarSource*(https://sonarsource.atlassian.net/browse/SONAR-11439) indicates no issues with this topic since release 7.7 of *SonarQube*.

**Describe the bug**
The purging of inactive, not analyzed branches isn't triggered after the configured threshold even if some branches of that repository were recently analyzed. 

**To Reproduce**
* Use the default settings of `Number of days before purging inactive branches and pull requests` or change it to some other value, e.g. 31 days
* Leave branches within a repository inactive above the configured threshold
* Analyze another branch e.g. `main` in regular intervals.
* Check progress regarding purging inactive branches
* Inactive branches aren't purged.

**Expected behavior**
Purging of inactive, not analyzed branches after the configured threshold is reached.

**Screenshots**
![image](https://user-images.githubusercontent.com/95353437/234500004-0b9dea79-a932-48fb-bec0-914f3e317a53.png)
![image](https://user-images.githubusercontent.com/95353437/234501345-a632e957-4289-456b-91e1-d2a71b75e485.png)

**Software Versions**
 - SonarQube Version: 9.9.0.65466 (Community Edition)
 - Plugin Version: 1.14.0

**Additional context**
-/-

**Comment by brother** [comment]
Same as https://github.com/mc1arke/sonarqube-community-branch-plugin/issues/757 ?

**Comment by scholz-afis** [comment]
> Same as #757 ?

Exactly same as #757. Explicitly setting a value e.g. "31" helped. Thanks.
