### ISSUE TITLE
[Question] GitHub PR annotation

### ISSUE THREAD

**Issue by OneCyrus** [mc1arke/sonarqube-community-branch-plugin#765]
This is just a question to understand the feature scope. On Azure DevOps we have PR annotation with SonarQube and this plugin. All detected issue are annotated right in the code. On GitHub we only have the comment with the stats on the PR.

Is it possible to annotate on GItHub like on Azure DevOps with SonarQube 9.9/10.x and this plugin? Or is this something which isn't supported/implemented on GitHub?

**Comment by mc1arke** [comment]
Github is supported by the plugin. Is it Github.com, or Github enterprise (and in which case which version) you're using?

**Comment by OneCyrus** [comment]
it's with github.com (enterprise cloud)

**Comment by OneCyrus** [comment]
any idea, @mc1arke? has anyone a screenshot how this would look on github? strangely I couldn't find any screenshot anywhere how this would look like.

**Comment by mc1arke** [comment]
Yes, the plugin support Github decoration. The following are screenshots of one of the repositories I use for release testing. My test instance isn't online hence the images failing to load in the summary message

![image](https://github.com/mc1arke/sonarqube-community-branch-plugin/assets/1250331/bc37cde7-c155-409d-a3d9-4a00873787df)
![image](https://github.com/mc1arke/sonarqube-community-branch-plugin/assets/1250331/8b5a203f-57b1-40dc-a469-6e7186db20df)
