### ISSUE TITLE
New project with pull requests causes UI to error.

### ISSUE THREAD

**Issue by mattseaborn** [mc1arke/sonarqube-community-branch-plugin#770]
**Describe the bug**

When creating a new project in SonarQube using the Sonar Scanner, if this includes any pull requests then the project will be inaccessible in the Sonar UI because the call to project_pull_requests errors.

The project has to be first created with just a branches, and pull requests added afterwards for it to work.

**To Reproduce**

1. Using Sonar Scanner, scan pull request and branches for a new project.
2. Using the SonarQube UI to attempt to view the project
3. The request to /api/project_pull_requests/list?project=XXXX will error

**Expected behavior**
It should be possible to create a new project with branches ad pull requests

**Software Versions**
 - SonarQube Version: 9.8 (build 63668)
 - Plugin Version: 1.14.0

**Comment by mc1arke** [comment]
It wouldn't be valid to create a project as a result of someone submitting a pull request analysis since the pull request needs a base branch to scan against. The initial branch that's scanned should also be the 'main' branch rather than just any ad-hoc branch. I suspect there needs to be some validation added to the plugin to prevent both the cases you've mentioned, but neither are something the plugin could actively support.

**Comment by hballangan-mdsol** [comment]
@mc1arke this also poses a problem in our code analysis CI/CD pipeline since the other users doesn't have access to sonarqube administration for some settings. Is there a way to do the analysis against the main if it detects that it's a new project?

**Comment by hballangan-mdsol** [comment]
Or I hope there's at least a way to remove autoconfiguration on github by setting a flag or something for first scan PRs.

**Comment by hballangan-mdsol** [comment]
Confirmed by manually setting in github CI that it is working: 
`-Dsonar.branch.name='' `

This means that there must be a bug somewhere in the validation which is restrictive but in truth should allow this instance.

**Comment by mc1arke** [comment]
@hballangan-mdsol You're mentioning Sonarqube 8 here which treated branches very differently from Sonarqube 9 and 10. Submitting a PR/MR analysis requires the target branch to already have been scanned to provide the baseline analysis. The scenario you're attempting of submitting a new project as part of a PR/MR doesn't make sense given the way Sonarqube works. Yes, the plugin should probably throw an exception during submission at that point, but there's no way it could give you a valid scan result
