### ISSUE TITLE
Branch analysis issues

### ISSUE THREAD

**Issue by jenistenxavier** [mc1arke/sonarqube-community-branch-plugin#772]
**Describe the bug**
Branch analysis showed issues with code smells before and after analysis on the feature branch and on the default branch on three different scenarios

Scenario - 1
On plugin version 1.14.0 running on sonar server - 9.8 (build 63668)
      Analysis of the PR showed zero issues
      After merging with base branch and analysing again, it showed 6 issues that were unreported in PR analysis

Scenario - 2 
On plugin version 1.10.0 running on sonar server - 9.3.0.51899
        PR analysis resulted in 3 'new issues' being reported. But all 3 are issues from old code.
        After merging the PR, the master branch analysis doesn't report any new issues

Scenario - 3 
On plugin version 1.10.0 running on sonar server - 9.3.0.51899
        Pull Request analysis showed 4 code smells on new code. 
        After merging and running analysis on master branch, the four old issues disappeared and new issues are reported as new issues.
        This shows the two issues we have to deal with:
        1. It will sometimes report old issues as new issues in PR analysis. Merging the PR will make them disappear and master branch analysis will not show any of those issues.
        2. It will sometimes report no issues in PR analysis, but show few brand new issues after merging PR with master branch and doing master branch analysis.

**To Reproduce**
1. Ran analysis on feature branch
2. Merged to the default branch
3. Ran analysis on the default branch
4. Compared the analysis results 
5. Upgraded the server version and the branch analysis plugin 
6. Repeated steps 1 to 4 again. 

**Expected behavior**
- Expecting the plugin to show up analysis results for the corresponding branch.

**Screenshots**
Scenario 1 - https://prnt.sc/WRQmOaGpr06E and https://prnt.sc/Z3X2XERrkHtH
Scenario 2 - https://prnt.sc/MTfgK0NbWhQj
Scenario 3 - https://prnt.sc/Y3HGhzApqs2Q

**Software Versions**
 - SonarQube Version: 9.8 (build 63668)
 - Plugin Version: 1.14.0 
 and 
 - SonarQube Version: 9.3 (build 51899)
 - Plugin Version: 1.10.0

**Additional context**
I observed that the older version (1.10.0) of the plugin had the issues. So I tried to upgrade the plugin to 1.14.0 and the SonarQube version to 9.8 and experienced the same issue.

**Comment by akovacspentalog** [comment]
I have observed the same issue.

**Comment by NathanAlcantara** [comment]
We are facing the same problem, the PR show no issue but when merge show some issues in the same code.
This happens with some specific rules, such as [RSPEC-1820](https://rules.sonarsource.com/java/RSPEC-1820)

We though that updating the versions would resolve, but appears not...

I don't know why this happens yet, probably we'll take a look into the code to discover something and send a PR. :man_technologist: 

**Software Versions**

- SonarQube Version: 8.9.10 (build 61524)
- Plugin Version: 1.8.2

**Comment by mc1arke** [comment]
Can someone who is encountering this provide a link to a public repo with commits that will demonstrate this please, or create a minimal repository where they can replicate the issue?

I suspect what's being encountered is an unfortunate part of the way Sonarqube works with Pull Requests: it reports issues against the first occurance of a violation for the likes of RSPEC-1820, so although the class now has a violation it's not on one of the lines changed in the commit, so the changed lines in the Pull Request are clean, but the subsequent full-project scan isn't.

**Comment by mc1arke** [comment]
Closing as unable to replicate
