### ISSUE TITLE
Feature Request - Support arm64

### ISSUE THREAD

**Issue by delrey1** [mc1arke/sonarqube-community-branch-plugin#773]
When publishing the Docker images, please could the platform also include linux/arm64

https://docs.docker.com/build/building/multi-platform/

Love the plugin, thank you for this project

**Comment by marcelstoer** [comment]
The `sonarqube` base image used by both `release.Dockerfile` and `Dockerfile` is already multi-platform supporting Arm. Hence, all that is required is running the Docker build using Buildx and an QEMU container for Arm.

Are the images created and pushed to Docker Hub manually in this project?

**Comment by mc1arke** [comment]
v1.15.0 pushed to dockerhub with ARM and AMD targets. I'll look to create a HCL file to make future buildx execution easier/repeatable
