### ISSUE TITLE
Sonarqube 9.7.1 On one of the environments, the plugin is not functioning.

### ISSUE THREAD

**Issue by nicolaizav93** [mc1arke/sonarqube-community-branch-plugin#774]
Hello Community !
 I have a problem with SonarQube 9.7.1 and the community-branch-plugin version 1.13.0. I have three environments: PROD, UAT, and DEV. The configurations are the same across all environments, but the plugin doesn't work on DEV. The test passes (the test is performed on Jenkins), but the dropdown in the SonarQube project doesn't work (it only shows the master branch), while on UAT and PROD, there is the option to view other branches (master/test_branch).

**To Reproduce**
1) Navigate to the project, in my case JMT.
2) Click on the branch next to the project name.
3) Switch the branch from master to another one (test_branch).
4) Error: Unable to switch to another branch.

**Expected behavior**
Expected behavior: The dropdown should be functional, allowing the selection of at least two different branches.

**Screenshots**
 
![uat environment](https://github.com/mc1arke/sonarqube-community-branch-plugin/assets/126586337/9e64c325-38a5-42a1-b39a-6742eabc2989)

![dev environment](https://github.com/mc1arke/sonarqube-community-branch-plugin/assets/126586337/5e6db7b5-53fe-460d-b8e5-15eab94e50d0)

**Software Versions**
 - SonarQube Version: Community EditionVersion 9.7.1 (build 62043)
 - Plugin Version: sonarqube-community-branch-plugin-1.13.0

**Additional context**
An attempt was made to test it on SonarQube versions 10.0 and 9.9.0 using the plugin version sonarqube-community-branch-plugin-1.14.0, but the result was the same. The plugin was installed strictly following the documentation provided in your instructions.
No warnings or errors related to the plugin were found in the sonar.log/web.log.

**Comment by Appelpitje** [comment]
Same issue here with **sonarqube Version 9.7.1 (build 62043)** and **plugin version 1.13.0**

While in the administration section we can see the plugin is installed:
Community Branch Plugin 1.13.0 installed

Server logs:

INFO web[][o.s.s.p.ServerPluginManager] Deploy Community Branch Plugin / 1.13.0 / null
...

java.lang.IllegalStateException: Current edition does not support branch feature at com.google.common.base.Preconditions.checkState(Preconditions.java:502) at org.sonar.server.ce.queue.BranchSupport.createComponentKey(BranchSupport.java:52) at org.sonar.server.ce.queue.ReportSubmitter.submit(ReportSubmitter.java:81) at org.sonar.server.ce.ws.SubmitAction.handle(SubmitAction.java:100) at org.sonar.server.ws.WebServiceEngine.execute(WebServiceEngine.java:111) at org.sonar.server.platform.web.WebServiceFilter.doFilter(WebServiceFilter.java:84) at org.sonar.server.platform.web.MasterServletFilter$GodFilterChain.doFilter(MasterServletFilter.java:139) at org.sonar.server.platform.web.SonarLintConnectionFilter.doFilter(SonarLintConnectionFilter.java:66) at org.sonar.server.platform.web.MasterServletFilter$GodFilterChain.doFilter(MasterServletFilter.java:139) at org.sonar.server.platform.web.MasterServletFilter.doFilter(MasterServletFilter.java:108) at jdk.internal.reflect.GeneratedMethodAccessor21.invoke(Unknown Source) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:566) at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:280) at java.base/java.security.AccessController.doPrivileged(Native Method) at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:550) at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:311) at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:187) at org.apache.catalina.core.ApplicationFilterChain.lambda$doFilter$0(ApplicationFilterChain.java:145) at java.base/java.security.AccessController.doPrivileged(Native Method) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:143)
...

**Comment by nicolaizav93** [comment]
I was able to fix it with the help of the developer's response (mc1arke):
https://github.com/mc1arke/sonarqube-community-branch-plugin/issues/523
... so you'll need to manually specify the sonar.branch or sonar.pullrequest parameters. ...
Now the line with -Dsonar.branch.name looks like this:
"-Dsonar.branch.name=${params.Branch}"
instead of:
"-Dsonar.branch.name=test_branch"
Thank you, mc1arke!
