### ISSUE TITLE
[Gitlab] Some codesmell have not been commented on in PR/MR

### ISSUE THREAD

**Issue by lzw5399** [mc1arke/sonarqube-community-branch-plugin#776]
# Veriosn Info
- Sonarqube version: 9.8-community
- sonarqube-community-branch-plugin: 1.14.0
- Git Registry: Gitlab Self-Hosted Community Edition 13.6.1

# Problem
As shown in the figure below. The quality gate returned 3 comments, but only 1 comment(To avoid confusion, deleting all old comments, then triggered the pipeline job of MR again, so only 2 comments)
![image](https://github.com/mc1arke/sonarqube-community-branch-plugin/assets/45249999/82d76a03-a748-436f-8572-07cf41336adf)

In the Sonarqube, I can saw the 3 codesmells
![image](https://github.com/mc1arke/sonarqube-community-branch-plugin/assets/45249999/0225d03e-fe8b-40e0-8c7a-c6b6d34fb353)

# Other Info
- use `golangci-lint` as golang's lint

This situation is not reproducible, it makes me very confused. Thanks for you job!

**Comment by boomaker** [comment]
I think I'm having the same issue.

May be related to Gitlab 16.0 update. May I ask what version of GitLab you use @lzw5399?

Example of a MR thread:
![image](https://github.com/mc1arke/sonarqube-community-branch-plugin/assets/1837884/0a9741be-d47c-4281-8d4a-4b7a20649ca2)
I reproduce the same issue with several projects & I have no errors in SonarQube logs.

**Comment by lzw5399** [comment]
> I think I'm having the same issue.
> 
> May be related to Gitlab 16.0 update. May I ask what version of GitLab you use @lzw5399?
> 
> Example of a MR thread: ![image](https://user-images.githubusercontent.com/1837884/243707434-0a9741be-d47c-4281-8d4a-4b7a20649ca2.png) I reproduce the same issue with several projects & I have no errors in SonarQube logs.

GitLab Community Edition [13.6.1](https://gitlab.com/gitlab-org/gitlab-foss/-/tags/v13.6.1)

![image](https://github.com/mc1arke/sonarqube-community-branch-plugin/assets/45249999/ade5f83b-70f7-49a5-9fe6-a6f150871d12)

**Comment by Zhuangkh** [comment]
HI @boomaker, I also use Gitlab 16.0. Does Sonarqube resend comment every time a CI is rerun with a new activity (branch code update) ? I have found that only the first CI when I created MR will now send a comment, none of the following, I wonder if I'm the only one with this problem?

**Comment by mc1arke** [comment]
I suspect you're hitting the issue that the Gitlab API is only accepting comments on lines that are included in the diff, so findings that are introduced in your change but on lines outside the diff (e.g. the first use of a repeated string, unused imports etc) are not accepted as comments by Gitlab. I've not investigated whether there's a way to force these comments to appear, but the API call we're making is valid, so I'm going to close this as 'not planned' for now
