### ISSUE TITLE
How to publish GitHub commit checks for Branch analysis (PR decoration works fine)?

### ISSUE THREAD

**Issue by gjabouley-invn** [mc1arke/sonarqube-community-branch-plugin#777]
**Describe the bug**
Configure ALM integration for GitHub so that commit checks are also published for branches (not only in Pull Requests)

**To Reproduce**
Created GitHub app following [those ](https://docs.sonarqube.org/latest/devops-platform-integration/github-integration/#importing-your-github-repositories-to-sonarqube) guidelines for permissions
Execute SQ analysis on a PR: Decoration works fine and commit checks are available
Execute SQ analysis on a branch: no commit check is published

**Expected behavior**
For each commit in master branch (for example), see a SonarQube commit check

**Screenshots**
PR analysis:
![image](https://github.com/mc1arke/sonarqube-community-branch-plugin/assets/47566129/b48ef7ea-0c2f-42e4-903f-f45ca45f9eab)

Branch analysis:
![image](https://github.com/mc1arke/sonarqube-community-branch-plugin/assets/47566129/8a2f97cb-5044-4f79-b7a2-a54aad38eae7)

**Software Versions**
 - SonarQube Version: 9.8 (build 63668)
 - Plugin Version: 1.14.0

**Additional context**
In log, we see following line during branch analysis:
```
2023.06.13 09:33:53 INFO  ce[AYi0Greg14Gia4nOmS_V][o.s.c.t.p.a.p.PostProjectAnalysisTasksExecutor] Pull Request Decoration | status=SUCCESS | time=0ms
```

**Comment by gjabouley-invn** [comment]
Hello, just for clarification, is it expected or not to have the commit checks published also for Branch analysis (not PR) ?

**Comment by mc1arke** [comment]
The plugin doesn't perform decoration of branches, only Pull Requests. It will scan branches, but it will be up to your CI tool to report the result against the branch/commit rather than having Sonarqube attempting to decorate the commit

**Comment by gjabouley-invn** [comment]
Hello @mc1arke , thanks for your clarification.

I can see that Developer edition actually publishes the SonarQube commit status also on branch analysis (as it is just a matter of commit).

Could this be handled as an enhancement request (instead of a bug)?
I could have a look and try to implement the behavior, if you are able to provide some guidance...
