### ISSUE TITLE
Last Analysis Date was not updated on Sonar7.9.2

### ISSUE THREAD

**Issue by patown** [mc1arke/sonarqube-community-branch-plugin#78]
**Describe the bug**
mvn sonar:sonar -Dsonar.branch.name to run an anayalis and it was successfully executed and the result was pushed to a Sonar7.9.2 server.
But on this server, the project's status was not updated on SonarQube's dashboard. 

**To Reproduce**
1. mvn sonar:sonar -Dsonar.branch.name, nothing updated on SonarQube's dashboard.
2. mvn sonar:sonar, and the project's status was updated  on SonarQube's dashboard.

**Software Versions**
 - SonarQube Version: 7.9.2
 - Plugin Version: 1.2.0

**Comment by mc1arke** [comment]
Could you share some screenshots, or more detailed steps as to there you're clicking to view the status? 'SonarQube dashboard' could refer to a number of screens within SonarQube, so it's difficult to try and triage your issue.

**Comment by mc1arke** [comment]
Closing this since it's not clear enough to replicate. Please re-open if you have further information that will help replicate it.

**Comment by djlindstr** [comment]
I have run into the same issue. "Dashboard" refers to the start page in SonarQube (at least for me). URL ends with `/projects?sort=-analysis_date`. The "Last analysis" date refers to when the master branch was analysed. After running analysis for a different branch I expect to find a new timestamp but "Last analysis" is not updated.

![sonar-analysis](https://user-images.githubusercontent.com/14195255/77759630-53385600-7035-11ea-901d-1b9ce9d4a975.png)

As I don't have the Developer Edition I cannot say how that behaves. But of course, if I did I wouldn't be trying out this plugin. :)

**Comment by jamesjallorina** [comment]
Is there any update on this? I have run into the same issue. Thanks!
