### ISSUE TITLE
Does not work with sonar 10.0.0 community edition 

### ISSUE THREAD

**Issue by nkatarmal** [mc1arke/sonarqube-community-branch-plugin#781]
**Describe the bug**
Using this plugin with sonarqube version 10.0.0 community edition causes sonarqube UI to hang on the loading screen. 

**To Reproduce**
Upgrade the sonarqube to version 10.0.0 community and try to login via web ui.

**Expected behavior**
It should be able to load the web ui page without being stuck on login screen.

**Screenshots**

**Software Versions**
 - SonarQube Version: 10.0.0-community dockerhub image
 - Plugin Version: 1.14.0

**Comment by brother** [comment]
Did you try the snapshot build or the 1.14.0 version?

https://github.com/mc1arke/sonarqube-community-branch-plugin/pull/754

find direct links here: https://github.com/mc1arke/sonarqube-community-branch-plugin/pull/754#issuecomment-1534290586

**Comment by AndreasMurk** [comment]
Snapshot works for me, thanks!

**Comment by mc1arke** [comment]
10.0 support released as 1.15.0
