### ISSUE TITLE
branches are not purged

### ISSUE THREAD

**Issue by TorstenKruse** [mc1arke/sonarqube-community-branch-plugin#783]
We recently discovered that the configured purge of stale branches does not work.
Key: sonar.dbcleaner.daysBeforeDeletingInactiveBranchesAndPRs is set to 30 (default), but in our projects are branchs over 1 year old which don't get purged.

Example from /api/project_branches/list

{
      "name": "ABC-4623_-_ECON-Code",
      "isMain": false,
      "type": "BRANCH",
      "status": {
        "qualityGateStatus": "OK"
      },
      "analysisDate": "2022-02-17T12:14:52+0100",
      "excludedFromPurge": false
    },
    {
      "name": "k3-revision-revert",
      "isMain": false,
      "type": "BRANCH",
      "status": {
        "qualityGateStatus": "OK"
      },
      "analysisDate": "2020-05-28T03:07:34+0200",
      "excludedFromPurge": false
    },

**Expected behavior**
This old branches should no longer exist in SQ.

**Software Versions**
 - SonarQube Version: 8.9 LTS
 - Plugin Version: 1.8.0

**Comment by rwalravens** [comment]
Did you try the solution suggested in #549?

**Comment by TorstenKruse** [comment]
Thanks for this hint. Setting Key: sonar.dbcleaner.daysBeforeDeletingInactiveBranchesAndPRs to 31 days solved the problem.
