### ISSUE TITLE
Version 1.12.0 does not work with sonar 9.3.0 community edition

### ISSUE THREAD

**Issue by fourirakbar** [mc1arke/sonarqube-community-branch-plugin#784]
**Describe the bug**
I using SonarQube version 9.3.0-community and deploying it on GKE using the chart from https://sonarsource.github.io/helm-chart-sonarqube. And I installing this plugin version 1.12.

**To Reproduce**
1. Deploy sonarqube using this helm chart https://sonarsource.github.io/helm-chart-sonarqube with version 9.3.0-community
2. Add plugins.install "https://github.com/mc1arke/sonarqube-community-branch-plugin/releases/download/1.12.0/sonarqube-community-branch-plugin-1.12.0.jar"
3. Whenever I run, I got this error
`==> web.log <==
2023.07.03 10:13:43 ERROR web[AYkbPkRbkkEVdTXfAAAQ][o.s.s.w.WebServiceEngine] Fail to process request http://mysonarurl/api/ce/submit?projectKey=myprojectkey%3Amyprojectname&projectName=3Amyprojectname&characteristic=pullRequest%3D104
java.lang.IllegalStateException: Current edition does not support branch feature`

**Expected behavior**

**Screenshots**
It should be able to run this plugin in sonarqube version 9.3.0-community. but its not working
![image](https://github.com/mc1arke/sonarqube-community-branch-plugin/assets/16026826/15f0ab72-6652-4a36-bd01-ca9a799f7c28)

**Software Versions**
 - SonarQube Version: 9.3.0.51899
 - Plugin Version: 1.12.0

**Comment by fourirakbar** [comment]
hi, sorry just wanna follow up abut this issue .. is there any update on this?

**Comment by mc1arke** [comment]
From the install instructions you've listed, you've missed setting the required Java Agent arguments on the Java Options: https://github.com/mc1arke/sonarqube-community-branch-plugin/tree/1.12.0?tab=readme-ov-file#manual-install
