### ISSUE TITLE
[Question] Possibility to not post comment in Gitlab PR in case quality gate passed?

### ISSUE THREAD

**Issue by artyom-veselov** [mc1arke/sonarqube-community-branch-plugin#787]
### Problem:
In our workflow we use auto-merge feature once Gitlab PR pipeline passed and is green.
Now it's not possible: even all the pipelines steps are green, Sonarqube and plugin post comment/thread in Gitlab. Until this Sonarqube's thread is resolved (we use rule in Gitlab to not allow merging PRs with unresolved threads), PR cannot be merged

### Question
Is there any possibility to disable posting Sonarqube comments in Gitlab if quality gate is passed and no new issues were discovered?

Thanks!

**Comment by marcelstoer** [comment]
That would be useful to have but the devil is in the details.

> if quality gate is passed and no new issues were discovered

Those are two different statements. The quality gate may pass even if new code smells were detected. Hence, the rule(s) when to skip posting MR/PR comments may quickly get complicated.

**Comment by alexintech** [comment]
If Quality Gate is `passed` the plugin should automatically resolve a Summary Note (Analysis Details) after creating a thread. 

Does it resolve a thread itself? Or even with autoresolve it prevents auto merging? Or do you have any errors in SonarQube while MR decoration?

**Comment by Eugeny** [comment]
Same problem, it doesn't autoresolve the new thread it creates. No errors in SQ logs either.

**Comment by Eugeny** [comment]
@alexintech thanks, I'd love to try it but is there a way to set a separate Gitlab token for each SQ project? Otherwise if I just swap out the global token SQ will lose access to other projects.

**Comment by alexintech** [comment]
@Eugeny I think you can try create another Gitlab Configuration at Administration -> DevOps Platform Integration. And set that new configuration in Project Settings of SQ project. 

I've not tried that 😄

**Comment by mc1arke** [comment]
> Does it resolve a thread itself? 

Yes!

> is there a way to set a separate Gitlab token for each SQ project
Yes, as suggested you can just create a second Gitlab integration with your alternative token, and setup and projects to use that ingegration.
