### ISSUE TITLE
Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.1.2184:sonar (default-cli) on project.

### ISSUE THREAD

**Issue by Rajula77** [mc1arke/sonarqube-community-branch-plugin#788]
**Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.1.2184:sonar (default-cli) on project xxx. Error creating bean with name 'org.sonarsource.sc
anner.api.internal.IsolatedClassloader@4690079a-org.sonar.scanner.bootstrap.ScannerPluginRepository': Initialization of bean failed; nested exception is java.lang.IllegalStateException: Fail t
o download plugin [scmcvs]**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Software Versions**
 - SonarQube Version: [9.9 LTS]
 - Plugin Version: [e.g. 3.9.1.2184]

**I am getting above when we are trying to test our code. I am using 9.9 LTS version with community edition. Please provide us the resolution for this error.**

**Comment by mc1arke** [comment]
Closing due to lack of detail to allow replication. The issue appears to be with other plugins in the Sonarqube server.
