### ISSUE TITLE
Scans cause Kubernetes Sonarqube Pod to Crash

### ISSUE THREAD

**Issue by CUCraigT** [mc1arke/sonarqube-community-branch-plugin#79]
**Describe the bug**
After installing the plugin (1.2) and restarting the server, my Kubernetes (Azure Kubernetes Service) pod crashes/is evicted every time I try to run a scan. Without the plugin, it works fine.

**To Reproduce**
1. Commit code to DEV
2. This kicks off my Azure DevOps build pipeline
3. An MS Build happens
4. Sonarqube is called
5. Container is evicted

**Expected behavior**
Scan works for DEV branch

**Screenshots**
N/A

**Software Versions**
 - SonarQube Version: 7.9.2 (build 30863)
 - Plugin Version: 1.2.0

**Additional context**
Are there extreme memory requirements for using this plugin? Currently I have a limit of 2.5 GB for my Sonarqube pod, which is fine without the plugin.

**Comment by CUCraigT** [comment]
Looks like issue system-wide for me, even after uninstalling the plugin; closing issue to troubleshoot more on my end.

**Comment by BobbyJohansen** [comment]
@CUCraigT can you explain how you installed the plugin on kube?
