### ISSUE TITLE
[Gitlab] Edit Summary Note instead of creating a new one every time

### ISSUE THREAD

**Issue by alexintech** [mc1arke/sonarqube-community-branch-plugin#790]
**Problem**
When we rerun a pipeline the plugin resolves old summary note and creates a new one, even if nothing changed and no new issue found. That clutters MR notes.

**What I'd like to see**
I suppose that editing existing Summary Note (even if it had been resolved earlier) will produce fewer mess.

**Comment by j-martin** [comment]
@alexintech I see you got your own fork with this feature implemented. How close were you to opening a PR against the main repo? We'd love to have this feature on our sonarqube instance.

**Comment by alexintech** [comment]
> @alexintech I see you got your own fork with this feature implemented. How close were you to opening a PR against the main repo? We'd love to have this feature on our sonarqube instance.

@j-martin PR has been closed by maintainer.  More information you can find [here](https://github.com/mc1arke/sonarqube-community-branch-plugin/pull/791)

**Comment by mc1arke** [comment]
I've raised #997 with an alternative approach which deleted comments with no follow-on threads, rather than editing in-place comments
