### ISSUE TITLE
Update Docker file ?

### ISSUE THREAD

**Issue by MarkEskander** [mc1arke/sonarqube-community-branch-plugin#794]
Hello, 
Any chance for updating image (with sonar 10.1) on dockerhub ?

**Comment by andersonstraube** [comment]
I have the same question, the last stable release was in December last year.

**Comment by LukasKlepper** [comment]
Would also be interested in to have the latest version.

**Comment by Numichi** [comment]
@mc1arke 
End of further updates?

**Comment by mc1arke** [comment]
10.1 is now on Dockerhub
