### ISSUE TITLE
troubles with release 1.12.0 and SonarQube 9.4.0

### ISSUE THREAD

**Issue by KasperHendrix** [mc1arke/sonarqube-community-branch-plugin#798]
**Describe the bug**
When I try to restart my pod, it's crash logging this:
`java.lang.IllegalStateException: Unable to read plugin manifest from jar : /opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin-1.12.0.jar`

**To Reproduce**
1. configure an initContainer inside my sonarqube deployment to download the release using wget
2. mount this as volume into main container
3. mount sonar.properties file as configMap with `sonar.web.javaAdditionalOpts=-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.12.0.jar=web` and `sonar.ce.javaAdditionalOpts=-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.12.0.jar=ce` edited
4. scaled up my deployment to start pod
5. after initContainer, main sonarqube container failed. The logs are: CrashLoopBackOff --> caused by: 
`org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jdk.internal.loader.ClassLoaders$AppClassLoader@277050dc-org.sonar.server.plugins.ServerPluginManager': Initialization of bean failed; nested exception is java.lang.IllegalStateException: Unable to read plugin manifest`
`...`
`...`
`...`
`Caused by: java.lang.IllegalStateException: Unable to read plugin manifest from jar : /opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin-1.12.0.jar`
`...`
`...`
`...`
`Caused by: java.util.zip.ZipException: zip END header not found`

**Expected behavior**
initContainer started for download the jar --> OK
sonarqube pod started with installed plugin --> KO

**Software Versions**
 - SonarQube Version: 9.4.0 (build 54424)
 - Plugin Version: 1.12.0

**Additional context**
I've tried to unzip the downloaded file and it's seems not corrupted, so I've checked the md5sum and sha. I've tried also to rollback all of my steps and download .jar directly inside the pod. After that, I've tried a `java -jar sonarqube-community-branch-plugin-1.12.0.jar` but the output was `no main manifest attribute, in sonarqube-community-branch-plugin-1.12.0.jar`

I've tried to find something usefull inside issues section but no one answer was helpfully. Is there a way to resolve this issue? Thanks!

**Comment by devilmind81** [comment]
Hi,
same issue for me, pls help!

**Comment by mc1arke** [comment]
Have you confirmed the file is being downloaded to the correct path and has the right owner/group for Sonarqube to access it?

**Comment by KasperHendrix** [comment]
> Have you confirmed the file is being downloaded to the correct path and has the right owner/group for Sonarqube to access it?

Can you confirm what's the correct path and open/grp please?
