### ISSUE TITLE
After installing the plugin in the container running Docker Sonarqube 10.1, an error occurs.

### ISSUE THREAD

**Issue by zhangye-maker** [mc1arke/sonarqube-community-branch-plugin#799]
**Describe the bug**
 First, I installed the latest community version of Sonarqube using Docker. Then, I downloaded the branch plugin and followed the tutorial to configure the sonar.properties file. After restarting the container, I encountered an error.

**Screenshots**
![image](https://github.com/mc1arke/sonarqube-community-branch-plugin/assets/61940076/35d8e536-c728-4d47-a5b8-4311b6e35508)
![image](https://github.com/mc1arke/sonarqube-community-branch-plugin/assets/61940076/6eb49b81-91e9-4259-ab1c-6df7391ff48a)

**Software Versions**
 - SonarQube Version: 1.10  docker
 - Plugin Version: 1.14.0

**Comment by zhangye-maker** [comment]
another screenshoot，  please help me resolve, thanks
![image](https://github.com/mc1arke/sonarqube-community-branch-plugin/assets/61940076/61225c2f-a3a1-4ab0-ae1f-65be2a393417)

**Comment by markoftw** [comment]
Plugin version 1.14.0 is not compatible with Sonar 10.1

See https://github.com/mc1arke/sonarqube-community-branch-plugin/pull/786

**Comment by zhangye-maker** [comment]
Thank you for your answer. I hope  can merge earlier. I really need it

**Comment by zhangye-maker** [comment]
@Adjunior Thank you for your answer  👍 https://github.com/mc1arke/sonarqube-community-branch-plugin/issues/782#issuecomment-1675217235
@bluebu   and thank you

Also, please keep in mind that it's important to exercise caution when modifying permissions and ensure that you have the necessary privileges and backups before proceeding:
1.Open the plugin directory.
2.Locate the 1.14.0 version plugin and delete it.
3.Set the permissions of the 1.15.0 version plugin to 777 (read, write, and execute for all users).

It's working for me!
