### ISSUE TITLE
Serve PR decoration images as static resources

### ISSUE THREAD

**Issue by don-vip** [mc1arke/sonarqube-community-branch-plugin#80]
**Describe the bug**
In order to display the PR decoration icons in the notifications created by the plugin, it is currently necessary to either have Internet access to https://raw.githubusercontent.com/mc1arke/sonarqube-community-branch-plugin/master/src/main/resources/pr-decoration-images or to host the images on a private web server and configure the `com.github.mc1arke.sonarqube.plugin.branch.image-url-base` property.

**Expected behavior**
All of this should not be necessary. SonarQube allows plugin to [serve static resources ](https://docs.sonarqube.org/8.0/extend/developing-plugin/#header-2) as follows:

_If you need to serve static resources from your plugin such as images or JavaScript files, place them in a directory under resources named static (myplugin/src/main/resources/static). At runtime they'll be available from http://{server}/static/{pluginKey}/{file}._

**Software Versions**
 - SonarQube Version: 8.0
 - Plugin Version: 1.2.1-SNAPSHOT (current master)

**Comment by NehaOberoi92** [comment]
As per above request , we no longer need to download file from https://raw.githubusercontent.com/mc1arke/sonarqube-community-branch-plugin/master/src/main/resources/static for sonar which is not accessible from github. 
Then what configuration si required for PR decoration, do I need to update Images base URL property in General > Pull Request settings ? If yes what needs to be updated in that
