### ISSUE TITLE
More like a question: Integration between Bitbucket and Sonarqube with community branch plugin

### ISSUE THREAD

**Issue by moley** [mc1arke/sonarqube-community-branch-plugin#804]
Hi, 

we are using both Bitbucket and Sonarqube with the community branch plugin. 
Everything is working perfect, but when configuring that pull request shall show sonarqube results, bitbucket is not able to access.... 

Bitbucket tries to find the project by id, e.g. https://sonarqube.intra.vsa.de/dashboard?id=mygroup%3Amytestmodule%2F%3Amybranch..... can you please give me a hint if I have to reconfigure bitbucket to find the branch or do you know by accident, if this is already supported in both bitbucket and your plugin? 

Any help appreciated
Thanks by advance

**Comment by mc1arke** [comment]
I don't have enough information to provide any guidance here: where is this link you're referring to coming from, and what are you expecting it to show?

**Comment by mc1arke** [comment]
Closing an unable to replicate
