### ISSUE TITLE
SonarQube Community 8.9 with Branch Plugin 1.8.3 seems to be translated into the same branch

### ISSUE THREAD

**Issue by HanChun45** [mc1arke/sonarqube-community-branch-plugin#807]
**Describe the bug**
sonarqube-community-8.9 use sonarqube-community-branch-plugin-1.8.3, After scanning multiple branches, the code seems to be translated into the same branch.(The number of rows, quality, and number of bugs are consistent)
sonarqube-community-8.9使用sonarqube-community-branch-plugin-1.8.3插件，扫描多个分支后似乎为同一分支的结果（行数，质量、bugs数量均一致）

**To Reproduce**
Scan result for the master branch:
master分支扫描结果:
![image](https://github.com/mc1arke/sonarqube-community-branch-plugin/assets/109121058/9dc51e04-a595-40fa-bc34-d120c1600e6e)
![image](https://github.com/mc1arke/sonarqube-community-branch-plugin/assets/109121058/50839fc6-6be7-42a9-8b5e-687c88f7330f)
Scan result for the dev-tyb branch:
dev- tyb分支扫描结果:
![image](https://github.com/mc1arke/sonarqube-community-branch-plugin/assets/109121058/33471b9b-c499-4e40-8598-4f5653cdc1fb)
![image](https://github.com/mc1arke/sonarqube-community-branch-plugin/assets/109121058/0ab63280-7faa-441d-aebc-b7edfc0fe8c5)
As shown in the figure, although I have scanned the code of multiple branches using SONa-scanner, the result of each branch is the same, even down to the number of lines, the dev-tyb branch has not been committed for a long time, which is clearly not correct
如图所示，尽管我使用了sonar-scanner扫描了多个分支的代码，但每个分支的结果都是一样的，甚至连行数都是，dev-tyb分支已经很久没有提交了，这显然不正确
master update nearly
master分支刚更新不久
![image](https://github.com/mc1arke/sonarqube-community-branch-plugin/assets/109121058/6df871fb-8916-4bf3-8435-844f652872d5)
The dev-tyb branch has not been committed for a long time
dev-tyb分支已经很久没有提交了
![image](https://github.com/mc1arke/sonarqube-community-branch-plugin/assets/109121058/21e275e2-0745-4355-b679-defd4dc463c6)
The command I use is as follows: Run git clone -b master git@xxx to pull down and scan the deployed code
我使用的命令如下，先使用git clone -b master git@xxx拉下所要、扫描部署的代码
Scan master branch
扫描master
```
mvn compile sonar:sonar   -Dsonar.projectKey=newyctech-yyglpt-equip   -Dsonar.host.url=http://192.168.11.152:9000   -Dsonar.login=8dfda10fd01832d25cdec8aeb8824e6d6ba3d983 -Dsonar.branch.name=master
```
Scan dev-tyb branch
扫描dev-tyb
```
mvn compile sonar:sonar   -Dsonar.projectKey=newyctech-yyglpt-equip   -Dsonar.host.url=http://192.168.11.152:9000   -Dsonar.login=8dfda10fd01832d25cdec8aeb8824e6d6ba3d983 -Dsonar.branch.name=dev-tyb
```
Even there is no test branch in the code warehouse, but it can still be scanned and show the same result. I think I should be where the configuration is wrong
甚至代码仓库中没有test分支，但依然能被扫描，并显示相同的结果，我想应该是我哪里配置错了
![image](https://github.com/mc1arke/sonarqube-community-branch-plugin/assets/109121058/18dc49c7-2404-4279-8174-77ac8bc9daee)
![image](https://github.com/mc1arke/sonarqube-community-branch-plugin/assets/109121058/3e44cc63-ddfb-4ea7-a876-767f2e3e7373)

```
mvn compile sonar:sonar   -Dsonar.projectKey=newyctech-yyglpt-equip   -Dsonar.host.url=http://192.168.11.152:9000   -Dsonar.login=8dfda10fd01832d25cdec8aeb8824e6d6ba3d983 -Dsonar.branch.name=test
```
The files under sonarqube/extensions/plugins are as follows
sonarqube/extensions/plugins/下文件如下
![image](https://github.com/mc1arke/sonarqube-community-branch-plugin/assets/109121058/223a8c91-1ce0-4c90-af1a-43f0eca918a0)
The files sonar.properties are as follows
sonar.properties配置如下
![image](https://github.com/mc1arke/sonarqube-community-branch-plugin/assets/109121058/614efbd4-218a-4e46-a0c4-6456c11ca616)

**Comment by CoderPanyy** [comment]
![image](https://github.com/mc1arke/sonarqube-community-branch-plugin/assets/48623002/3e94bb0e-5b63-48e6-9192-1de71ec4220f)

Why is the domain name of sonaqube MASKED when I submit the code on gitlab and the scanning result is [MASKED]? How can I configure it to show the full domain name

**Comment by brother** [comment]
As I understand it the gitlab CI has a setting for masking variables, make sure that this URL is not in a variable marked as masked.

https://docs.gitlab.com/ee/ci/variables/#mask-a-cicd-variable

**Comment by mc1arke** [comment]
I can't replicate the original reported issue on Sonarqube 9.9 (current LTS). @HanChun45 please upgrade to the latest LTS (or latest version), check if you still encounter the problem, and raise a new issue if you do.
