### ISSUE TITLE
SonarQube branches cleanup seems to not trigger

### ISSUE THREAD

**Issue by boomaker** [mc1arke/sonarqube-community-branch-plugin#812]
**Describe the bug**
Looks like the branch cleanup native feature of SonarQube is not working with the plugin.
Maybe because the relative code is based on the condition "if Community Edition then no need to clear branches" since is should have only the master one ?

**Expected behavior**
Branches without analysis should be deleted after 30 days.

**Screenshots**
![image](https://github.com/mc1arke/sonarqube-community-branch-plugin/assets/1837884/424ffb1f-e24c-41b5-8626-b45418ab842b)

**Software Versions**
 - SonarQube Version: 9.9.0.65466
 - Plugin Version: 1.14.0

**Additional context**
Actually my DB is taking 42GB with live_measures table taking 26GB.

**Comment by kzhuklinets** [comment]
Try this https://github.com/mc1arke/sonarqube-community-branch-plugin/issues/549

**Comment by boomaker** [comment]
Thanks! I confirm that solves the issue!

Sorry my search in the GitHub issues was not optimal :-/
