### ISSUE TITLE
How to use the plugin

### ISSUE THREAD

**Issue by eloo** [mc1arke/sonarqube-community-branch-plugin#82]
**Describe the bug**
Hi, i'm trying your plugin but i'm not sure if i do it right. 
Sadly i cant find a documentation or example how i need to configure my projects.

At the moment my configuration has the following sonar properties in the pom.xml of the project i want to scan:

```
<sonar.branch.name>feature/test-sonar-branch-name</sonar.branch.name>
<sonar.branch.target>master</sonar.branch.target>
```
But i'm getting every time an error when i run `mvn compile sonar:sonar`. In the sonar logs i see something like this 
```
java.lang.IllegalStateException: Current edition does not support branch feature
```

**Expected behavior**
* My analysis is triggered for the branches
* The build is not failing because of an error while sonar execution

**Software Versions**
 - SonarQube Version: Community EditionVersion 7.9.2 (build 30863)
 - Plugin Version: 1.2.0

Thanks for your help

**Comment by mc1arke** [comment]
This doesn't sound like a bug, it sounds like the plugin hasn't been installed properly. Is the plugin file present in both the lib/common and extensions/plugins directory in your Sonarqube directory as per the README?

**Comment by eloo** [comment]
Ah thats totally right!
I'm using a helm chart for sonar and missed the plugins.lib configuration. Now its working as expected together with BitBucket server. Thanks a lot!
