### ISSUE TITLE
Missing Coverage information in pull request decoration

### ISSUE THREAD

**Issue by nishwalshetty** [mc1arke/sonarqube-community-branch-plugin#822]
**Describe the bug**
Code Coverage information is missing in pull request decoration, it always shows no coverage information

**To Reproduce**
write new code and write unit tests

**Expected behavior**
coverage information like percentage of new code coverged to be displayed in PR comment

**Screenshots**
![image](https://github.com/mc1arke/sonarqube-community-branch-plugin/assets/48088420/24e05849-c20c-4a05-8ea8-21d910542a99)
but coverage information is available in the sonarqube dashboard(see below)
![image](https://github.com/mc1arke/sonarqube-community-branch-plugin/assets/48088420/d84d8d21-59bc-4170-9fe5-683b7c0c4071)

so the question here is why does it say no coverage information ?  when i write the same code and try with enterprise edition of sonarqube i see the below which is what i am expected this plugin to do for me for the community edition as well.

![image](https://github.com/mc1arke/sonarqube-community-branch-plugin/assets/48088420/e1acf15f-f80c-4dee-b92b-455070b6f97a)

**Software Versions**
 - SonarQube Version: 9.9 LTS
 - Plugin Version:  1.14.0

**Additional context**
None

**Comment by mc1arke** [comment]
Without something to replicate against I can't provide any guidance here: possibly a Github project I can run a build from, or enough details about your build environment (build tools, plugins, type of changes etc) to give a change of debugging the issue locally

**Comment by takanuva15** [comment]
fyi for future readers, I had to add `-Dsonar.newCode.referenceBranch=main` to the sonar-scanner command to fix this issue since sonarqube community doesn't use reference branches by default for tracking coverage changes
