### ISSUE TITLE
Update the java version to 17

### ISSUE THREAD

**Issue by mericozkayagan** [mc1arke/sonarqube-community-branch-plugin#834]
https://github.com/mc1arke/sonarqube-community-branch-plugin/blob/7499112f133cceca3acf7738ffbc8c29379eae20/.github/workflows/build.yml#L44

Greetings I am using sonarqube:9.9-community with your extension 1.14.0. Today I got an error with the java version like this
```
Run ./.sonar/scanner/dotnet-sonarscanner end /d:sonar.login="***"
  ./.sonar/scanner/dotnet-sonarscanner end /d:sonar.login="***"
  shell: /usr/bin/bash -e {0}
  env:
    DOTNET_ROOT: /usr/share/dotnet
    GITHUB_TOKEN: ***
SonarScanner for MSBuild 6.0
Using the .NET Core version of the Scanner for MSBuild
Post-processing started.
Calling the SonarScanner CLI...
Error: LinkageError occurred while loading main class org.sonarsource.scanner.cli.Main
	java.lang.UnsupportedClassVersionError: org/sonarsource/scanner/cli/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
The SonarScanner did not complete successfully
Error: Process completed with exit code 1.
```

Upon researching I found that the java version in this plugin do not support this class file as its shown here in
![image](https://github.com/mc1arke/sonarqube-community-branch-plugin/assets/96292408/bfa4c4f3-bb5d-4cbc-9185-a4c8eea57fdf)

Are you thinking about a version update? Since I think it is the cause of this error?

**Comment by mc1arke** [comment]
Java 17 is used as of the Sonarqube 10.0 compatible build (v1.15.0) but has to produce Java 11 class files to remain compatible with anyone using older Sonar scanner versions.

**Comment by CamiloBernal** [comment]
> Find the error. https://docs.sonarsource.com/sonarqube/latest/analyzing-source-code/scanners/sonarscanner-for-dotnet/ Sonar scanner for Dotnet just dropped the java 11 support 3 days ago with version 6.0.0. I have pinned to 5.15.0 to function correctly. For now it is solved but any updates for the java 17 update on your side?

Thanks @mericozkayagan , it work for me. I downgraded dotnet-sonarscanner to 5.15.0 and the error no longer appears. Thanks for the help

**Comment by FaizanMomin25** [comment]
Thanks, @mericozkayagan! It worked for me.

I was encountering a SonarQube error:

```

> Error: LinkageError occurred while loading main class org.sonarsource.scanner.cli.Main
> java.lang.UnsupportedClassVersionError: org/sonarsource/scanner/cli/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
> [Pipeline] }
> WARN: Unable to locate 'report-task.txt' in the workspace. Did the SonarScanner succeed?

```

I resolved it by upgrading the Java version from JDK 11 to JDK 17 in the Jenkins Global Tool Configuration. After that, the scanner ran successfully.
