### ISSUE TITLE
Missing Release 1.15.0

### ISSUE THREAD

**Issue by arturkasperek** [mc1arke/sonarqube-community-branch-plugin#835]
**Describe the bug**
Release 1.15.0 is missing - it should include jar file to use. Only tag is available
<img width="1357" alt="Zrzut ekranu 2023-12-7 o 12 53 37" src="https://github.com/mc1arke/sonarqube-community-branch-plugin/assets/6894763/0bf83422-e788-4efc-88a4-8abe5e219873">

cc @mc1arke

**Comment by garbelini** [comment]
Strange that the release action seems to have passed.

https://github.com/mc1arke/sonarqube-community-branch-plugin/actions/runs/6208474461/job/16854691151

**Comment by llopusinski** [comment]
@garbelini It passed but with strange url 
![image](https://github.com/mc1arke/sonarqube-community-branch-plugin/assets/86770071/5bafd767-74d0-4647-a554-45cf3a0ab0e6)

**Comment by mericozkayagan** [comment]
any updates here?

**Comment by mc1arke** [comment]
Fixed. Releases are created as hidden until I approve them, but given my available time to perform follow-on actions (docker image publishing etc) I didn't get round to the final steps. This has now been completed.
