### ISSUE TITLE
Wrong Gitlab API url for MR decoration

### ISSUE THREAD

**Issue by Brightside56** [mc1arke/sonarqube-community-branch-plugin#84]
Hello. First of all, thanks for a good job.

I've compiled jar from here:

https://github.com/mc1arke/sonarqube-community-branch-plugin/tree/sq-8_1-support

and when it comes publishing MR comment, plugin fails to do that. I'm seeing following in console:

GET /api/v4/api/v4/projects/root%2Fsonarqube/merge_requests/13/commits

As I see plugin gets hostURL with /api/v4, but also adds its own /api/v4 to url

**Comment by mc1arke** [comment]
Firstly, can you confirm this is the latest version of that branch you're using (the one that was published on Sunday)?

Can you also confirm how the host URL is being submitted? Is this auto-detected from the Gitlab CI environment by the Sonar Runner, of a property that you're passing as part of the launch arguments for the scanner?

**Comment by Brightside56** [comment]
Hello. Yes, it's last commit, you can see my git output below:

brightside@hp ~/git/sonarqube-community-branch-plugin
 % git fetch origin
brightside@hp ~/git/sonarqube-community-branch-plugin
 % git pull
Already up to date.
brightside@hp ~/git/sonarqube-community-branch-plugin
 % git status
On branch sq-8_1-support

It seems to be autodetected. I'm running gitlab-ci ce pipeline this way:

- sonar-scanner -Dsonar.qualitygate.wait=true -Dsonar.projectKey=sonatest -Dsonar.branch.name=$CI_COMMIT_BRANCH

**Comment by mc1arke** [comment]
Ok. We're auto-detecting it from the CI pipeline variables then. I'll update the Gitlab decorator to not include the `/api/v4` in the URL, and make sure it's clear to users that they need to include this if manually specifying it from the command line

**Comment by Brightside56** [comment]
@mc1arke I've changed URL for me to bypass issue, but here we have next:

2020.02.04 10:24:25 DEBUG ce[AXAPusCdBS3onnwVoRCE][o.a.h.i.c.DefaultHttpClientConnectionOperator] Connection established 172.19.0.2:37308<->192.168.30.77:8090
2020.02.04 10:24:25 DEBUG ce[AXAPusCdBS3onnwVoRCE][o.a.h.i.e.MainClientExec] Executing request GET /api/v4/projects/root%2Fsonarqube/merge_requests/14/commits HTTP/1.1
2020.02.04 10:24:25 DEBUG ce[AXAPusCdBS3onnwVoRCE][o.a.h.i.e.MainClientExec] Target auth state: UNCHALLENGED
2020.02.04 10:24:25 DEBUG ce[AXAPusCdBS3onnwVoRCE][o.a.h.i.e.MainClientExec] Proxy auth state: UNCHALLENGED
2020.02.04 10:24:25 DEBUG ce[AXAPusCdBS3onnwVoRCE][o.a.http.headers] http-outgoing-0 >> GET /api/v4/projects/root%2Fsonarqube/merge_requests/14/commits HTTP/1.1
2020.02.04 10:24:25 DEBUG ce[AXAPusCdBS3onnwVoRCE][o.a.http.headers] http-outgoing-0 >> PRIVATE-TOKEN: 5bd2fa3b42d1b8358a76a6edb7242353a78ab597
2020.02.04 10:24:25 DEBUG ce[AXAPusCdBS3onnwVoRCE][o.a.http.headers] http-outgoing-0 >> Accept: application/json
2020.02.04 10:24:25 DEBUG ce[AXAPusCdBS3onnwVoRCE][o.a.http.headers] http-outgoing-0 >> Host: 192.168.30.77:8090
2020.02.04 10:24:25 DEBUG ce[AXAPusCdBS3onnwVoRCE][o.a.http.headers] http-outgoing-0 >> Connection: Keep-Alive
2020.02.04 10:24:25 DEBUG ce[AXAPusCdBS3onnwVoRCE][o.a.http.headers] http-outgoing-0 >> User-Agent: Apache-HttpClient/4.5.10 (Java/11.0.6)
2020.02.04 10:24:25 DEBUG ce[AXAPusCdBS3onnwVoRCE][o.a.http.headers] http-outgoing-0 >> Accept-Encoding: gzip,deflate
2020.02.04 10:24:25 DEBUG ce[AXAPusCdBS3onnwVoRCE][org.apache.http.wire] http-outgoing-0 >> "GET /api/v4/projects/root%2Fsonarqube/merge_requests/14/commits HTTP/1.1[\r][\n]"
2020.02.04 10:24:25 DEBUG ce[AXAPusCdBS3onnwVoRCE][org.apache.http.wire] http-outgoing-0 >> "PRIVATE-TOKEN: 5bd2fa3b42d1b8358a76a6edb7242353a78ab597[\r][\n]"
2020.02.04 10:24:25 DEBUG ce[AXAPusCdBS3onnwVoRCE][org.apache.http.wire] http-outgoing-0 >> "Accept: application/json[\r][\n]"
2020.02.04 10:24:25 DEBUG ce[AXAPusCdBS3onnwVoRCE][org.apache.http.wire] http-outgoing-0 >> "Host: 192.168.30.77:8090[\r][\n]"
2020.02.04 10:24:25 DEBUG ce[AXAPusCdBS3onnwVoRCE][org.apache.http.wire] http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
2020.02.04 10:24:25 DEBUG ce[AXAPusCdBS3onnwVoRCE][org.apache.http.wire] http-outgoing-0 >> "User-Agent: Apache-HttpClient/4.5.10 (Java/11.0.6)[\r][\n]"
2020.02.04 10:24:25 DEBUG ce[AXAPusCdBS3onnwVoRCE][org.apache.http.wire] http-outgoing-0 >> "Accept-Encoding: gzip,deflate[\r][\n]"
2020.02.04 10:24:25 DEBUG ce[AXAPusCdBS3onnwVoRCE][org.apache.http.wire] http-outgoing-0 >> "[\r][\n]"
2020.02.04 10:24:25 DEBUG ce[AXAPusCdBS3onnwVoRCE][org.apache.http.wire] http-outgoing-0 << "HTTP/1.1 401 Unauthorized[\r][\n]"
2020.02.04 10:24:25 DEBUG ce[AXAPusCdBS3onnwVoRCE][org.apache.http.wire] http-outgoing-0 << "Server: nginx[\r][\n]"
2020.02.04 10:24:25 DEBUG ce[AXAPusCdBS3onnwVoRCE][org.apache.http.wire] http-outgoing-0 << "Date: Tue, 04 Feb 2020 10:24:25 GMT[\r][\n]"
2020.02.04 10:24:25 DEBUG ce[AXAPusCdBS3onnwVoRCE][org.apache.http.wire] http-outgoing-0 << "Content-Type: application/json[\r][\n]"
2020.02.04 10:24:25 DEBUG ce[AXAPusCdBS3onnwVoRCE][org.apache.http.wire] http-outgoing-0 << "Content-Length: 30[\r][\n]"
2020.02.04 10:24:25 DEBUG ce[AXAPusCdBS3onnwVoRCE][org.apache.http.wire] http-outgoing-0 << "Connection: keep-alive[\r][\n]"
2020.02.04 10:24:25 DEBUG ce[AXAPusCdBS3onnwVoRCE][org.apache.http.wire] http-outgoing-0 << "Cache-Control: no-cache[\r][\n]"
2020.02.04 10:24:25 DEBUG ce[AXAPusCdBS3onnwVoRCE][org.apache.http.wire] http-outgoing-0 << "Vary: Origin[\r][\n]"
2020.02.04 10:24:25 DEBUG ce[AXAPusCdBS3onnwVoRCE][org.apache.http.wire] http-outgoing-0 << "X-Content-Type-Options: nosniff[\r][\n]"
2020.02.04 10:24:25 DEBUG ce[AXAPusCdBS3onnwVoRCE][org.apache.http.wire] http-outgoing-0 << "X-Frame-Options: SAMEORIGIN[\r][\n]"
2020.02.04 10:24:25 DEBUG ce[AXAPusCdBS3onnwVoRCE][org.apache.http.wire] http-outgoing-0 << "X-Request-Id: 1Cj3pW02zP5[\r][\n]"
2020.02.04 10:24:25 DEBUG ce[AXAPusCdBS3onnwVoRCE][org.apache.http.wire] http-outgoing-0 << "X-Runtime: 0.192637[\r][\n]"
2020.02.04 10:24:25 DEBUG ce[AXAPusCdBS3onnwVoRCE][org.apache.http.wire] http-outgoing-0 << "[\r][\n]"
2020.02.04 10:24:25 DEBUG ce[AXAPusCdBS3onnwVoRCE][org.apache.http.wire] http-outgoing-0 << "{"message":"401 Unauthorized"}"

**Comment by Brightside56** [comment]
After removing /api/v4 from URL it's working great with gitlab

**Comment by mc1arke** [comment]
Fixed in #87
