### ISSUE TITLE
Gitlab PR decoration throws exception when no new_coverage condition is provided

### ISSUE THREAD

**Issue by kortov** [mc1arke/sonarqube-community-branch-plugin#85]
**Describe the bug**
When in Sonar conditions there is no new_coverage condition (and i doubt that this condition is necessary) the plugin throws Exception. `IllegalStateException("Could not find New Coverage Condition in analysis")`.  I guess it's kinda related to #62 but the reason of the issue lies here https://github.com/mc1arke/sonarqube-community-branch-plugin/blob/1e28de64c8d608db5bdc1bd020dcfa073b9e0e89/src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/gitlab/GitlabServerPullRequestDecorator.java#L153-L155

The easiest solution would be 

```
String coverageValue = analysis.findQualityGateCondition(CoreMetrics.NEW_COVERAGE_KEY)
                            .filter(condition -> condition.getStatus() != QualityGate.EvaluationStatus.NO_VALUE)
                            .map(QualityGate.Condition::getValue)
                            .orElse("0");
```

it's kinda duplicates the code from here https://github.com/mc1arke/sonarqube-community-branch-plugin/blob/1e28de64c8d608db5bdc1bd020dcfa073b9e0e89/src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/AnalysisDetails.java#L115-L120

So may be we can put some duplicated lines into separate method from `AnalysisDetails.java`. I unfortunately have no idea how to implement fix nicely

**Expected behavior**
The plugin should not throw an exception. May be only log some info.

**Screenshots**

**Software Versions**
 - SonarQube Version:  Version 7.9.2
 - Plugin Version:  custom build from master at commit 1e28de64c8d608db5bdc1bd020dcfa073b9e0e89]

**Comment by mc1arke** [comment]
Fixed in #87
