### ISSUE TITLE
overwrite pull request Analysis Details

### ISSUE THREAD

**Issue by Zavy86** [mc1arke/sonarqube-community-branch-plugin#851]
Hi, is it possible to make the pull request analysis be overwritten rather than adding a new one every time?
Is there any parameter to set?
thank you so much!

**Comment by alexintech** [comment]
Actually an issue https://github.com/mc1arke/sonarqube-community-branch-plugin/issues/790 exists and a PR https://github.com/mc1arke/sonarqube-community-branch-plugin/pull/791 is open.

I suppose maintainer doesn't like overwriting analysis details and that PR may not be merged.

You can use a plugin with this functionality from my fork https://github.com/alexintech/sonarqube-community-branch-plugin/releases
