### ISSUE TITLE
[BUG]  10.3 SQ + 1.18.0 plugin release "No branch exists in Sonarqube with the name" for a PR to non existing branch

### ISSUE THREAD

**Issue by kzhuklinets** [mc1arke/sonarqube-community-branch-plugin#854]
Hi, 

We use Azure DevOps and when we try to analyze a PR merge to a non-existing branch in SQ, we receive an error "No branch exists in Sonarqube with the name xxxx"

This is a check which exists here, in plugin: https://github.com/mc1arke/sonarqube-community-branch-plugin/blob/5e5ca504c435f5844f86feee02880469344c7de7/src/main/java/com/github/mc1arke/sonarqube/plugin/scanner/BranchConfigurationFactory.java#L50C31-L50C31

The branch really doesn't exist, so to make it works we had to run analyze on the branch itself and then - PR merge. 

**To Reproduce**
1. Make a PR to a non-existing branch in SQ

**Expected behavior**
1. Non-existing branch is created automatically
2. PR merge works without errors

**Software Versions**
 - SonarQube Version: 10.3
 - Plugin Version: 1.18.0

**Additional context**
We haven't faced with it before (we are using SQ CE versions 9.8, 9.9, 10 with the plugin for more then year), so it might be some missing functionality, but on the other hand the check tells that it is intendent. SQ documentation doesn't show anything useful for this case.

**Comment by mc1arke** [comment]
This is intentional under #847 as part of #738: if we don't have the reference branch then we can't correctly report issues. We can't just create the missing branch as we don't know what it contains.

**Comment by jeremytbrun** [comment]
@mc1arke I'm having a similar issue when running a PR build but I've verified that the "master" branch exists in the SonarQube project. Any suggestions on how to fix this?

![image](https://github.com/mc1arke/sonarqube-community-branch-plugin/assets/28311946/b30b0b20-9d49-412e-8277-42be3eb8179e)

![image](https://github.com/mc1arke/sonarqube-community-branch-plugin/assets/28311946/217d3416-49e2-48c0-badb-f7cd0b11fae8)

**Comment by jeremytbrun** [comment]
I found that my issue was caused by build pipelines running older versions of the SonarQubePrepare, SonarQubeAnalyze, and SonarQubePublish VSTS pipelines tasks. By updating them to v5 tasks it resolved the issue.

SonarQubePrepare@5
SonarQubeAnalyze@5
SonarQubePublish@5

**Comment by jovanz-getbgd** [comment]
> This is intentional under #847 as part of #738: if we don't have the reference branch then we can't correctly report issues. We can't just create the missing branch as we don't know what it contains.

How did this work correctly in previous versions then? The situation we have is not related to project creation, the project and its master and dev branches exist in SQ and are analyzed regularly, we are getting this issue when we try to do a PR into a temp release or hotfix branch.

I would consider this a breaking change for the plugin, which is not indicated by only increasing the minor release version.

**Comment by mc1arke** [comment]
@jovanz-getbgd it defaulted to using your project's 'default' branch as the reference branch. This meant that the baselines were incorrect and Sonarqube was reporting misleading reference information. It may cause problems in workflows that haven't pre-scanned target branches, but I wouldn't class it as a breaking change since the process wasn't working properly for those scans anyway.

**Comment by jovanz-getbgd** [comment]
Thanks so much for a detailed explanation. Makes total sense now.

**Comment by fourirakbar** [comment]
hi @jeremytbrun , I wanna ask how you solve this issue? because I face it now. I use
sonarqube -> 10.3.0-community using helm chart
sonarqube community branch plugin -> 1.18.0
sonar scanner maven version -> 3.11.0.3922

I'm a bit confused, where can i update this to v5?
SonarQubePrepare@5
SonarQubeAnalyze@5
SonarQubePublish@5

**Comment by hballangan-mdsol** [comment]
Same issue faced when opening PRs against release branches. Before we were able to analyze new PRs against a release branch but now with the new version it isn't possible. I think the old function was actually helpful as we were able to analyze bugfixes or additional features.
