### ISSUE TITLE
Error while upgrading sonarqube from 8.3.1 to 8.9-community version 

### ISSUE THREAD

**Issue by someshrathi02** [mc1arke/sonarqube-community-branch-plugin#856]
**Describe the bug**
Current setup - sonarQube version 8.3.1  and plugin version sonarqube-community-branch-plugin-1.5.0.jar.
Now we are planning to upgrade sonarqube version from 8.3.1 to 8.9-community version ( docker image ) 

We are getting below error when upgrading the sonarqube from 8.3  to 8.9-community version . 

```
2024.01.17 13:53:44 ERROR app[][startup] Startup failed: Plugins can't be loaded. See web logs for more information
**2024.01.17 13:53:44 ERROR web[][o.s.s.p.PlatformImpl] Web server startup failed: The following plugins are no longer compatible with this version of SonarQube: 'scmgit', 'scmsvn'**
2024.01.17 13:53:44 INFO  web[][o.s.s.a.EmbeddedTomcat] HTTP connector enabled on port 9000
2024.01.17 13:53:44 INFO  web[][o.s.p.ProcessEntryPoint] Hard stopping process
2024.01.17 13:53:44 INFO  app[][o.s.a.SchedulerImpl] Process[web] is stopped
2024.01.17 13:53:44 INFO  app[][o.s.a.SchedulerImpl] Process[es] is stopped
2024.01.17 13:53:44 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
2024.01.17 13:53:44 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [es]: 143
```
We have also downloaded the [sonarqube-community-branch-plugin-1.8.0.jar](https://github.com/mc1arke/sonarqube-community-branch-plugin/releases/download/1.8.0/sonarqube-community-branch-plugin-1.8.0.jar) which is mentioned as compatible with Sonarqube 8.9

**To Reproduce**
1. We have downloaded  the compatible plugin sonarqube-community-branch-plugin-1.8.0.jar for sonarqube version 8.9 as mentioned in https://github.com/mc1arke/sonarqube-community-branch-plugin/releases/tag/1.8.0 and then 
 
Executed below docker command 

```
sudo docker run -d --name sonarqube \
-p 9000:9000 \
-e SONAR_JDBC_URL=DB URL \
-e SONAR_JDBC_USERNAME=username \
-e SONAR_JDBC_PASSWORD=password \
-v sonarqube_data:/opt/sonarqube/data \
-v sonarqube_extensions:/opt/sonarqube/extensions \
-v sonarqube_logs:/opt/sonarqube/logs \
--security-opt seccomp=/root/seccomp/profile.json \
-v /root/sonarqube-community-branch-plugin-1.8.0.jar:/opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin.jar \
-v /root/sonarqube-community-branch-plugin-1.8.0.jar:/opt/sonarqube/lib/common/sonarqube-community-branch-plugin.jar \

```

**Expected behavior**
sonarqube server should have started succesfully. 
**Screenshots**

**Software Versions**
 - SonarQube Version: [e.g. docker image  -> sonarQube 8.9-community   ]
 - Plugin Version: [[e.g. 1.1.0, or custom build from master at commit 004AD34FAA](https://github.com/mc1arke/sonarqube-community-branch-plugin/releases/tag/1.8.0)]

**Additional context**

**Comment by mc1arke** [comment]
> The following plugins are no longer compatible with this version of SonarQube: 'scmgit', 'scmsvn'

It looks like you need to upgrade your scmgit and scmsvn plugins
