### ISSUE TITLE
GitLab comments in files - non-obvious parameter requirement

### ISSUE THREAD

**Issue by rusguliev** [mc1arke/sonarqube-community-branch-plugin#86]
**Bug summary**
If you enable the com.github.mc1arke.sonarqube.plugin.branch.pullrequest.file.comment.enabled = parameter, but leave the com.github.mc1arke.sonarqube.plugin.branch.pullrequest.delete.comments.enabled ( default = False), the server will not comment on the source code. This is true because if the server comments on the source code for each analysis, the comments will repeat the same problems (if they have not been resolved), but this is not obvious to the end user. When the user turns on the com.github.mc1arke.sonarqube.plugin.branch.pullrequest.file.comment.enabled = parameter True, the com.github.mc1arke.sonarqube.plugin.branch.pullrequest.delete.comments.enabled parameter should turn on automatically.

**To Reproduce**
1. In the project settings, enable the "Enable file comment" option using the GitLab provider:
![screenshot](https://habrastorage.org/webt/lw/tq/rw/lwtqrwivx8s6nkxkmj0ebqeqe28.png)
2. In the project settings, configure the section according to your server.
3. Run the pullrequest Analysis
4. SonarQube don't create threads in source code in GitLab.

**Expected behavior**
SonarQube server creates threads in source code in GitLab

**Software Versions**
 - SonarQube Version: 7.9.2
 - Plugin Version: last commit in master branch

**Comment by rusguliev** [comment]
Dependence of parameters in the source code of the plugin: https://github.com/mc1arke/sonarqube-community-branch-plugin/blob/1e28de64c8d608db5bdc1bd020dcfa073b9e0e89/src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/gitlab/GitlabServerPullRequestDecorator.java#L129
https://github.com/mc1arke/sonarqube-community-branch-plugin/blob/1e28de64c8d608db5bdc1bd020dcfa073b9e0e89/src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/gitlab/GitlabServerPullRequestDecorator.java#L227

**Comment by kortov** [comment]
>  leave the `com.github.mc1arke.sonarqube.plugin.branch.pullrequest.delete.comments.enabled` is `False`, the server will not comment on the source code

will be fixed in #74 . As was said https://github.com/mc1arke/sonarqube-community-branch-plugin/pull/74#issuecomment-574180840 "that is clearly a bug!"

> "When the user turns on the `com.github.mc1arke.sonarqube.plugin.branch.pullrequest.file.comment.enabled` = `True`, the `com.github.mc1arke.sonarqube.plugin.branch.pullrequest.delete.comments.enabled` parameter should turn on automatically"

I guess it's hard to implement, the easiest solution would be to make `delete.comments.enabled` = `true` by default. Don't know what others think about it.

**Comment by mc1arke** [comment]
Fixed in #87
