### ISSUE TITLE
Scanning with the plugin does not show the author of the issue.

### ISSUE THREAD

**Issue by jrroberth** [mc1arke/sonarqube-community-branch-plugin#872]
Thank you, this plugin is incredible and very helpful for those of us who use the community version.

**Bug**
Shows the issues but not the author.

![sonar](https://github.com/mc1arke/sonarqube-community-branch-plugin/assets/40367059/cf1ce881-4fc0-4634-b006-eaafa26771c5)

**To Reproduce**
I performed the scan from the Azure Devops pipeline.

**Software Versions**
sonarqube-10.2.1.78527
sonarqube-community-branch-plugin-1.17.1.jar

**Additional context**
When I do a local scan it works and shows the author.

**Comment by mc1arke** [comment]
Closing as abandoned
