### ISSUE TITLE
Quality gate passes with failed test

### ISSUE THREAD

**Issue by RemiBajart1** [mc1arke/sonarqube-community-branch-plugin#878]
**Describe the bug**
In my quality gate configuration, I have
> Unit Test Errors is greater than 0  
> Unit Test Failures  is greater than 0   
> Unit Test Success (%) is less than 100%

The CI is configured not to block when there is test failures, only to fail on Sonar QG

If a test fails, QG is not blocking the PR.

**Expected behavior**
QG should fail if unit test expectation not met.

**Software Versions**
 - SonarQube Version: 9.9.3.79811
 - Plugin Version: 1.14.0

**Comment by mc1arke** [comment]
Does your Sonarqube report any tests as failed? The plugin doesn't directly manage anything to do with unit test status - it's just managing distinction and processing of data for each branch - so it's unlikely this is something to do with the plugin, and probably more likely to be related to your scanner not submitting test results to Sonarqube

**Comment by mc1arke** [comment]
Closing as abandoned
