### ISSUE TITLE
Docker and volume to /opt/sonarqube/lib/common

### ISSUE THREAD

**Issue by Roemer** [mc1arke/sonarqube-community-branch-plugin#88]
Hello
Having a volume to `/opt/sonarqube/lib/common` in Docker seems not optimal. As there are tons of other files, they will all be copied to this volume. Now when someone updates Sonarqube by updating the image and re-create the container, those data will not be updated by the new container / version and could potentially break the installation.
I am unsure about the best solution to fix that issue.
In the first place, best would be if copying to that folder would not be necessary. Is there any chance for that to happen?

**Comment by 4n4n4s** [comment]
Hi @Roemer,
I think the only current solution is to only copy the plugin to this folder like:

/home/4n4n4s/sonarqube-community-branch-plugin***.jar:/opt/sonarqube/lib/common/sonarqube-community-branch-plugin.jar

Br

**Comment by Roemer** [comment]
Not extremely optimal as well as that needs to be done after each container clean or rebuild.

**Comment by timothydowney** [comment]
We end up installing all plugins via an entryPoint and pass all sonar props via environment.  This allows us to have a fully source code based deploy where none of the configuration is done via the admin guis.  This is nice since the only volume we use is the `sonarqube/data` volume.

Our entrypoint (or Dockerfile for the built in ones) can fetch and install plugins from either sonarsource or github.

If folks are interested, I can share it.  In our case, we treat it as a benefit that any manual changes via the admin interface are erased on restart.

**Comment by gjabouley-invn** [comment]
Hello

we are (for now) building another image on top of community image, with following step:
```
COPY resources/sonarqube-community-branch-plugin-1.2.1-SNAPSHOT.jar ${SONARQUBE_HOME}/lib/common
COPY resources/sonarqube-community-branch-plugin-1.2.1-SNAPSHOT.jar ${SONARQUBE_HOME}/extensions_save/plugins
```

Before starting/upgrading the container, you just need to ensure to wipe the mounted volume for /extensions folder.
It will then get auto-populated by content of _extensions_save_, as implemented [here](https://github.com/SonarSource/docker-sonarqube/blob/master/8/community/run.sh#L64).

Drawback is you cannot install plugins by copying them on mounted volume for /extensions (as described [here](https://docs.sonarqube.org/latest/setup/install-plugin/#header-2)), as you might loose those when wiping the volume.

**Comment by mc1arke** [comment]
The basic answer to your original question is 'no'. We have to use 'lib/common' as that's where Sonarqube loads its extensions from. I can create a new docker image for distributing this plugin through which would have this pre-installed, but that's not going to help you if you're needing to use an alternative base image.

**Comment by VladPapacostea-SM** [comment]
> 
> 
> The basic answer to your original question is 'no'. We have to use 'lib/common' as that's where Sonarqube loads its extensions from. I can create a new docker image for distributing this plugin through which would have this pre-installed, but that's not going to help you if you're needing to use an alternative base image.

Hey @mc1arke, I was wondering if you ever ended up building that image with the plugin pre-installed ?
