### ISSUE TITLE
authentication error when accesing some branch

### ISSUE THREAD

**Issue by sistemasITI** [mc1arke/sonarqube-community-branch-plugin#885]
**Describe the bug**
Hello,
I have a problem when using the plugin, when accessing any of the branches it takes me to the Sonar login page with the following error:
_"You are not authorized to access this page. Please log in with more privileges and try again."_

**To Reproduce**
access some branch from the branch selector.

**Expected behavior**
access without authentication error

**Screenshots**
clic here:
![image](https://github.com/mc1arke/sonarqube-community-branch-plugin/assets/135716002/f0ec64d6-3600-46d2-a261-7b686b762fd7)
and then error:
![image](https://github.com/mc1arke/sonarqube-community-branch-plugin/assets/135716002/44d25a29-0a5e-4b76-97bd-c59e872a744f)

**Software Versions**
 - SonarQube Version: 10.3
 - Plugin Version: 1.18.0

thank you.

**Comment by mc1arke** [comment]
You'd need to share your web log to allow any troubleshooting of this. I don't think it's related to this plugin given you've managed to create branches and pull requests.

**Comment by sistemasITI** [comment]
Here nginx log when accesing to branch (I have change our dns name to xxx on the URL):

`10.0.0.12 - - [11/Mar/2024:11:13:03 +0100] "GET /api/navigation/component?component=IPAUBack&pullRequest=38 HTTP/1.1" 403 180 "https://xxx/dashboard?id=IPAUBack&pullRequest=38" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
10.0.0.12 - - [11/Mar/2024:11:13:03 +0100] "GET /api/components/show?component=IPAUBack&pullRequest=38 HTTP/1.1" 403 180 "https://xxx/dashboard?id=IPAUBack&pullRequest=38" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
10.0.0.12 - - [11/Mar/2024:11:13:03 +0100] "GET /sessions/new?return_to=%2Fdashboard%3Fid%3DIPAUBack%26pullRequest%3D38&authorizationError=true HTTP/1.1" 200 607 "https://xxx/dashboard?id=IPAUBack&pullRequest=38" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
10.0.0.12 - - [11/Mar/2024:11:13:03 +0100] "GET /api/project_pull_requests/list?project=IPAUBack HTTP/1.1" 200 366 "https://xxx/dashboard?id=IPAUBack&pullRequest=38" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
10.0.0.12 - - [11/Mar/2024:11:13:03 +0100] "GET /api/project_branches/list?project=IPAUBack HTTP/1.1" 200 304 "https://xxx/dashboard?id=IPAUBack&pullRequest=38" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
10.0.0.12 - - [11/Mar/2024:11:13:04 +0100] "GET /api/ce/analysis_status?component=IPAUBack&pullRequest=38 HTTP/1.1" 403 180 "https://xxx/dashboard?id=IPAUBack&pullRequest=38" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
10.0.0.12 - - [11/Mar/2024:11:13:04 +0100] "GET /api/qualitygates/project_status?projectKey=IPAUBack&pullRequest=38 HTTP/1.1" 403 180 "https://xxx/dashboard?id=IPAUBack&pullRequest=38" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
10.0.0.12 - - [11/Mar/2024:11:13:04 +0100] "GET /api/measures/component?additionalFields=metrics&component=IPAUBack&metricKeys=coverage%2Cnew_coverage%2Cnew_lines_to_cover%2Cnew_violations%2Cduplicated_lines_density%2Cnew_duplicated_lines_density%2Cnew_lines%2Cnew_code_smells%2Cnew_maintainability_rating%2Cnew_bugs%2Cnew_reliability_rating%2Cnew_vulnerabilities%2Cnew_security_hotspots%2Cnew_security_review_rating%2Cnew_security_rating&pullRequest=38 HTTP/1.1" 403 180 "https://xxx/dashboard?id=IPAUBack&pullRequest=38" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
10.0.0.12 - - [11/Mar/2024:11:13:04 +0100] "GET /api/qualitygates/get_by_project?project=IPAUBack HTTP/1.1" 499 0 "https://xxx/dashboard?id=IPAUBack&pullRequest=38" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
10.0.0.12 - - [11/Mar/2024:11:13:04 +0100] "GET /api/l10n/index?locale=es-ES HTTP/1.1" 200 96109 "https://xxx/sessions/new?return_to=%2Fdashboard%3Fid%3DIPAUBack%26pullRequest%3D38&authorizationError=true" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
10.0.0.12 - - [11/Mar/2024:11:13:04 +0100] "GET /api/users/identity_providers HTTP/1.1" 200 60 "https://xxx/sessions/new?return_to=%2Fdashboard%3Fid%3DIPAUBack%26pullRequest%3D38&authorizationError=true" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
10.0.0.12 - - [11/Mar/2024:11:13:04 +0100] "GET /api/settings/login_message HTTP/1.1" 200 51 "https://xxx/sessions/new?return_to=%2Fdashboard%3Fid%3DIPAUBack%26pullRequest%3D38&authorizationError=true" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36`

**Comment by mc1arke** [comment]
It was the Sonarqube Web component's logs I was asking for:  I need to see the startup of the Web services and what was reported when you're seeing one of these failures. The Nginx logs don't provide enough insight into what's going on inside Sonarqube and why.

**Comment by sistemasITI** [comment]
Hello, where can I find this logs?
I am looking in logs folder inside sonar installation folder.

**Comment by mc1arke** [comment]
They're available for download in the admin screen of your Sonarqube instance

**Comment by mc1arke** [comment]
Closing as unable to replicate
