### ISSUE TITLE
Update Docker hub repo to 1.19

### ISSUE THREAD

**Issue by hansjm10** [mc1arke/sonarqube-community-branch-plugin#903]
Currently if you were to install from Docker you would still be on version 1.18 of the plugin, while the git repo has moved forward to 1.19.1.

**Comment by ValentinAUCLERC** [comment]
Hello @mc1arke is it possible to update it to the latest version ? (1.21 now) 
Thank you !

**Comment by mc1arke** [comment]
1.22.0 has been pushed to Docker Hub
