### ISSUE TITLE
Supporting the project

### ISSUE THREAD

**Issue by dcherniv** [mc1arke/sonarqube-community-branch-plugin#91]
I really appreciate all the work that went into this plugin. And it would be nice to have some way to support it. 
@mc1arke is there a buy me coffee page or something similar where we can donate?

**Comment by bambuca** [comment]
There are definitely more of us who would like to support your project (paypal/patreon/...)

**Comment by kortov** [comment]
I think https://help.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository is suitable here

**Comment by ezintz** [comment]
I also appreciate all the work you are doing here. It works pretty amazing with our internal GitLab and SonarQube 8.9. How can we support you?

**Comment by mc1arke** [comment]
I've added my Github Sponsorship button to the repo. Any contributions are welcome, but are by no means expected.
