### ISSUE TITLE
SonarQube 10.4 compatibility documentation

### ISSUE THREAD

**Issue by glalloue** [mc1arke/sonarqube-community-branch-plugin#919]
**Describe the bug**
I see several PR or issues created to be compatible with sonarqube 10.4 version : 
- https://github.com/mc1arke/sonarqube-community-branch-plugin/pull/873
- https://github.com/mc1arke/sonarqube-community-branch-plugin/issues/870

And some issues are already discussing about 10.5 version

But the documentation do not mention any compatibility with 10.4 version : 
![image](https://github.com/mc1arke/sonarqube-community-branch-plugin/assets/10628710/ff8cd965-574e-4f1d-9778-033043b8593e)

Is this plugin officially compatible with 10.4 version ? 

**To Reproduce**
1. Go to https://github.com/mc1arke/sonarqube-community-branch-plugin/blob/master/README.md
2. Go to "compatibility" paragraph
3. See no information about 10.4

**Expected behavior**
related to the issues and PR listed above, it seems like the plugin is compatible with 10.4 version, but it's not added into the documentation.

**Comment by mc1arke** [comment]
Agreed that the documentation needs updated, but the release notes do state the compatibility: https://github.com/mc1arke/sonarqube-community-branch-plugin/releases/tag/1.19.0

**Comment by CoSoKG** [comment]
There is a waiting PR to update the table https://github.com/mc1arke/sonarqube-community-branch-plugin/pull/906

**Comment by kzhuklinets** [comment]
There is a waiting PR https://github.com/mc1arke/sonarqube-community-branch-plugin/pull/906 to update the table.
