### ISSUE TITLE
maven build

### ISSUE THREAD

**Issue by sergiobortsov** [mc1arke/sonarqube-community-branch-plugin#924]
**Description**
Sorry it's not exactly a bug, but just a question about some guidance how to build the plugin without gradle, but using maven.
Could you please suggest if there's a easy way without using the maven wrapper around the gradle?

Thanks a lot

**Comment by mc1arke** [comment]
Sorry, there's no direct support for building with Maven. Is there a reason you can't use Gradle?

**Comment by sergiobortsov** [comment]
Thanks for a prompt response.
Yeah, it's not really up to me. All other applications are being built by maven, so it's a bit complicated to develop another pipeline for gradle. That's why we're a looking for a bit easier option.
I'll try to play around with maven-gradle plugin.
Thanks for your assistance.
