### ISSUE TITLE
HTML-Tags not escaped on GitLab Pull Request Decoration

### ISSUE THREAD

**Issue by tritumMf** [mc1arke/sonarqube-community-branch-plugin#93]
Some issues from SonarQube will contain HTML-Tags which are not escaped.

**To Reproduce**
1. Scan a GitLab Merge Request with bogous HTML, such as an &lt;i&gt; Tag [provided that rule is activated]
2. Check the comments for that error

**Expected behavior**
Escaped HTML output

**Screenshots**
![A message on a GitLab MR: Replace this <i> tag by <em>. Instead of the Tag Names, the part after `this` is in italics.](https://user-images.githubusercontent.com/37835663/74828844-ba147200-5307-11ea-8bc6-aabc7b35b368.png)
![Browser Developer Console showing the above sentence. The browser has interpreted the `i` and `em` tags.](https://user-images.githubusercontent.com/37835663/74829980-14163700-530a-11ea-824d-371aaf6d167c.png)

**Software Versions**
 - SonarQube Version: Community Edition 8.1 (build 31237) via [Docker](https://hub.docker.com/_/sonarqube)
 - Plugin Version: cae9131 (sq-8_1-support)
-  GitLab Version: Community Edition 12.7.4 via [Docker](https://hub.docker.com/r/gitlab/gitlab-ce)
-  GitLab Runner Version: 12.7.1 via [Docker](https://hub.docker.com/r/gitlab/gitlab-runner)

**Additional context**
*This section is intentionally left blank.*

**Comment by mc1arke** [comment]
Released in 1.5.0 of the plugin
