### ISSUE TITLE
Docker Image for Sonar Version 9.9.0 

### ISSUE THREAD

**Issue by scorpio-naveen** [mc1arke/sonarqube-community-branch-plugin#930]
For setting up sonar v9.9, we used the Current [Docker Image](https://hub.docker.com/layers/mc1arke/sonarqube-with-community-branch-plugin/9.9-community/images/sha256-1be4c833e5c20902347ede22fd35d8f39c9e680d65e230e4db55aa9eb5363276?context=explore).
This docker image installs Sonar 9.9.3 (build 79811). But, we need Sonar Version 9.9.0 (build 65466). 
So, is there any possibility to install Version 9.9.0 (build 65466)

**Comment by mc1arke** [comment]
I'm not clear on why you'd want 9.9.0, as  9.9.3 contains security patches for vulnerabilities that were present in Sonarqube 9.9.0. You're welcome to build your own container based on 9.9.0 with the plugin included if you want to take that risk, but we'll not re-publish previous version of the 9.9 branch. As I appear to have missed notifications of the 9.9 release train, the 9.9.3 container is likely to be replaced by a 9.9.6 container shortly.
