### ISSUE TITLE
How to set MR decoration

### ISSUE THREAD

**Issue by devssun** [mc1arke/sonarqube-community-branch-plugin#935]
**Describe the bug**
How to set MR decoration? I set GitLab Integration.
When I make MR (sub branch to master) and execute sonarqube, but sonarqube doesn't make mr decoration.
Is there anything that I missing? please help me.

I set GitLab Integration, serverbaseURL

**Expected behavior**
make MR decoration

**Software Versions**
 - SonarQube Version: Community Edition 10.6
 - Plugin Version: 1.19.1 https://github.com/phoval/sonarqube-community-branch-plugin/releases/tag/1.19.1

**Comment by mc1arke** [comment]
You need to configure MR decoration against the 'DevOps Integration' for the project in Sonarqube. This requires you to have setup the Gitlab integration at the global level

**Comment by devssun** [comment]
I set DevOps Integration for the project, but it doesn't work..
