### ISSUE TITLE
 Issue with Test Coverage Reporting for Branches on GitLab with Spring Boot 3.3.0

### ISSUE THREAD

**Issue by Nikita-hs** [mc1arke/sonarqube-community-branch-plugin#936]
### Describe
Hello!
After upgrading version of Spring Boot from 3.2.8 to 3.3.0 we stopped having any coverage related information for our branches. We checked the project build and for the both versions it is the same.

### Software Version
Spring Boot 3.3.0 (3.2.8)
Jacoco 0.8.9
Gradle 8.3
SonarQube 10.3-community
Java 17
CI: GitLab

**Plugin Version** 1.8.0

### Screenshots
![image for 3.3.0 version](https://github.com/user-attachments/assets/9baf1be7-9b2c-42fd-99db-e5f5d67ba216)
![image for 3.2.8 version](https://github.com/user-attachments/assets/3c23c50f-97c5-4845-a883-2ebece0620e6)

Is there a way to replicate the previous behavior for current setup?

**Comment by shitikanth** [comment]
@Nikita-hs Did you figure out what the issue was or some other workaround?
