### ISSUE TITLE
Sonarqube 10.2 配置后没有生效

### ISSUE THREAD

**Issue by hairui08** [mc1arke/sonarqube-community-branch-plugin#939]
![sonarqube](https://github.com/user-attachments/assets/c642de30-194b-4e75-805b-fc8c95c288ea)

**相关配置已经放到附件中**

我安装的SonarQube版本是社区版  10.2，
1、下载了1.71.1版本的sonarqube-community-branch-plugin
2、把插件目录挂载到/opt/sonarqube/extensions/plugins/中
3、文件夹中放了对应版本的jar（sonarqube-community-branch-plugin-1.17.1.jar）
4、修改sonar.properties
5、重启容器

问题：试了一下没有生效，作者帮忙看看是否还缺少哪些步骤

**Comment by duanlizhi** [comment]
解决了吗？我也遇到了相同的问题，页面也显示了插件已经安装，但是提交分支分析时报错：Current edition does not support branch feature
