### ISSUE TITLE
Pull request analysis does not store the date of analysis

### ISSUE THREAD

**Issue by lorentz-1** [mc1arke/sonarqube-community-branch-plugin#940]
**Describe the bug**
On version 1.18.0 of plugin with SonarQube 10.3, Pull request analysis do not have the field `Last Analysis Date` filled out. It seems to only be filled out for branch scans and not PR scans. 

**To Reproduce**
1. Perform a PR analysis for any project and also perform a branch analysis 
2. Go to the project on SonarQube once analysis is done for both project and the pull requests,
3. Click on Project Settings tab
4. Click on Branches and Pull Requests tab
5. See that branches will show Last Analysis Date for all Branches that have been scanned
6. See that the Pull requests tab wont show Analysis Date for any PRs that have been scanned

**Expected behavior**
I expect the `Last Analysis Date` tab to be filled for both Pull Request and Branches. 

**Screenshots**
Pull request: 
![image](https://github.com/user-attachments/assets/d878aa76-0522-40bc-906c-e93556127bc8)

Branch Scan
![image](https://github.com/user-attachments/assets/a26f0302-2c69-4c07-94f6-f43a28c02400)

**Software Versions**
 - SonarQube Version: 10.3
 - Plugin Version: 1.18.0

**Additional context**
Since the in-build housekeeping does not work for SonarQube 10.3 , our Database is never being cleaned up. So I rely on the Last Analysis data to perform manual clean ups. 
This issue never existed on older version of SonarQube / Plugin 9.9 (LTS) | 1.14.0

**Comment by mc1arke** [comment]
> Since the in-build housekeeping does not work for SonarQube 10.3

You should be able to kick this into life by changing the retention days to something other than the default value, and then change it back.

**Comment by lorentz-1** [comment]
> > Since the in-build housekeeping does not work for SonarQube 10.3
> 
> You should be able to kick this into life by changing the retention days to something other than the default value, and then change it back.

Just did this and now it seems to work for all branches. However the Pull Requests are still left without being cleaned up.

**Comment by lilayam** [comment]
Waiting for this fix.

**Comment by mc1arke** [comment]
Released in 1.22.0
