### ISSUE TITLE
GitLab MR decoration: new stage and job created

### ISSUE THREAD

**Issue by mribeiro** [mc1arke/sonarqube-community-branch-plugin#941]
**Describe the bug**
When integrating with GitLab, a new stage named "external" with a job named "SonarQube" is created. By clicking this job, the user is taken to sonarqube page.

**To Reproduce**
1. Create a gitlab-ci pipeline with a job to trigger a scan in sonar
2. Set the project ID in gitlab
3. Run the scan in a merge request
4. Look at the pipeline jobs -- a new job "SonarQube" in stage "external" is created.

**Expected behavior**
No jobs are added

**Screenshots**
![image](https://github.com/user-attachments/assets/b5386e2e-1d7c-4e12-b901-29fc7a6afb96)

**Software Versions**
 - SonarQube Version: 10.6 (92116)
 - Plugin Version: 1.9.0 (with fixes to run on 10.6)

**Additional context**
nothing to add

**Comment by mc1arke** [comment]
This is working as per expectations. Sonarqube is decorating your MR with findings, so Gitlab reports this as a job. Since it isn't the output of a step in Gitlab CI it gets reported as an 'External' step.
