### ISSUE TITLE
PR Decorator for GitHub not Visible on PR 

### ISSUE THREAD

**Issue by sgupta-2810** [mc1arke/sonarqube-community-branch-plugin#947]
I am currently using mc1arke/sonarqube-with-community-branch-plugin:10.3-community image tag and I am able to see the analysis in Sonarqube. I want to be reflected in PR after analysis. However the PR only shows gate checks 
![Screenshot 2024-08-13 at 4 47 12 PM](https://github.com/user-attachments/assets/e7c6d2b5-6844-4fa1-b027-2bb5c5d54e3c)

**Comment by mc1arke** [comment]
You've not provided nearly enough detail to allow investigation or any realistic guidance. Have you set-up Pull Request decoration in your Sonarqube instance, do the logs show this attempting to run, what is your target platform (Github? self hosted or cloud), how does your build script work (pre-build-merge, rebase, straight execution of commit etc).

**Comment by sgupta-2810** [comment]
Sonarqube version : 10.3-community 
We are generating reports with Every Github PR Raise and Merge. 
Sonarqube is currently in EKS. 
Analysis is visible on Sonarqube portal for every PR and branch that we have configured, However before moving to EKS from ec2 it was working fine.
