### ISSUE TITLE
The settings for the Pull Request are not present

### ISSUE THREAD

**Issue by Dzamir** [mc1arke/sonarqube-community-branch-plugin#95]
**Describe the bug**
The settings for the Pull Request are not present

**To Reproduce**
1. Installed Sonarqube 8.0.0 with docker-compose
2. Installed the plugin by coping the jar into /opt/sq/extensions/plugins and /opt/sq/lib/common
3. Restarted sonarqube
4. The Pull Request settings is not present in the project setting or in the general settings

**Expected behavior**
I think that the Pull Request should be present, I don’t know where to put the gitlab URL and the gitlab token for commenting. This comment shows how it should work: https://github.com/mc1arke/sonarqube-community-branch-plugin/pull/34#issuecomment-572727409

**Software Versions**
 - SonarQube Version: 8.0.0
 - Plugin Version: 1.2.0

**Additional context**
The build already publish the analysis to Sonarqube with this command:

`mvn verify sonar:sonar $MAVEN_CLI_OPTS -env -Dsonar.qualitygate.wait=true -Dsonar.scm.provider=git -Dsonar.pullrequest.key=“${CI_MERGE_REQUEST_IID}” -Dsonar.pullrequest.branch=“${$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}” -Dsonar.pullrequest.base=“${$CI_MERGE_REQUEST_TARGET_BRANCH_NAME}” -Dsonar.gitlab.url=“${CI_SERVER_URL}” -Dsonar.gitlab.user_token=“${SONAR_GITLAB_USER_TOKEN}” -DskipTests`

**Comment by dcherniv** [comment]
@Dzamir pull request changes are not in 1.2.0 release as far as i recall. You need to build from source.

**Comment by Dzamir** [comment]
Thanks @dcherniv !

The option is there if I build the master branch from source
