### ISSUE TITLE
Will the request decorator trigger a gitlab merge_request update webhook?

### ISSUE THREAD

**Issue by freezingeyes** [mc1arke/sonarqube-community-branch-plugin#952]
**Describe the bug**
I set a merge_request webhook on my gitlab repository  to trigger ci pipeline on bkci. When I create a merge request, pipeline was triggered.After sonarqube pull request analysis, plugin writed analysis report to gitlab merge request comment.This make pipeline triggered again and again. This looks like an infinite loop.

Is there something wrong with my gitlab repository configuration? For example, webhook, or branch merge rules?

**Screenshots**
this my pipeline build history. v-nietao is my gitlab account, dz-ci is a gitlab admin account. 
![image](https://github.com/user-attachments/assets/aed82b6f-0d0d-4531-8b0c-3a2fecb6b80f)

![image](https://github.com/user-attachments/assets/bddedafd-fd95-44d8-a034-d66a1c6ddb35)

![image](https://github.com/user-attachments/assets/5566fcf5-5352-48b4-b99a-e1f3e17819f2)

![image](https://github.com/user-attachments/assets/36c4932b-b209-4313-89ad-b76c5ff2bba8)

**Comment by mc1arke** [comment]
What's listening to that webhook and running the pipeline, and what events is it configured to listen to?

**Comment by freezingeyes** [comment]
> What's listening to that webhook and running the pipeline, and what events is it configured to listen to?

![image](https://github.com/user-attachments/assets/18c99ac8-387d-4b36-900f-6b5659b9285c)
![image](https://github.com/user-attachments/assets/2eed6a10-c4f4-4a60-b013-210925896a31)

I use bkci,an open source cicd tool to listening to that webhook and running the pipeline, I configure it only listening to merge_request event. 
I checked the webhook details, it seems that trigger a merge_request update event after plugin decorate  pull requests ?

**Comment by mc1arke** [comment]
You should be able to see the history of execution for each webhook to see the content that was sent in the webhook, so find which webhook was triggering your workflow and what action it was that caused it to trigger

**Comment by freezingeyes** [comment]
> You should be able to see the history of execution for each webhook to see the content that was sent in the webhook, so find which webhook was triggering your workflow and what action it was that caused it to trigger

I think I found the problem. The merge request status will change from Preparing to Ready to Merge after plugin decorating it. That triggered webhook. As my webhook handler has no way to filter merge_requests events, such as status changed, approve, approval, I have to rewrite a webhook handler  myself to achieve the function I wanted.

I’m sorry to bother you with something so small. And thank you for your help.
