### ISSUE TITLE
Status checks don’t update.

### ISSUE THREAD

**Issue by TauanSantana** [mc1arke/sonarqube-community-branch-plugin#955]
**Describe the bug**
Everything works fine, the Pull Request Decoration appears, the Pull Request analytics appear in SonarQube, but the Status checks don’t update.
I tried several patterns for the Status Check name, but none of them work.
Am I doing something wrong or is this a bug?

**To Reproduce**

0. Configure "DevOps Platform Integration" on SonarQube Administration and in Project
1. Create a ruleset and enable "Require status checks"
2. Add the name of the expected Status.
3. Run an analysis on the main branch
4. An action will start analyzing the Main
5. Create a branch and change something.
6. Make a pull request to the main branch
7. An action will start analyzing the Pull Request

**Expected behavior**
After the pull request analysis, the Status Check (required) should be resolved, as the Quality Gate passed successfully.

**Screenshots**
![image (2)](https://github.com/user-attachments/assets/876e12e1-3fc3-40f2-8d6b-268c0c551e04)
![image (3)](https://github.com/user-attachments/assets/9b151aea-7e15-4bb5-abbd-b38417e994b8)

**Software Versions**
 - SonarQube Version: v10.6 (build 92116)]
 - Plugin Version: 1.21.0

**Comment by jenistenxavier** [comment]
@TauanSantana : Would like to check the steps that are executed on these jobs. I believe certain actions have this impact on the status checks reported back to Github.
May be alternative way to test this would be to print hello world step (excluding all the current steps on the job) and check out the status check feature on GitHub.

**Comment by mc1arke** [comment]
Does the `action [that] will start analyzing the Pull Request` complete successfully? This is the one what creates the status

**Comment by mc1arke** [comment]
Closing as unable to replicate due to lack of further information
