### ISSUE TITLE
Scanning master branch fails with SonarQube 10.6 and plugin version 1.22.0 at

### ISSUE THREAD

**Issue by sarahgp** [mc1arke/sonarqube-community-branch-plugin#965]
The scan of master branch fails with the below error but passes on other branches.

Error creating bean with name 'BranchConfiguration' defined in org.sonar.scanner.scan.branch.BranchConfigurationProvider: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.sonar.scanner.scan.branch.BranchConfiguration]: Factory method 'provide' threw exception; nested exception is java.lang.NoSuchMethodError: 'org.slf4j.spi.LoggingEventBuilder org.slf4j.Logger.atInfo()' -> [Help 1]

 - SonarQube Version: 10.6
 - Plugin Version: 1.22.0

**Comment by mc1arke** [comment]
You're missing a lot of detail on here:

1. What command are you using to launch the scanner, both in a working case, and in a non-working case
2. What platform are you running this on? Possibly a CI build for Gitlab, Github, Jenkins etc?
3. Did this work for you in previous versions, or is 1.22.0 the first version you're trying it on
4. How is your Sonarqube hosted? e.g. provided docker image, manual install

**Comment by mc1arke** [comment]
Closing since the issue doesn't contain the required details to allow replication

**Comment by cardosov** [comment]
Hi!

**Comment by cardosov** [comment]
It's working for me now. In my case, although building the default branch (`master`), I had to add `-Dsonar.branch.name`.
