### ISSUE TITLE
Housekeeping feature question

### ISSUE THREAD

**Issue by nfalco79** [mc1arke/sonarqube-community-branch-plugin#966]
Sonarqube 9.9.6 (LTS) has a fuctionality to remove stale/old branches using a global configuration under Housekeeping settings. It's clear that this feature is for branches that means developers edition.

Our sonarqube instance have projects with hundred of pull requests or support (release) branches older than 30 days (the default) without analysis.
So I would ask if using this plugin with community edition the housekeeping feature works by design or there is something that this plugin should to implement to honor the feature?

**Software Versions**
 - SonarQube Version: 9.9.6
 - Plugin Version: 1.14

**Comment by mc1arke** [comment]
https://github.com/mc1arke/sonarqube-community-branch-plugin/issues/221

**Comment by nfalco79** [comment]
For what is my understanding (I did not found other issue looking for housekeep) it should work by design for sonarqube but seems that something is missing because the plugin that act as bridge misconfigure sonar.
I will try to have a look

Thank for quick response
