### ISSUE TITLE
Disable summary comment if no issues found.

### ISSUE THREAD

**Issue by exxbrain** [mc1arke/sonarqube-community-branch-plugin#97]
It will be convenient to not to post a summary comment when no issues found. It could be one more configuration property added. This will prevent unnecessary noise and spam.

**Comment by dcherniv** [comment]
@exxbrain i would argue that configuration property is a must here. Otherwise the question is: "Was there no issues found or sonarqube scan just didn't run properly?"

**Comment by exxbrain** [comment]
> Was there no issues found or sonarqube scan just didn't run properly?
I think in the case of any error in sonar a scan task should be completed with status failed and summary comment shouldn't be shown as well.

**Comment by exxbrain** [comment]
<img width="994" alt="Screenshot 2020-02-26 at 13 55 20" src="https://user-images.githubusercontent.com/1011558/75338586-00d21100-58a0-11ea-8e7c-7642d9a2efed.png">
Also this can negatively affect a logic of a code review process. This gitlab thread must be resolved before merge request could be merged. So it prevents merge request from being merged automatically.

**Comment by kortov** [comment]
Interestengly, can plugin post a comment like "no issues, bla-bla" and resolve it automatically? And is it needed?

**Comment by rusguliev** [comment]
> Интересно, может ли плагин оставить комментарий типа «нет проблем, бла-бла» и разрешить его автоматически? И нужно ли это?

This is what you need?
https://docs.gitlab.com/ce/api/discussions.html#resolve-a-merge-request-thread

**Comment by exxbrain** [comment]
Now this issue looks really as #106 duplicate. 
https://github.com/mc1arke/sonarqube-community-branch-plugin/issues/106#issuecomment-591391383

**Comment by kortov** [comment]
I guess it can live as a feature itself, it's sound reasonable, but I think 106 has a higher priority and 97 is just a feature.

**Comment by mc1arke** [comment]
Closing this since not posting a comment doesn't make it clear whether the report didn't succeed. Given the summary comment also indicates useful information for MR/PR reviewers such as findings that couldn't be attribute to an annotate-able line of code, then this outweighs any noise that the plugin may be perceived to cause, but then subsequently clean-up on additional scans.
