### ISSUE TITLE
{"errors":[{"msg":"Current edition does not support branch feature"}]}

### ISSUE THREAD

**Issue by EvgeniyKhodos** [mc1arke/sonarqube-community-branch-plugin#980]
Hello. I can't configure merge request verification.
I get message in log: {"errors":[{"msg":"Current edition does not support branch feature"}]} when executing stage Sonarqube check

In my values.yaml:

```
plugins:
  install: 
    - "https://nexus.company.local/repository/sonar-l10n-ru-plugin-10.3.jar"
    - "https://nexus.company.local/repository/sonarqube-community-branch-plugin-1.20.0.jar"

SONAR_WEB_JAVAOPTS: "-javaagent:/opt/sonarqube/extensions/sonarqube-community-branch-plugin-1.20.0.jar=web"
SONAR_CE_JAVAOPTS: "-javaagent:/opt/sonarqube/extensions/sonarqube-community-branch-plugin-1.20.0.jar=ce"
```
an in my app.yaml

```
Sonarqube check:
  stage: Sonar  
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar" 
    MAVEN_OPTS: "-Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -Dmaven.wagon.http.ssl.ignore.validity.dates=true -Dsonar.pullrequest.id=$CI_MERGE_REQUEST_IID -Dsonar.pullrequest.sourceBranch=$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME -Dsonar.branch.name=$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME -Dsonar.pullrequest.targetBranch=$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
```
What else needs to be added ?

**Comment by mc1arke** [comment]
You're missing a lot of detail here: I presume this is Helm given you're referring to `values.yaml` but you've not specified which chart you're using, or which version of Sonarqube it's running, and would typically need to provide things like the compute engine and web startup logs and check the plugins screen in the admin section to show the plugin was reporting as installed

**Comment by EvgeniyKhodos** [comment]
I solved this problem myself. It turned out that I have Sonarqube version 10.3, not 10.5. I was looking at another line on the chart. You should have looked at this 
```
image:
  repository: sonarqube
  tag: 10.3.0-{{ .Values.edition }}
```  
After installing the 1.18.0 plugin, everything worked quite quickly.
