### ISSUE TITLE
Spammy reporting

### ISSUE THREAD

**Issue by gtrias** [mc1arke/sonarqube-community-branch-plugin#981]
**Describe the bug**

GitHub comments are being added for each commit when running CI, which leads to excessive noise in PRs and a poor developer experience.

**To Reproduce**
1. Set up the Github Devops in Sonarqube
2. Open a Pull request with the Sonarqube plugin. 
3. Start iterating the PR by submitting commits
4. For every CI cycle, sonarqube-community-branch-plugin is appending a new comment to the PR.

**Expected behavior**
- sonarqube-community-branch-plugin should remove old messages and keep only the latest ones.
- Ideally, it would be great to configure it, to only leave the comment if new issues are introduced. This would also help to reduce the number of comments.

**Screenshots**
![image](https://github.com/user-attachments/assets/3bd0bc14-6870-4031-b91c-0ff53a392db2)

**Software Versions**
 - SonarQube Version: v10.6 
 - Plugin Version: 1.22.0

**Comment by mc1arke** [comment]
This isn't a bug - it's working as intended. When pushing new commits you're making changes to the code base so impact coverage and quality. If you'd expected your changes to reach a certain coverage level or to not have issues but your coverage isn't high enough of you do have issues then you're likely to want to know about it.

The point about deleting old comments is a reasonable direction I've mentioned in other areas (we've had conversations similar to this about the Gitlab decorator), but that would be a feature request rather than a bug

**Comment by gtrias** [comment]
> This isn't a bug - it's working as intended. When pushing new commits you're making changes to the code base so impact coverage and quality. If you'd expected your changes to reach a certain coverage level or to not have issues but your coverage isn't high enough of you do have issues then you're likely to want to know about it.
> 
> The point about deleting old comments is a reasonable direction I've mentioned in other areas (we've had conversations similar to this about the Gitlab decorator), but that would be a feature request rather than a bug

I see. Sorry for the noise then. I understand we get that many because I have code coverage analysis broken :(

Sorry, I was looking for a way to suggest features such as "replace" older comments with newer ones, but I was not able to find the template when creating the issue. Sonarqube Enterprise works like this. It does not keep older irrelevant comments when new ones appear.

**Comment by gtrias** [comment]
Then, considering your answer, should I also get comments like this one? It clearly passed, so I don't get any value from it

![image](https://github.com/user-attachments/assets/a9a7c3d9-9988-48ae-a8d6-abe6756057cc)

**Comment by mc1arke** [comment]
Yes, we currently report any time sonarqube performs an analysis

**Comment by gtrias** [comment]
> Yes, we currently report any time sonarqube performs an analysis

Got it. Thanks :)

Is there any future plans to tweak or configure how this report behavior is performed?
