### ISSUE TITLE
Web server startup failed: Plugin Community Branch Plugin [communityBranchPlugin] requires at least SonarQube 9.8.0.63668

### ISSUE THREAD

**Issue by 232295311** [mc1arke/sonarqube-community-branch-plugin#996]
**My docker-compose.yml**

version: "2"
 
services:
  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    restart: always
    depends_on:
      - db
    ports:
      - 9000:9000
    networks:
      - sonarnet
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - ./sonarqube/conf:/opt/sonarqube/conf
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/extensions:/opt/sonarqube/extensions
      - ./sonarqube/lib/bundled-plugins-plugins:/opt/sonarqube/lib/bundled-plugins
      - ./sonarqube-community-branch-plugin-1.14.0.jar:/opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin.jar
      - ./sonarqube-community-branch-plugin-1.14.0.jar:/opt/sonarqube/lib/common/sonarqube-community-branch-plugin.jar
 
  db:
    image: postgres
    container_name: postgres
    networks:
      - sonarnet
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - ./postgresql:/var/lib/postgresql
      - ./postgresql/data:/var/lib/postgresql/data
      
networks:
  sonarnet:
    driver: bridge
 
 When I use `docker compose up -d` and `docker logs sonarqube`:
 2024.11.16 08:28:26 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /opt/sonarqube/temp
2024.11.16 08:28:26 INFO  app[][o.s.a.es.EsSettings] Elasticsearch listening on [HTTP: 127.0.0.1:9001, TCP: 127.0.0.1:41710]
2024.11.16 08:28:26 INFO  app[][o.s.a.ProcessLauncherImpl] Launch process[[key='es', ipcIndex=1, logFilenamePrefix=es]] from [/opt/sonarqube/elasticsearch]: /opt/sonarqube/elasticsearch/bin/elasticsearch
2024.11.16 08:28:26 INFO  app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running
warning: no-jdk distributions that do not bundle a JDK are deprecated and will be removed in a future release
2024.11.16 08:28:33 INFO  es[][o.e.n.Node] version[7.16.2], pid[37], build[default/tar/2b937c44140b6559905130a8650c64dbd0879cfb/2021-12-18T19:42:46.604893745Z], OS[Linux/3.10.0-1160.119.1.el7.x86_64/amd64], JVM[AdoptOpenJDK/OpenJDK 64-Bit Server VM/11.0.11/11.0.11+9]
2024.11.16 08:28:33 INFO  es[][o.e.n.Node] JVM home [/opt/java/openjdk]
2024.11.16 08:28:33 INFO  es[][o.e.n.Node] JVM arguments [-XX:+UseG1GC, -Djava.io.tmpdir=/opt/sonarqube/temp, -XX:ErrorFile=../logs/es_hs_err_pid%p.log, -Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -Djna.tmpdir=/opt/sonarqube/temp, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dio.netty.allocator.numDirectArenas=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j2.formatMsgNoLookups=true, -Djava.locale.providers=COMPAT, -Des.enforce.bootstrap.checks=true, -Xmx512m, -Xms512m, -XX:MaxDirectMemorySize=256m, -XX:+HeapDumpOnOutOfMemoryError, -Des.path.home=/opt/sonarqube/elasticsearch, -Des.path.conf=/opt/sonarqube/temp/conf/es, -Des.distribution.flavor=default, -Des.distribution.type=tar, -Des.bundled_jdk=false]
2024.11.16 08:28:34 INFO  es[][o.e.p.PluginsService] loaded module [analysis-common]
2024.11.16 08:28:34 INFO  es[][o.e.p.PluginsService] loaded module [lang-painless]
2024.11.16 08:28:34 INFO  es[][o.e.p.PluginsService] loaded module [parent-join]
2024.11.16 08:28:34 INFO  es[][o.e.p.PluginsService] loaded module [transport-netty4]
2024.11.16 08:28:34 INFO  es[][o.e.p.PluginsService] no plugins loaded
2024.11.16 08:28:34 INFO  es[][o.e.e.NodeEnvironment] using [1] data paths, mounts [[/opt/sonarqube/data (/dev/vda1)]], net usable_space [24.1gb], net total_space [39.2gb], types [ext4]
2024.11.16 08:28:34 INFO  es[][o.e.e.NodeEnvironment] heap size [512mb], compressed ordinary object pointers [true]
2024.11.16 08:28:35 INFO  es[][o.e.n.Node] node name [sonarqube], node ID [CZL4MJEQTfOJ68VSvUo04g], cluster name [sonarqube], roles [data_frozen, master, remote_cluster_client, data, data_content, data_hot, data_warm, data_cold, ingest]
2024.11.16 08:28:43 INFO  es[][o.e.t.NettyAllocator] creating NettyAllocator with the following configs: [name=unpooled, suggested_max_allocation_size=256kb, factors={es.unsafe.use_unpooled_allocator=null, g1gc_enabled=true, g1gc_region_size=1mb, heap_size=512mb}]
2024.11.16 08:28:43 INFO  es[][o.e.d.DiscoveryModule] using discovery type [zen] and seed hosts providers [settings]
2024.11.16 08:28:44 INFO  es[][o.e.g.DanglingIndicesState] gateway.auto_import_dangling_indices is disabled, dangling indices will not be automatically detected or imported and must be managed manually
2024.11.16 08:28:45 INFO  es[][o.e.n.Node] initialized
2024.11.16 08:28:45 INFO  es[][o.e.n.Node] starting ...
2024.11.16 08:28:45 INFO  es[][o.e.t.TransportService] publish_address {127.0.0.1:41710}, bound_addresses {127.0.0.1:41710}
2024.11.16 08:28:46 INFO  es[][o.e.b.BootstrapChecks] explicitly enforcing bootstrap checks
2024.11.16 08:28:46 INFO  es[][o.e.c.c.Coordinator] cluster UUID [p2begzvMRfO2uT_-L7NjeQ]
2024.11.16 08:28:46 INFO  es[][o.e.c.s.MasterService] elected-as-master ([1] nodes joined)[{sonarqube}{CZL4MJEQTfOJ68VSvUo04g}{lDbR-fWtRBaAAk5E3AffTA}{127.0.0.1}{127.0.0.1:41710}{cdfhimrsw} elect leader, _BECOME_MASTER_TASK_, _FINISH_ELECTION_], term: 32, version: 63, delta: master node changed {previous [], current [{sonarqube}{CZL4MJEQTfOJ68VSvUo04g}{lDbR-fWtRBaAAk5E3AffTA}{127.0.0.1}{127.0.0.1:41710}{cdfhimrsw}]}
2024.11.16 08:28:46 INFO  es[][o.e.c.s.ClusterApplierService] master node changed {previous [], current [{sonarqube}{CZL4MJEQTfOJ68VSvUo04g}{lDbR-fWtRBaAAk5E3AffTA}{127.0.0.1}{127.0.0.1:41710}{cdfhimrsw}]}, term: 32, version: 63, reason: Publication{term=32, version=63}
2024.11.16 08:28:46 INFO  es[][o.e.h.AbstractHttpServerTransport] publish_address {127.0.0.1:9001}, bound_addresses {127.0.0.1:9001}
2024.11.16 08:28:46 INFO  es[][o.e.n.Node] started
2024.11.16 08:28:47 INFO  es[][o.e.g.GatewayService] recovered [0] indices into cluster_state
2024.11.16 08:28:47 INFO  app[][o.s.a.SchedulerImpl] Process[es] is up
2024.11.16 08:28:47 INFO  app[][o.s.a.ProcessLauncherImpl] Launch process[[key='web', ipcIndex=2, logFilenamePrefix=web]] from [/opt/sonarqube]: /opt/java/openjdk/bin/java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/opt/sonarqube/temp -XX:-OmitStackTraceInFastThrow --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED -Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError -Dhttp.nonProxyHosts=localhost|127.*|[::1] -cp ./lib/sonar-application-8.9.6.50800.jar:/opt/sonarqube/lib/jdbc/postgresql/postgresql-42.2.19.jar org.sonar.server.app.WebServer /opt/sonarqube/temp/sq-process15291107146133636760properties
2024.11.16 08:28:48 INFO  web[][o.s.p.ProcessEntryPoint] Starting web
2024.11.16 08:28:49 INFO  web[][o.a.t.u.n.NioSelectorPool] Using a shared selector for servlet write/read
2024.11.16 08:28:51 INFO  web[][o.s.s.e.EsClientProvider] Connected to local Elasticsearch: [http://localhost:9001]
2024.11.16 08:28:52 INFO  web[][o.s.s.p.LogServerVersion] SonarQube Server / 8.9.6.50800 / d65f231536c03e1a5181c1b1892112f6533d357f
2024.11.16 08:28:52 INFO  web[][o.sonar.db.Database] Create JDBC data source for jdbc:postgresql://db:5432/sonar
2024.11.16 08:28:56 INFO  web[][o.s.s.p.ServerFileSystemImpl] SonarQube home: /opt/sonarqube
2024.11.16 08:28:56 INFO  web[][o.s.s.u.SystemPasscodeImpl] System authentication by passcode is disabled
2024.11.16 08:28:56 ERROR web[][o.s.s.p.PlatformImpl] Web server startup failed: Plugin Community Branch Plugin [communityBranchPlugin] requires at least SonarQube 9.8.0.63668
2024.11.16 08:28:57 INFO  web[][o.s.s.a.EmbeddedTomcat] HTTP connector enabled on port 9000
2024.11.16 08:28:57 INFO  web[][o.s.p.ProcessEntryPoint] Hard stopping process
2024.11.16 08:28:57 INFO  app[][o.s.a.SchedulerImpl] Process[web] is stopped
2024.11.16 08:28:57 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [es]: 143
2024.11.16 08:28:57 INFO  app[][o.s.a.SchedulerImpl] Process[es] is stopped
2024.11.16 08:28:57 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped

**Comment by mc1arke** [comment]
The error is right given the logs state that your Sonarqube version is `SonarQube Server / 8.9.6.50800 / d65f231536c03e1a5181c1b1892112f6533d357f`. You'd need to investigate why you're not pulling the latest LTS with your target image.
